# Imports

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

import os
from datetime import datetime, timedelta

In [2]:
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier

In [3]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Variables

In [4]:
footballdata_wTeamStats_path = \
    os.path.abspath(os.getcwd())+"\\Data\\teamStats_byLeague"

In [5]:
for filename in [f for f in os.listdir(footballdata_wTeamStats_path)]:
    print(filename)

footballdata_wTeamStats_Belgium_Jupiler.csv
footballdata_wTeamStats_England_Championship.csv
footballdata_wTeamStats_englishpremierleague.csv
footballdata_wTeamStats_France_Ligue1.csv
footballdata_wTeamStats_France_Ligue2.csv
footballdata_wTeamStats_Germany_Bundesliga1.csv
footballdata_wTeamStats_Germany_Bundesliga2.csv
footballdata_wTeamStats_Greece_SuperLeague.csv
footballdata_wTeamStats_Italy_SerieA.csv
footballdata_wTeamStats_Italy_SerieB.csv
footballdata_wTeamStats_Netherlands_Eredivisie.csv
footballdata_wTeamStats_Portugal_PrimeiraLiga.csv
footballdata_wTeamStats_Spain_Laliga.csv
footballdata_wTeamStats_Spain_Laliga2.csv
footballdata_wTeamStats_Turkey_SuperLeague.csv


In [18]:
leagues_toConsider = ['Netherlands_Eredivisie', 'Belgium_Jupiler']

In [19]:
[f for f in os.listdir(footballdata_wTeamStats_path) if any(x in f for x in leagues_toConsider)]

['footballdata_wTeamStats_Belgium_Jupiler.csv',
 'footballdata_wTeamStats_Netherlands_Eredivisie.csv']

# Load Football-Data File with Indexes

In [20]:
footballdata_wTeamStats = pd.DataFrame()
for filename in [f for f in os.listdir(footballdata_wTeamStats_path) if any(x in f for x in leagues_toConsider)]:
    footballdata_wTeamStats = footballdata_wTeamStats.append(pd.read_csv(footballdata_wTeamStats_path+"\\"+filename, 
                                                                         index_col=0))
footballdata_wTeamStats

AverageAwayWinOdd  AverageDrawWinOdd  AverageHomeWinOdd  AvgOver2_5  \
0                  4.75               3.60               1.73        1.93   
1                 10.00               6.50               1.20        1.51   
2                  1.91               3.30               3.75        1.77   
3                  3.80               3.30               1.91        1.76   
4                  3.20               3.20               2.10        1.84   
...                 ...                ...                ...         ...   
3602               8.97               5.79               1.29        1.45   
3603               2.56               3.63               2.55        1.64   
3604              14.63               7.97               1.16        1.32   
3605               6.46               4.49               1.47        1.64   
3606               1.88               3.56               4.09        1.97   

      AvgUnder2_5  AwayGoals  AwayTeamId AwayTeamName        Date    Div  \
0            1.83        1.0       600.0      Waregem  30/07/2010  144.0   
1            2.41        1.0       739.0        Eupen  31/07/2010  144.0   
2            2.01        0.0       569.0  Club Brugge  31/07/2010  144.0   
3            2.00        0.0       737.0      Lokeren  31/07/2010  144.0   
4            1.93        0.0      1392.0       Lierse  31/07/2010  144.0   
...           ...        ...         ...          ...         ...    ...   
3602         2.67        0.0       210.0   Heerenveen  13/08/2022   88.0   
3603         2.24        4.0       413.0     Nijmegen  14/08/2022   88.0   
3604         3.32        1.0       202.0    Groningen  14/08/2022   88.0   
3605         2.23        0.0       205.0  For Sittard  14/08/2022   88.0   
3606         1.82        3.0       201.0   AZ Alkmaar  14/08/2022   88.0   

     FullTimeResult  HomeGoals      HomeTeamName  HomeTeamid  Season  \
0                 D        1.0          Standard       733.0  2010.0   
1                 H        4.0        Anderlecht       554.0  2010.0   
2                 H        1.0          Kortrijk       734.0  2010.0   
3                 H        2.0          Mechelen       266.0  2010.0   
4                 H        1.0        St Truiden       735.0  2010.0   
...             ...        ...               ...         ...     ...   
3602              D        0.0         Feyenoord       209.0  2022.0   
3603              A        1.0          Volendam       416.0  2022.0   
3604              H        6.0              Ajax       194.0  2022.0   
3605              H        3.0            Twente       415.0  2022.0   
3606              A        2.0  Sparta Rotterdam       426.0  2022.0   

      away_average_away_goals_against  away_average_away_goals_for  \
0                                 0.0                          0.0   
1                                 0.0                          0.0   
2                                 0.0                          0.0   
3                                 0.0                          0.0   
4                                 0.0                          0.0   
...                               ...                          ...   
3602                              0.0                          0.0   
3603                              0.0                          0.0   
3604                              0.0                          0.0   
3605                              0.0                          0.0   
3606                              0.0                          0.0   

      away_average_home_goals_against  away_average_home_goals_for  \
0                                 0.0                          0.0   
1                                 0.0                          0.0   
2                                 0.0                          0.0   
3                                 0.0                          0.0   
4                                 0.0                          0.0   
...                               ...     

In [9]:
footballdata_wTeamStats.columns.to_list()

['AverageAwayWinOdd',
 'AverageDrawWinOdd',
 'AverageHomeWinOdd',
 'AvgOver2_5',
 'AvgUnder2_5',
 'AwayGoals',
 'AwayTeamId',
 'AwayTeamName',
 'Date',
 'Div',
 'FullTimeResult',
 'HomeGoals',
 'HomeTeamName',
 'HomeTeamid',
 'Season',
 'away_average_away_goals_against',
 'away_average_away_goals_for',
 'away_average_home_goals_against',
 'away_average_home_goals_for',
 'away_average_total_goals_against',
 'away_average_total_goals_for',
 'away_away_clean_sheets',
 'away_away_draws',
 'away_away_goals_against',
 'away_away_goals_for',
 'away_away_loses',
 'away_away_wins',
 'away_biggest_away_goals_against',
 'away_biggest_away_goals_for',
 'away_biggest_away_lose',
 'away_biggest_away_win',
 'away_biggest_draw_streak',
 'away_biggest_home_goals_against',
 'away_biggest_home_goals_for',
 'away_biggest_home_lose',
 'away_biggest_home_win',
 'away_biggest_lose_streak',
 'away_biggest_win_streak',
 'away_failed_to_score_away',
 'away_failed_to_score_home',
 'away_failed_to_score_total',
 

# Data Prep

## Remove Incomplete Columns & Non important (except indexes)

In [21]:
not_complete = ['away_red_cards_minute_0_15', 'away_red_cards_minute_0_15_percentage',
               'away_red_cards_minute_16_30', 'away_red_cards_minute_16_30_percentage',
               'away_red_cards_minute_31_45', 'away_red_cards_minute_31_45_percentage',
               'away_red_cards_minute_46_60', 'away_red_cards_minute_46_60_percentage',
               'away_red_cards_minute_61_75', 'away_red_cards_minute_61_75_percentage',
               'away_red_cards_minute_61_75', 'away_red_cards_minute_61_75_percentage',
               'away_red_cards_minute_76_90', 'away_red_cards_minute_76_90_percentage',
               'away_red_cards_minute_91_105', 'away_red_cards_minute_91_105_percentage',
               'away_yellow_cards_minute_0_15', 'away_yellow_cards_minute_0_15_percentage',
               'away_yellow_cards_minute_16_30', 'away_yellow_cards_minute_16_30_percentage',
               'away_yellow_cards_minute_31_45', 'away_yellow_cards_minute_31_45_percentage',
               'away_yellow_cards_minute_46_60', 'away_yellow_cards_minute_46_60_percentage',
               'away_yellow_cards_minute_61_75', 'away_yellow_cards_minute_61_75_percentage',
               'away_yellow_cards_minute_76_90', 'away_yellow_cards_minute_76_90_percentage',
               'away_yellow_cards_minute_91_105', 'away_yellow_cards_minute_91_105_percentage',
                'home_red_cards_minute_0_15', 'home_red_cards_minute_0_15_percentage',
               'home_red_cards_minute_16_30', 'home_red_cards_minute_16_30_percentage',
               'home_red_cards_minute_31_45', 'home_red_cards_minute_31_45_percentage',
               'home_red_cards_minute_46_60', 'home_red_cards_minute_46_60_percentage',
               'home_red_cards_minute_61_75', 'home_red_cards_minute_61_75_percentage',
               'home_red_cards_minute_61_75', 'home_red_cards_minute_61_75_percentage',
               'home_red_cards_minute_76_90', 'home_red_cards_minute_76_90_percentage',
               'home_red_cards_minute_91_105', 'home_red_cards_minute_91_105_percentage',
               'home_yellow_cards_minute_0_15', 'home_yellow_cards_minute_0_15_percentage',
               'home_yellow_cards_minute_16_30', 'home_yellow_cards_minute_16_30_percentage',
               'home_yellow_cards_minute_31_45', 'home_yellow_cards_minute_31_45_percentage',
               'home_yellow_cards_minute_46_60', 'home_yellow_cards_minute_46_60_percentage',
               'home_yellow_cards_minute_61_75', 'home_yellow_cards_minute_61_75_percentage',
               'home_yellow_cards_minute_76_90', 'home_yellow_cards_minute_76_90_percentage',
               'home_yellow_cards_minute_91_105', 'home_yellow_cards_minute_91_105_percentage']

# away average goals and home average goals will be removed because we will average all columns
not_features = [
               'away_biggest_away_lose', 'away_biggest_away_win', 'away_biggest_home_lose', 'away_biggest_home_win',
               'away_lineups',
               'home_biggest_away_lose', 'home_biggest_away_win', 'home_biggest_home_lose', 'home_biggest_home_win',
               'home_lineups',
    
               'away_biggest_away_goals_against', 'away_biggest_away_goals_for', 'away_biggest_draw_streak',
               'away_biggest_home_goals_against', 'away_biggest_home_goals_for', 'away_biggest_lose_streak',
               'away_biggest_win_streak',
               'home_biggest_away_goals_against', 'home_biggest_away_goals_for', 'home_biggest_draw_streak',
               'home_biggest_home_goals_against', 'home_biggest_home_goals_for', 'home_biggest_lose_streak',
               'home_biggest_win_streak',
    
               'away_average_away_goals_against', 'away_average_away_goals_for', 'away_average_home_goals_against',
               'away_average_home_goals_for', 'away_average_total_goals_against', 'away_average_total_goals_for',
               'home_average_away_goals_against', 'home_average_away_goals_for', 'home_average_home_goals_against',
               'home_average_home_goals_for', 'home_average_total_goals_against', 'home_average_total_goals_for',
    
               'away_penalties_missed', 'away_penalties_missed_percentage', 'away_penalties_scored',
               'away_penalties_scored', 'away_penalties_scored_percentage',
               'home_penalties_missed', 'home_penalties_missed_percentage', 'home_penalties_scored',
               'home_penalties_scored', 'home_penalties_scored_percentage'
               ]

In [22]:
footballdata_wTeamStats = \
    footballdata_wTeamStats[list(set(footballdata_wTeamStats.columns.tolist()) - set(not_complete + not_features))]
footballdata_wTeamStats

away_total_goals_for away_goals_against_minute_31_45_percentage  \
0                      0.0                                        NaN   
1                      0.0                                        NaN   
2                      0.0                                        NaN   
3                      0.0                                        NaN   
4                      0.0                                        NaN   
...                    ...                                        ...   
3602                   0.0                                        NaN   
3603                   0.0                                        NaN   
3604                   2.0                                     50.00%   
3605                   2.0                                        NaN   
3606                   2.0                                        NaN   

     away_goals_against_minute_76_90_percentage  AwayGoals  away_home_wins  \
0                                           NaN        1.0             0.0   
1                                           NaN        1.0             0.0   
2                                           NaN        0.0             0.0   
3                                           NaN        0.0             0.0   
4                                           NaN        0.0             0.0   
...                                         ...        ...             ...   
3602                                        NaN        0.0             0.0   
3603                                        NaN        4.0             0.0   
3604                                        NaN        1.0             0.0   
3605                                        NaN        0.0             0.0   
3606                                        NaN        3.0             1.0   

      home_away_clean_sheets  home_goals_against_minute_46_60  \
0                        0.0                              NaN   
1                        0.0                              NaN   
2                        0.0                              NaN   
3                        0.0                              NaN   
4                        0.0                              NaN   
...                      ...                              ...   
3602                     0.0                              1.0   
3603                     0.0                              NaN   
3604                     0.0                              NaN   
3605                     1.0                              NaN   
3606                     1.0                              NaN   

      away_goals_against_minute_76_90  home_home_loses  \
0                                 NaN              0.0   
1                                 NaN              0.0   
2                                 NaN              0.0   
3                                 NaN              0.0   
4                                 NaN              0.0   
...                               ...              ...   
3602                              NaN              0.0   
3603                              NaN              0.0   
3604                              NaN              0.0   
3605                              NaN              0.0   
3606                              NaN              0.0   

      home_away_goals_against home_goals_against_minute_16_30_percentage  \
0                         0.0                                        NaN   
1                         0.0                                        NaN   
2                         0.0                                        NaN   
3                         0.0                                        NaN   
4                         0.0                                        NaN   
...                       ...                                        ...   
3602                      2.0                                     50.00%   
3603                      2.0                                        NaN   
3604                      2.0 

## Convert NaN/Nulls to 0

In [18]:
nan_to_zero = ['away_goals_against_minute_0_15', 'away_goals_against_minute_0_15_percentage',
            'away_goals_against_minute_16_30', 'away_goals_against_minute_16_30_percentage',
            'away_goals_against_minute_16_30_percentage', 'away_goals_against_minute_31_45',
             'away_goals_against_minute_31_45_percentage', 'away_goals_against_minute_46_60',
            'away_goals_against_minute_46_60_percentage', 'away_goals_against_minute_61_75',
            'away_goals_against_minute_61_75_percentage', 'away_goals_against_minute_76_90',
            'away_goals_against_minute_76_90_percentage', 'away_goals_against_minute_91_105',
            'away_goals_against_minute_91_105_percentage', 'away_goals_for_minute_0_15',
            'away_goals_for_minute_0_15_percentage', 'away_goals_for_minute_16_30', 'away_goals_for_minute_16_30_percentage',
            'away_goals_for_minute_31_45', 'away_goals_for_minute_31_45_percentage', 'away_goals_for_minute_46_60',
            'away_goals_for_minute_46_60_percentage', 'away_goals_for_minute_61_75', 'away_goals_for_minute_61_75_percentage',
            'away_goals_for_minute_76_90', 'away_goals_for_minute_76_90_percentage', 'away_goals_for_minute_91_105',
            'away_goals_for_minute_91_105_percentage',
             'home_goals_against_minute_0_15', 'home_goals_against_minute_0_15_percentage',
            'home_goals_against_minute_16_30', 'home_goals_against_minute_16_30_percentage',
            'home_goals_against_minute_16_30_percentage', 'home_goals_against_minute_31_45',
             'home_goals_against_minute_31_45_percentage', 'home_goals_against_minute_46_60',
            'home_goals_against_minute_46_60_percentage', 'home_goals_against_minute_61_75',
            'home_goals_against_minute_61_75_percentage', 'home_goals_against_minute_76_90',
            'home_goals_against_minute_76_90_percentage', 'home_goals_against_minute_91_105',
            'home_goals_against_minute_91_105_percentage', 'home_goals_for_minute_0_15',
            'home_goals_for_minute_0_15_percentage', 'home_goals_for_minute_16_30', 'home_goals_for_minute_16_30_percentage',
            'home_goals_for_minute_31_45', 'home_goals_for_minute_31_45_percentage', 'home_goals_for_minute_46_60',
            'home_goals_for_minute_46_60_percentage', 'home_goals_for_minute_61_75', 'home_goals_for_minute_61_75_percentage',
            'home_goals_for_minute_76_90', 'home_goals_for_minute_76_90_percentage', 'home_goals_for_minute_91_105',
            'home_goals_for_minute_91_105_percentage']

In [19]:
print(footballdata_wTeamStats.count().sort_values().to_string())

away_goals_against_minute_91_105_percentage    29537
away_goals_against_minute_91_105               29537
home_goals_against_minute_91_105_percentage    29640
home_goals_against_minute_91_105               29640
home_goals_for_minute_91_105_percentage        29835
home_goals_for_minute_91_105                   29835
away_goals_for_minute_91_105                   29898
away_goals_for_minute_91_105_percentage        29898
home_goals_for_minute_0_15_percentage          40780
home_goals_for_minute_0_15                     40780
away_goals_against_minute_0_15                 40900
away_goals_against_minute_0_15_percentage      40900
away_goals_for_minute_0_15_percentage          40933
away_goals_for_minute_0_15                     40933
home_goals_against_minute_0_15                 41066
home_goals_against_minute_0_15_percentage      41066
home_goals_for_minute_16_30                    41636
home_goals_for_minute_16_30_percentage         41636
away_goals_against_minute_16_30_percentage    

In [20]:
for column in footballdata_wTeamStats.columns:
    if 'percentage' in column:
        footballdata_wTeamStats[column] = footballdata_wTeamStats[column].str.slice(0,-1,1).astype(float)

for column in nan_to_zero:
    if 'percentage' in column:
        footballdata_wTeamStats[column] = footballdata_wTeamStats[column].fillna(0.0)
    else:
        footballdata_wTeamStats[column] = footballdata_wTeamStats[column].fillna(0).astype(int)
footballdata_wTeamStats

<ipython-input-20-04bdf39b3b3a>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  footballdata_wTeamStats[column] = footballdata_wTeamStats[column].str.slice(0,-1,1).astype(float)
<ipython-input-20-04bdf39b3b3a>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  footballdata_wTeamStats[column] = footballdata_wTeamStats[column].fillna(0).astype(int)
<ipython-input-20-04bdf39b3b3a>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexe

AvgUnder2_5  away_total_goals_for  away_home_goals_against  \
0            1.83                   0.0                      0.0   
1            2.41                   0.0                      0.0   
2            2.01                   0.0                      0.0   
3            2.00                   0.0                      0.0   
4            1.93                   0.0                      0.0   
...           ...                   ...                      ...   
4259         1.90                   7.0                      4.0   
4260         1.64                   5.0                      2.0   
4261         1.68                  10.0                      1.0   
4262         1.86                  11.0                      7.0   
4263         2.20                  12.0                      3.0   

      home_goals_against_minute_0_15_percentage home_form        Date  \
0                                          0.00       NaN  30/07/2010   
1                                          0.00       NaN  31/07/2010   
2                                          0.00       NaN  31/07/2010   
3                                          0.00       NaN  31/07/2010   
4                                          0.00       NaN  31/07/2010   
...                                         ...       ...         ...   
4259                                      14.29  LWWWDWWD  16/10/2021   
4260                                       0.00  LLWDWWWL  17/10/2021   
4261                                       0.00  LDLLLWWL  17/10/2021   
4262                                       0.00   DDDDWDW  17/10/2021   
4263                                      14.29   WDWDDWL  17/10/2021   

      home_total_goals_against  home_home_goals_against  \
0                          0.0                      0.0   
1                          0.0                      0.0   
2                          0.0                      0.0   
3                          0.0                      0.0   
4                          0.0                      0.0   
...                        ...                      ...   
4259                       7.0                      0.0   
4260                       8.0                      1.0   
4261                      11.0                      5.0   
4262                       3.0                      1.0   
4263                       7.0                      4.0   

      away_away_clean_sheets  home_goals_for_minute_31_45  \
0                        0.0                            0   
1                        0.0                            0   
2                        0.0                            0   
3                        0.0                            0   
4                        0.0                            0   
...                      ...                          ...   
4259                     1.0                            1   
4260                     1.0                            3   
4261                     2.0                            1   
4262                     1.0                            1   
4263                     1.0                            0   

      away_failed_to_score_home  away_goals_for_minute_16_30_percentage  \
0                           0.0                                    0.00   
1                           0.0                                    0.00   
2                           0.0                                    0.00   
3                           0.0                                    0.00   
4                           0.0                                    0.00   
...                         ...                                     ...   
4259                        1.0                                   37.50   
4260                        1.0                                   20.00   
4261                        0.0                                   20.00   
4262                        2.0                                   16.67   
4263                        0.0              

In [21]:
footballdata_wTeamStats.tail(5)

AvgUnder2_5  away_total_goals_for  away_home_goals_against  \
4259         1.90                   7.0                      4.0   
4260         1.64                   5.0                      2.0   
4261         1.68                  10.0                      1.0   
4262         1.86                  11.0                      7.0   
4263         2.20                  12.0                      3.0   

      home_goals_against_minute_0_15_percentage home_form        Date  \
4259                                      14.29  LWWWDWWD  16/10/2021   
4260                                       0.00  LLWDWWWL  17/10/2021   
4261                                       0.00  LDLLLWWL  17/10/2021   
4262                                       0.00   DDDDWDW  17/10/2021   
4263                                      14.29   WDWDDWL  17/10/2021   

      home_total_goals_against  home_home_goals_against  \
4259                       7.0                      0.0   
4260                       8.0                      1.0   
4261                      11.0                      5.0   
4262                       3.0                      1.0   
4263                       7.0                      4.0   

      away_away_clean_sheets  home_goals_for_minute_31_45  \
4259                     1.0                            1   
4260                     1.0                            3   
4261                     2.0                            1   
4262                     1.0                            1   
4263                     1.0                            0   

      away_failed_to_score_home  away_goals_for_minute_16_30_percentage  \
4259                        1.0                                   37.50   
4260                        1.0                                   20.00   
4261                        0.0                                   20.00   
4262                        2.0                                   16.67   
4263                        0.0                                    9.09   

      home_home_clean_sheets  home_goals_against_minute_61_75  \
4259                     4.0                                1   
4260                     2.0                                1   
4261                     1.0                                2   
4262                     2.0                                0   
4263                     1.0                                0   

      home_goals_for_minute_91_105_percentage  home_goals_for_minute_0_15  \
4259                                     0.00                           0   
4260                                    14.29                           4   
4261                                    14.29                           1   
4262                                    22.22                           1   
4263                                    18.18                           3   

      home_home_loses  home_goals_for_minute_61_75  \
4259              0.0                            3   
4260              0.0                            0   
4261              3.0                            2   
4262              0.0                            2   
4263              0.0                            1   

      home_goals_against_minute_46_60 AwayTeamName  \
4259                                2     Mallorca   
4260                                1        Elche   
4261                                3      Sevilla   
4262                                1      Osasuna   
4263                                1     Valencia   

      home_goals_against_minute_91_105_percentage  \
4259                                        14.29   
4260                                        14.29   
4261                                         0.00   
4262                                         0.00   
4263                                         0.00   

      away_goals_against_minute_46_60  AvgOver2_5  \
4259                                2        1.93   
4260                                2        2.29   
426

In [22]:
print(footballdata_wTeamStats.count().sort_values().to_string())

home_form                                      48928
away_form                                      48942
AverageDrawWinOdd                              52119
AverageAwayWinOdd                              52119
AverageHomeWinOdd                              52119
AvgUnder2_5                                    52140
AvgOver2_5                                     52141
HomeGoals                                      52205
FullTimeResult                                 52205
AwayGoals                                      52205
away_goals_against_minute_16_30_percentage     52207
away_goals_against_minute_61_75_percentage     52207
away_goals_for_minute_76_90_percentage         52207
home_home_wins                                 52207
home_goals_against_minute_76_90_percentage     52207
away_goals_against_minute_61_75                52207
away_away_goals_against                        52207
away_home_goals_for                            52207
away_goals_for_minute_91_105_percentage       

## Modifications

### Add Total wins, draws & losses

In [23]:
footballdata_wTeamStats['home_total_wins'] = \
    footballdata_wTeamStats['home_home_wins'] + footballdata_wTeamStats['home_away_wins']
footballdata_wTeamStats['home_total_draws'] = \
    footballdata_wTeamStats['home_home_draws'] + footballdata_wTeamStats['home_away_draws']
footballdata_wTeamStats['home_total_loses'] = \
    footballdata_wTeamStats['home_home_loses'] + footballdata_wTeamStats['home_away_loses']

# TODO: total games is computed bases only on the home games (might require future change)
footballdata_wTeamStats['home_total_games'] = footballdata_wTeamStats['home_total_wins']+\
    footballdata_wTeamStats['home_total_draws']+footballdata_wTeamStats['home_total_loses']

footballdata_wTeamStats['away_total_wins'] = \
    footballdata_wTeamStats['away_home_wins'] + footballdata_wTeamStats['away_away_wins']
footballdata_wTeamStats['away_total_draws'] = \
    footballdata_wTeamStats['away_home_draws'] + footballdata_wTeamStats['away_away_draws']
footballdata_wTeamStats['away_total_loses'] = \
    footballdata_wTeamStats['away_home_loses'] + footballdata_wTeamStats['away_away_loses']

footballdata_wTeamStats['away_total_games'] = footballdata_wTeamStats['away_total_wins']+\
    footballdata_wTeamStats['away_total_draws']+footballdata_wTeamStats['away_total_loses']

footballdata_wTeamStats['home_total_home_games'] = footballdata_wTeamStats['home_home_wins']+\
    footballdata_wTeamStats['home_home_draws']+footballdata_wTeamStats['home_home_loses']
footballdata_wTeamStats['home_total_away_games'] = footballdata_wTeamStats['home_away_wins']+\
    footballdata_wTeamStats['home_away_draws']+footballdata_wTeamStats['home_away_loses']

footballdata_wTeamStats['away_total_home_games'] = footballdata_wTeamStats['away_home_wins']+\
    footballdata_wTeamStats['away_home_draws']+footballdata_wTeamStats['away_home_loses']
footballdata_wTeamStats['away_total_away_games'] = footballdata_wTeamStats['away_away_wins']+\
    footballdata_wTeamStats['away_away_draws']+footballdata_wTeamStats['away_away_loses']

footballdata_wTeamStats

<ipython-input-23-26fe08bd73ab>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  footballdata_wTeamStats['home_total_wins'] = \
<ipython-input-23-26fe08bd73ab>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  footballdata_wTeamStats['home_total_draws'] = \
<ipython-input-23-26fe08bd73ab>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-

AvgUnder2_5  away_total_goals_for  away_home_goals_against  \
0            1.83                   0.0                      0.0   
1            2.41                   0.0                      0.0   
2            2.01                   0.0                      0.0   
3            2.00                   0.0                      0.0   
4            1.93                   0.0                      0.0   
...           ...                   ...                      ...   
4259         1.90                   7.0                      4.0   
4260         1.64                   5.0                      2.0   
4261         1.68                  10.0                      1.0   
4262         1.86                  11.0                      7.0   
4263         2.20                  12.0                      3.0   

      home_goals_against_minute_0_15_percentage home_form        Date  \
0                                          0.00       NaN  30/07/2010   
1                                          0.00       NaN  31/07/2010   
2                                          0.00       NaN  31/07/2010   
3                                          0.00       NaN  31/07/2010   
4                                          0.00       NaN  31/07/2010   
...                                         ...       ...         ...   
4259                                      14.29  LWWWDWWD  16/10/2021   
4260                                       0.00  LLWDWWWL  17/10/2021   
4261                                       0.00  LDLLLWWL  17/10/2021   
4262                                       0.00   DDDDWDW  17/10/2021   
4263                                      14.29   WDWDDWL  17/10/2021   

      home_total_goals_against  home_home_goals_against  \
0                          0.0                      0.0   
1                          0.0                      0.0   
2                          0.0                      0.0   
3                          0.0                      0.0   
4                          0.0                      0.0   
...                        ...                      ...   
4259                       7.0                      0.0   
4260                       8.0                      1.0   
4261                      11.0                      5.0   
4262                       3.0                      1.0   
4263                       7.0                      4.0   

      away_away_clean_sheets  home_goals_for_minute_31_45  \
0                        0.0                            0   
1                        0.0                            0   
2                        0.0                            0   
3                        0.0                            0   
4                        0.0                            0   
...                      ...                          ...   
4259                     1.0                            1   
4260                     1.0                            3   
4261                     2.0                            1   
4262                     1.0                            1   
4263                     1.0                            0   

      away_failed_to_score_home  away_goals_for_minute_16_30_percentage  \
0                           0.0                                    0.00   
1                           0.0                                    0.00   
2                           0.0                                    0.00   
3                           0.0                                    0.00   
4                           0.0                                    0.00   
...                         ...                                     ...   
4259                        1.0                                   37.50   
4260                        1.0                                   20.00   
4261                        0.0                                   20.00   
4262                        2.0                                   16.67   
4263                        0.0              

### Away Team & Home Team Form

In [24]:
to_modify = ['away_form', 'home_form']

In [25]:
# Same as before but normalized
games = [1, 2, 5, 10]
for column in to_modify:
    footballdata_wTeamStats[column] = footballdata_wTeamStats[column].fillna('')
    for nr in games:
        footballdata_wTeamStats[column+f"_last{nr}games_wins"] = \
            footballdata_wTeamStats[column].apply(lambda x : x[-nr:]).str.count('W') / \
            footballdata_wTeamStats['home_total_games'].clip(upper=10)
        footballdata_wTeamStats[column+f"_last{nr}games_draws"] = \
            footballdata_wTeamStats[column].apply(lambda x : x[-nr:]).str.count('D') / \
            footballdata_wTeamStats['home_total_games'].clip(upper=10)
        footballdata_wTeamStats[column+f"_last{nr}games_loses"] = \
            footballdata_wTeamStats[column].apply(lambda x : x[-nr:]).str.count('L') / \
            footballdata_wTeamStats['home_total_games'].clip(upper=10)
footballdata_wTeamStats

<ipython-input-25-4b1632eb5d92>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  footballdata_wTeamStats[column] = footballdata_wTeamStats[column].fillna('')
<ipython-input-25-4b1632eb5d92>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  footballdata_wTeamStats[column+f"_last{nr}games_wins"] = \
<ipython-input-25-4b1632eb5d92>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documen

AvgUnder2_5  away_total_goals_for  away_home_goals_against  \
0            1.83                   0.0                      0.0   
1            2.41                   0.0                      0.0   
2            2.01                   0.0                      0.0   
3            2.00                   0.0                      0.0   
4            1.93                   0.0                      0.0   
...           ...                   ...                      ...   
4259         1.90                   7.0                      4.0   
4260         1.64                   5.0                      2.0   
4261         1.68                  10.0                      1.0   
4262         1.86                  11.0                      7.0   
4263         2.20                  12.0                      3.0   

      home_goals_against_minute_0_15_percentage home_form        Date  \
0                                          0.00            30/07/2010   
1                                          0.00            31/07/2010   
2                                          0.00            31/07/2010   
3                                          0.00            31/07/2010   
4                                          0.00            31/07/2010   
...                                         ...       ...         ...   
4259                                      14.29  LWWWDWWD  16/10/2021   
4260                                       0.00  LLWDWWWL  17/10/2021   
4261                                       0.00  LDLLLWWL  17/10/2021   
4262                                       0.00   DDDDWDW  17/10/2021   
4263                                      14.29   WDWDDWL  17/10/2021   

      home_total_goals_against  home_home_goals_against  \
0                          0.0                      0.0   
1                          0.0                      0.0   
2                          0.0                      0.0   
3                          0.0                      0.0   
4                          0.0                      0.0   
...                        ...                      ...   
4259                       7.0                      0.0   
4260                       8.0                      1.0   
4261                      11.0                      5.0   
4262                       3.0                      1.0   
4263                       7.0                      4.0   

      away_away_clean_sheets  home_goals_for_minute_31_45  \
0                        0.0                            0   
1                        0.0                            0   
2                        0.0                            0   
3                        0.0                            0   
4                        0.0                            0   
...                      ...                          ...   
4259                     1.0                            1   
4260                     1.0                            3   
4261                     2.0                            1   
4262                     1.0                            1   
4263                     1.0                            0   

      away_failed_to_score_home  away_goals_for_minute_16_30_percentage  \
0                           0.0                                    0.00   
1                           0.0                                    0.00   
2                           0.0                                    0.00   
3                           0.0                                    0.00   
4                           0.0                                    0.00   
...                         ...                                     ...   
4259                        1.0                                   37.50   
4260                        1.0                                   20.00   
4261                        0.0                                   20.00   
4262                        2.0                                   16.67   
4263                        0.0              

In [26]:
footballdata_wTeamStats = footballdata_wTeamStats.drop(columns=to_modify)

In [27]:
print(footballdata_wTeamStats.dtypes.sort_values().to_string())

home_goals_against_minute_31_45                  int32
home_goals_for_minute_16_30                      int32
home_goals_for_minute_91_105                     int32
away_goals_against_minute_0_15                   int32
home_goals_against_minute_16_30                  int32
away_goals_for_minute_16_30                      int32
home_goals_for_minute_76_90                      int32
away_goals_for_minute_61_75                      int32
away_goals_against_minute_76_90                  int32
away_goals_against_minute_91_105                 int32
away_goals_against_minute_46_60                  int32
home_goals_for_minute_46_60                      int32
away_goals_for_minute_46_60                      int32
home_goals_against_minute_46_60                  int32
home_goals_for_minute_61_75                      int32
away_goals_against_minute_31_45                  int32
home_goals_for_minute_0_15                       int32
away_goals_against_minute_61_75                  int32
home_goals

### Remove 1st 5 "jornadas"

In [28]:
footballdata_wTeamStats = footballdata_wTeamStats[footballdata_wTeamStats['home_total_games']>=5]
footballdata_wTeamStats.reindex(sorted(footballdata_wTeamStats.columns), axis=1)

AverageAwayWinOdd  AverageDrawWinOdd  AverageHomeWinOdd  AvgOver2_5  \
40                 1.73               3.60               4.75        1.86   
41                 4.33               3.50               1.83        2.03   
42                 3.25               3.30               2.20        2.13   
43                 1.67               3.75               5.00        1.60   
44                 7.00               4.00               1.50        1.76   
...                 ...                ...                ...         ...   
4259               8.13               4.44               1.43        1.93   
4260               4.65               3.57               1.82        2.29   
4261               2.26               3.18               3.42        2.22   
4262               5.18               3.87               1.68        1.97   
4263               6.23               4.29               1.54        1.68   

      AvgUnder2_5  AwayGoals  AwayTeamId   AwayTeamName        Date    Div  \
40           1.92        2.0       554.0     Anderlecht  10/09/2010  144.0   
41           1.74        0.0       736.0      Charleroi  11/09/2010  144.0   
42           1.64        0.0       266.0       Mechelen  11/09/2010  144.0   
43           2.21        2.0       631.0           Gent  11/09/2010  144.0   
44           2.00        0.0       741.0  Cercle Brugge  11/09/2010  144.0   
...           ...        ...         ...            ...         ...    ...   
4259         1.90        0.0       798.0       Mallorca  16/10/2021  140.0   
4260         1.64        1.0       797.0          Elche  17/10/2021  140.0   
4261         1.68        1.0       536.0        Sevilla  17/10/2021  140.0   
4262         1.86        2.0       727.0        Osasuna  17/10/2021  140.0   
4263         2.20        1.0       532.0       Valencia  17/10/2021  140.0   

     FullTimeResult  HomeGoals HomeTeamName  HomeTeamid  Season  \
40                A        0.0   St Truiden       735.0  2010.0   
41                H        1.0     Germinal      4654.0  2010.0   
42                H        1.0     Kortrijk       734.0  2010.0   
43                D        2.0       Lierse      1392.0  2010.0   
44                H        2.0     Standard       733.0  2010.0   
...             ...        ...          ...         ...     ...   
4259              H        1.0     Sociedad       548.0  2021.0   
4260              H        2.0    Vallecano       728.0  2021.0   
4261              A        0.0        Celta       538.0  2021.0   
4262              A        1.0   Villarreal       533.0  2021.0   
4263              H        3.0    Barcelona       529.0  2021.0   

      away_away_clean_sheets  away_away_draws  away_away_goals_against  \
40                       2.0              1.0                      0.0   
41                       0.0              1.0                      6.0   
42                       0.0              0.0                      2.0   
43                       1.0              0.0                      1.0   
44                       1.0              1.0                      4.0   
...                      ...              ...                      ...   
4259                     1.0              0.0                      8.0   
4260                     1.0              0.0                      6.0   
4261                     2.0              2.0                      2.0   
4262                     1.0              0.0                      4.0   
4263                     1.0              2.0                      5.0   

      away_away_goals_for  away_away_loses  away_away_wins  \
40                    3.0              0.0             1.0   
41                    1.0              1.0             0.0   
42                    4.0              0.0             2.0   
43                    4.0              0.0             2.0   
44                    0.0              1.0             0.0   
...                   ...              ...             ...   
4259            

## Define indexes and labels

In [29]:
indexes = ['AverageAwayWinOdd', 'AverageDrawWinOdd', 'AverageHomeWinOdd',
               'AvgOver2_5', 'AvgUnder2_5', 'AwayGoals', 'AwayTeamId',
               'AwayTeamId', 'AwayTeamName', 'Date', 'Div',
               'HomeGoals', 'HomeTeamName', 'HomeTeamid', 'Season',
               ]
label = ['FullTimeResult']

In [30]:
print(footballdata_wTeamStats.drop(columns=indexes).dtypes.sort_index().to_string())

FullTimeResult                                  object
away_away_clean_sheets                         float64
away_away_draws                                float64
away_away_goals_against                        float64
away_away_goals_for                            float64
away_away_loses                                float64
away_away_wins                                 float64
away_failed_to_score_away                      float64
away_failed_to_score_home                      float64
away_failed_to_score_total                     float64
away_form_last10games_draws                    float64
away_form_last10games_loses                    float64
away_form_last10games_wins                     float64
away_form_last1games_draws                     float64
away_form_last1games_loses                     float64
away_form_last1games_wins                      float64
away_form_last2games_draws                     float64
away_form_last2games_loses                     float64
away_form_

In [31]:
list(set(footballdata_wTeamStats.columns.to_list())-set(indexes)-set(label))

['away_total_goals_for',
 'away_home_goals_against',
 'home_goals_against_minute_0_15_percentage',
 'away_form_last1games_loses',
 'home_total_goals_against',
 'away_total_draws',
 'away_away_clean_sheets',
 'home_home_goals_against',
 'home_goals_for_minute_31_45',
 'away_form_last1games_wins',
 'away_failed_to_score_home',
 'away_goals_for_minute_16_30_percentage',
 'home_home_clean_sheets',
 'home_goals_against_minute_61_75',
 'home_goals_for_minute_91_105_percentage',
 'home_form_last2games_loses',
 'home_goals_for_minute_0_15',
 'home_home_loses',
 'away_total_wins',
 'home_goals_for_minute_61_75',
 'home_goals_against_minute_46_60',
 'home_total_loses',
 'home_goals_against_minute_91_105_percentage',
 'away_goals_against_minute_46_60',
 'away_goals_against_minute_76_90',
 'away_goals_for_minute_61_75',
 'away_form_last2games_draws',
 'away_goals_against_minute_46_60_percentage',
 'home_away_draws',
 'away_away_loses',
 'away_away_wins',
 'away_total_clean_sheets',
 'away_total_ho

## Normalize Features (per game)

In [32]:
away_away_games_norm = ['away_away_clean_sheets', 'away_away_draws', 'away_away_goals_against',
                      'away_away_goals_for', 'away_away_loses', 'away_away_wins', 'away_failed_to_score_away']

away_home_games_norm = ['away_failed_to_score_home', 'away_home_clean_sheets',
                       'away_home_draws', 'away_home_goals_against', 'away_home_goals_for',
                       'away_home_loses', 'away_home_wins']

away_total_games_norm = ['away_failed_to_score_total', 'away_goals_against_minute_0_15',
                        'away_goals_against_minute_16_30', 'away_goals_against_minute_31_45',
                        'away_goals_against_minute_46_60', 'away_goals_against_minute_61_75',
                        'away_goals_against_minute_76_90', 'away_goals_against_minute_91_105',
                        'away_goals_for_minute_0_15', 'away_goals_for_minute_16_30',
                        'away_goals_for_minute_31_45', 'away_goals_for_minute_46_60',
                        'away_goals_for_minute_61_75', 'away_goals_for_minute_76_90',
                        'away_goals_for_minute_91_105', 'away_penalties_for', 'away_total_clean_sheets',
                        'away_total_draws', 'away_total_goals_against', 'away_total_goals_for', 'away_total_loses',
                        'away_total_wins']

home_away_games_norm = ['home_away_clean_sheets', 'home_away_draws', 'home_away_goals_against',
                      'home_away_goals_for', 'home_away_loses', 'home_away_wins', 'home_failed_to_score_away']

home_home_games_norm = ['home_failed_to_score_home', 'home_home_clean_sheets',
                       'home_home_draws', 'home_home_goals_against', 'home_home_goals_for',
                       'home_home_loses', 'home_home_wins']

home_total_games_norm = ['home_failed_to_score_total', 'home_goals_against_minute_0_15',
                        'home_goals_against_minute_16_30', 'home_goals_against_minute_31_45',
                        'home_goals_against_minute_46_60', 'home_goals_against_minute_61_75',
                        'home_goals_against_minute_76_90', 'home_goals_against_minute_91_105',
                        'home_goals_for_minute_0_15', 'home_goals_for_minute_16_30',
                        'home_goals_for_minute_31_45', 'home_goals_for_minute_46_60',
                        'home_goals_for_minute_61_75', 'home_goals_for_minute_76_90',
                        'home_goals_for_minute_91_105', 'home_penalties_for', 'home_total_clean_sheets',
                        'home_total_draws', 'home_total_goals_against', 'home_total_goals_for', 'home_total_loses',
                        'home_total_wins']

In [33]:
for feature in away_away_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['away_total_away_games']
for feature in away_home_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['away_total_home_games']
for feature in away_total_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['away_total_games']
    
for feature in home_away_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['home_total_away_games']
for feature in home_home_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['home_total_home_games']
for feature in home_total_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['home_total_games']
    
footballdata_wTeamStats

AvgUnder2_5  away_total_goals_for  away_home_goals_against  \
40           1.92              2.200000                 0.333333   
41           1.74              0.800000                 1.000000   
42           1.64              1.400000                 0.000000   
43           2.21              1.400000                 1.666667   
44           2.00              1.000000                 1.000000   
...           ...                   ...                      ...   
4259         1.90              0.875000                 0.800000   
4260         1.64              0.625000                 0.500000   
4261         1.68              1.428571                 0.333333   
4262         1.86              1.375000                 1.400000   
4263         2.20              1.500000                 0.750000   

      home_goals_against_minute_0_15_percentage        Date  \
40                                        33.33  10/09/2010   
41                                        28.57  11/09/2010   
42                                         0.00  11/09/2010   
43                                         8.33  11/09/2010   
44                                        16.67  11/09/2010   
...                                         ...         ...   
4259                                      14.29  16/10/2021   
4260                                       0.00  17/10/2021   
4261                                       0.00  17/10/2021   
4262                                       0.00  17/10/2021   
4263                                      14.29  17/10/2021   

      home_total_goals_against  home_home_goals_against  \
40                    1.200000                 0.000000   
41                    1.400000                 0.000000   
42                    0.600000                 0.000000   
43                    2.400000                 3.000000   
44                    1.200000                 1.333333   
...                        ...                      ...   
4259                  0.875000                 0.000000   
4260                  1.000000                 0.333333   
4261                  1.375000                 1.250000   
4262                  0.428571                 0.333333   
4263                  1.000000                 1.000000   

      away_away_clean_sheets  home_goals_for_minute_31_45  \
40                  1.000000                     0.000000   
41                  0.000000                     0.000000   
42                  0.000000                     0.000000   
43                  0.500000                     0.000000   
44                  0.500000                     0.200000   
...                      ...                          ...   
4259                0.333333                     0.125000   
4260                0.250000                     0.375000   
4261                0.500000                     0.125000   
4262                0.333333                     0.142857   
4263                0.250000                     0.000000   

      away_failed_to_score_home  away_goals_for_minute_16_30_percentage  \
40                     0.333333                                    0.00   
41                     0.333333                                    0.00   
42                     0.333333                                   14.29   
43                     0.333333                                    0.00   
44                     0.000000                                    0.00   
...                         ...                                     ...   
4259                   0.200000                                   37.50   
4260                   0.250000                                   20.00   
4261                   0.000000                                   20.00   
4262                   0.400000                                   16.67   
4263                   0.000000                                    9.09   

      home_home_clean_sheets  home_goals_against_minute_61_75  \
40                  1.00

In [34]:
#TODO: this is based only on home team games (for most cases should be ok)
footballdata_wTeamStats['total_games'] = footballdata_wTeamStats['home_total_games']
footballdata_wTeamStats = \
    footballdata_wTeamStats.drop(columns=['away_total_away_games','away_total_home_games', 'away_total_games',
                                          'home_total_away_games', 'home_total_home_games', 'home_total_games'])
footballdata_wTeamStats

AvgUnder2_5  away_total_goals_for  away_home_goals_against  \
40           1.92              2.200000                 0.333333   
41           1.74              0.800000                 1.000000   
42           1.64              1.400000                 0.000000   
43           2.21              1.400000                 1.666667   
44           2.00              1.000000                 1.000000   
...           ...                   ...                      ...   
4259         1.90              0.875000                 0.800000   
4260         1.64              0.625000                 0.500000   
4261         1.68              1.428571                 0.333333   
4262         1.86              1.375000                 1.400000   
4263         2.20              1.500000                 0.750000   

      home_goals_against_minute_0_15_percentage        Date  \
40                                        33.33  10/09/2010   
41                                        28.57  11/09/2010   
42                                         0.00  11/09/2010   
43                                         8.33  11/09/2010   
44                                        16.67  11/09/2010   
...                                         ...         ...   
4259                                      14.29  16/10/2021   
4260                                       0.00  17/10/2021   
4261                                       0.00  17/10/2021   
4262                                       0.00  17/10/2021   
4263                                      14.29  17/10/2021   

      home_total_goals_against  home_home_goals_against  \
40                    1.200000                 0.000000   
41                    1.400000                 0.000000   
42                    0.600000                 0.000000   
43                    2.400000                 3.000000   
44                    1.200000                 1.333333   
...                        ...                      ...   
4259                  0.875000                 0.000000   
4260                  1.000000                 0.333333   
4261                  1.375000                 1.250000   
4262                  0.428571                 0.333333   
4263                  1.000000                 1.000000   

      away_away_clean_sheets  home_goals_for_minute_31_45  \
40                  1.000000                     0.000000   
41                  0.000000                     0.000000   
42                  0.000000                     0.000000   
43                  0.500000                     0.000000   
44                  0.500000                     0.200000   
...                      ...                          ...   
4259                0.333333                     0.125000   
4260                0.250000                     0.375000   
4261                0.500000                     0.125000   
4262                0.333333                     0.142857   
4263                0.250000                     0.000000   

      away_failed_to_score_home  away_goals_for_minute_16_30_percentage  \
40                     0.333333                                    0.00   
41                     0.333333                                    0.00   
42                     0.333333                                   14.29   
43                     0.333333                                    0.00   
44                     0.000000                                    0.00   
...                         ...                                     ...   
4259                   0.200000                                   37.50   
4260                   0.250000                                   20.00   
4261                   0.000000                                   20.00   
4262                   0.400000                                   16.67   
4263                   0.000000                                    9.09   

      home_home_clean_sheets  home_goals_against_minute_61_75  \
40                  1.00

## Extract Features

In [35]:
footballdata_wTeamStats.groupby('FullTimeResult').count()

AvgUnder2_5  away_total_goals_for  away_home_goals_against  \
FullTimeResult                                                               
A                     12524                 12495                    12495   
D                     11275                 11222                    11222   
H                     19353                 19250                    19249   

                home_goals_against_minute_0_15_percentage   Date  \
FullTimeResult                                                     
A                                                   12546  12546   
D                                                   11284  11284   
H                                                   19385  19385   

                home_total_goals_against  home_home_goals_against  \
FullTimeResult                                                      
A                                  12546                    12546   
D                                  11284                    11284   
H                                  19385                    19385   

                away_away_clean_sheets  home_goals_for_minute_31_45  \
FullTimeResult                                                        
A                                12495                        12546   
D                                11222                        11284   
H                                19250                        19385   

                away_failed_to_score_home  \
FullTimeResult                              
A                                   12495   
D                                   11222   
H                                   19249   

                away_goals_for_minute_16_30_percentage  \
FullTimeResult                                           
A                                                12546   
D                                                11284   
H                                                19385   

                home_home_clean_sheets  home_goals_against_minute_61_75  \
FullTimeResult                                                            
A                                12546                            12546   
D                                11284                            11284   
H                                19385                            19385   

                home_goals_for_minute_91_105_percentage  \
FullTimeResult                                            
A                                                 12546   
D                                                 11284   
H                                                 19385   

                home_goals_for_minute_0_15  home_home_loses  \
FullTimeResult                                                
A                                    12546            12546   
D                                    11284            11284   
H                                    19385            19385   

                home_goals_for_minute_61_75  home_goals_against_minute_46_60  \
FullTimeResult                                                                 
A                                     12546                            12546   
D                                     11284                            11284   
H                                     19385                            19385   

                AwayTeamName  home_goals_against_minute_91_105_percentage  \
FullTimeResult                                                              
A                      12546                                        12546   
D                      11284                                        11284   
H                      19385                                        19385   

                away_goals_against_minute_46_60  AvgOver2_5  \
FullTimeResult                                                
A                                         12495       12524   
D                                         11222       11275   
H                                     

In [49]:
footballdata_wTeamStats = footballdata_wTeamStats.dropna()
footballdata_wTeamStats.groupby('FullTimeResult').count()

AvgUnder2_5  away_total_goals_for  away_home_goals_against  \
FullTimeResult                                                               
A                     12461                 12461                    12461   
D                     11206                 11206                    11206   
H                     19191                 19191                    19191   

                home_goals_against_minute_0_15_percentage   Date  \
FullTimeResult                                                     
A                                                   12461  12461   
D                                                   11206  11206   
H                                                   19191  19191   

                home_total_goals_against  home_home_goals_against  \
FullTimeResult                                                      
A                                  12461                    12461   
D                                  11206                    11206   
H                                  19191                    19191   

                away_away_clean_sheets  home_goals_for_minute_31_45  \
FullTimeResult                                                        
A                                12461                        12461   
D                                11206                        11206   
H                                19191                        19191   

                away_failed_to_score_home  \
FullTimeResult                              
A                                   12461   
D                                   11206   
H                                   19191   

                away_goals_for_minute_16_30_percentage  \
FullTimeResult                                           
A                                                12461   
D                                                11206   
H                                                19191   

                home_home_clean_sheets  home_goals_against_minute_61_75  \
FullTimeResult                                                            
A                                12461                            12461   
D                                11206                            11206   
H                                19191                            19191   

                home_goals_for_minute_91_105_percentage  \
FullTimeResult                                            
A                                                 12461   
D                                                 11206   
H                                                 19191   

                home_goals_for_minute_0_15  home_home_loses  \
FullTimeResult                                                
A                                    12461            12461   
D                                    11206            11206   
H                                    19191            19191   

                home_goals_for_minute_61_75  home_goals_against_minute_46_60  \
FullTimeResult                                                                 
A                                     12461                            12461   
D                                     11206                            11206   
H                                     19191                            19191   

                AwayTeamName  home_goals_against_minute_91_105_percentage  \
FullTimeResult                                                              
A                      12461                                        12461   
D                      11206                                        11206   
H                      19191                                        19191   

                away_goals_against_minute_46_60  AvgOver2_5  \
FullTimeResult                                                
A                                         12461       12461   
D                                         11206       11206   
H                                     

In [50]:
X = footballdata_wTeamStats[list(set(footballdata_wTeamStats.columns.to_list())-set(indexes)-set(label))].values
y = footballdata_wTeamStats[label].values
y = y.reshape((y.shape[0],))
y = np.array([0 if label=='H' else 1 if label=='D' else 2 for label in y])

In [51]:
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
X

array([[ 1.80295633, -0.9665123 ,  1.58388787, ..., -0.93586796,
         0.85986247, -0.79009461],
       [-1.11111265, -0.9665123 , -0.99686078, ..., -0.93586796,
         0.85986247, -2.39904393],
       [ 0.13777406, -0.9665123 ,  1.58388787, ..., -0.93586796,
        -0.56559497,  0.01438004],
       ...,
       [ 0.19724485,  1.1178651 ,  0.61610713, ..., -0.93586796,
         0.04531536, -1.19233194],
       [ 0.08573711,  4.50497838,  0.84653111, ...,  0.95185703,
        -0.20923061,  0.8188547 ],
       [ 0.34592184,  0.85731792,  0.84653111, ..., -0.93586796,
        -1.10014151,  1.62332936]])

In [52]:
print ('The first element of X is: ', X[0])

The first element of X is:  [ 1.80295633e+00 -9.66512305e-01  1.58388787e+00 -1.76963470e+00
  2.61392968e+00 -6.51893584e-01 -3.13692124e-01  1.13406336e+00
 -1.69403217e+00  1.08195810e+00  4.42194382e+00 -2.40445206e+00
 -1.57753083e+00 -8.33045305e-01  9.87416124e-02 -1.57818253e+00
  5.87467388e-01 -1.71513308e+00  1.60014501e-01 -8.28259245e-01
  3.55992467e+00  1.09199519e+00 -1.78052584e+00 -9.24749209e-01
 -1.04472128e+00  8.36197884e-01  2.96812621e-01 -1.46602215e+00
  1.33946401e+00 -1.91252632e+00 -1.64492756e+00 -6.54135129e-01
  1.45471753e+00  1.19262915e+00  2.24319570e+00  2.03690894e-01
 -1.54885642e+00 -9.45567091e-01 -1.55673761e+00 -9.91866160e-01
  3.50427258e+00 -1.77263872e+00  9.97400190e+00  9.66995510e-01
 -1.74479895e+00  5.56734226e+00 -9.29757850e-01  1.94505090e+00
 -2.69543730e+00  2.03011045e+00 -1.93924730e+00 -1.77706272e+00
  3.89493900e-01 -2.02275912e+00  2.50543740e+00  1.02632942e+00
  3.78732793e+00  2.19983893e-02 -1.94279973e+00  1.89903409e-

In [53]:
print ('The first element of y is: ', y[0])
print ('The last element of y is: ', y[-1])

The first element of y is:  2
The last element of y is:  0


In [54]:
print ('The shape of X is: ' + str(X.shape))
print ('The shape of y is: ' + str(y.shape))

The shape of X is: (42858, 125)
The shape of y is: (42858,)


In [55]:
#train_size = int(X.shape[0]*0.8)
#train_size

In [56]:
#X_train = X[:train_size]
#print(X_train.shape)
#X_test = X[train_size:]
#print(X_test.shape)

In [57]:
#y_train = y[:train_size]
#print(y_train.shape)
#y_test = y[train_size:]
#print(y_test.shape)

In [58]:
X_train, X_test, y_train, y_test \
    = train_test_split(X, y, test_size=0.2, random_state=1)

X_train, X_val, y_train, y_val \
    = train_test_split(X_train, y_train, test_size=0.25, random_state=1) # 0.25 x 0.8 = 0.2

In [59]:
print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

(25714, 125)
(8572, 125)
(8572, 125)


In [60]:
print(y_train.shape)
print(y_val.shape)
print(y_test.shape)

(25714,)
(8572,)
(8572,)


# ML Algorithms

In [61]:
def accuracy(confusion_matrix):
    diagonal_sum = confusion_matrix.trace()
    sum_of_all_elements = confusion_matrix.sum()
    return diagonal_sum / sum_of_all_elements

## MLP

In [63]:
model = Sequential(
    [ 
        tf.keras.Input(shape=(125,)),
        Dense(60, activation = 'relu', name='L1', kernel_regularizer=tf.keras.regularizers.l2(0.1)),
        Dense(20, activation = 'relu', name='L2', kernel_regularizer=tf.keras.regularizers.l2(0.1)),
        Dense(3, activation = 'linear', name='L3')    # < softmax activation here
    ]
)
model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.Adam(0.0001),
)
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 L1 (Dense)                  (None, 60)                7560      
                                                                 
 L2 (Dense)                  (None, 20)                1220      
                                                                 
 L3 (Dense)                  (None, 3)                 63        
                                                                 
Total params: 8,843
Trainable params: 8,843
Non-trainable params: 0
_________________________________________________________________


In [64]:
model.fit(
    X_train,y_train,
    epochs=1000
)

Epoch 1/1000
804/804 [==============================] - 1s 924us/step - loss: 8.3841
Epoch 2/1000
804/804 [==============================] - 1s 880us/step - loss: 3.5114
Epoch 3/1000
804/804 [==============================] - 1s 793us/step - loss: 1.7418
Epoch 4/1000
804/804 [==============================] - 1s 811us/step - loss: 1.2106
Epoch 5/1000
804/804 [==============================] - 1s 790us/step - loss: 1.0787
Epoch 6/1000
804/804 [==============================] - 1s 799us/step - loss: 1.0502
Epoch 7/1000
804/804 [==============================] - 1s 819us/step - loss: 1.0435
Epoch 8/1000
804/804 [==============================] - 1s 830us/step - loss: 1.0409
Epoch 9/1000
804/804 [==============================] - 1s 791us/step - loss: 1.0389
Epoch 10/1000
804/804 [==============================] - 1s 786us/step - loss: 1.0377
Epoch 11/1000
804/804 [==============================] - 1s 804us/step - loss: 1.0364
Epoch 12/1000
804/804 [==============================] - 1s 769

804/804 [==============================] - 1s 851us/step - loss: 1.0211
Epoch 191/1000
804/804 [==============================] - 1s 837us/step - loss: 1.0212
Epoch 192/1000
804/804 [==============================] - 1s 815us/step - loss: 1.0211
Epoch 193/1000
804/804 [==============================] - 1s 826us/step - loss: 1.0210
Epoch 194/1000
804/804 [==============================] - 1s 817us/step - loss: 1.0211
Epoch 195/1000
804/804 [==============================] - 1s 834us/step - loss: 1.0210
Epoch 196/1000
804/804 [==============================] - 1s 848us/step - loss: 1.0210
Epoch 197/1000
804/804 [==============================] - 1s 833us/step - loss: 1.0209
Epoch 198/1000
804/804 [==============================] - 1s 1ms/step - loss: 1.0210
Epoch 199/1000
804/804 [==============================] - 1s 852us/step - loss: 1.0208
Epoch 200/1000
804/804 [==============================] - 1s 828us/step - loss: 1.0208
Epoch 201/1000
804/804 [==============================] - 1s

804/804 [==============================] - 1s 815us/step - loss: 1.0186
Epoch 379/1000
804/804 [==============================] - 1s 848us/step - loss: 1.0186
Epoch 380/1000
804/804 [==============================] - 1s 865us/step - loss: 1.0185
Epoch 381/1000
804/804 [==============================] - 1s 840us/step - loss: 1.0184
Epoch 382/1000
804/804 [==============================] - 1s 835us/step - loss: 1.0185
Epoch 383/1000
804/804 [==============================] - 1s 821us/step - loss: 1.0185
Epoch 384/1000
804/804 [==============================] - 1s 845us/step - loss: 1.0186
Epoch 385/1000
804/804 [==============================] - 1s 852us/step - loss: 1.0186
Epoch 386/1000
804/804 [==============================] - 1s 854us/step - loss: 1.0184
Epoch 387/1000
804/804 [==============================] - 1s 830us/step - loss: 1.0186
Epoch 388/1000
804/804 [==============================] - 1s 844us/step - loss: 1.0185
Epoch 389/1000
804/804 [==============================] - 

804/804 [==============================] - 1s 841us/step - loss: 1.0172
Epoch 567/1000
804/804 [==============================] - 1s 870us/step - loss: 1.0173
Epoch 568/1000
804/804 [==============================] - 1s 926us/step - loss: 1.0172
Epoch 569/1000
804/804 [==============================] - 1s 1ms/step - loss: 1.0172
Epoch 570/1000
804/804 [==============================] - 1s 1ms/step - loss: 1.0172
Epoch 571/1000
804/804 [==============================] - 1s 863us/step - loss: 1.0173
Epoch 572/1000
804/804 [==============================] - 1s 1ms/step - loss: 1.0173
Epoch 573/1000
804/804 [==============================] - 1s 967us/step - loss: 1.0172
Epoch 574/1000
804/804 [==============================] - 1s 985us/step - loss: 1.0172
Epoch 575/1000
804/804 [==============================] - 1s 1ms/step - loss: 1.0171
Epoch 576/1000
804/804 [==============================] - 1s 848us/step - loss: 1.0170
Epoch 577/1000
804/804 [==============================] - 1s 849us

804/804 [==============================] - 1s 951us/step - loss: 1.0166
Epoch 755/1000
804/804 [==============================] - 1s 845us/step - loss: 1.0166
Epoch 756/1000
804/804 [==============================] - 1s 888us/step - loss: 1.0165
Epoch 757/1000
804/804 [==============================] - 1s 843us/step - loss: 1.0165
Epoch 758/1000
804/804 [==============================] - 1s 846us/step - loss: 1.0164
Epoch 759/1000
804/804 [==============================] - 1s 883us/step - loss: 1.0164
Epoch 760/1000
804/804 [==============================] - 1s 890us/step - loss: 1.0166
Epoch 761/1000
804/804 [==============================] - 1s 890us/step - loss: 1.0165
Epoch 762/1000
804/804 [==============================] - 1s 926us/step - loss: 1.0167
Epoch 763/1000
804/804 [==============================] - 1s 980us/step - loss: 1.0165
Epoch 764/1000
804/804 [==============================] - 1s 861us/step - loss: 1.0165
Epoch 765/1000
804/804 [==============================] - 

804/804 [==============================] - 1s 1ms/step - loss: 1.0158
Epoch 943/1000
804/804 [==============================] - 1s 978us/step - loss: 1.0161
Epoch 944/1000
804/804 [==============================] - 1s 1ms/step - loss: 1.0160
Epoch 945/1000
804/804 [==============================] - 1s 909us/step - loss: 1.0160
Epoch 946/1000
804/804 [==============================] - 1s 915us/step - loss: 1.0160
Epoch 947/1000
804/804 [==============================] - 1s 831us/step - loss: 1.0159
Epoch 948/1000
804/804 [==============================] - 1s 853us/step - loss: 1.0159
Epoch 949/1000
804/804 [==============================] - 1s 879us/step - loss: 1.0159
Epoch 950/1000
804/804 [==============================] - 1s 855us/step - loss: 1.0160
Epoch 951/1000
804/804 [==============================] - 1s 1ms/step - loss: 1.0156
Epoch 952/1000
804/804 [==============================] - 1s 895us/step - loss: 1.0160
Epoch 953/1000
804/804 [==============================] - 1s 866

In [65]:
[layer1, layer2, layer3] = model.layers
W1,b1 = layer1.get_weights()
W2,b2 = layer2.get_weights()
W3,b3 = layer3.get_weights()

In [66]:
W1

array([[-4.16545469e-34,  2.28909066e-34, -4.43431137e-34, ...,
         4.73008480e-35,  2.74443123e-02,  4.81219194e-34],
       [-3.44551537e-34,  8.43791886e-35, -4.56865752e-34, ...,
         4.44224963e-34,  1.21035874e-02, -5.61834321e-34],
       [ 4.82077534e-34, -1.31393935e-34, -1.60739979e-34, ...,
        -2.31593050e-36, -1.39638381e-02, -4.48177287e-34],
       ...,
       [ 2.77141803e-34,  4.81286142e-34,  4.70644428e-34, ...,
         9.56713213e-35,  3.99228791e-03,  3.88297972e-34],
       [-4.66255197e-34,  5.41383796e-34, -1.81721038e-34, ...,
        -8.52118151e-35, -6.10954734e-03,  1.35813851e-34],
       [-4.60950939e-35, -3.80626816e-34,  4.69605723e-34, ...,
        -3.98308684e-35, -1.08247565e-04, -4.86185037e-35]], dtype=float32)

In [67]:
y_train_pred_probs = tf.nn.softmax(model.predict(X_train)).numpy()
y_train_pred_probs

804/804 [==============================] - 1s 697us/step


array([[0.7952788 , 0.14715494, 0.05756623],
       [0.7068743 , 0.18981138, 0.10331434],
       [0.50239176, 0.2634983 , 0.23410992],
       ...,
       [0.44250584, 0.28360578, 0.27388838],
       [0.5612564 , 0.25142023, 0.18732344],
       [0.40958664, 0.28923014, 0.30118322]], dtype=float32)

In [68]:
y_test_pred_probs = tf.nn.softmax(model.predict(X_test)).numpy()
y_test_pred_probs

268/268 [==============================] - 0s 788us/step


array([[0.27684802, 0.2821549 , 0.44099715],
       [0.4004097 , 0.2763508 , 0.32323954],
       [0.31941196, 0.2879011 , 0.39268696],
       ...,
       [0.39905763, 0.28965127, 0.31129107],
       [0.20041792, 0.26061717, 0.53896487],
       [0.36572385, 0.28785828, 0.3464178 ]], dtype=float32)

In [69]:
y_train_pred = np.argmax(y_train_pred_probs, axis=1)
y_test_pred = np.argmax(y_test_pred_probs, axis=1)

In [70]:
cm_train = confusion_matrix(y_train_pred, y_train)
cm_train

array([[9603, 4960, 4190],
       [   0,    0,    0],
       [1912, 1804, 3245]], dtype=int64)

In [71]:
cm_test = confusion_matrix(y_test_pred, y_test)
cm_test

array([[3191, 1583, 1441],
       [   0,    0,    0],
       [ 629,  637, 1091]], dtype=int64)

In [72]:
for i in range(10):
    print( f"{y_train_pred_probs[-i]}, predicted_category: {np.argmax(y_train_pred_probs[-i])}, category: {y_train[-i]}")

[0.7952788  0.14715494 0.05756623], predicted_category: 0, category: 0
[0.40958664 0.28923014 0.30118322], predicted_category: 0, category: 2
[0.5612564  0.25142023 0.18732344], predicted_category: 0, category: 0
[0.44250584 0.28360578 0.27388838], predicted_category: 0, category: 0
[0.50021845 0.26706627 0.2327153 ], predicted_category: 0, category: 2
[0.51173556 0.26680377 0.22146067], predicted_category: 0, category: 2
[0.59141207 0.23968618 0.16890185], predicted_category: 0, category: 0
[0.35628113 0.2898111  0.35390776], predicted_category: 0, category: 2
[0.24000552 0.27314988 0.4868446 ], predicted_category: 2, category: 2
[0.3875445  0.29044512 0.32201037], predicted_category: 0, category: 1


In [73]:
for i in range(10):
    print( f"{y_test_pred_probs[-i]}, predicted_category: {np.argmax(y_test_pred_probs[-i])}, category: {y_test[-i]}")

[0.27684802 0.2821549  0.44099715], predicted_category: 2, category: 0
[0.36572385 0.28785828 0.3464178 ], predicted_category: 0, category: 2
[0.20041792 0.26061717 0.53896487], predicted_category: 2, category: 2
[0.39905763 0.28965127 0.31129107], predicted_category: 0, category: 0
[0.32027367 0.28766364 0.39206278], predicted_category: 2, category: 0
[0.5448222  0.25132814 0.20384964], predicted_category: 0, category: 2
[0.4864392  0.27250597 0.24105482], predicted_category: 0, category: 0
[0.3629093  0.29073986 0.34635088], predicted_category: 0, category: 0
[0.42141932 0.28654402 0.29203665], predicted_category: 0, category: 2
[0.7353725  0.17758726 0.08704021], predicted_category: 0, category: 0


In [74]:
print('Train accuracy: '+ str(accuracy(cm_train)))
print('Test accuracy: '+ str(accuracy(cm_test)))

Train accuracy: 0.4996499961110679
Test accuracy: 0.4995333644423705


## GBT

### Test changing only max_depth

In [75]:
max_val_score = 0
iterations_wo_update = 0
for max_depth in range(125):
    max_depth += 1 # start on 1
    print(f"Testing Max Depth: {max_depth}")
    gbtClassifier = GradientBoostingClassifier(max_depth = max_depth, n_iter_no_change=7, verbose=1).fit(X_train, y_train)
    val_score = gbtClassifier.score(X_val, y_val)
    if val_score > max_val_score:
        iterations_wo_update = 0
        best_max_depth = max_depth
        max_val_score = val_score
        best_model = gbtClassifier
        print(f"New best max depth: {best_max_depth}, validation score: {max_val_score}")
    else:
        iterations_wo_update +=1
        if iterations_wo_update >= 10:
            print("No improvements on the last 10 iterations, stopping here...")
            break
            
gbtClassifier = best_model

Testing Max Depth: 1
      Iter       Train Loss   Remaining Time 
         1           1.0656           32.25s
         2           1.0618           32.29s
         3           1.0585           32.03s
         4           1.0556           31.80s
         5           1.0528           31.49s
         6           1.0504           31.05s
         7           1.0482           30.69s
         8           1.0462           30.36s
         9           1.0442           29.88s
        10           1.0424           29.55s
        20           1.0298           25.41s
        30           1.0226           21.96s
        40           1.0181           18.95s
        50           1.0149           15.77s
        60           1.0127           12.61s
        70           1.0109            9.44s
        80           1.0095            6.27s
        90           1.0084            3.13s
       100           1.0074            0.00s
New best max depth: 1, validation score: 0.4889174055062996
Testing Max Depth:

In [76]:
best_model.score(X_train, y_train)

0.49758886209846775

In [77]:
best_model.score(X_test, y_test)

0.4986000933271115

In [78]:
y_train_pred = gbtClassifier.predict(X_train)
y_test_pred = gbtClassifier.predict(X_test)

In [79]:
cm_train = confusion_matrix(y_train_pred, y_train)
cm_train

array([[10023,  5303,  4672],
       [   22,    29,    20],
       [ 1470,  1432,  2743]], dtype=int64)

In [80]:
cm_test = confusion_matrix(y_test_pred, y_test)
cm_test

array([[3342, 1706, 1597],
       [  10,    6,    9],
       [ 468,  508,  926]], dtype=int64)

### Test changing also n_estimators

In [81]:
gbtClassifier = GradientBoostingClassifier(n_estimators=20, verbose=1).fit(X_train, y_train)
print(gbtClassifier.score(X_train, y_train))
gbtClassifier.score(X_test, y_test)

      Iter       Train Loss   Remaining Time 
         1           1.0605           19.28s
         2           1.0529           18.00s
         3           1.0463           17.03s
         4           1.0409           16.72s
         5           1.0361           15.48s
         6           1.0319           14.35s
         7           1.0284           13.24s
         8           1.0252           12.17s
         9           1.0225           11.11s
        10           1.0201           10.07s
        20           1.0053            0.00s
0.5003111145679396


0.49848343443770415

In [82]:
max_val_score = 0
for n_estimators in range(5,100,5):
    print(f"Testing N Estimators: {n_estimators}")
    iterations_wo_update = 0
    for max_depth in range(125):
        max_depth += 1 # start on 1
        gbtClassifier = GradientBoostingClassifier(max_depth = max_depth, n_estimators=n_estimators).fit(X_train, y_train)
        val_score = gbtClassifier.score(X_val, y_val)
        if val_score > max_val_score:
            iterations_wo_update = 0
            best_max_depth = max_depth
            max_val_score = val_score
            best_model = gbtClassifier
            print(f"New best max depth and N estimators: ({best_max_depth}, {n_estimators}), validation score: {max_val_score}")
        else:
            iterations_wo_update +=1
            if iterations_wo_update >= 10:
                print("No improvements on the last 10 iterations, moving on...")
                break
            
gbtClassifier = best_model

Testing N Estimators: 5
New best max depth and N estimators: (1, 5), validation score: 0.4498366775548297
New best max depth and N estimators: (2, 5), validation score: 0.46978534764349045
New best max depth and N estimators: (3, 5), validation score: 0.47316845543630426
New best max depth and N estimators: (4, 5), validation score: 0.4788847410172655
New best max depth and N estimators: (5, 5), validation score: 0.4794680354643024
No improvements on the last 10 iterations, moving on...
Testing N Estimators: 10
New best max depth and N estimators: (3, 10), validation score: 0.4836677554829678
New best max depth and N estimators: (4, 10), validation score: 0.4841343910405973
New best max depth and N estimators: (5, 10), validation score: 0.4849510032664489
No improvements on the last 10 iterations, moving on...
Testing N Estimators: 15
New best max depth and N estimators: (3, 15), validation score: 0.48611759216052264
New best max depth and N estimators: (4, 15), validation score: 0.486

In [83]:
gbtClassifier.score(X_train, y_train)

0.5594617717974644

In [84]:
gbtClassifier.score(X_test, y_test)

0.4996500233317779

In [85]:
y_train_pred = gbtClassifier.predict(X_train)
y_test_pred = gbtClassifier.predict(X_test)

In [86]:
cm_train = confusion_matrix(y_train_pred, y_train)
cm_train

array([[10198,  4701,  3894],
       [   45,   698,    51],
       [ 1272,  1365,  3490]], dtype=int64)

In [87]:
cm_test = confusion_matrix(y_test_pred, y_test)
cm_test

array([[3233, 1595, 1495],
       [  61,   50,   37],
       [ 526,  575, 1000]], dtype=int64)