# Imports

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

import os
from datetime import datetime, timedelta

In [2]:
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier

In [3]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Variables

In [4]:
footballdata_wTeamStats_path = \
    os.path.abspath(os.getcwd())+"\\Data\\teamStats_byLeague"

In [5]:
for filename in [f for f in os.listdir(footballdata_wTeamStats_path)]:
    print(filename)

footballdata_wTeamStats_Belgium_Jupiler.csv
footballdata_wTeamStats_England_Championship.csv
footballdata_wTeamStats_englishpremierleague.csv
footballdata_wTeamStats_France_Ligue1.csv
footballdata_wTeamStats_France_Ligue2.csv
footballdata_wTeamStats_Germany_Bundesliga1.csv
footballdata_wTeamStats_Germany_Bundesliga2.csv
footballdata_wTeamStats_Greece_SuperLeague.csv
footballdata_wTeamStats_Italy_SerieA.csv
footballdata_wTeamStats_Italy_SerieB.csv
footballdata_wTeamStats_Netherlands_Eredivisie.csv
footballdata_wTeamStats_Portugal_PrimeiraLiga.csv
footballdata_wTeamStats_Spain_Laliga.csv
footballdata_wTeamStats_Spain_Laliga2.csv
footballdata_wTeamStats_Turkey_SuperLeague.csv


# Load Football-Data File with Indexes

In [6]:
footballdata_wTeamStats = pd.DataFrame()
for filename in [f for f in os.listdir(footballdata_wTeamStats_path)]:
    footballdata_wTeamStats = footballdata_wTeamStats.append(pd.read_csv(footballdata_wTeamStats_path+"\\"+filename, 
                                                                         index_col=0))
footballdata_wTeamStats

C:\Users\ldoutors\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (96,113,194,211) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
C:\Users\ldoutors\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (96,194) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
C:\Users\ldoutors\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (113,194) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


AverageAwayWinOdd  AverageDrawWinOdd  AverageHomeWinOdd  AvgOver2_5  \
0                  4.75               3.60               1.73        1.93   
1                 10.00               6.50               1.20        1.51   
2                  1.91               3.30               3.75        1.77   
3                  3.80               3.30               1.91        1.76   
4                  3.20               3.20               2.10        1.84   
...                 ...                ...                ...         ...   
3805               3.73               3.64               1.94        1.83   
3806               7.10               4.59               1.43        1.72   
3807               3.66               3.51               1.99        1.89   
3808               2.31               3.41               2.99        1.82   
3809               2.37               3.55               2.81        1.68   

      AvgUnder2_5  AwayGoals  AwayTeamId AwayTeamName        Date    Div  \
0            1.83        1.0       600.0      Waregem  30/07/2010  144.0   
1            2.41        1.0       739.0        Eupen  31/07/2010  144.0   
2            2.01        0.0       569.0  Club Brugge  31/07/2010  144.0   
3            2.00        0.0       737.0      Lokeren  31/07/2010  144.0   
4            1.93        0.0      1392.0       Lierse  31/07/2010  144.0   
...           ...        ...         ...          ...         ...    ...   
3805         1.97        0.0      1002.0    Sivasspor  13/08/2022  203.0   
3806         2.10        1.0      3574.0  Giresunspor  13/08/2022  203.0   
3807         1.90        0.0      1010.0   Ankaragucu  14/08/2022  203.0   
3808         1.98        1.0      1005.0  Antalyaspor  14/08/2022  203.0   
3809         2.15        3.0       549.0     Besiktas  14/08/2022  203.0   

     FullTimeResult  HomeGoals   HomeTeamName  HomeTeamid  Season  \
0                 D        1.0       Standard       733.0  2010.0   
1                 H        4.0     Anderlecht       554.0  2010.0   
2                 H        1.0       Kortrijk       734.0  2010.0   
3                 H        2.0       Mechelen       266.0  2010.0   
4                 H        1.0     St Truiden       735.0  2010.0   
...             ...        ...            ...         ...     ...   
3805              H        3.0  Ad. Demirspor      3563.0  2022.0   
3806              A        0.0    Galatasaray       645.0  2022.0   
3807              H        1.0      Gaziantep      3573.0  2022.0   
3808              A        0.0   Umraniyespor      3577.0  2022.0   
3809              D        3.0     Alanyaspor       996.0  2022.0   

      away_average_away_goals_against  away_average_away_goals_for  \
0                                 0.0                          0.0   
1                                 0.0                          0.0   
2                                 0.0                          0.0   
3                                 0.0                          0.0   
4                                 0.0                          0.0   
...                               ...                          ...   
3805                              0.0                          0.0   
3806                              0.0                          0.0   
3807                              0.0                          0.0   
3808                              0.0                          0.0   
3809                              0.0                          0.0   

      away_average_home_goals_against  away_average_home_goals_for  \
0                                 0.0                          0.0   
1                                 0.0                          0.0   
2                                 0.0                          0.0   
3                                 0.0                          0.0   
4                                 0.0                          0.0   
...                               ...                          ...   
3805    

# Data Prep

## Remove Incomplete Columns & Non important (except indexes)

In [7]:
not_complete = ['away_red_cards_minute_0_15', 'away_red_cards_minute_0_15_percentage',
               'away_red_cards_minute_16_30', 'away_red_cards_minute_16_30_percentage',
               'away_red_cards_minute_31_45', 'away_red_cards_minute_31_45_percentage',
               'away_red_cards_minute_46_60', 'away_red_cards_minute_46_60_percentage',
               'away_red_cards_minute_61_75', 'away_red_cards_minute_61_75_percentage',
               'away_red_cards_minute_61_75', 'away_red_cards_minute_61_75_percentage',
               'away_red_cards_minute_76_90', 'away_red_cards_minute_76_90_percentage',
               'away_red_cards_minute_91_105', 'away_red_cards_minute_91_105_percentage',
               'away_yellow_cards_minute_0_15', 'away_yellow_cards_minute_0_15_percentage',
               'away_yellow_cards_minute_16_30', 'away_yellow_cards_minute_16_30_percentage',
               'away_yellow_cards_minute_31_45', 'away_yellow_cards_minute_31_45_percentage',
               'away_yellow_cards_minute_46_60', 'away_yellow_cards_minute_46_60_percentage',
               'away_yellow_cards_minute_61_75', 'away_yellow_cards_minute_61_75_percentage',
               'away_yellow_cards_minute_76_90', 'away_yellow_cards_minute_76_90_percentage',
               'away_yellow_cards_minute_91_105', 'away_yellow_cards_minute_91_105_percentage',
                'home_red_cards_minute_0_15', 'home_red_cards_minute_0_15_percentage',
               'home_red_cards_minute_16_30', 'home_red_cards_minute_16_30_percentage',
               'home_red_cards_minute_31_45', 'home_red_cards_minute_31_45_percentage',
               'home_red_cards_minute_46_60', 'home_red_cards_minute_46_60_percentage',
               'home_red_cards_minute_61_75', 'home_red_cards_minute_61_75_percentage',
               'home_red_cards_minute_61_75', 'home_red_cards_minute_61_75_percentage',
               'home_red_cards_minute_76_90', 'home_red_cards_minute_76_90_percentage',
               'home_red_cards_minute_91_105', 'home_red_cards_minute_91_105_percentage',
               'home_yellow_cards_minute_0_15', 'home_yellow_cards_minute_0_15_percentage',
               'home_yellow_cards_minute_16_30', 'home_yellow_cards_minute_16_30_percentage',
               'home_yellow_cards_minute_31_45', 'home_yellow_cards_minute_31_45_percentage',
               'home_yellow_cards_minute_46_60', 'home_yellow_cards_minute_46_60_percentage',
               'home_yellow_cards_minute_61_75', 'home_yellow_cards_minute_61_75_percentage',
               'home_yellow_cards_minute_76_90', 'home_yellow_cards_minute_76_90_percentage',
               'home_yellow_cards_minute_91_105', 'home_yellow_cards_minute_91_105_percentage']

# away average goals and home average goals will be removed because we will average all columns
not_features = [
               'away_biggest_away_lose', 'away_biggest_away_win', 'away_biggest_home_lose', 'away_biggest_home_win',
               'away_lineups',
               'home_biggest_away_lose', 'home_biggest_away_win', 'home_biggest_home_lose', 'home_biggest_home_win',
               'home_lineups',
    
               'away_biggest_away_goals_against', 'away_biggest_away_goals_for', 'away_biggest_draw_streak',
               'away_biggest_home_goals_against', 'away_biggest_home_goals_for', 'away_biggest_lose_streak',
               'away_biggest_win_streak',
               'home_biggest_away_goals_against', 'home_biggest_away_goals_for', 'home_biggest_draw_streak',
               'home_biggest_home_goals_against', 'home_biggest_home_goals_for', 'home_biggest_lose_streak',
               'home_biggest_win_streak',
    
               'away_average_away_goals_against', 'away_average_away_goals_for', 'away_average_home_goals_against',
               'away_average_home_goals_for', 'away_average_total_goals_against', 'away_average_total_goals_for',
               'home_average_away_goals_against', 'home_average_away_goals_for', 'home_average_home_goals_against',
               'home_average_home_goals_for', 'home_average_total_goals_against', 'home_average_total_goals_for',
    
               'away_penalties_missed', 'away_penalties_missed_percentage', 'away_penalties_scored',
               'away_penalties_scored', 'away_penalties_scored_percentage',
               'home_penalties_missed', 'home_penalties_missed_percentage', 'home_penalties_scored',
               'home_penalties_scored', 'home_penalties_scored_percentage'
               ]

In [8]:
footballdata_wTeamStats = \
    footballdata_wTeamStats[list(set(footballdata_wTeamStats.columns.tolist()) - set(not_complete + not_features))]
footballdata_wTeamStats

home_goals_for_minute_46_60_percentage  away_goals_for_minute_0_15  \
0                                       NaN                         NaN   
1                                       NaN                         NaN   
2                                       NaN                         NaN   
3                                       NaN                         NaN   
4                                       NaN                         NaN   
...                                     ...                         ...   
3805                                    NaN                         NaN   
3806                                    NaN                         NaN   
3807                                    NaN                         NaN   
3808                                    NaN                         NaN   
3809                                    NaN                         NaN   

      away_failed_to_score_total  home_home_clean_sheets  \
0                            0.0                     0.0   
1                            0.0                     0.0   
2                            0.0                     0.0   
3                            0.0                     0.0   
4                            0.0                     0.0   
...                          ...                     ...   
3805                         0.0                     0.0   
3806                         0.0                     0.0   
3807                         1.0                     0.0   
3808                         1.0                     0.0   
3809                         0.0                     0.0   

     home_goals_against_minute_31_45_percentage  away_away_goals_against  \
0                                           NaN                      0.0   
1                                           NaN                      0.0   
2                                           NaN                      0.0   
3                                           NaN                      0.0   
4                                           NaN                      0.0   
...                                         ...                      ...   
3805                                        NaN                      0.0   
3806                                        NaN                      0.0   
3807                                        NaN                      0.0   
3808                                        NaN                      0.0   
3809                                        NaN                      0.0   

     home_goals_for_minute_61_75_percentage  home_away_goals_against  \
0                                       NaN                      0.0   
1                                       NaN                      0.0   
2                                       NaN                      0.0   
3                                       NaN                      0.0   
4                                       NaN                      0.0   
...                                     ...                      ...   
3805                                    NaN                      2.0   
3806                                    NaN                      0.0   
3807                                    NaN                      1.0   
3808                                 66.67%                      3.0   
3809                                 25.00%                      2.0   

     home_goals_against_minute_61_75_percentage  \
0                                           NaN   
1                                           NaN   
2                                           NaN   
3                                           NaN   
4                                           NaN   
...                                         ...   
3805                                        NaN   
3806                                        NaN   
3807                                    100.00%   
3808                                        NaN   
3809                                     50.

## Convert NaN/Nulls to 0

In [9]:
nan_to_zero = ['away_goals_against_minute_0_15', 'away_goals_against_minute_0_15_percentage',
            'away_goals_against_minute_16_30', 'away_goals_against_minute_16_30_percentage',
            'away_goals_against_minute_16_30_percentage', 'away_goals_against_minute_31_45',
             'away_goals_against_minute_31_45_percentage', 'away_goals_against_minute_46_60',
            'away_goals_against_minute_46_60_percentage', 'away_goals_against_minute_61_75',
            'away_goals_against_minute_61_75_percentage', 'away_goals_against_minute_76_90',
            'away_goals_against_minute_76_90_percentage', 'away_goals_against_minute_91_105',
            'away_goals_against_minute_91_105_percentage', 'away_goals_for_minute_0_15',
            'away_goals_for_minute_0_15_percentage', 'away_goals_for_minute_16_30', 'away_goals_for_minute_16_30_percentage',
            'away_goals_for_minute_31_45', 'away_goals_for_minute_31_45_percentage', 'away_goals_for_minute_46_60',
            'away_goals_for_minute_46_60_percentage', 'away_goals_for_minute_61_75', 'away_goals_for_minute_61_75_percentage',
            'away_goals_for_minute_76_90', 'away_goals_for_minute_76_90_percentage', 'away_goals_for_minute_91_105',
            'away_goals_for_minute_91_105_percentage',
             'home_goals_against_minute_0_15', 'home_goals_against_minute_0_15_percentage',
            'home_goals_against_minute_16_30', 'home_goals_against_minute_16_30_percentage',
            'home_goals_against_minute_16_30_percentage', 'home_goals_against_minute_31_45',
             'home_goals_against_minute_31_45_percentage', 'home_goals_against_minute_46_60',
            'home_goals_against_minute_46_60_percentage', 'home_goals_against_minute_61_75',
            'home_goals_against_minute_61_75_percentage', 'home_goals_against_minute_76_90',
            'home_goals_against_minute_76_90_percentage', 'home_goals_against_minute_91_105',
            'home_goals_against_minute_91_105_percentage', 'home_goals_for_minute_0_15',
            'home_goals_for_minute_0_15_percentage', 'home_goals_for_minute_16_30', 'home_goals_for_minute_16_30_percentage',
            'home_goals_for_minute_31_45', 'home_goals_for_minute_31_45_percentage', 'home_goals_for_minute_46_60',
            'home_goals_for_minute_46_60_percentage', 'home_goals_for_minute_61_75', 'home_goals_for_minute_61_75_percentage',
            'home_goals_for_minute_76_90', 'home_goals_for_minute_76_90_percentage', 'home_goals_for_minute_91_105',
            'home_goals_for_minute_91_105_percentage']

In [10]:
print(footballdata_wTeamStats.count().sort_values().to_string())

away_goals_against_minute_91_105               33879
away_goals_against_minute_91_105_percentage    33879
home_goals_against_minute_91_105               33987
home_goals_against_minute_91_105_percentage    33987
home_goals_for_minute_91_105                   34090
home_goals_for_minute_91_105_percentage        34090
away_goals_for_minute_91_105                   34159
away_goals_for_minute_91_105_percentage        34159
home_goals_for_minute_0_15                     46051
home_goals_for_minute_0_15_percentage          46051
away_goals_for_minute_0_15                     46243
away_goals_for_minute_0_15_percentage          46243
away_goals_against_minute_0_15_percentage      46255
away_goals_against_minute_0_15                 46255
home_goals_against_minute_0_15_percentage      46455
home_goals_against_minute_0_15                 46455
home_goals_for_minute_16_30                    47049
home_goals_for_minute_16_30_percentage         47049
away_goals_against_minute_16_30               

In [11]:
for column in footballdata_wTeamStats.columns:
    if 'percentage' in column:
        footballdata_wTeamStats[column] = footballdata_wTeamStats[column].str.slice(0,-1,1).astype(float)

for column in nan_to_zero:
    if 'percentage' in column:
        footballdata_wTeamStats[column] = footballdata_wTeamStats[column].fillna(0.0)
    else:
        footballdata_wTeamStats[column] = footballdata_wTeamStats[column].fillna(0).astype(int)
footballdata_wTeamStats

<ipython-input-11-04bdf39b3b3a>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  footballdata_wTeamStats[column] = footballdata_wTeamStats[column].str.slice(0,-1,1).astype(float)
<ipython-input-11-04bdf39b3b3a>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  footballdata_wTeamStats[column] = footballdata_wTeamStats[column].fillna(0).astype(int)
<ipython-input-11-04bdf39b3b3a>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexe

home_goals_for_minute_46_60_percentage  away_goals_for_minute_0_15  \
0                                        0.0                           0   
1                                        0.0                           0   
2                                        0.0                           0   
3                                        0.0                           0   
4                                        0.0                           0   
...                                      ...                         ...   
3805                                     0.0                           0   
3806                                     0.0                           0   
3807                                     0.0                           0   
3808                                     0.0                           0   
3809                                     0.0                           0   

      away_failed_to_score_total  home_home_clean_sheets  \
0                            0.0                     0.0   
1                            0.0                     0.0   
2                            0.0                     0.0   
3                            0.0                     0.0   
4                            0.0                     0.0   
...                          ...                     ...   
3805                         0.0                     0.0   
3806                         0.0                     0.0   
3807                         1.0                     0.0   
3808                         1.0                     0.0   
3809                         0.0                     0.0   

      home_goals_against_minute_31_45_percentage  away_away_goals_against  \
0                                            0.0                      0.0   
1                                            0.0                      0.0   
2                                            0.0                      0.0   
3                                            0.0                      0.0   
4                                            0.0                      0.0   
...                                          ...                      ...   
3805                                         0.0                      0.0   
3806                                         0.0                      0.0   
3807                                         0.0                      0.0   
3808                                         0.0                      0.0   
3809                                         0.0                      0.0   

      home_goals_for_minute_61_75_percentage  home_away_goals_against  \
0                                       0.00                      0.0   
1                                       0.00                      0.0   
2                                       0.00                      0.0   
3                                       0.00                      0.0   
4                                       0.00                      0.0   
...                                      ...                      ...   
3805                                    0.00                      2.0   
3806                                    0.00                      0.0   
3807                                    0.00                      1.0   
3808                                   66.67                      3.0   
3809                                   25.00                      2.0   

      home_goals_against_minute_61_75_percentage  \
0                                            0.0   
1                                            0.0   
2                                            0.0   
3                                            0.0   
4                                            0.0   
...                                          ...   
3805                                         0.0   
3806                                         0.0   
3807                                       100.0   
3808                                         0.0  

In [12]:
footballdata_wTeamStats.tail(5)

home_goals_for_minute_46_60_percentage  away_goals_for_minute_0_15  \
3805                                     0.0                           0   
3806                                     0.0                           0   
3807                                     0.0                           0   
3808                                     0.0                           0   
3809                                     0.0                           0   

      away_failed_to_score_total  home_home_clean_sheets  \
3805                         0.0                     0.0   
3806                         0.0                     0.0   
3807                         1.0                     0.0   
3808                         1.0                     0.0   
3809                         0.0                     0.0   

      home_goals_against_minute_31_45_percentage  away_away_goals_against  \
3805                                         0.0                      0.0   
3806                                         0.0                      0.0   
3807                                         0.0                      0.0   
3808                                         0.0                      0.0   
3809                                         0.0                      0.0   

      home_goals_for_minute_61_75_percentage  home_away_goals_against  \
3805                                    0.00                      2.0   
3806                                    0.00                      0.0   
3807                                    0.00                      1.0   
3808                                   66.67                      3.0   
3809                                   25.00                      2.0   

      home_goals_against_minute_61_75_percentage  \
3805                                         0.0   
3806                                         0.0   
3807                                       100.0   
3808                                         0.0   
3809                                        50.0   

      away_goals_against_minute_46_60  away_home_goals_for  \
3805                                0                  1.0   
3806                                0                  2.0   
3807                                0                  0.0   
3808                                0                  0.0   
3809                                0                  1.0   

      away_penalties_for  home_total_goals_against  \
3805                 1.0                       2.0   
3806                 0.0                       0.0   
3807                 0.0                       1.0   
3808                 0.0                       3.0   
3809                 0.0                       2.0   

      away_goals_for_minute_46_60  home_goals_against_minute_61_75  \
3805                            0                                0   
3806                            1                                0   
3807                            0                                1   
3808                            0                                0   
3809                            0                                1   

      home_penalties_for  away_goals_for_minute_31_45  \
3805                 0.0                            0   
3806                 0.0                            0   
3807                 0.0                            0   
3808                 1.0                            0   
3809                 0.0                            0   

      away_goals_for_minute_61_75  home_goals_for_minute_61_75  \
3805                            1                            0   
3806                            0                            0   
3807                            0                            0   
3808                            0                            2   
3809                            0                            1   

      home_goals_against_minute_0_15  away_goals_against_minute_0_15  \
3805                               0      

In [13]:
print(footballdata_wTeamStats.count().sort_values().to_string())

home_form                                      55330
away_form                                      55340
AverageDrawWinOdd                              59564
AverageAwayWinOdd                              59564
AverageHomeWinOdd                              59564
AvgUnder2_5                                    59593
AvgOver2_5                                     59594
HomeGoals                                      59680
AwayGoals                                      59680
FullTimeResult                                 59680
home_goals_for_minute_46_60_percentage         59682
away_failed_to_score_away                      59682
away_goals_for_minute_76_90                    59682
away_away_draws                                59682
away_goals_against_minute_61_75_percentage     59682
HomeTeamName                                   59682
away_goals_against_minute_0_15_percentage      59682
AwayTeamName                                   59682
away_goals_for_minute_16_30_percentage        

## Modifications

### Add Total wins, draws & losses

In [14]:
footballdata_wTeamStats['home_total_wins'] = \
    footballdata_wTeamStats['home_home_wins'] + footballdata_wTeamStats['home_away_wins']
footballdata_wTeamStats['home_total_draws'] = \
    footballdata_wTeamStats['home_home_draws'] + footballdata_wTeamStats['home_away_draws']
footballdata_wTeamStats['home_total_loses'] = \
    footballdata_wTeamStats['home_home_loses'] + footballdata_wTeamStats['home_away_loses']

# TODO: total games is computed bases only on the home games (might require future change)
footballdata_wTeamStats['home_total_games'] = footballdata_wTeamStats['home_total_wins']+\
    footballdata_wTeamStats['home_total_draws']+footballdata_wTeamStats['home_total_loses']

footballdata_wTeamStats['away_total_wins'] = \
    footballdata_wTeamStats['away_home_wins'] + footballdata_wTeamStats['away_away_wins']
footballdata_wTeamStats['away_total_draws'] = \
    footballdata_wTeamStats['away_home_draws'] + footballdata_wTeamStats['away_away_draws']
footballdata_wTeamStats['away_total_loses'] = \
    footballdata_wTeamStats['away_home_loses'] + footballdata_wTeamStats['away_away_loses']

footballdata_wTeamStats['away_total_games'] = footballdata_wTeamStats['away_total_wins']+\
    footballdata_wTeamStats['away_total_draws']+footballdata_wTeamStats['away_total_loses']

footballdata_wTeamStats['home_total_home_games'] = footballdata_wTeamStats['home_home_wins']+\
    footballdata_wTeamStats['home_home_draws']+footballdata_wTeamStats['home_home_loses']
footballdata_wTeamStats['home_total_away_games'] = footballdata_wTeamStats['home_away_wins']+\
    footballdata_wTeamStats['home_away_draws']+footballdata_wTeamStats['home_away_loses']

footballdata_wTeamStats['away_total_home_games'] = footballdata_wTeamStats['away_home_wins']+\
    footballdata_wTeamStats['away_home_draws']+footballdata_wTeamStats['away_home_loses']
footballdata_wTeamStats['away_total_away_games'] = footballdata_wTeamStats['away_away_wins']+\
    footballdata_wTeamStats['away_away_draws']+footballdata_wTeamStats['away_away_loses']

footballdata_wTeamStats

<ipython-input-14-26fe08bd73ab>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  footballdata_wTeamStats['home_total_wins'] = \
<ipython-input-14-26fe08bd73ab>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  footballdata_wTeamStats['home_total_draws'] = \
<ipython-input-14-26fe08bd73ab>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-

home_goals_for_minute_46_60_percentage  away_goals_for_minute_0_15  \
0                                        0.0                           0   
1                                        0.0                           0   
2                                        0.0                           0   
3                                        0.0                           0   
4                                        0.0                           0   
...                                      ...                         ...   
3805                                     0.0                           0   
3806                                     0.0                           0   
3807                                     0.0                           0   
3808                                     0.0                           0   
3809                                     0.0                           0   

      away_failed_to_score_total  home_home_clean_sheets  \
0                            0.0                     0.0   
1                            0.0                     0.0   
2                            0.0                     0.0   
3                            0.0                     0.0   
4                            0.0                     0.0   
...                          ...                     ...   
3805                         0.0                     0.0   
3806                         0.0                     0.0   
3807                         1.0                     0.0   
3808                         1.0                     0.0   
3809                         0.0                     0.0   

      home_goals_against_minute_31_45_percentage  away_away_goals_against  \
0                                            0.0                      0.0   
1                                            0.0                      0.0   
2                                            0.0                      0.0   
3                                            0.0                      0.0   
4                                            0.0                      0.0   
...                                          ...                      ...   
3805                                         0.0                      0.0   
3806                                         0.0                      0.0   
3807                                         0.0                      0.0   
3808                                         0.0                      0.0   
3809                                         0.0                      0.0   

      home_goals_for_minute_61_75_percentage  home_away_goals_against  \
0                                       0.00                      0.0   
1                                       0.00                      0.0   
2                                       0.00                      0.0   
3                                       0.00                      0.0   
4                                       0.00                      0.0   
...                                      ...                      ...   
3805                                    0.00                      2.0   
3806                                    0.00                      0.0   
3807                                    0.00                      1.0   
3808                                   66.67                      3.0   
3809                                   25.00                      2.0   

      home_goals_against_minute_61_75_percentage  \
0                                            0.0   
1                                            0.0   
2                                            0.0   
3                                            0.0   
4                                            0.0   
...                                          ...   
3805                                         0.0   
3806                                         0.0   
3807                                       100.0   
3808                                         0.0  

### Away Team & Home Team Form

In [15]:
to_modify = ['away_form', 'home_form']

In [16]:
# Same as before but normalized
games = [1, 2, 5, 10]
for column in to_modify:
    footballdata_wTeamStats[column] = footballdata_wTeamStats[column].fillna('')
    for nr in games:
        footballdata_wTeamStats[column+f"_last{nr}games_wins"] = \
            footballdata_wTeamStats[column].apply(lambda x : x[-nr:]).str.count('W') / \
            footballdata_wTeamStats['home_total_games'].clip(upper=10)
        footballdata_wTeamStats[column+f"_last{nr}games_draws"] = \
            footballdata_wTeamStats[column].apply(lambda x : x[-nr:]).str.count('D') / \
            footballdata_wTeamStats['home_total_games'].clip(upper=10)
        footballdata_wTeamStats[column+f"_last{nr}games_loses"] = \
            footballdata_wTeamStats[column].apply(lambda x : x[-nr:]).str.count('L') / \
            footballdata_wTeamStats['home_total_games'].clip(upper=10)
footballdata_wTeamStats

<ipython-input-16-4b1632eb5d92>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  footballdata_wTeamStats[column] = footballdata_wTeamStats[column].fillna('')
<ipython-input-16-4b1632eb5d92>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  footballdata_wTeamStats[column+f"_last{nr}games_wins"] = \
<ipython-input-16-4b1632eb5d92>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documen

home_goals_for_minute_46_60_percentage  away_goals_for_minute_0_15  \
0                                        0.0                           0   
1                                        0.0                           0   
2                                        0.0                           0   
3                                        0.0                           0   
4                                        0.0                           0   
...                                      ...                         ...   
3805                                     0.0                           0   
3806                                     0.0                           0   
3807                                     0.0                           0   
3808                                     0.0                           0   
3809                                     0.0                           0   

      away_failed_to_score_total  home_home_clean_sheets  \
0                            0.0                     0.0   
1                            0.0                     0.0   
2                            0.0                     0.0   
3                            0.0                     0.0   
4                            0.0                     0.0   
...                          ...                     ...   
3805                         0.0                     0.0   
3806                         0.0                     0.0   
3807                         1.0                     0.0   
3808                         1.0                     0.0   
3809                         0.0                     0.0   

      home_goals_against_minute_31_45_percentage  away_away_goals_against  \
0                                            0.0                      0.0   
1                                            0.0                      0.0   
2                                            0.0                      0.0   
3                                            0.0                      0.0   
4                                            0.0                      0.0   
...                                          ...                      ...   
3805                                         0.0                      0.0   
3806                                         0.0                      0.0   
3807                                         0.0                      0.0   
3808                                         0.0                      0.0   
3809                                         0.0                      0.0   

      home_goals_for_minute_61_75_percentage  home_away_goals_against  \
0                                       0.00                      0.0   
1                                       0.00                      0.0   
2                                       0.00                      0.0   
3                                       0.00                      0.0   
4                                       0.00                      0.0   
...                                      ...                      ...   
3805                                    0.00                      2.0   
3806                                    0.00                      0.0   
3807                                    0.00                      1.0   
3808                                   66.67                      3.0   
3809                                   25.00                      2.0   

      home_goals_against_minute_61_75_percentage  \
0                                            0.0   
1                                            0.0   
2                                            0.0   
3                                            0.0   
4                                            0.0   
...                                          ...   
3805                                         0.0   
3806                                         0.0   
3807                                       100.0   
3808                                         0.0  

In [17]:
footballdata_wTeamStats = footballdata_wTeamStats.drop(columns=to_modify)

In [18]:
print(footballdata_wTeamStats.dtypes.sort_values().to_string())

home_goals_against_minute_16_30                  int32
home_goals_for_minute_31_45                      int32
home_goals_for_minute_76_90                      int32
away_goals_against_minute_31_45                  int32
home_goals_for_minute_16_30                      int32
home_goals_against_minute_31_45                  int32
away_goals_for_minute_16_30                      int32
home_goals_for_minute_46_60                      int32
home_goals_for_minute_91_105                     int32
away_goals_against_minute_61_75                  int32
away_goals_against_minute_0_15                   int32
home_goals_against_minute_0_15                   int32
home_goals_for_minute_61_75                      int32
home_goals_against_minute_46_60                  int32
away_goals_for_minute_31_45                      int32
away_goals_for_minute_61_75                      int32
home_goals_against_minute_61_75                  int32
away_goals_for_minute_0_15                       int32
home_goals

### Remove 1st 5 "jornadas"

In [19]:
footballdata_wTeamStats = footballdata_wTeamStats[footballdata_wTeamStats['home_total_games']>=5]
footballdata_wTeamStats.reindex(sorted(footballdata_wTeamStats.columns), axis=1)

AverageAwayWinOdd  AverageDrawWinOdd  AverageHomeWinOdd  AvgOver2_5  \
40                 1.73               3.60               4.75        1.86   
41                 4.33               3.50               1.83        2.03   
42                 3.25               3.30               2.20        2.13   
43                 1.67               3.75               5.00        1.60   
44                 7.00               4.00               1.50        1.76   
...                 ...                ...                ...         ...   
3789               1.22               6.78              11.22        1.38   
3790               4.22               3.77               1.80        1.79   
3791               2.20               3.68               3.01        1.55   
3792               6.41               5.09               1.41        1.38   
3793               3.30               3.56               2.11        1.71   

      AvgUnder2_5  AwayGoals  AwayTeamId   AwayTeamName        Date    Div  \
40           1.92        2.0       554.0     Anderlecht  10/09/2010  144.0   
41           1.74        0.0       736.0      Charleroi  11/09/2010  144.0   
42           1.64        0.0       266.0       Mechelen  11/09/2010  144.0   
43           2.21        2.0       631.0           Gent  11/09/2010  144.0   
44           2.00        0.0       741.0  Cercle Brugge  11/09/2010  144.0   
...           ...        ...         ...            ...         ...    ...   
3789         2.96        5.0       611.0     Fenerbahce  21/05/2022  203.0   
3790         2.01        1.0       998.0    Trabzonspor  22/05/2022  203.0   
3791         2.40        1.0       996.0     Alanyaspor  22/05/2022  203.0   
3792         2.95        0.0       994.0         Goztep  22/05/2022  203.0   
3793         2.11        1.0      3574.0    Giresunspor  22/05/2022  203.0   

     FullTimeResult  HomeGoals      HomeTeamName  HomeTeamid  Season  \
40                A        0.0        St Truiden       735.0  2010.0   
41                H        1.0          Germinal      4654.0  2010.0   
42                H        1.0          Kortrijk       734.0  2010.0   
43                D        2.0            Lierse      1392.0  2010.0   
44                H        2.0          Standard       733.0  2010.0   
...             ...        ...               ...         ...     ...   
3789              A        0.0  Yeni Malatyaspor       999.0  2021.0   
3790              H        3.0        Buyuksehyr       564.0  2021.0   
3791              A        0.0        Karagumruk      3589.0  2021.0   
3792              H        7.0     Ad. Demirspor      3563.0  2021.0   
3793              H        4.0         Hatayspor      3575.0  2021.0   

      away_away_clean_sheets  away_away_draws  away_away_goals_against  \
40                       2.0              1.0                      0.0   
41                       0.0              1.0                      6.0   
42                       0.0              0.0                      2.0   
43                       1.0              0.0                      1.0   
44                       1.0              1.0                      4.0   
...                      ...              ...                      ...   
3789                     4.0              5.0                     21.0   
3790                     6.0              5.0                     16.0   
3791                     4.0              3.0                     27.0   
3792                     0.0              5.0                     36.0   
3793                     5.0              4.0                     22.0   

      away_away_goals_for  away_away_loses  away_away_wins  \
40                    3.0              0.0             1.0   
41                    1.0              1.0             0.0   
42                    4.0              0.0             2.0   
43                    4.0              0.0             2.0   
44                    0.0              1.0             0.0   
...               

## Define indexes and labels

In [20]:
indexes = ['AverageAwayWinOdd', 'AverageDrawWinOdd', 'AverageHomeWinOdd',
               'AvgOver2_5', 'AvgUnder2_5', 'AwayGoals', 'AwayTeamId',
               'AwayTeamId', 'AwayTeamName', 'Date', 'Div',
               'HomeGoals', 'HomeTeamName', 'HomeTeamid', 'Season',
               'FullTimeResult'
               ]

label = ['goals']

footballdata_wTeamStats[label] = footballdata_wTeamStats['AwayGoals'] + footballdata_wTeamStats['HomeGoals']

In [21]:
print(footballdata_wTeamStats.drop(columns=indexes).dtypes.sort_index().to_string())

away_away_clean_sheets                         float64
away_away_draws                                float64
away_away_goals_against                        float64
away_away_goals_for                            float64
away_away_loses                                float64
away_away_wins                                 float64
away_failed_to_score_away                      float64
away_failed_to_score_home                      float64
away_failed_to_score_total                     float64
away_form_last10games_draws                    float64
away_form_last10games_loses                    float64
away_form_last10games_wins                     float64
away_form_last1games_draws                     float64
away_form_last1games_loses                     float64
away_form_last1games_wins                      float64
away_form_last2games_draws                     float64
away_form_last2games_loses                     float64
away_form_last2games_wins                      float64
away_form_

In [22]:
list(set(footballdata_wTeamStats.columns.to_list())-set(indexes)-set(label))

['home_goals_for_minute_46_60_percentage',
 'away_goals_for_minute_0_15',
 'home_total_loses',
 'away_failed_to_score_total',
 'home_home_clean_sheets',
 'away_total_draws',
 'home_goals_against_minute_31_45_percentage',
 'away_away_goals_against',
 'home_goals_for_minute_61_75_percentage',
 'home_total_wins',
 'home_away_goals_against',
 'away_form_last5games_loses',
 'home_goals_against_minute_61_75_percentage',
 'away_total_away_games',
 'away_total_loses',
 'away_form_last1games_loses',
 'away_goals_against_minute_46_60',
 'away_home_goals_for',
 'away_penalties_for',
 'home_total_goals_against',
 'home_form_last10games_wins',
 'away_goals_for_minute_46_60',
 'away_total_home_games',
 'home_goals_against_minute_61_75',
 'away_form_last2games_wins',
 'home_penalties_for',
 'away_goals_for_minute_31_45',
 'away_goals_for_minute_61_75',
 'home_goals_for_minute_61_75',
 'home_goals_against_minute_0_15',
 'home_form_last5games_wins',
 'away_goals_against_minute_0_15',
 'away_goals_again

## Normalize Features (per game)

In [23]:
away_away_games_norm = ['away_away_clean_sheets', 'away_away_draws', 'away_away_goals_against',
                      'away_away_goals_for', 'away_away_loses', 'away_away_wins', 'away_failed_to_score_away']

away_home_games_norm = ['away_failed_to_score_home', 'away_home_clean_sheets',
                       'away_home_draws', 'away_home_goals_against', 'away_home_goals_for',
                       'away_home_loses', 'away_home_wins']

away_total_games_norm = ['away_failed_to_score_total', 'away_goals_against_minute_0_15',
                        'away_goals_against_minute_16_30', 'away_goals_against_minute_31_45',
                        'away_goals_against_minute_46_60', 'away_goals_against_minute_61_75',
                        'away_goals_against_minute_76_90', 'away_goals_against_minute_91_105',
                        'away_goals_for_minute_0_15', 'away_goals_for_minute_16_30',
                        'away_goals_for_minute_31_45', 'away_goals_for_minute_46_60',
                        'away_goals_for_minute_61_75', 'away_goals_for_minute_76_90',
                        'away_goals_for_minute_91_105', 'away_penalties_for', 'away_total_clean_sheets',
                        'away_total_draws', 'away_total_goals_against', 'away_total_goals_for', 'away_total_loses',
                        'away_total_wins']

home_away_games_norm = ['home_away_clean_sheets', 'home_away_draws', 'home_away_goals_against',
                      'home_away_goals_for', 'home_away_loses', 'home_away_wins', 'home_failed_to_score_away']

home_home_games_norm = ['home_failed_to_score_home', 'home_home_clean_sheets',
                       'home_home_draws', 'home_home_goals_against', 'home_home_goals_for',
                       'home_home_loses', 'home_home_wins']

home_total_games_norm = ['home_failed_to_score_total', 'home_goals_against_minute_0_15',
                        'home_goals_against_minute_16_30', 'home_goals_against_minute_31_45',
                        'home_goals_against_minute_46_60', 'home_goals_against_minute_61_75',
                        'home_goals_against_minute_76_90', 'home_goals_against_minute_91_105',
                        'home_goals_for_minute_0_15', 'home_goals_for_minute_16_30',
                        'home_goals_for_minute_31_45', 'home_goals_for_minute_46_60',
                        'home_goals_for_minute_61_75', 'home_goals_for_minute_76_90',
                        'home_goals_for_minute_91_105', 'home_penalties_for', 'home_total_clean_sheets',
                        'home_total_draws', 'home_total_goals_against', 'home_total_goals_for', 'home_total_loses',
                        'home_total_wins']

In [24]:
for feature in away_away_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['away_total_away_games']
for feature in away_home_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['away_total_home_games']
for feature in away_total_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['away_total_games']
    
for feature in home_away_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['home_total_away_games']
for feature in home_home_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['home_total_home_games']
for feature in home_total_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['home_total_games']
    
footballdata_wTeamStats

home_goals_for_minute_46_60_percentage  away_goals_for_minute_0_15  \
40                                      0.00                    0.200000   
41                                      0.00                    0.200000   
42                                     66.67                    0.200000   
43                                      0.00                    0.000000   
44                                     11.11                    0.400000   
...                                      ...                         ...   
3789                                   15.38                    0.270270   
3790                                   25.49                    0.324324   
3791                                   11.11                    0.270270   
3792                                   21.82                    0.108108   
3793                                   11.76                    0.081081   

      away_failed_to_score_total  home_home_clean_sheets  \
40                      0.400000                1.000000   
41                      0.400000                1.000000   
42                      0.200000                1.000000   
43                      0.200000                0.000000   
44                      0.400000                0.333333   
...                          ...                     ...   
3789                    0.081081                0.166667   
3790                    0.054054                0.388889   
3791                    0.162162                0.388889   
3792                    0.297297                0.388889   
3793                    0.297297                0.277778   

      home_goals_against_minute_31_45_percentage  away_away_goals_against  \
40                                         16.67                 0.000000   
41                                          0.00                 3.000000   
42                                          0.00                 1.000000   
43                                          8.33                 0.500000   
44                                         33.33                 2.000000   
...                                          ...                      ...   
3789                                       11.94                 1.166667   
3790                                       21.62                 0.888889   
3791                                       11.32                 1.500000   
3792                                        6.67                 2.000000   
3793                                        8.33                 1.222222   

      home_goals_for_minute_61_75_percentage  home_away_goals_against  \
40                                      0.00                 2.000000   
41                                      0.00                 2.333333   
42                                     16.67                 1.000000   
43                                     33.33                 2.000000   
44                                     44.44                 1.000000   
...                                      ...                      ...   
3789                                   15.38                 1.473684   
3790                                   11.76                 1.105263   
3791                                   20.00                 1.789474   
3792                                   16.36                 1.578947   
3793                                   21.57                 2.052632   

      home_goals_against_minute_61_75_percentage  \
40                                          0.00   
41                                         28.57   
42                                         33.33   
43                                         25.00   
44                                          0.00   
...                                          ...   
3789                                       25.37   
3790                                       10.81   
3791                                       13.21   
3792                                       13.33  

In [25]:
#TODO: this is based only on home team games (for most cases should be ok)
footballdata_wTeamStats['total_games'] = footballdata_wTeamStats['home_total_games']
footballdata_wTeamStats = \
    footballdata_wTeamStats.drop(columns=['away_total_away_games','away_total_home_games', 'away_total_games',
                                          'home_total_away_games', 'home_total_home_games', 'home_total_games'])
footballdata_wTeamStats

home_goals_for_minute_46_60_percentage  away_goals_for_minute_0_15  \
40                                      0.00                    0.200000   
41                                      0.00                    0.200000   
42                                     66.67                    0.200000   
43                                      0.00                    0.000000   
44                                     11.11                    0.400000   
...                                      ...                         ...   
3789                                   15.38                    0.270270   
3790                                   25.49                    0.324324   
3791                                   11.11                    0.270270   
3792                                   21.82                    0.108108   
3793                                   11.76                    0.081081   

      away_failed_to_score_total  home_home_clean_sheets  \
40                      0.400000                1.000000   
41                      0.400000                1.000000   
42                      0.200000                1.000000   
43                      0.200000                0.000000   
44                      0.400000                0.333333   
...                          ...                     ...   
3789                    0.081081                0.166667   
3790                    0.054054                0.388889   
3791                    0.162162                0.388889   
3792                    0.297297                0.388889   
3793                    0.297297                0.277778   

      home_goals_against_minute_31_45_percentage  away_away_goals_against  \
40                                         16.67                 0.000000   
41                                          0.00                 3.000000   
42                                          0.00                 1.000000   
43                                          8.33                 0.500000   
44                                         33.33                 2.000000   
...                                          ...                      ...   
3789                                       11.94                 1.166667   
3790                                       21.62                 0.888889   
3791                                       11.32                 1.500000   
3792                                        6.67                 2.000000   
3793                                        8.33                 1.222222   

      home_goals_for_minute_61_75_percentage  home_away_goals_against  \
40                                      0.00                 2.000000   
41                                      0.00                 2.333333   
42                                     16.67                 1.000000   
43                                     33.33                 2.000000   
44                                     44.44                 1.000000   
...                                      ...                      ...   
3789                                   15.38                 1.473684   
3790                                   11.76                 1.105263   
3791                                   20.00                 1.789474   
3792                                   16.36                 1.578947   
3793                                   21.57                 2.052632   

      home_goals_against_minute_61_75_percentage  \
40                                          0.00   
41                                         28.57   
42                                         33.33   
43                                         25.00   
44                                          0.00   
...                                          ...   
3789                                       25.37   
3790                                       10.81   
3791                                       13.21   
3792                                       13.33  

## Extract Features

In [26]:
footballdata_wTeamStats.groupby(label).count()

home_goals_for_minute_46_60_percentage  away_goals_for_minute_0_15  \
goals                                                                       
0.0                                      3823                        3809   
1.0                                      8647                        8615   
2.0                                     12142                       12070   
3.0                                     10668                       10611   
4.0                                      7133                        7095   
5.0                                      3824                        3807   
6.0                                      1738                        1725   
7.0                                       622                         617   
8.0                                       246                         246   
9.0                                        64                          64   
10.0                                       13                          13   
11.0                                        3                           3   
12.0                                        1                           1   
13.0                                        1                           1   

       away_failed_to_score_total  home_home_clean_sheets  \
goals                                                       
0.0                          3809                    3823   
1.0                          8615                    8647   
2.0                         12070                   12142   
3.0                         10611                   10668   
4.0                          7095                    7133   
5.0                          3807                    3824   
6.0                          1725                    1738   
7.0                           617                     622   
8.0                           246                     246   
9.0                            64                      64   
10.0                           13                      13   
11.0                            3                       3   
12.0                            1                       1   
13.0                            1                       1   

       home_goals_against_minute_31_45_percentage  away_away_goals_against  \
goals                                                                        
0.0                                          3823                     3809   
1.0                                          8647                     8615   
2.0                                         12142                    12070   
3.0                                         10668                    10611   
4.0                                          7133                     7095   
5.0                                          3824                     3807   
6.0                                          1738                     1725   
7.0                                           622                      617   
8.0                                           246                      246   
9.0                                            64                       64   
10.0                                           13                       13   
11.0                                            3                        3   
12.0                                            1                        1   
13.0                                            1                        1   

       home_goals_for_minute_61_75_percentage  home_away_goals_against  \
goals                                                                    
0.0                                      3823                     3823   
1.0                                      8647                     8647   
2.0                                     12142                    12142   
3.0                                     10668                    10668   
4.0                                      7133                     7133   
5.0                           

In [27]:
footballdata_wTeamStats = footballdata_wTeamStats.dropna()
footballdata_wTeamStats.groupby(label).count()

home_goals_for_minute_46_60_percentage  away_goals_for_minute_0_15  \
goals                                                                       
0.0                                      3805                        3805   
1.0                                      8575                        8575   
2.0                                     12045                       12045   
3.0                                     10562                       10562   
4.0                                      7086                        7086   
5.0                                      3800                        3800   
6.0                                      1722                        1722   
7.0                                       616                         616   
8.0                                       246                         246   
9.0                                        63                          63   
10.0                                       13                          13   
11.0                                        3                           3   
12.0                                        1                           1   
13.0                                        1                           1   

       away_failed_to_score_total  home_home_clean_sheets  \
goals                                                       
0.0                          3805                    3805   
1.0                          8575                    8575   
2.0                         12045                   12045   
3.0                         10562                   10562   
4.0                          7086                    7086   
5.0                          3800                    3800   
6.0                          1722                    1722   
7.0                           616                     616   
8.0                           246                     246   
9.0                            63                      63   
10.0                           13                      13   
11.0                            3                       3   
12.0                            1                       1   
13.0                            1                       1   

       home_goals_against_minute_31_45_percentage  away_away_goals_against  \
goals                                                                        
0.0                                          3805                     3805   
1.0                                          8575                     8575   
2.0                                         12045                    12045   
3.0                                         10562                    10562   
4.0                                          7086                     7086   
5.0                                          3800                     3800   
6.0                                          1722                     1722   
7.0                                           616                      616   
8.0                                           246                      246   
9.0                                            63                       63   
10.0                                           13                       13   
11.0                                            3                        3   
12.0                                            1                        1   
13.0                                            1                        1   

       home_goals_for_minute_61_75_percentage  home_away_goals_against  \
goals                                                                    
0.0                                      3805                     3805   
1.0                                      8575                     8575   
2.0                                     12045                    12045   
3.0                                     10562                    10562   
4.0                                      7086                     7086   
5.0                           

In [28]:
X = footballdata_wTeamStats[list(set(footballdata_wTeamStats.columns.to_list())-set(indexes)-set(label))].values
y = footballdata_wTeamStats[label].values
y = y.reshape((y.shape[0],))
y = (y>2.5).astype(int)
#y = np.array([0 if label=='H' else 1 if label=='D' else 2 for label in y])

In [29]:
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
X

array([[-1.93397865,  0.30293363, -2.75738706, ..., -0.60952664,
         0.11660008, -0.93037594],
       [-1.93397865,  0.30293363,  1.22642511, ...,  1.06102025,
        -1.62786433, -0.93037594],
       [ 5.21327442,  0.30293363, -2.25941054, ..., -0.60952664,
        -1.62786433, -0.93037594],
       ...,
       [-0.74294848,  0.93061236,  0.64769564, ..., -0.24832732,
         1.43673531, -0.93037594],
       [ 0.40520032, -0.517877  ,  1.45522513, ..., -0.02257774,
         0.49378157,  0.37174964],
       [-0.67326625, -0.75929189, -0.36171623, ..., -0.4740769 ,
         2.37968904,  0.47384202]])

In [30]:
print ('The first element of X is: ', X[0])

The first element of X is:  [-1.93397865  0.30293363 -2.75738706 -1.90688331  0.21347987  0.86287124
  3.56178549  2.23668955  0.37606031  1.3665761  -1.65042374  1.06200122
  2.02751342  0.20149573 -2.71619553 -1.91372478  0.22518129  0.99271356
 -0.83016788 -1.35540553  1.82585051  2.63652796 -1.43652049 -1.76591698
 -1.94713279 -1.75995084  2.04369371 -1.76017184 -0.9922634  -2.21134215
 -0.64733696 -1.77438487  1.99551368  2.52765688  3.49813565 -0.79261353
  0.87224021  0.59237746 -0.29450485  0.19745652  1.05546034 -0.46534061
  1.16624553  0.595564   -1.70398118 -1.59112694 -1.77047658  1.51318043
  0.88530591 -1.21569432  1.15119918 -1.91906269  0.01691791  5.68899222
 -1.65749604  1.32557645  0.8756402   2.21126075  1.53047447 -1.54918488
 -1.91687232  0.16618366  3.8166326   0.4812655  -1.93581748 -0.83506861
 -1.76785051 -0.97504131  2.61013503 -0.95346943  4.44760236  0.83754904
 -1.55709755  0.37206446  0.02444982 -1.6181416  -1.46073841 -0.65008365
 -0.94504028  0.0170714

In [31]:
print ('The first element of y is: ', y[0])
print ('The last element of y is: ', y[-1])

The first element of y is:  0
The last element of y is:  1


In [32]:
print ('The shape of X is: ' + str(X.shape))
print ('The shape of y is: ' + str(y.shape))

The shape of X is: (48538, 125)
The shape of y is: (48538,)


In [55]:
#train_size = int(X.shape[0]*0.8)
#train_size

In [56]:
#X_train = X[:train_size]
#print(X_train.shape)
#X_test = X[train_size:]
#print(X_test.shape)

In [57]:
#y_train = y[:train_size]
#print(y_train.shape)
#y_test = y[train_size:]
#print(y_test.shape)

In [33]:
X_train, X_test, y_train, y_test \
    = train_test_split(X, y, test_size=0.2, random_state=1)

X_train, X_val, y_train, y_val \
    = train_test_split(X_train, y_train, test_size=0.25, random_state=1) # 0.25 x 0.8 = 0.2

In [34]:
print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

(29122, 125)
(9708, 125)
(9708, 125)


In [35]:
print(y_train.shape)
print(y_val.shape)
print(y_test.shape)

(29122,)
(9708,)
(9708,)


# ML Algorithms

In [36]:
def accuracy(confusion_matrix):
    diagonal_sum = confusion_matrix.trace()
    sum_of_all_elements = confusion_matrix.sum()
    return diagonal_sum / sum_of_all_elements

## MLP

In [37]:
model = Sequential(
    [ 
        tf.keras.Input(shape=(125,)),
        Dense(60, activation = 'relu', name='L1', kernel_regularizer=tf.keras.regularizers.l2(0.1)),
        Dense(20, activation = 'relu', name='L2', kernel_regularizer=tf.keras.regularizers.l2(0.1)),
        Dense(3, activation = 'linear', name='L3')    # < softmax activation here
    ]
)
model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.Adam(0.0001),
)
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 L1 (Dense)                  (None, 60)                7560      
                                                                 
 L2 (Dense)                  (None, 20)                1220      
                                                                 
 L3 (Dense)                  (None, 3)                 63        
                                                                 
Total params: 8,843
Trainable params: 8,843
Non-trainable params: 0
_________________________________________________________________


In [38]:
model.fit(
    X_train,y_train,
    epochs=200
)

Epoch 1/200
911/911 [==============================] - 1s 1ms/step - loss: 7.6112
Epoch 2/200
911/911 [==============================] - 1s 887us/step - loss: 2.7102
Epoch 3/200
911/911 [==============================] - 1s 817us/step - loss: 1.2178
Epoch 4/200
911/911 [==============================] - 1s 815us/step - loss: 0.8384
Epoch 5/200
911/911 [==============================] - 1s 964us/step - loss: 0.7472
Epoch 6/200
911/911 [==============================] - 1s 849us/step - loss: 0.7232
Epoch 7/200
911/911 [==============================] - 1s 852us/step - loss: 0.7131
Epoch 8/200
911/911 [==============================] - 1s 875us/step - loss: 0.7071
Epoch 9/200
911/911 [==============================] - 1s 848us/step - loss: 0.7029
Epoch 10/200
911/911 [==============================] - 1s 844us/step - loss: 0.6999
Epoch 11/200
911/911 [==============================] - 1s 844us/step - loss: 0.6978
Epoch 12/200
911/911 [==============================] - 1s 807us/step - loss

911/911 [==============================] - 1s 1ms/step - loss: 0.6883
Epoch 98/200
911/911 [==============================] - 1s 940us/step - loss: 0.6882
Epoch 99/200
911/911 [==============================] - 1s 1ms/step - loss: 0.6883
Epoch 100/200
911/911 [==============================] - 1s 928us/step - loss: 0.6883
Epoch 101/200
911/911 [==============================] - 1s 819us/step - loss: 0.6883
Epoch 102/200
911/911 [==============================] - 1s 923us/step - loss: 0.6882
Epoch 103/200
911/911 [==============================] - 1s 931us/step - loss: 0.6881
Epoch 104/200
911/911 [==============================] - 1s 877us/step - loss: 0.6882
Epoch 105/200
911/911 [==============================] - 1s 916us/step - loss: 0.6881
Epoch 106/200
911/911 [==============================] - 1s 996us/step - loss: 0.6881
Epoch 107/200
911/911 [==============================] - 1s 850us/step - loss: 0.6881
Epoch 108/200
911/911 [==============================] - 1s 765us/step - l

911/911 [==============================] - 1s 813us/step - loss: 0.6870
Epoch 194/200
911/911 [==============================] - 1s 883us/step - loss: 0.6871
Epoch 195/200
911/911 [==============================] - 1s 843us/step - loss: 0.6870
Epoch 196/200
911/911 [==============================] - 1s 758us/step - loss: 0.6870
Epoch 197/200
911/911 [==============================] - 1s 796us/step - loss: 0.6870
Epoch 198/200
911/911 [==============================] - 1s 765us/step - loss: 0.6870
Epoch 199/200
911/911 [==============================] - 1s 778us/step - loss: 0.6870
Epoch 200/200
911/911 [==============================] - 1s 780us/step - loss: 0.6869


In [39]:
[layer1, layer2, layer3] = model.layers
W1,b1 = layer1.get_weights()
W2,b2 = layer2.get_weights()
W3,b3 = layer3.get_weights()

In [40]:
W1

array([[ 2.1419599e-34,  3.9565028e-34, -1.8294948e-34, ...,
         2.8100525e-34, -4.5790051e-35,  3.0751502e-34],
       [ 3.8268671e-34,  3.1734509e-34,  4.5830233e-34, ...,
         2.3245975e-34,  3.6441606e-34, -1.9707712e-34],
       [-3.3076650e-34, -1.2831210e-34, -5.2512850e-34, ...,
         4.0707865e-34,  1.4394026e-34,  3.9873599e-34],
       ...,
       [ 1.8373521e-34,  2.6828955e-34,  4.1844458e-34, ...,
         5.2696966e-34, -2.0132448e-34,  4.3010255e-34],
       [ 7.0079509e-36, -1.4753168e-34, -2.3762504e-34, ...,
         3.4355822e-34,  4.5444621e-34, -2.1205847e-34],
       [-2.6544109e-34,  3.2522581e-34, -3.7657242e-34, ...,
         4.7010682e-35,  5.0261416e-34, -2.0458017e-34]], dtype=float32)

In [41]:
y_train_pred_probs = tf.nn.softmax(model.predict(X_train)).numpy()
y_train_pred_probs

911/911 [==============================] - 1s 769us/step


array([[5.6419140e-01, 4.3580857e-01, 3.4221626e-09],
       [5.5382890e-01, 4.4617113e-01, 3.3855196e-09],
       [5.2483958e-01, 4.7516033e-01, 3.2801668e-09],
       ...,
       [5.3398389e-01, 4.6601608e-01, 3.3142402e-09],
       [5.1185411e-01, 4.8814595e-01, 3.2314691e-09],
       [4.3822080e-01, 5.6177920e-01, 2.9259064e-09]], dtype=float32)

In [42]:
y_test_pred_probs = tf.nn.softmax(model.predict(X_test)).numpy()
y_test_pred_probs

304/304 [==============================] - 0s 795us/step


array([[5.9939146e-01, 4.0060860e-01, 3.5364796e-09],
       [4.4613627e-01, 5.5386370e-01, 2.9611933e-09],
       [5.2017820e-01, 4.7982186e-01, 3.2615552e-09],
       ...,
       [4.2032063e-01, 5.7967937e-01, 2.8467946e-09],
       [5.6580144e-01, 4.3419853e-01, 3.4286831e-09],
       [5.1780385e-01, 4.8219609e-01, 3.2542748e-09]], dtype=float32)

In [43]:
y_train_pred = np.argmax(y_train_pred_probs, axis=1)
y_test_pred = np.argmax(y_test_pred_probs, axis=1)

In [44]:
cm_train = confusion_matrix(y_train_pred, y_train)
cm_train

array([[10530,  8734],
       [ 4113,  5745]], dtype=int64)

In [45]:
cm_test = confusion_matrix(y_test_pred, y_test)
cm_test

array([[3459, 2998],
       [1432, 1819]], dtype=int64)

In [72]:
for i in range(10):
    print( f"{y_train_pred_probs[-i]}, predicted_category: {np.argmax(y_train_pred_probs[-i])}, category: {y_train[-i]}")

[0.7952788  0.14715494 0.05756623], predicted_category: 0, category: 0
[0.40958664 0.28923014 0.30118322], predicted_category: 0, category: 2
[0.5612564  0.25142023 0.18732344], predicted_category: 0, category: 0
[0.44250584 0.28360578 0.27388838], predicted_category: 0, category: 0
[0.50021845 0.26706627 0.2327153 ], predicted_category: 0, category: 2
[0.51173556 0.26680377 0.22146067], predicted_category: 0, category: 2
[0.59141207 0.23968618 0.16890185], predicted_category: 0, category: 0
[0.35628113 0.2898111  0.35390776], predicted_category: 0, category: 2
[0.24000552 0.27314988 0.4868446 ], predicted_category: 2, category: 2
[0.3875445  0.29044512 0.32201037], predicted_category: 0, category: 1


In [73]:
for i in range(10):
    print( f"{y_test_pred_probs[-i]}, predicted_category: {np.argmax(y_test_pred_probs[-i])}, category: {y_test[-i]}")

[0.27684802 0.2821549  0.44099715], predicted_category: 2, category: 0
[0.36572385 0.28785828 0.3464178 ], predicted_category: 0, category: 2
[0.20041792 0.26061717 0.53896487], predicted_category: 2, category: 2
[0.39905763 0.28965127 0.31129107], predicted_category: 0, category: 0
[0.32027367 0.28766364 0.39206278], predicted_category: 2, category: 0
[0.5448222  0.25132814 0.20384964], predicted_category: 0, category: 2
[0.4864392  0.27250597 0.24105482], predicted_category: 0, category: 0
[0.3629093  0.29073986 0.34635088], predicted_category: 0, category: 0
[0.42141932 0.28654402 0.29203665], predicted_category: 0, category: 2
[0.7353725  0.17758726 0.08704021], predicted_category: 0, category: 0


In [46]:
print('Train accuracy: '+ str(accuracy(cm_train)))
print('Test accuracy: '+ str(accuracy(cm_test)))

Train accuracy: 0.5588558478126502
Test accuracy: 0.5436753193242686


## GBT

### Test changing only max_depth

In [47]:
max_val_score = 0
iterations_wo_update = 0
for max_depth in range(125):
    max_depth += 1 # start on 1
    print(f"Testing Max Depth: {max_depth}")
    gbtClassifier = GradientBoostingClassifier(max_depth = max_depth, n_iter_no_change=7, verbose=1).fit(X_train, y_train)
    val_score = gbtClassifier.score(X_val, y_val)
    if val_score > max_val_score:
        iterations_wo_update = 0
        best_max_depth = max_depth
        max_val_score = val_score
        best_model = gbtClassifier
        print(f"New best max depth: {best_max_depth}, validation score: {max_val_score}")
    else:
        iterations_wo_update +=1
        if iterations_wo_update >= 10:
            print("No improvements on the last 10 iterations, stopping here...")
            break
            
gbtClassifier = best_model

Testing Max Depth: 1
      Iter       Train Loss   Remaining Time 
         1           1.3846           11.48s
         2           1.3831           11.46s
         3           1.3819           11.24s
         4           1.3809           11.04s
         5           1.3799           11.15s
         6           1.3792           11.00s
         7           1.3785           11.07s
         8           1.3779           11.06s
         9           1.3775           10.82s
        10           1.3770           10.83s
        20           1.3734            9.61s
        30           1.3710            8.35s
        40           1.3692            7.12s
        50           1.3677            5.85s
New best max depth: 1, validation score: 0.5458384837247631
Testing Max Depth: 2
      Iter       Train Loss   Remaining Time 
         1           1.3838           21.22s
         2           1.3817           21.31s
         3           1.3798           20.86s
         4           1.3784           21.

In [48]:
best_model.score(X_train, y_train)

0.6273264198887439

In [49]:
best_model.score(X_test, y_test)

0.5471775854964978

In [50]:
y_train_pred = gbtClassifier.predict(X_train)
y_test_pred = gbtClassifier.predict(X_test)

In [51]:
cm_train = confusion_matrix(y_train_pred, y_train)
cm_train

array([[10033,  6243],
       [ 4610,  8236]], dtype=int64)

In [52]:
cm_test = confusion_matrix(y_test_pred, y_test)
cm_test

array([[2963, 2468],
       [1928, 2349]], dtype=int64)

### Test changing also n_estimators

In [81]:
gbtClassifier = GradientBoostingClassifier(n_estimators=20, verbose=1).fit(X_train, y_train)
print(gbtClassifier.score(X_train, y_train))
gbtClassifier.score(X_test, y_test)

      Iter       Train Loss   Remaining Time 
         1           1.0605           19.28s
         2           1.0529           18.00s
         3           1.0463           17.03s
         4           1.0409           16.72s
         5           1.0361           15.48s
         6           1.0319           14.35s
         7           1.0284           13.24s
         8           1.0252           12.17s
         9           1.0225           11.11s
        10           1.0201           10.07s
        20           1.0053            0.00s
0.5003111145679396


0.49848343443770415

In [82]:
max_val_score = 0
for n_estimators in range(5,100,5):
    print(f"Testing N Estimators: {n_estimators}")
    iterations_wo_update = 0
    for max_depth in range(125):
        max_depth += 1 # start on 1
        gbtClassifier = GradientBoostingClassifier(max_depth = max_depth, n_estimators=n_estimators).fit(X_train, y_train)
        val_score = gbtClassifier.score(X_val, y_val)
        if val_score > max_val_score:
            iterations_wo_update = 0
            best_max_depth = max_depth
            max_val_score = val_score
            best_model = gbtClassifier
            print(f"New best max depth and N estimators: ({best_max_depth}, {n_estimators}), validation score: {max_val_score}")
        else:
            iterations_wo_update +=1
            if iterations_wo_update >= 10:
                print("No improvements on the last 10 iterations, moving on...")
                break
            
gbtClassifier = best_model

Testing N Estimators: 5
New best max depth and N estimators: (1, 5), validation score: 0.4498366775548297
New best max depth and N estimators: (2, 5), validation score: 0.46978534764349045
New best max depth and N estimators: (3, 5), validation score: 0.47316845543630426
New best max depth and N estimators: (4, 5), validation score: 0.4788847410172655
New best max depth and N estimators: (5, 5), validation score: 0.4794680354643024
No improvements on the last 10 iterations, moving on...
Testing N Estimators: 10
New best max depth and N estimators: (3, 10), validation score: 0.4836677554829678
New best max depth and N estimators: (4, 10), validation score: 0.4841343910405973
New best max depth and N estimators: (5, 10), validation score: 0.4849510032664489
No improvements on the last 10 iterations, moving on...
Testing N Estimators: 15
New best max depth and N estimators: (3, 15), validation score: 0.48611759216052264
New best max depth and N estimators: (4, 15), validation score: 0.486

In [83]:
gbtClassifier.score(X_train, y_train)

0.5594617717974644

In [84]:
gbtClassifier.score(X_test, y_test)

0.4996500233317779

In [85]:
y_train_pred = gbtClassifier.predict(X_train)
y_test_pred = gbtClassifier.predict(X_test)

In [86]:
cm_train = confusion_matrix(y_train_pred, y_train)
cm_train

array([[10198,  4701,  3894],
       [   45,   698,    51],
       [ 1272,  1365,  3490]], dtype=int64)

In [87]:
cm_test = confusion_matrix(y_test_pred, y_test)
cm_test

array([[3233, 1595, 1495],
       [  61,   50,   37],
       [ 526,  575, 1000]], dtype=int64)