# Imports

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

import os
from datetime import datetime, timedelta

In [31]:
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [3]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Variables

In [4]:
footballdata_wTeamStats_path = \
    os.path.abspath(os.getcwd())+"\\Data\\teamStats_byLeague\\footballdata_wTeamStats_englishpremierleague.csv"

# Load Football-Data File with Indexes

In [5]:
footballdata_wTeamStats = pd.read_csv(footballdata_wTeamStats_path, index_col=0)
footballdata_wTeamStats.head(5)

C:\Users\ldoutors\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (96,113,194,211) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


AverageAwayWinOdd  AverageDrawWinOdd  AverageHomeWinOdd  AvgOver2_5  \
0                4.0               3.30               2.00        2.01   
1                2.5               3.25               2.88        2.08   
2                3.4               3.30               2.20        2.09   
3               17.0               7.00               1.17        1.49   
4                3.6               3.30               2.10        2.16   

   AvgUnder2_5  AwayGoals  AwayTeamId AwayTeamName        Date  Div  \
0         1.75          0          48     West Ham  14/08/2010   39   
1         1.70          0          45      Everton  14/08/2010   39   
2         1.69          0          36       Fulham  14/08/2010   39   
3         2.49          0          60    West Brom  14/08/2010   39   
4         1.65          2          54   Birmingham  14/08/2010   39   

  FullTimeResult  HomeGoals HomeTeamName  HomeTeamid  Season  \
0              H          3  Aston Villa          66    2010   
1              H          1    Blackburn          67    2010   
2              D          0       Bolton          68    2010   
3              H          6      Chelsea          49    2010   
4              D          2   Sunderland         746    2010   

   away_average_away_goals_against  away_average_away_goals_for  \
0                              0.0                          0.0   
1                              0.0                          0.0   
2                              0.0                          0.0   
3                              0.0                          0.0   
4                              0.0                          0.0   

   away_average_home_goals_against  away_average_home_goals_for  \
0                              0.0                          0.0   
1                              0.0                          0.0   
2                              0.0                          0.0   
3                              0.0                          0.0   
4                              0.0                          0.0   

   away_average_total_goals_against  away_average_total_goals_for  \
0                               0.0                           0.0   
1                               0.0                           0.0   
2                               0.0                           0.0   
3                               0.0                           0.0   
4                               0.0                           0.0   

   away_away_clean_sheets  away_away_draws  away_away_goals_against  \
0                       0                0                        0   
1                       0                0                        0   
2                       0                0                        0   
3                       0                0                        0   
4                       0                0                        0   

   away_away_goals_for  away_away_loses  away_away_wins  \
0                    0                0               0   
1                    0                0               0   
2                    0                0               0   
3                    0                0               0   
4                    0                0               0   

   away_biggest_away_goals_against  away_biggest_away_goals_for  \
0                                0                            0   
1                                0                            0   
2                                0                            0   
3                                0                            0   
4                                0                            0   

  away_biggest_away_lose away_biggest_away_win  away_biggest_draw_streak  \
0                    NaN                   NaN                         0   
1                    NaN                   NaN                         0   
2                    NaN                   NaN                         0   
3                    NaN            

# Data Prep

## Remove Incomplete Columns & Non important (except indexes)

In [6]:
not_complete = ['away_red_cards_minute_0_15', 'away_red_cards_minute_0_15_percentage',
               'away_red_cards_minute_16_30', 'away_red_cards_minute_16_30_percentage',
               'away_red_cards_minute_31_45', 'away_red_cards_minute_31_45_percentage',
               'away_red_cards_minute_46_60', 'away_red_cards_minute_46_60_percentage',
               'away_red_cards_minute_61_75', 'away_red_cards_minute_61_75_percentage',
               'away_red_cards_minute_61_75', 'away_red_cards_minute_61_75_percentage',
               'away_red_cards_minute_76_90', 'away_red_cards_minute_76_90_percentage',
               'away_red_cards_minute_91_105', 'away_red_cards_minute_91_105_percentage',
               'away_yellow_cards_minute_0_15', 'away_yellow_cards_minute_0_15_percentage',
               'away_yellow_cards_minute_16_30', 'away_yellow_cards_minute_16_30_percentage',
               'away_yellow_cards_minute_31_45', 'away_yellow_cards_minute_31_45_percentage',
               'away_yellow_cards_minute_46_60', 'away_yellow_cards_minute_46_60_percentage',
               'away_yellow_cards_minute_61_75', 'away_yellow_cards_minute_61_75_percentage',
               'away_yellow_cards_minute_76_90', 'away_yellow_cards_minute_76_90_percentage',
               'away_yellow_cards_minute_91_105', 'away_yellow_cards_minute_91_105_percentage',
                'home_red_cards_minute_0_15', 'home_red_cards_minute_0_15_percentage',
               'home_red_cards_minute_16_30', 'home_red_cards_minute_16_30_percentage',
               'home_red_cards_minute_31_45', 'home_red_cards_minute_31_45_percentage',
               'home_red_cards_minute_46_60', 'home_red_cards_minute_46_60_percentage',
               'home_red_cards_minute_61_75', 'home_red_cards_minute_61_75_percentage',
               'home_red_cards_minute_61_75', 'home_red_cards_minute_61_75_percentage',
               'home_red_cards_minute_76_90', 'home_red_cards_minute_76_90_percentage',
               'home_red_cards_minute_91_105', 'home_red_cards_minute_91_105_percentage',
               'home_yellow_cards_minute_0_15', 'home_yellow_cards_minute_0_15_percentage',
               'home_yellow_cards_minute_16_30', 'home_yellow_cards_minute_16_30_percentage',
               'home_yellow_cards_minute_31_45', 'home_yellow_cards_minute_31_45_percentage',
               'home_yellow_cards_minute_46_60', 'home_yellow_cards_minute_46_60_percentage',
               'home_yellow_cards_minute_61_75', 'home_yellow_cards_minute_61_75_percentage',
               'home_yellow_cards_minute_76_90', 'home_yellow_cards_minute_76_90_percentage',
               'home_yellow_cards_minute_91_105', 'home_yellow_cards_minute_91_105_percentage']

not_features = [
               'away_biggest_away_lose', 'away_biggest_away_win', 'away_biggest_home_lose', 'away_biggest_home_win',
               'away_lineups',
               'home_biggest_away_lose', 'home_biggest_away_win', 'home_biggest_home_lose', 'home_biggest_home_win',
               'home_lineups'
               ]

In [7]:
footballdata_wTeamStats = \
    footballdata_wTeamStats[list(set(footballdata_wTeamStats.columns.tolist()) - set(not_complete + not_features))]
footballdata_wTeamStats

away_goals_against_minute_76_90_percentage  \
0                                           NaN   
1                                           NaN   
2                                           NaN   
3                                           NaN   
4                                           NaN   
...                                         ...   
4533                                     16.13%   
4534                                     18.67%   
4535                                     18.87%   
4536                                     13.04%   
4537                                     13.95%   

     away_goals_against_minute_0_15_percentage  \
0                                          NaN   
1                                          NaN   
2                                          NaN   
3                                          NaN   
4                                          NaN   
...                                        ...   
4533                                     6.45%   
4534                                    14.67%   
4535                                    11.32%   
4536                                    26.09%   
4537                                    11.63%   

     home_goals_against_minute_61_75_percentage  \
0                                           NaN   
1                                           NaN   
2                                           NaN   
3                                           NaN   
4                                           NaN   
...                                         ...   
4533                                     15.07%   
4534                                     16.36%   
4535                                     11.76%   
4536                                     30.56%   
4537                                     17.78%   

      away_average_home_goals_against  AvgOver2_5  \
0                                 0.0        2.01   
1                                 0.0        2.08   
2                                 0.0        2.09   
3                                 0.0        1.49   
4                                 0.0        2.16   
...                               ...         ...   
4533                              1.2        1.64   
4534                              2.1        1.61   
4535                              1.2        1.91   
4536                              0.7        1.66   
4537                              0.9        1.78   

     home_goals_for_minute_16_30_percentage  away_biggest_win_streak  \
0                                       NaN                        0   
1                                       NaN                        0   
2                                       NaN                        0   
3                                       NaN                        0   
4                                       NaN                        0   
...                                     ...                      ...   
4533                                 17.50%                        5   
4534                                 12.00%                        2   
4535                                 20.59%                        2   
4536                                 15.15%                       12   
4537                                 12.73%                        5   

      away_home_loses home_goals_against_minute_31_45_percentage  \
0                   0                                        NaN   
1                   0                                        NaN   
2                   0                                        NaN   
3                   0                                        NaN   
4                   0                                        NaN   
...               ...                                        ...   
4533                3                                     12.33%   
4534               12                                     10.91%   
4535                7                                     17.65%

## Convert NaN/Nulls to 0

In [8]:
nan_to_zero = ['away_goals_against_minute_0_15', 'away_goals_against_minute_0_15_percentage',
            'away_goals_against_minute_16_30', 'away_goals_against_minute_16_30_percentage',
            'away_goals_against_minute_16_30_percentage', 'away_goals_against_minute_31_45',
             'away_goals_against_minute_31_45_percentage', 'away_goals_against_minute_46_60',
            'away_goals_against_minute_46_60_percentage', 'away_goals_against_minute_61_75',
            'away_goals_against_minute_61_75_percentage', 'away_goals_against_minute_76_90',
            'away_goals_against_minute_76_90_percentage', 'away_goals_against_minute_91_105',
            'away_goals_against_minute_91_105_percentage', 'away_goals_for_minute_0_15',
            'away_goals_for_minute_0_15_percentage', 'away_goals_for_minute_16_30', 'away_goals_for_minute_16_30_percentage',
            'away_goals_for_minute_31_45', 'away_goals_for_minute_31_45_percentage', 'away_goals_for_minute_46_60',
            'away_goals_for_minute_46_60_percentage', 'away_goals_for_minute_61_75', 'away_goals_for_minute_61_75_percentage',
            'away_goals_for_minute_76_90', 'away_goals_for_minute_76_90_percentage', 'away_goals_for_minute_91_105',
            'away_goals_for_minute_91_105_percentage',
             'home_goals_against_minute_0_15', 'home_goals_against_minute_0_15_percentage',
            'home_goals_against_minute_16_30', 'home_goals_against_minute_16_30_percentage',
            'home_goals_against_minute_16_30_percentage', 'home_goals_against_minute_31_45',
             'home_goals_against_minute_31_45_percentage', 'home_goals_against_minute_46_60',
            'home_goals_against_minute_46_60_percentage', 'home_goals_against_minute_61_75',
            'home_goals_against_minute_61_75_percentage', 'home_goals_against_minute_76_90',
            'home_goals_against_minute_76_90_percentage', 'home_goals_against_minute_91_105',
            'home_goals_against_minute_91_105_percentage', 'home_goals_for_minute_0_15',
            'home_goals_for_minute_0_15_percentage', 'home_goals_for_minute_16_30', 'home_goals_for_minute_16_30_percentage',
            'home_goals_for_minute_31_45', 'home_goals_for_minute_31_45_percentage', 'home_goals_for_minute_46_60',
            'home_goals_for_minute_46_60_percentage', 'home_goals_for_minute_61_75', 'home_goals_for_minute_61_75_percentage',
            'home_goals_for_minute_76_90', 'home_goals_for_minute_76_90_percentage', 'home_goals_for_minute_91_105',
            'home_goals_for_minute_91_105_percentage']

In [9]:
print(footballdata_wTeamStats.count().sort_values().to_string())

away_goals_against_minute_91_105_percentage    2813
away_goals_against_minute_91_105               2813
home_goals_against_minute_91_105               2816
home_goals_against_minute_91_105_percentage    2816
home_goals_for_minute_91_105_percentage        2878
home_goals_for_minute_91_105                   2878
away_goals_for_minute_91_105                   2887
away_goals_for_minute_91_105_percentage        2887
away_goals_against_minute_0_15_percentage      3760
away_goals_against_minute_0_15                 3760
home_goals_against_minute_0_15                 3762
home_goals_against_minute_0_15_percentage      3762
home_goals_for_minute_16_30                    3781
away_goals_for_minute_0_15                     3781
away_goals_for_minute_0_15_percentage          3781
home_goals_for_minute_16_30_percentage         3781
home_goals_for_minute_0_15_percentage          3783
home_goals_for_minute_0_15                     3783
away_goals_for_minute_16_30                    3802
away_goals_f

In [10]:
for column in footballdata_wTeamStats.columns:
    if 'percentage' in column:
        footballdata_wTeamStats[column] = footballdata_wTeamStats[column].str.slice(0,-1,1).astype(float)

for column in nan_to_zero:
    if 'percentage' in column:
        footballdata_wTeamStats[column] = footballdata_wTeamStats[column].fillna(0.0)
    else:
        footballdata_wTeamStats[column] = footballdata_wTeamStats[column].fillna(0).astype(int)
footballdata_wTeamStats

away_goals_against_minute_76_90_percentage  \
0                                           0.00   
1                                           0.00   
2                                           0.00   
3                                           0.00   
4                                           0.00   
...                                          ...   
4533                                       16.13   
4534                                       18.67   
4535                                       18.87   
4536                                       13.04   
4537                                       13.95   

      away_goals_against_minute_0_15_percentage  \
0                                          0.00   
1                                          0.00   
2                                          0.00   
3                                          0.00   
4                                          0.00   
...                                         ...   
4533                                       6.45   
4534                                      14.67   
4535                                      11.32   
4536                                      26.09   
4537                                      11.63   

      home_goals_against_minute_61_75_percentage  \
0                                           0.00   
1                                           0.00   
2                                           0.00   
3                                           0.00   
4                                           0.00   
...                                          ...   
4533                                       15.07   
4534                                       16.36   
4535                                       11.76   
4536                                       30.56   
4537                                       17.78   

      away_average_home_goals_against  AvgOver2_5  \
0                                 0.0        2.01   
1                                 0.0        2.08   
2                                 0.0        2.09   
3                                 0.0        1.49   
4                                 0.0        2.16   
...                               ...         ...   
4533                              1.2        1.64   
4534                              2.1        1.61   
4535                              1.2        1.91   
4536                              0.7        1.66   
4537                              0.9        1.78   

      home_goals_for_minute_16_30_percentage  away_biggest_win_streak  \
0                                       0.00                        0   
1                                       0.00                        0   
2                                       0.00                        0   
3                                       0.00                        0   
4                                       0.00                        0   
...                                      ...                      ...   
4533                                   17.50                        5   
4534                                   12.00                        2   
4535                                   20.59                        2   
4536                                   15.15                       12   
4537                                   12.73                        5   

      away_home_loses  home_goals_against_minute_31_45_percentage  \
0                   0                                        0.00   
1                   0                                        0.00   
2                   0                                        0.00   
3                   0                                        0.00   
4                   0                                        0.00   
...               ...                                         ...   
4533                3                                       12.33   
4534               12                                       10.91   
4535    

In [11]:
footballdata_wTeamStats.tail(5)

away_goals_against_minute_76_90_percentage  \
4533                                       16.13   
4534                                       18.67   
4535                                       18.87   
4536                                       13.04   
4537                                       13.95   

      away_goals_against_minute_0_15_percentage  \
4533                                       6.45   
4534                                      14.67   
4535                                      11.32   
4536                                      26.09   
4537                                      11.63   

      home_goals_against_minute_61_75_percentage  \
4533                                       15.07   
4534                                       16.36   
4535                                       11.76   
4536                                       30.56   
4537                                       17.78   

      away_average_home_goals_against  AvgOver2_5  \
4533                              1.2        1.64   
4534                              2.1        1.61   
4535                              1.2        1.91   
4536                              0.7        1.66   
4537                              0.9        1.78   

      home_goals_for_minute_16_30_percentage  away_biggest_win_streak  \
4533                                   17.50                        5   
4534                                   12.00                        2   
4535                                   20.59                        2   
4536                                   15.15                       12   
4537                                   12.73                        5   

      away_home_loses  home_goals_against_minute_31_45_percentage  \
4533                3                                       12.33   
4534               12                                       10.91   
4535                7                                       17.65   
4536                2                                       19.44   
4537                4                                       17.78   

      away_goals_for_minute_16_30                            home_form  \
4533                           12  LDDLDLWLDWDLDWDLLLWWLDLLLLLLWWDWDLL   
4534                            2   WLWLLDDWWLDLWDLWLWLDLDLWWLWDWLDDLL   
4535                            7  WLLLWDLLWLLWLLLLLLDLDLLWLDLLWLLLLLL   
4536                           11  LLLWLWWWDWLWDDLLWDWWWLWWLLLWWLWLLLD   
4537                           12  WWWLLLWWLLDWWWDWDWWLLLWLWWLWWWWLDWD   

      HomeGoals  home_goals_against_minute_76_90  \
4533          0                                9   
4534          3                                8   
4535          0                               10   
4536          1                                6   
4537          3                                8   

      home_goals_against_minute_91_105_percentage  away_away_draws  \
4533                                         6.85                4   
4534                                         9.09                3   
4535                                         8.82                3   
4536                                         8.33                3   
4537                                         8.89                1   

      away_biggest_home_goals_against  away_goals_for_minute_0_15  \
4533                                4                           8   
4534                                5                           5   
4535                                5                           4   
4536                                3                          15   
4537                                2                          11   

      home_average_total_goals_for  home_average_away_goals_for  \
4533                           1.1                          1.2   
4534                           1.4                          1.3   
4535                           0.9                          0.9   
4536                           1.0    

In [12]:
print(footballdata_wTeamStats.count().sort_values().to_string())

away_form                                      4418
home_form                                      4418
away_goals_against_minute_76_90_percentage     4538
away_goals_for_minute_31_45                    4538
home_goals_for_minute_76_90                    4538
home_goals_against_minute_61_75                4538
home_goals_for_minute_46_60_percentage         4538
away_total_clean_sheets                        4538
home_goals_against_minute_16_30                4538
home_goals_for_minute_0_15                     4538
home_goals_for_minute_31_45                    4538
home_goals_for_minute_16_30                    4538
home_goals_against_minute_46_60                4538
home_home_wins                                 4538
away_penalties_missed_percentage               4538
away_goals_against_minute_61_75_percentage     4538
away_biggest_away_goals_against                4538
away_goals_against_minute_46_60_percentage     4538
away_failed_to_score_home                      4538
away_home_dr

## Modifications

### Away Team & Home Team Form

In [13]:
to_modify = ['away_form', 'home_form']

In [14]:
games = [1, 2, 5]
for column in to_modify:
    footballdata_wTeamStats[column] = footballdata_wTeamStats[column].fillna('')
    for nr in games:
        footballdata_wTeamStats[column+f"_last{nr}games_wins"] = \
            footballdata_wTeamStats[column].apply(lambda x : x[-nr:]).str.count('W')
        footballdata_wTeamStats[column+f"_last{nr}games_draws"] = \
            footballdata_wTeamStats[column].apply(lambda x : x[-nr:]).str.count('D')
        footballdata_wTeamStats[column+f"_last{nr}games_loses"] = \
            footballdata_wTeamStats[column].apply(lambda x : x[-nr:]).str.count('L')
footballdata_wTeamStats

away_goals_against_minute_76_90_percentage  \
0                                           0.00   
1                                           0.00   
2                                           0.00   
3                                           0.00   
4                                           0.00   
...                                          ...   
4533                                       16.13   
4534                                       18.67   
4535                                       18.87   
4536                                       13.04   
4537                                       13.95   

      away_goals_against_minute_0_15_percentage  \
0                                          0.00   
1                                          0.00   
2                                          0.00   
3                                          0.00   
4                                          0.00   
...                                         ...   
4533                                       6.45   
4534                                      14.67   
4535                                      11.32   
4536                                      26.09   
4537                                      11.63   

      home_goals_against_minute_61_75_percentage  \
0                                           0.00   
1                                           0.00   
2                                           0.00   
3                                           0.00   
4                                           0.00   
...                                          ...   
4533                                       15.07   
4534                                       16.36   
4535                                       11.76   
4536                                       30.56   
4537                                       17.78   

      away_average_home_goals_against  AvgOver2_5  \
0                                 0.0        2.01   
1                                 0.0        2.08   
2                                 0.0        2.09   
3                                 0.0        1.49   
4                                 0.0        2.16   
...                               ...         ...   
4533                              1.2        1.64   
4534                              2.1        1.61   
4535                              1.2        1.91   
4536                              0.7        1.66   
4537                              0.9        1.78   

      home_goals_for_minute_16_30_percentage  away_biggest_win_streak  \
0                                       0.00                        0   
1                                       0.00                        0   
2                                       0.00                        0   
3                                       0.00                        0   
4                                       0.00                        0   
...                                      ...                      ...   
4533                                   17.50                        5   
4534                                   12.00                        2   
4535                                   20.59                        2   
4536                                   15.15                       12   
4537                                   12.73                        5   

      away_home_loses  home_goals_against_minute_31_45_percentage  \
0                   0                                        0.00   
1                   0                                        0.00   
2                   0                                        0.00   
3                   0                                        0.00   
4                   0                                        0.00   
...               ...                                         ...   
4533                3                                       12.33   
4534               12                                       10.91   
4535    

In [15]:
footballdata_wTeamStats = footballdata_wTeamStats.drop(columns=to_modify)

In [16]:
print(footballdata_wTeamStats.dtypes.sort_values().to_string())

away_goals_against_minute_76_90                  int32
home_goals_for_minute_76_90                      int32
away_goals_for_minute_31_45                      int32
away_goals_for_minute_46_60                      int32
away_goals_against_minute_16_30                  int32
away_goals_for_minute_91_105                     int32
away_goals_against_minute_0_15                   int32
home_goals_against_minute_61_75                  int32
away_goals_against_minute_61_75                  int32
away_goals_for_minute_76_90                      int32
home_goals_for_minute_61_75                      int32
home_goals_for_minute_46_60                      int32
away_goals_for_minute_61_75                      int32
home_goals_against_minute_0_15                   int32
home_goals_against_minute_91_105                 int32
away_goals_against_minute_46_60                  int32
home_goals_against_minute_16_30                  int32
home_goals_against_minute_31_45                  int32
home_goals

### Add Total wins, draws & losses

In [17]:
footballdata_wTeamStats['home_total_wins'] = \
    footballdata_wTeamStats['home_home_wins'] + footballdata_wTeamStats['home_away_wins']
footballdata_wTeamStats['home_total_draws'] = \
    footballdata_wTeamStats['home_home_draws'] + footballdata_wTeamStats['home_away_draws']
footballdata_wTeamStats['home_total_loses'] = \
    footballdata_wTeamStats['home_home_loses'] + footballdata_wTeamStats['home_away_loses']

footballdata_wTeamStats['home_total_games'] = footballdata_wTeamStats['home_total_wins']+\
    footballdata_wTeamStats['home_total_draws']+footballdata_wTeamStats['home_total_loses']

footballdata_wTeamStats['away_total_wins'] = \
    footballdata_wTeamStats['away_home_wins'] + footballdata_wTeamStats['away_away_wins']
footballdata_wTeamStats['away_total_draws'] = \
    footballdata_wTeamStats['away_home_draws'] + footballdata_wTeamStats['away_away_draws']
footballdata_wTeamStats['away_total_loses'] = \
    footballdata_wTeamStats['away_home_loses'] + footballdata_wTeamStats['away_away_loses']

footballdata_wTeamStats

away_goals_against_minute_76_90_percentage  \
0                                           0.00   
1                                           0.00   
2                                           0.00   
3                                           0.00   
4                                           0.00   
...                                          ...   
4533                                       16.13   
4534                                       18.67   
4535                                       18.87   
4536                                       13.04   
4537                                       13.95   

      away_goals_against_minute_0_15_percentage  \
0                                          0.00   
1                                          0.00   
2                                          0.00   
3                                          0.00   
4                                          0.00   
...                                         ...   
4533                                       6.45   
4534                                      14.67   
4535                                      11.32   
4536                                      26.09   
4537                                      11.63   

      home_goals_against_minute_61_75_percentage  \
0                                           0.00   
1                                           0.00   
2                                           0.00   
3                                           0.00   
4                                           0.00   
...                                          ...   
4533                                       15.07   
4534                                       16.36   
4535                                       11.76   
4536                                       30.56   
4537                                       17.78   

      away_average_home_goals_against  AvgOver2_5  \
0                                 0.0        2.01   
1                                 0.0        2.08   
2                                 0.0        2.09   
3                                 0.0        1.49   
4                                 0.0        2.16   
...                               ...         ...   
4533                              1.2        1.64   
4534                              2.1        1.61   
4535                              1.2        1.91   
4536                              0.7        1.66   
4537                              0.9        1.78   

      home_goals_for_minute_16_30_percentage  away_biggest_win_streak  \
0                                       0.00                        0   
1                                       0.00                        0   
2                                       0.00                        0   
3                                       0.00                        0   
4                                       0.00                        0   
...                                      ...                      ...   
4533                                   17.50                        5   
4534                                   12.00                        2   
4535                                   20.59                        2   
4536                                   15.15                       12   
4537                                   12.73                        5   

      away_home_loses  home_goals_against_minute_31_45_percentage  \
0                   0                                        0.00   
1                   0                                        0.00   
2                   0                                        0.00   
3                   0                                        0.00   
4                   0                                        0.00   
...               ...                                         ...   
4533                3                                       12.33   
4534               12                                       10.91   
4535    

### Remove 1st 5 "jornadas"

In [18]:
footballdata_wTeamStats = footballdata_wTeamStats[footballdata_wTeamStats['home_total_games']>=5]
footballdata_wTeamStats

away_goals_against_minute_76_90_percentage  \
50                                         10.00   
51                                         23.08   
52                                          0.00   
53                                          0.00   
54                                         66.67   
...                                          ...   
4533                                       16.13   
4534                                       18.67   
4535                                       18.87   
4536                                       13.04   
4537                                       13.95   

      away_goals_against_minute_0_15_percentage  \
50                                        20.00   
51                                         0.00   
52                                         0.00   
53                                        28.57   
54                                        16.67   
...                                         ...   
4533                                       6.45   
4534                                      14.67   
4535                                      11.32   
4536                                      26.09   
4537                                      11.63   

      home_goals_against_minute_61_75_percentage  \
50                                          0.00   
51                                         33.33   
52                                          7.69   
53                                          0.00   
54                                         16.67   
...                                          ...   
4533                                       15.07   
4534                                       16.36   
4535                                       11.76   
4536                                       30.56   
4537                                       17.78   

      away_average_home_goals_against  AvgOver2_5  \
50                                0.7        1.42   
51                                3.3        2.13   
52                                1.0        1.81   
53                                1.7        2.18   
54                                1.0        1.90   
...                               ...         ...   
4533                              1.2        1.64   
4534                              2.1        1.61   
4535                              1.2        1.91   
4536                              0.7        1.66   
4537                              0.9        1.78   

      home_goals_for_minute_16_30_percentage  away_biggest_win_streak  \
50                                     15.38                        1   
51                                      0.00                        1   
52                                     14.29                        1   
53                                      0.00                        0   
54                                      0.00                        1   
...                                      ...                      ...   
4533                                   17.50                        5   
4534                                   12.00                        2   
4535                                   20.59                        2   
4536                                   15.15                       12   
4537                                   12.73                        5   

      away_home_loses  home_goals_against_minute_31_45_percentage  \
50                  0                                       20.00   
51                  3                                        0.00   
52                  1                                       30.77   
53                  1                                        0.00   
54                  0                                       16.67   
...               ...                                         ...   
4533                3                                       12.33   
4534               12                                       10.91   
4535    

## Define indexes and labels

In [19]:
indexes = ['AverageAwayWinOdd', 'AverageDrawWinOdd', 'AverageHomeWinOdd',
               'AvgOver2_5', 'AvgUnder2_5', 'AwayGoals', 'AwayTeamId',
               'AwayTeamId', 'AwayTeamName', 'Date', 'Div',
               'HomeGoals', 'HomeTeamName', 'HomeTeamid', 'Season',
               ]
label = ['FullTimeResult']

In [21]:
print(footballdata_wTeamStats.drop(columns=indexes).dtypes.sort_values().to_string())

away_goals_against_minute_76_90                  int32
away_goals_for_minute_91_105                     int32
away_goals_against_minute_0_15                   int32
away_goals_against_minute_91_105                 int32
home_goals_for_minute_46_60                      int32
home_goals_for_minute_91_105                     int32
home_goals_against_minute_31_45                  int32
away_goals_for_minute_46_60                      int32
home_goals_for_minute_61_75                      int32
away_goals_for_minute_61_75                      int32
away_goals_against_minute_31_45                  int32
away_goals_for_minute_76_90                      int32
home_goals_against_minute_0_15                   int32
home_goals_against_minute_46_60                  int32
home_goals_for_minute_16_30                      int32
away_goals_for_minute_0_15                       int32
home_goals_for_minute_31_45                      int32
home_goals_for_minute_0_15                       int32
away_goals

In [22]:
list(set(footballdata_wTeamStats.columns.to_list())-set(indexes)-set(label))

['away_goals_against_minute_76_90_percentage',
 'away_total_loses',
 'away_goals_against_minute_0_15_percentage',
 'home_goals_against_minute_61_75_percentage',
 'away_average_home_goals_against',
 'home_goals_for_minute_16_30_percentage',
 'away_biggest_win_streak',
 'away_home_loses',
 'home_goals_against_minute_31_45_percentage',
 'away_goals_for_minute_16_30',
 'home_goals_against_minute_76_90',
 'home_goals_against_minute_91_105_percentage',
 'away_away_draws',
 'away_biggest_home_goals_against',
 'away_goals_for_minute_0_15',
 'home_average_total_goals_for',
 'home_average_away_goals_for',
 'home_penalties_for',
 'home_home_goals_against',
 'home_home_clean_sheets',
 'away_goals_against_minute_31_45_percentage',
 'away_away_goals_against',
 'home_goals_for_minute_31_45_percentage',
 'home_form_last1games_draws',
 'home_home_loses',
 'home_biggest_win_streak',
 'away_failed_to_score_away',
 'home_average_away_goals_against',
 'home_total_wins',
 'home_away_goals_against',
 'away_a

In [23]:
X = footballdata_wTeamStats[list(set(footballdata_wTeamStats.columns.to_list())-set(indexes)-set(label))].values
y = footballdata_wTeamStats[label].values
y = y.reshape((y.shape[0],))
y = np.array([0 if label=='H' else 1 if label=='D' else 2 for label in y])

In [24]:
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
X

array([[-0.84005408, -1.13016253,  1.05674562, ..., -0.61733901,
        -1.17242911, -1.04342181],
       [ 0.61844852, -0.93403056, -1.7087721 , ..., -1.43595259,
        -1.17242911, -1.04342181],
       [-1.95511723, -1.13016253, -1.7087721 , ..., -1.43595259,
        -1.17242911, -1.04342181],
       ...,
       [ 0.14900693,  2.20408097, -0.14348907, ...,  1.01988813,
         1.58100289,  1.10959269],
       [-0.50107488, -0.93403056,  1.89884577, ...,  1.01988813,
         2.68237569,  3.2626072 ],
       [-0.39960414,  0.63502521, -0.10062354, ...,  0.61058135,
         1.03031649,  1.10959269]])

In [25]:
print ('The first element of X is: ', X[0])

The first element of X is:  [-0.84005408 -1.13016253  1.05674562 -2.02426245 -1.12496461  0.15627577
 -0.81256854 -1.33269906  0.56487127 -1.33969093 -0.91312454 -1.05967165
 -1.39139378 -1.75951052 -1.35317354  2.79292186  0.13335915 -0.60786107
 -1.57036501 -1.00188677 -0.62905642 -0.95694981 -0.00855176  1.75855497
 -1.30467623  0.20713482 -0.54276862 -1.00380312 -0.89416869 -1.48422495
 -2.19120912 -1.09645181 -1.27589576  3.64966337 -1.79983584 -1.26393024
 -1.29449585 -1.5000399   0.74910274  0.35139512  0.12827762 -2.03627239
  0.89564073 -1.61860064  0.         -0.7969567  -1.15611675  1.14415511
  1.14654644 -1.06168262 -1.43638648 -1.14497459 -0.33577184 -1.03519388
 -1.28018511 -1.24949554 -0.8877899   0.19378691 -0.70051639 -1.12859492
  0.88385013 -1.1466469  -1.13200552 -1.15240261  0.63497873 -0.8696808
 -1.69194372  0.28806768 -0.55847653 -0.01593942 -1.02919594 -1.64640917
 -0.69528501 -1.4969001  -0.59085006  1.08180715 -1.43335562  2.50013671
 -0.87776106 -0.98689143

In [26]:
print ('The first element of y is: ', y[0])
print ('The last element of y is: ', y[-1])

The first element of y is:  2
The last element of y is:  0


In [27]:
print ('The shape of X is: ' + str(X.shape))
print ('The shape of y is: ' + str(y.shape))

The shape of X is: (3937, 153)
The shape of y is: (3937,)


In [28]:
train_size = int(X.shape[0]*0.9)
train_size

3543

In [29]:
X_train = X[:train_size]
print(X_train.shape)
X_test = X[train_size:]
print(X_test.shape)

(3543, 153)
(394, 153)


In [30]:
y_train = y[:train_size]
print(y_train.shape)
y_test = y[train_size:]
print(y_test.shape)

(3543,)
(394,)


# Useful Functions

In [37]:
def accuracy(confusion_matrix):
    diagonal_sum = confusion_matrix.trace()
    sum_of_all_elements = confusion_matrix.sum()
    return diagonal_sum / sum_of_all_elements

# MLP

In [297]:
# TODO: Activation Functions ReLU on hidden layers -> softmax for output (result case), ReLU for output (goals case)

#(spareCategoricalCrossentropy loss function) for softmax

## Tensorflow

In [298]:
model = Sequential(
    [ 
        tf.keras.Input(shape=(153,)),
        Dense(20, activation = 'relu'),
        Dense(12, activation = 'relu'),
        Dense(3, activation = 'linear')    # < softmax activation here
    ]
)
model.summary()

Model: "sequential_25"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_70 (Dense)            (None, 20)                3080      
                                                                 
 dense_71 (Dense)            (None, 12)                252       
                                                                 
 dense_72 (Dense)            (None, 3)                 39        
                                                                 
Total params: 3,371
Trainable params: 3,371
Non-trainable params: 0
_________________________________________________________________


In [299]:
[layer1, layer2, layer3] = model.layers
W1,b1 = layer1.get_weights()
W2,b2 = layer2.get_weights()
W3,b3 = layer3.get_weights()

In [300]:
W1

array([[-0.17098702,  0.03959715, -0.08905134, ..., -0.04297359,
        -0.00780609,  0.02932917],
       [ 0.1177116 , -0.09912139,  0.14287719, ..., -0.01679233,
        -0.10478035,  0.09513432],
       [-0.18557373, -0.10589987,  0.1099118 , ...,  0.05253898,
        -0.04439469,  0.10017824],
       ...,
       [ 0.04107514,  0.00895093, -0.08227056, ..., -0.0256525 ,
        -0.1688409 ,  0.08301631],
       [-0.16990346,  0.05691341, -0.1239221 , ..., -0.15278612,
         0.12586847, -0.05793175],
       [-0.08881038,  0.05022538, -0.05822738, ..., -0.14205423,
         0.01785116,  0.08791938]], dtype=float32)

In [301]:
model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.Adam(0.001),
)

model.fit(
    X_train,y_train,
    epochs=200
)

Epoch 1/200
111/111 [==============================] - 0s 1ms/step - loss: 1.0579
Epoch 2/200
111/111 [==============================] - 0s 873us/step - loss: 0.9938
Epoch 3/200
111/111 [==============================] - 0s 900us/step - loss: 0.9742
Epoch 4/200
111/111 [==============================] - 0s 891us/step - loss: 0.9612
Epoch 5/200
111/111 [==============================] - 0s 1ms/step - loss: 0.9494
Epoch 6/200
111/111 [==============================] - 0s 927us/step - loss: 0.9370
Epoch 7/200
111/111 [==============================] - 0s 891us/step - loss: 0.9276
Epoch 8/200
111/111 [==============================] - 0s 909us/step - loss: 0.9174
Epoch 9/200
111/111 [==============================] - 0s 1ms/step - loss: 0.9079
Epoch 10/200
111/111 [==============================] - 0s 1ms/step - loss: 0.8969
Epoch 11/200
111/111 [==============================] - 0s 1ms/step - loss: 0.8919
Epoch 12/200
111/111 [==============================] - 0s 1ms/step - loss: 0.8781
E

111/111 [==============================] - 0s 1ms/step - loss: 0.3061
Epoch 196/200
111/111 [==============================] - 0s 1ms/step - loss: 0.2997
Epoch 197/200
111/111 [==============================] - 0s 1ms/step - loss: 0.2983
Epoch 198/200
111/111 [==============================] - 0s 1ms/step - loss: 0.3027
Epoch 199/200
111/111 [==============================] - 0s 1ms/step - loss: 0.3002
Epoch 200/200
111/111 [==============================] - 0s 1ms/step - loss: 0.3014


In [302]:
[layer1, layer2, layer3] = model.layers
W1,b1 = layer1.get_weights()
W2,b2 = layer2.get_weights()
W3,b3 = layer3.get_weights()

In [303]:
W1

array([[-0.1439539 ,  0.04069866,  0.0868286 , ..., -0.09193739,
         0.02355442, -0.15614027],
       [-0.04087792, -0.28764585,  0.37363678, ..., -0.10942627,
        -0.21056499,  0.27458617],
       [ 0.19715947, -0.30894893,  0.44890535, ...,  0.06487266,
         0.00941219,  0.31237543],
       ...,
       [-0.23078823, -0.42555156, -0.30341718, ...,  0.17935584,
        -0.25946254,  0.28317454],
       [-0.57265234,  0.30766335, -0.31023568, ..., -0.38457203,
         0.11769634, -0.20833394],
       [-0.10265654,  0.09933889, -0.39580202, ..., -0.0926751 ,
         0.06241724,  0.23508066]], dtype=float32)

In [304]:
y_train_pred_probs = tf.nn.softmax(model.predict(X_train)).numpy()
y_train_pred_probs

111/111 [==============================] - 0s 1ms/step


array([[1.5140572e-01, 7.6210958e-09, 8.4859425e-01],
       [7.7231139e-02, 9.2276883e-01, 2.1093627e-09],
       [5.1547922e-02, 7.5022201e-03, 9.4094980e-01],
       ...,
       [9.9993908e-01, 8.0201150e-12, 6.0896145e-05],
       [5.4041918e-02, 6.9578519e-08, 9.4595802e-01],
       [5.4977649e-01, 3.9061587e-02, 4.1116193e-01]], dtype=float32)

In [305]:
y_test_pred_probs = tf.nn.softmax(model.predict(X_test)).numpy()
y_test_pred_probs

13/13 [==============================] - 0s 2ms/step


array([[6.4887230e-05, 6.8657702e-01, 3.1335807e-01],
       [2.1624398e-01, 3.7185341e-01, 4.1190264e-01],
       [9.9826115e-01, 1.7385468e-03, 3.0896297e-07],
       ...,
       [6.0351022e-02, 4.8387596e-01, 4.5577306e-01],
       [5.0218976e-01, 1.8173677e-01, 3.1607345e-01],
       [2.1270438e-07, 9.9999690e-01, 2.9172463e-06]], dtype=float32)

In [306]:
y_train_pred = np.argmax(y_train_pred_probs, axis=1)
y_test_pred = np.argmax(y_test_pred_probs, axis=1)

In [307]:
cm_train = confusion_matrix(y_train_pred, y_train)
cm_train

array([[1505,   43,  121],
       [  16,  741,   28],
       [ 108,   69,  912]], dtype=int64)

In [308]:
cm_test = confusion_matrix(y_test_pred, y_test)
cm_test

array([[94, 43, 53],
       [38, 23, 40],
       [34, 20, 49]], dtype=int64)

In [309]:
for i in range(10):
    print( f"{y_train_pred_probs[-i]}, predicted_category: {np.argmax(y_train_pred_probs[-i])}, category: {y_train[-i]}")

[1.5140572e-01 7.6210958e-09 8.4859425e-01], predicted_category: 2, category: 2
[0.5497765  0.03906159 0.41116193], predicted_category: 0, category: 2
[5.404192e-02 6.957852e-08 9.459580e-01], predicted_category: 2, category: 2
[9.9993908e-01 8.0201150e-12 6.0896145e-05], predicted_category: 0, category: 0
[7.3145041e-03 2.1112289e-06 9.9268335e-01], predicted_category: 2, category: 2
[6.3649591e-06 2.4113534e-03 9.9758232e-01], predicted_category: 2, category: 2
[0.11011256 0.88872766 0.00115981], predicted_category: 1, category: 1
[9.9540991e-01 3.2443648e-08 4.5900298e-03], predicted_category: 0, category: 0
[0.01509602 0.00135664 0.9835473 ], predicted_category: 2, category: 2
[0.0146584  0.17346968 0.8118719 ], predicted_category: 2, category: 2


In [310]:
for i in range(10):
    print( f"{y_test_pred_probs[-i]}, predicted_category: {np.argmax(y_test_pred_probs[-i])}, category: {y_test[-i]}")

[6.4887230e-05 6.8657702e-01 3.1335807e-01], predicted_category: 1, category: 0
[2.1270438e-07 9.9999690e-01 2.9172463e-06], predicted_category: 1, category: 0
[0.50218976 0.18173677 0.31607345], predicted_category: 0, category: 2
[0.06035102 0.48387596 0.45577306], predicted_category: 1, category: 1
[2.9785312e-03 9.9640226e-01 6.1919459e-04], predicted_category: 1, category: 0
[1.3386627e-01 1.1073740e-04 8.6602300e-01], predicted_category: 2, category: 2
[9.3599950e-04 4.5883076e-04 9.9860519e-01], predicted_category: 2, category: 2
[9.9998021e-01 1.0663052e-17 1.9819736e-05], predicted_category: 0, category: 0
[0.8102159  0.00283659 0.18694751], predicted_category: 0, category: 2
[0.01530053 0.9807772  0.00392225], predicted_category: 1, category: 2


In [312]:
print('Train accuracy: '+ str(accuracy(cm_train)))
print('Test accuracy: '+ str(accuracy(cm_test)))

Train accuracy: 0.8913350268134349
Test accuracy: 0.4213197969543147


## Sckit-learn

In [313]:
mlp = MLPClassifier(hidden_layer_sizes=(20, 12), random_state=1, max_iter=1000)
mlp.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=(20, 12), max_iter=1000, random_state=1)

In [314]:
ypred = mlp.predict(X_test)
ypred

array([2, 2, 0, 0, 1, 2, 2, 0, 0, 2, 0, 0, 0, 2, 1, 1, 2, 0, 0, 0, 0, 2,
       0, 0, 2, 0, 0, 1, 0, 2, 1, 2, 0, 0, 2, 2, 1, 0, 0, 2, 0, 1, 0, 0,
       2, 1, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 1, 0, 1, 0, 2, 0, 2, 1,
       0, 1, 2, 0, 0, 2, 2, 2, 2, 0, 0, 0, 2, 0, 1, 2, 0, 2, 2, 2, 2, 0,
       0, 2, 1, 0, 1, 0, 2, 0, 0, 0, 2, 0, 0, 1, 1, 0, 0, 0, 2, 1, 0, 2,
       1, 1, 0, 1, 2, 2, 0, 2, 1, 0, 2, 0, 2, 1, 0, 2, 0, 0, 0, 0, 2, 0,
       2, 2, 0, 2, 1, 2, 1, 1, 1, 0, 1, 0, 2, 2, 2, 0, 0, 0, 2, 1, 2, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 2, 0, 0, 1, 2, 0, 2, 0, 0, 0, 2, 1, 0, 2,
       0, 0, 2, 2, 2, 2, 2, 2, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 1, 1, 2, 0, 1,
       0, 2, 0, 2, 0, 2, 0, 0, 2, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 2, 2, 0, 2, 0, 1, 2, 0, 0, 2, 0, 2, 0, 0, 0, 2, 2, 1, 0, 2,
       2, 1, 0, 1, 2, 2, 0, 0, 0, 0, 1, 0, 1, 0, 2, 0, 0, 2, 0, 0, 0, 0,
       2, 1, 1, 0, 2, 1, 1, 2, 2, 2, 0, 2, 1, 0, 0,

In [315]:
cm = confusion_matrix(ypred, y_test)
cm

array([[97, 42, 53],
       [27, 22, 31],
       [42, 22, 58]], dtype=int64)

In [317]:
accuracy(cm)

0.44923857868020306

# Logistic Regression

In [33]:
log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [39]:
ypred_train = log_reg.predict(X_train)
ypred_train

array([0, 0, 0, ..., 0, 2, 0])

In [40]:
cm = confusion_matrix(ypred_train, y_train)
cm

array([[1296,  511,  437],
       [  66,  100,   59],
       [ 267,  242,  565]], dtype=int64)

In [41]:
accuracy(cm)

0.5534857465424782

In [35]:
ypred = log_reg.predict(X_test)
ypred

array([1, 2, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 0, 0, 2,
       0, 0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0,
       2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 2, 1, 0, 0, 2, 0, 2, 0,
       0, 1, 2, 0, 0, 0, 0, 2, 2, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 2, 1, 0,
       0, 2, 0, 0, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 2, 0,
       2, 1, 2, 0, 0, 1, 2, 0, 0, 0, 1, 0, 2, 1, 0, 2, 0, 0, 0, 0, 2, 0,
       0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 1, 0, 2, 2, 2, 2, 0,
       0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 2, 2, 2, 0, 2,
       0, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 0,
       0, 0, 0, 2, 2, 2, 2, 0, 2, 0, 0, 2, 2, 2, 0, 0, 1, 2, 0, 2, 0, 2,
       2, 0, 0, 1, 1, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0,
       1, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 1, 1, 2,
       2, 2, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2,

In [36]:
cm = confusion_matrix(ypred, y_test)
cm

array([[128,  58,  64],
       [ 10,   8,  10],
       [ 28,  20,  68]], dtype=int64)

In [38]:
accuracy(cm)

0.5177664974619289

In [42]:
print(log_reg.coef_)

[[-1.30755663e-02 -4.45358014e-02 -7.32339826e-02  1.40962961e-01
   1.36038280e-01  3.33363589e-02  1.36274383e-02  3.11227896e-02
   1.11215746e-01 -1.24596932e-01  2.08744083e-02  1.06307468e-01
  -5.82111336e-02 -4.38477462e-02  7.82409982e-03  3.12421559e-01
   6.50663349e-02 -3.29714760e-02  1.26505168e-01  6.17663305e-02
   8.47312292e-02 -1.44128519e-02 -3.53724509e-02 -1.21043690e-02
  -1.01346251e-01  3.27165224e-02 -3.50529142e-02  3.74193848e-01
   7.32707932e-04 -1.24090831e-01 -2.65299177e-01  4.60776286e-02
  -1.70942824e-03  9.44400738e-02  3.56963469e-02  8.44193565e-02
   6.16639620e-04  1.59859073e-01  4.17728158e-02  1.26112076e-02
   2.20350173e-01  5.79455644e-02 -9.50319155e-03 -1.22462245e-02
   0.00000000e+00 -9.93387329e-02  3.69991523e-02 -5.29611529e-02
   3.33236221e-02  9.43526302e-03  7.33590489e-02 -1.11284862e-02
   7.45457548e-02 -4.95008519e-02 -2.14067937e-02 -1.35215659e-01
   2.69011653e-01  6.91758763e-02  4.27352338e-02 -7.89327395e-02
  -7.05192

In [43]:
pd.DataFrame(data=log_reg.coef_, columns=list(set(footballdata_wTeamStats.columns.to_list())-set(indexes)-set(label)))

away_goals_against_minute_76_90_percentage  away_total_loses  \
0                                   -0.013076         -0.044536   
1                                    0.041957          0.219610   
2                                   -0.028881         -0.175074   

   away_goals_against_minute_0_15_percentage  \
0                                  -0.073234   
1                                   0.045824   
2                                   0.027410   

   home_goals_against_minute_61_75_percentage  \
0                                    0.140963   
1                                    0.015789   
2                                   -0.156752   

   away_average_home_goals_against  home_goals_for_minute_16_30_percentage  \
0                         0.136038                                0.033336   
1                        -0.144023                                0.047603   
2                         0.007985                               -0.080940   

   away_biggest_win_streak  away_home_loses  \
0                 0.013627         0.031123   
1                -0.017948         0.275203   
2                 0.004321        -0.306326   

   home_goals_against_minute_31_45_percentage  away_goals_for_minute_16_30  \
0                                    0.111216                    -0.124597   
1                                    0.015205                     0.019256   
2                                   -0.126420                     0.105341   

   home_goals_against_minute_76_90  \
0                         0.020874   
1                        -0.080913   
2                         0.060038   

   home_goals_against_minute_91_105_percentage  away_away_draws  \
0                                     0.106307        -0.058211   
1                                     0.044179         0.042229   
2                                    -0.150486         0.015982   

   away_biggest_home_goals_against  away_goals_for_minute_0_15  \
0                        -0.043848                    0.007824   
1                         0.015156                   -0.013675   
2                         0.028692                    0.005851   

   home_average_total_goals_for  home_average_away_goals_for  \
0                      0.312422                     0.065066   
1                      0.170305                    -0.119869   
2                     -0.482727                     0.054802   

   home_penalties_for  home_home_goals_against  home_home_clean_sheets  \
0           -0.032971                 0.126505                0.061766   
1            0.008906                 0.074143               -0.024972   
2            0.024065                -0.200648               -0.036794   

   away_goals_against_minute_31_45_percentage  away_away_goals_against  \
0                                    0.084731                -0.014413   
1                                   -0.041212                 0.018921   
2                                   -0.043520                -0.004508   

   home_goals_for_minute_31_45_percentage  home_form_last1games_draws  \
0                               -0.035372                   -0.012104   
1                                0.010207                    0.008351   
2                                0.025166                    0.003753   

   home_home_loses  home_biggest_win_streak  away_failed_to_score_away  \
0        -0.101346                 0.032717                  -0.035053   
1        -0.128084                -0.026973                   0.081493   
2         0.229430                -0.005743                  -0.046440   

   home_average_away_goals_against  home_total_wins  home_away_goals_against  \
0                         0.374194         0.000733                -0.124091   
1                        -0.218559        -0.128792                 0.133179   
2                        -0.155635         0.128059                -0.009089   

   away_average_away_goals_for  away_goals_against_minute_16_30  \
0            