# Imports

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

import os
from datetime import datetime, timedelta

In [2]:
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier

In [3]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Variables

In [4]:
footballdata_wTeamStats_path = \
    os.path.abspath(os.getcwd())+"\\Data\\teamStats_byLeague\\footballdata_wTeamStats_englishpremierleague.csv"

# Load Football-Data File with Indexes

In [5]:
footballdata_wTeamStats = pd.read_csv(footballdata_wTeamStats_path, index_col=0)
footballdata_wTeamStats.head(5)

C:\Users\ldoutors\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (96,113,194,211) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


AverageAwayWinOdd  AverageDrawWinOdd  AverageHomeWinOdd  AvgOver2_5  \
0                4.0               3.30               2.00        2.01   
1                2.5               3.25               2.88        2.08   
2                3.4               3.30               2.20        2.09   
3               17.0               7.00               1.17        1.49   
4                3.6               3.30               2.10        2.16   

   AvgUnder2_5  AwayGoals  AwayTeamId AwayTeamName        Date  Div  \
0         1.75          0          48     West Ham  14/08/2010   39   
1         1.70          0          45      Everton  14/08/2010   39   
2         1.69          0          36       Fulham  14/08/2010   39   
3         2.49          0          60    West Brom  14/08/2010   39   
4         1.65          2          54   Birmingham  14/08/2010   39   

  FullTimeResult  HomeGoals HomeTeamName  HomeTeamid  Season  \
0              H          3  Aston Villa          66    2010   
1              H          1    Blackburn          67    2010   
2              D          0       Bolton          68    2010   
3              H          6      Chelsea          49    2010   
4              D          2   Sunderland         746    2010   

   away_average_away_goals_against  away_average_away_goals_for  \
0                              0.0                          0.0   
1                              0.0                          0.0   
2                              0.0                          0.0   
3                              0.0                          0.0   
4                              0.0                          0.0   

   away_average_home_goals_against  away_average_home_goals_for  \
0                              0.0                          0.0   
1                              0.0                          0.0   
2                              0.0                          0.0   
3                              0.0                          0.0   
4                              0.0                          0.0   

   away_average_total_goals_against  away_average_total_goals_for  \
0                               0.0                           0.0   
1                               0.0                           0.0   
2                               0.0                           0.0   
3                               0.0                           0.0   
4                               0.0                           0.0   

   away_away_clean_sheets  away_away_draws  away_away_goals_against  \
0                       0                0                        0   
1                       0                0                        0   
2                       0                0                        0   
3                       0                0                        0   
4                       0                0                        0   

   away_away_goals_for  away_away_loses  away_away_wins  \
0                    0                0               0   
1                    0                0               0   
2                    0                0               0   
3                    0                0               0   
4                    0                0               0   

   away_biggest_away_goals_against  away_biggest_away_goals_for  \
0                                0                            0   
1                                0                            0   
2                                0                            0   
3                                0                            0   
4                                0                            0   

  away_biggest_away_lose away_biggest_away_win  away_biggest_draw_streak  \
0                    NaN                   NaN                         0   
1                    NaN                   NaN                         0   
2                    NaN                   NaN                         0   
3                    NaN            

# Data Prep

## Remove Incomplete Columns & Non important (except indexes)

In [6]:
not_complete = ['away_red_cards_minute_0_15', 'away_red_cards_minute_0_15_percentage',
               'away_red_cards_minute_16_30', 'away_red_cards_minute_16_30_percentage',
               'away_red_cards_minute_31_45', 'away_red_cards_minute_31_45_percentage',
               'away_red_cards_minute_46_60', 'away_red_cards_minute_46_60_percentage',
               'away_red_cards_minute_61_75', 'away_red_cards_minute_61_75_percentage',
               'away_red_cards_minute_61_75', 'away_red_cards_minute_61_75_percentage',
               'away_red_cards_minute_76_90', 'away_red_cards_minute_76_90_percentage',
               'away_red_cards_minute_91_105', 'away_red_cards_minute_91_105_percentage',
               'away_yellow_cards_minute_0_15', 'away_yellow_cards_minute_0_15_percentage',
               'away_yellow_cards_minute_16_30', 'away_yellow_cards_minute_16_30_percentage',
               'away_yellow_cards_minute_31_45', 'away_yellow_cards_minute_31_45_percentage',
               'away_yellow_cards_minute_46_60', 'away_yellow_cards_minute_46_60_percentage',
               'away_yellow_cards_minute_61_75', 'away_yellow_cards_minute_61_75_percentage',
               'away_yellow_cards_minute_76_90', 'away_yellow_cards_minute_76_90_percentage',
               'away_yellow_cards_minute_91_105', 'away_yellow_cards_minute_91_105_percentage',
                'home_red_cards_minute_0_15', 'home_red_cards_minute_0_15_percentage',
               'home_red_cards_minute_16_30', 'home_red_cards_minute_16_30_percentage',
               'home_red_cards_minute_31_45', 'home_red_cards_minute_31_45_percentage',
               'home_red_cards_minute_46_60', 'home_red_cards_minute_46_60_percentage',
               'home_red_cards_minute_61_75', 'home_red_cards_minute_61_75_percentage',
               'home_red_cards_minute_61_75', 'home_red_cards_minute_61_75_percentage',
               'home_red_cards_minute_76_90', 'home_red_cards_minute_76_90_percentage',
               'home_red_cards_minute_91_105', 'home_red_cards_minute_91_105_percentage',
               'home_yellow_cards_minute_0_15', 'home_yellow_cards_minute_0_15_percentage',
               'home_yellow_cards_minute_16_30', 'home_yellow_cards_minute_16_30_percentage',
               'home_yellow_cards_minute_31_45', 'home_yellow_cards_minute_31_45_percentage',
               'home_yellow_cards_minute_46_60', 'home_yellow_cards_minute_46_60_percentage',
               'home_yellow_cards_minute_61_75', 'home_yellow_cards_minute_61_75_percentage',
               'home_yellow_cards_minute_76_90', 'home_yellow_cards_minute_76_90_percentage',
               'home_yellow_cards_minute_91_105', 'home_yellow_cards_minute_91_105_percentage']

# away average goals and home average goals will be removed because we will average all columns
not_features = [
               'away_biggest_away_lose', 'away_biggest_away_win', 'away_biggest_home_lose', 'away_biggest_home_win',
               'away_lineups',
               'home_biggest_away_lose', 'home_biggest_away_win', 'home_biggest_home_lose', 'home_biggest_home_win',
               'home_lineups',
    
               'away_biggest_away_goals_against', 'away_biggest_away_goals_for', 'away_biggest_draw_streak',
               'away_biggest_home_goals_against', 'away_biggest_home_goals_for', 'away_biggest_lose_streak',
               'away_biggest_win_streak',
               'home_biggest_away_goals_against', 'home_biggest_away_goals_for', 'home_biggest_draw_streak',
               'home_biggest_home_goals_against', 'home_biggest_home_goals_for', 'home_biggest_lose_streak',
               'home_biggest_win_streak',
    
               'away_average_away_goals_against', 'away_average_away_goals_for', 'away_average_home_goals_against',
               'away_average_home_goals_for', 'away_average_total_goals_against', 'away_average_total_goals_for',
               'home_average_away_goals_against', 'home_average_away_goals_for', 'home_average_home_goals_against',
               'home_average_home_goals_for', 'home_average_total_goals_against', 'home_average_total_goals_for',
    
               'away_penalties_missed', 'away_penalties_missed_percentage', 'away_penalties_scored',
               'away_penalties_scored', 'away_penalties_scored_percentage',
               'home_penalties_missed', 'home_penalties_missed_percentage', 'home_penalties_scored',
               'home_penalties_scored', 'home_penalties_scored_percentage'
               ]

In [7]:
footballdata_wTeamStats = \
    footballdata_wTeamStats[list(set(footballdata_wTeamStats.columns.tolist()) - set(not_complete + not_features))]
footballdata_wTeamStats

away_failed_to_score_away away_goals_against_minute_31_45_percentage  \
0                             0                                        NaN   
1                             0                                        NaN   
2                             0                                        NaN   
3                             0                                        NaN   
4                             0                                        NaN   
...                         ...                                        ...   
4533                          3                                      6.45%   
4534                         11                                     17.33%   
4535                          6                                     15.09%   
4536                          2                                      4.35%   
4537                          6                                     18.60%   

     home_goals_for_minute_91_105_percentage  \
0                                        NaN   
1                                        NaN   
2                                        NaN   
3                                        NaN   
4                                        NaN   
...                                      ...   
4533                                  15.00%   
4534                                   4.00%   
4535                                  11.76%   
4536                                  12.12%   
4537                                   7.27%   

     home_goals_against_minute_0_15_percentage  \
0                                          NaN   
1                                          NaN   
2                                          NaN   
3                                          NaN   
4                                          NaN   
...                                        ...   
4533                                    13.70%   
4534                                    16.36%   
4535                                    14.71%   
4536                                     2.78%   
4537                                    15.56%   

     away_goals_against_minute_0_15_percentage  home_away_draws  \
0                                          NaN                0   
1                                          NaN                0   
2                                          NaN                0   
3                                          NaN                0   
4                                          NaN                0   
...                                        ...              ...   
4533                                     6.45%                5   
4534                                    14.67%                5   
4535                                    11.32%                3   
4536                                    26.09%                3   
4537                                    11.63%                4   

     away_goals_against_minute_61_75_percentage  away_home_wins  AwayGoals  \
0                                           NaN               0          0   
1                                           NaN               0          0   
2                                           NaN               0          0   
3                                           NaN               0          0   
4                                           NaN               0          2   
...                                         ...             ...        ...   
4533                                     19.35%               8          3   
4534                                     18.67%               3          0   
4535                                     16.98%               8          0   
4536                                      8.70%              14          5   
4537                                     20.93%              12          0   

      away_away_clean_sheets away_goals_for_minute_16_30_percentage  Season  \
0                          0                                    NaN   

## Convert NaN/Nulls to 0

In [8]:
nan_to_zero = ['away_goals_against_minute_0_15', 'away_goals_against_minute_0_15_percentage',
            'away_goals_against_minute_16_30', 'away_goals_against_minute_16_30_percentage',
            'away_goals_against_minute_16_30_percentage', 'away_goals_against_minute_31_45',
             'away_goals_against_minute_31_45_percentage', 'away_goals_against_minute_46_60',
            'away_goals_against_minute_46_60_percentage', 'away_goals_against_minute_61_75',
            'away_goals_against_minute_61_75_percentage', 'away_goals_against_minute_76_90',
            'away_goals_against_minute_76_90_percentage', 'away_goals_against_minute_91_105',
            'away_goals_against_minute_91_105_percentage', 'away_goals_for_minute_0_15',
            'away_goals_for_minute_0_15_percentage', 'away_goals_for_minute_16_30', 'away_goals_for_minute_16_30_percentage',
            'away_goals_for_minute_31_45', 'away_goals_for_minute_31_45_percentage', 'away_goals_for_minute_46_60',
            'away_goals_for_minute_46_60_percentage', 'away_goals_for_minute_61_75', 'away_goals_for_minute_61_75_percentage',
            'away_goals_for_minute_76_90', 'away_goals_for_minute_76_90_percentage', 'away_goals_for_minute_91_105',
            'away_goals_for_minute_91_105_percentage',
             'home_goals_against_minute_0_15', 'home_goals_against_minute_0_15_percentage',
            'home_goals_against_minute_16_30', 'home_goals_against_minute_16_30_percentage',
            'home_goals_against_minute_16_30_percentage', 'home_goals_against_minute_31_45',
             'home_goals_against_minute_31_45_percentage', 'home_goals_against_minute_46_60',
            'home_goals_against_minute_46_60_percentage', 'home_goals_against_minute_61_75',
            'home_goals_against_minute_61_75_percentage', 'home_goals_against_minute_76_90',
            'home_goals_against_minute_76_90_percentage', 'home_goals_against_minute_91_105',
            'home_goals_against_minute_91_105_percentage', 'home_goals_for_minute_0_15',
            'home_goals_for_minute_0_15_percentage', 'home_goals_for_minute_16_30', 'home_goals_for_minute_16_30_percentage',
            'home_goals_for_minute_31_45', 'home_goals_for_minute_31_45_percentage', 'home_goals_for_minute_46_60',
            'home_goals_for_minute_46_60_percentage', 'home_goals_for_minute_61_75', 'home_goals_for_minute_61_75_percentage',
            'home_goals_for_minute_76_90', 'home_goals_for_minute_76_90_percentage', 'home_goals_for_minute_91_105',
            'home_goals_for_minute_91_105_percentage']

In [9]:
print(footballdata_wTeamStats.count().sort_values().to_string())

away_goals_against_minute_91_105               2813
away_goals_against_minute_91_105_percentage    2813
home_goals_against_minute_91_105               2816
home_goals_against_minute_91_105_percentage    2816
home_goals_for_minute_91_105_percentage        2878
home_goals_for_minute_91_105                   2878
away_goals_for_minute_91_105                   2887
away_goals_for_minute_91_105_percentage        2887
away_goals_against_minute_0_15_percentage      3760
away_goals_against_minute_0_15                 3760
home_goals_against_minute_0_15                 3762
home_goals_against_minute_0_15_percentage      3762
away_goals_for_minute_0_15_percentage          3781
home_goals_for_minute_16_30_percentage         3781
home_goals_for_minute_16_30                    3781
away_goals_for_minute_0_15                     3781
home_goals_for_minute_0_15                     3783
home_goals_for_minute_0_15_percentage          3783
away_goals_for_minute_16_30                    3802
away_goals_f

In [10]:
for column in footballdata_wTeamStats.columns:
    if 'percentage' in column:
        footballdata_wTeamStats[column] = footballdata_wTeamStats[column].str.slice(0,-1,1).astype(float)

for column in nan_to_zero:
    if 'percentage' in column:
        footballdata_wTeamStats[column] = footballdata_wTeamStats[column].fillna(0.0)
    else:
        footballdata_wTeamStats[column] = footballdata_wTeamStats[column].fillna(0).astype(int)
footballdata_wTeamStats

away_failed_to_score_away  away_goals_against_minute_31_45_percentage  \
0                             0                                        0.00   
1                             0                                        0.00   
2                             0                                        0.00   
3                             0                                        0.00   
4                             0                                        0.00   
...                         ...                                         ...   
4533                          3                                        6.45   
4534                         11                                       17.33   
4535                          6                                       15.09   
4536                          2                                        4.35   
4537                          6                                       18.60   

      home_goals_for_minute_91_105_percentage  \
0                                        0.00   
1                                        0.00   
2                                        0.00   
3                                        0.00   
4                                        0.00   
...                                       ...   
4533                                    15.00   
4534                                     4.00   
4535                                    11.76   
4536                                    12.12   
4537                                     7.27   

      home_goals_against_minute_0_15_percentage  \
0                                          0.00   
1                                          0.00   
2                                          0.00   
3                                          0.00   
4                                          0.00   
...                                         ...   
4533                                      13.70   
4534                                      16.36   
4535                                      14.71   
4536                                       2.78   
4537                                      15.56   

      away_goals_against_minute_0_15_percentage  home_away_draws  \
0                                          0.00                0   
1                                          0.00                0   
2                                          0.00                0   
3                                          0.00                0   
4                                          0.00                0   
...                                         ...              ...   
4533                                       6.45                5   
4534                                      14.67                5   
4535                                      11.32                3   
4536                                      26.09                3   
4537                                      11.63                4   

      away_goals_against_minute_61_75_percentage  away_home_wins  AwayGoals  \
0                                           0.00               0          0   
1                                           0.00               0          0   
2                                           0.00               0          0   
3                                           0.00               0          0   
4                                           0.00               0          2   
...                                          ...             ...        ...   
4533                                       19.35               8          3   
4534                                       18.67               3          0   
4535                                       16.98               8          0   
4536                                        8.70              14          5   
4537                                       20.93              12          0   

      away_away_clean_sheets  away_goals_for_minute_16_30_percentage  Season  \
0        

In [11]:
footballdata_wTeamStats.tail(5)

away_failed_to_score_away  away_goals_against_minute_31_45_percentage  \
4533                          3                                        6.45   
4534                         11                                       17.33   
4535                          6                                       15.09   
4536                          2                                        4.35   
4537                          6                                       18.60   

      home_goals_for_minute_91_105_percentage  \
4533                                    15.00   
4534                                     4.00   
4535                                    11.76   
4536                                    12.12   
4537                                     7.27   

      home_goals_against_minute_0_15_percentage  \
4533                                      13.70   
4534                                      16.36   
4535                                      14.71   
4536                                       2.78   
4537                                      15.56   

      away_goals_against_minute_0_15_percentage  home_away_draws  \
4533                                       6.45                5   
4534                                      14.67                5   
4535                                      11.32                3   
4536                                      26.09                3   
4537                                      11.63                4   

      away_goals_against_minute_61_75_percentage  away_home_wins  AwayGoals  \
4533                                       19.35               8          3   
4534                                       18.67               3          0   
4535                                       16.98               8          0   
4536                                        8.70              14          5   
4537                                       20.93              12          0   

      away_away_clean_sheets  away_goals_for_minute_16_30_percentage  Season  \
4533                       9                                   17.14    2021   
4534                       3                                    9.09    2021   
4535                       1                                   17.50    2021   
4536                      10                                   12.64    2021   
4537                       6                                   21.82    2021   

      home_away_clean_sheets  away_goals_for_minute_76_90_percentage  \
4533                       3                                   12.86   
4534                       1                                   13.64   
4535                       3                                   15.00   
4536                       7                                   14.94   
4537                       7                                   10.91   

      home_goals_against_minute_31_45_percentage AwayTeamName  \
4533                                       12.33      Chelsea   
4534                                       10.91      Norwich   
4535                                       17.65      Everton   
4536                                       19.44     Man City   
4537                                       17.78      Arsenal   

      away_goals_against_minute_61_75                            home_form  \
4533                                6  LDDLDLWLDWDLDWDLLLWWLDLLLLLLWWDWDLL   
4534                               14   WLWLLDDWWLDLWDLWLWLDLDLWWLWDWLDDLL   
4535                                9  WLLLWDLLWLLWLLLLLLDLDLLWLDLLWLLLLLL   
4536                                2  LLLWLWWWDWLWDDLLWDWWWLWWLLLWWLWLLLD   
4537                                9  WWWLLLWWLLDWWWDWDWWLLLWLWWLWWWWLDWD   

      away_goals_against_minute_91_105_percentage  \
4533                                         9.68   
4534                                         6.67   
4535                                         3.77   
4536                                         8.70   
4537  

In [12]:
print(footballdata_wTeamStats.count().sort_values().to_string())

away_form                                      4418
home_form                                      4418
away_failed_to_score_away                      4538
away_away_goals_for                            4538
home_home_clean_sheets                         4538
home_goals_against_minute_76_90_percentage     4538
home_away_wins                                 4538
away_goals_for_minute_31_45                    4538
home_goals_against_minute_91_105               4538
home_penalties_for                             4538
home_home_goals_for                            4538
away_goals_against_minute_16_30_percentage     4538
HomeTeamid                                     4538
away_total_goals_for                           4538
home_goals_against_minute_0_15                 4538
AwayTeamId                                     4538
home_goals_for_minute_0_15                     4538
away_goals_against_minute_91_105               4538
away_away_goals_against                        4538
away_goals_f

## Modifications

### Add Total wins, draws & losses

In [13]:
footballdata_wTeamStats['home_total_wins'] = \
    footballdata_wTeamStats['home_home_wins'] + footballdata_wTeamStats['home_away_wins']
footballdata_wTeamStats['home_total_draws'] = \
    footballdata_wTeamStats['home_home_draws'] + footballdata_wTeamStats['home_away_draws']
footballdata_wTeamStats['home_total_loses'] = \
    footballdata_wTeamStats['home_home_loses'] + footballdata_wTeamStats['home_away_loses']

# TODO: total games is computed bases only on the home games (might require future change)
footballdata_wTeamStats['home_total_games'] = footballdata_wTeamStats['home_total_wins']+\
    footballdata_wTeamStats['home_total_draws']+footballdata_wTeamStats['home_total_loses']

footballdata_wTeamStats['away_total_wins'] = \
    footballdata_wTeamStats['away_home_wins'] + footballdata_wTeamStats['away_away_wins']
footballdata_wTeamStats['away_total_draws'] = \
    footballdata_wTeamStats['away_home_draws'] + footballdata_wTeamStats['away_away_draws']
footballdata_wTeamStats['away_total_loses'] = \
    footballdata_wTeamStats['away_home_loses'] + footballdata_wTeamStats['away_away_loses']

footballdata_wTeamStats['away_total_games'] = footballdata_wTeamStats['away_total_wins']+\
    footballdata_wTeamStats['away_total_draws']+footballdata_wTeamStats['away_total_loses']

footballdata_wTeamStats['home_total_home_games'] = footballdata_wTeamStats['home_home_wins']+\
    footballdata_wTeamStats['home_home_draws']+footballdata_wTeamStats['home_home_loses']
footballdata_wTeamStats['home_total_away_games'] = footballdata_wTeamStats['home_away_wins']+\
    footballdata_wTeamStats['home_away_draws']+footballdata_wTeamStats['home_away_loses']

footballdata_wTeamStats['away_total_home_games'] = footballdata_wTeamStats['away_home_wins']+\
    footballdata_wTeamStats['away_home_draws']+footballdata_wTeamStats['away_home_loses']
footballdata_wTeamStats['away_total_away_games'] = footballdata_wTeamStats['away_away_wins']+\
    footballdata_wTeamStats['away_away_draws']+footballdata_wTeamStats['away_away_loses']

footballdata_wTeamStats

away_failed_to_score_away  away_goals_against_minute_31_45_percentage  \
0                             0                                        0.00   
1                             0                                        0.00   
2                             0                                        0.00   
3                             0                                        0.00   
4                             0                                        0.00   
...                         ...                                         ...   
4533                          3                                        6.45   
4534                         11                                       17.33   
4535                          6                                       15.09   
4536                          2                                        4.35   
4537                          6                                       18.60   

      home_goals_for_minute_91_105_percentage  \
0                                        0.00   
1                                        0.00   
2                                        0.00   
3                                        0.00   
4                                        0.00   
...                                       ...   
4533                                    15.00   
4534                                     4.00   
4535                                    11.76   
4536                                    12.12   
4537                                     7.27   

      home_goals_against_minute_0_15_percentage  \
0                                          0.00   
1                                          0.00   
2                                          0.00   
3                                          0.00   
4                                          0.00   
...                                         ...   
4533                                      13.70   
4534                                      16.36   
4535                                      14.71   
4536                                       2.78   
4537                                      15.56   

      away_goals_against_minute_0_15_percentage  home_away_draws  \
0                                          0.00                0   
1                                          0.00                0   
2                                          0.00                0   
3                                          0.00                0   
4                                          0.00                0   
...                                         ...              ...   
4533                                       6.45                5   
4534                                      14.67                5   
4535                                      11.32                3   
4536                                      26.09                3   
4537                                      11.63                4   

      away_goals_against_minute_61_75_percentage  away_home_wins  AwayGoals  \
0                                           0.00               0          0   
1                                           0.00               0          0   
2                                           0.00               0          0   
3                                           0.00               0          0   
4                                           0.00               0          2   
...                                          ...             ...        ...   
4533                                       19.35               8          3   
4534                                       18.67               3          0   
4535                                       16.98               8          0   
4536                                        8.70              14          5   
4537                                       20.93              12          0   

      away_away_clean_sheets  away_goals_for_minute_16_30_percentage  Season  \
0        

### Away Team & Home Team Form

In [14]:
to_modify = ['away_form', 'home_form']

In [15]:
# Same as before but normalized
games = [1, 2, 5, 10]
for column in to_modify:
    footballdata_wTeamStats[column] = footballdata_wTeamStats[column].fillna('')
    for nr in games:
        footballdata_wTeamStats[column+f"_last{nr}games_wins"] = \
            footballdata_wTeamStats[column].apply(lambda x : x[-nr:]).str.count('W') / \
            footballdata_wTeamStats['home_total_games'].clip(upper=10)
        footballdata_wTeamStats[column+f"_last{nr}games_draws"] = \
            footballdata_wTeamStats[column].apply(lambda x : x[-nr:]).str.count('D') / \
            footballdata_wTeamStats['home_total_games'].clip(upper=10)
        footballdata_wTeamStats[column+f"_last{nr}games_loses"] = \
            footballdata_wTeamStats[column].apply(lambda x : x[-nr:]).str.count('L') / \
            footballdata_wTeamStats['home_total_games'].clip(upper=10)
footballdata_wTeamStats

away_failed_to_score_away  away_goals_against_minute_31_45_percentage  \
0                             0                                        0.00   
1                             0                                        0.00   
2                             0                                        0.00   
3                             0                                        0.00   
4                             0                                        0.00   
...                         ...                                         ...   
4533                          3                                        6.45   
4534                         11                                       17.33   
4535                          6                                       15.09   
4536                          2                                        4.35   
4537                          6                                       18.60   

      home_goals_for_minute_91_105_percentage  \
0                                        0.00   
1                                        0.00   
2                                        0.00   
3                                        0.00   
4                                        0.00   
...                                       ...   
4533                                    15.00   
4534                                     4.00   
4535                                    11.76   
4536                                    12.12   
4537                                     7.27   

      home_goals_against_minute_0_15_percentage  \
0                                          0.00   
1                                          0.00   
2                                          0.00   
3                                          0.00   
4                                          0.00   
...                                         ...   
4533                                      13.70   
4534                                      16.36   
4535                                      14.71   
4536                                       2.78   
4537                                      15.56   

      away_goals_against_minute_0_15_percentage  home_away_draws  \
0                                          0.00                0   
1                                          0.00                0   
2                                          0.00                0   
3                                          0.00                0   
4                                          0.00                0   
...                                         ...              ...   
4533                                       6.45                5   
4534                                      14.67                5   
4535                                      11.32                3   
4536                                      26.09                3   
4537                                      11.63                4   

      away_goals_against_minute_61_75_percentage  away_home_wins  AwayGoals  \
0                                           0.00               0          0   
1                                           0.00               0          0   
2                                           0.00               0          0   
3                                           0.00               0          0   
4                                           0.00               0          2   
...                                          ...             ...        ...   
4533                                       19.35               8          3   
4534                                       18.67               3          0   
4535                                       16.98               8          0   
4536                                        8.70              14          5   
4537                                       20.93              12          0   

      away_away_clean_sheets  away_goals_for_minute_16_30_percentage  Season  \
0        

In [16]:
footballdata_wTeamStats = footballdata_wTeamStats.drop(columns=to_modify)

In [17]:
print(footballdata_wTeamStats.dtypes.sort_values().to_string())

home_goals_against_minute_76_90                  int32
away_goals_against_minute_31_45                  int32
home_goals_for_minute_76_90                      int32
away_goals_against_minute_16_30                  int32
home_goals_for_minute_61_75                      int32
away_goals_for_minute_16_30                      int32
away_goals_for_minute_0_15                       int32
away_goals_against_minute_46_60                  int32
away_goals_for_minute_76_90                      int32
home_goals_for_minute_46_60                      int32
away_goals_for_minute_61_75                      int32
home_goals_against_minute_16_30                  int32
away_goals_for_minute_31_45                      int32
home_goals_against_minute_91_105                 int32
home_goals_for_minute_91_105                     int32
home_goals_against_minute_0_15                   int32
home_goals_against_minute_61_75                  int32
home_goals_for_minute_0_15                       int32
away_goals

### Remove 1st 5 "jornadas"

In [18]:
footballdata_wTeamStats = footballdata_wTeamStats[footballdata_wTeamStats['home_total_games']>=5]
footballdata_wTeamStats.reindex(sorted(footballdata_wTeamStats.columns), axis=1)

AverageAwayWinOdd  AverageDrawWinOdd  AverageHomeWinOdd  AvgOver2_5  \
50                15.00               6.00               1.22        1.42   
51                 4.50               3.50               1.83        2.13   
52                 2.30               3.25               3.20        1.81   
53                 2.63               3.20               2.75        2.18   
54                 7.50               4.33               1.44        1.90   
...                 ...                ...                ...         ...   
4533               1.67               4.17               4.98        1.64   
4534               7.02               4.90               1.44        1.61   
4535               1.87               3.68               4.26        1.91   
4536               1.26               5.88              12.83        1.66   
4537               3.42               3.60               2.12        1.78   

      AvgUnder2_5  AwayGoals  AwayTeamId AwayTeamName        Date  Div  \
50           2.68          3          60    West Brom  25/09/2010   39   
51           1.67          0          61        Wigan  25/09/2010   39   
52           1.95          2          67    Blackburn  25/09/2010   39   
53           1.65          0          45      Everton  25/09/2010   39   
54           1.85          2         746   Sunderland  25/09/2010   39   
...           ...        ...         ...          ...         ...  ...   
4533         2.28          3          49      Chelsea  11/05/2022   39   
4534         2.34          0          71      Norwich  11/05/2022   39   
4535         1.92          0          45      Everton  11/05/2022   39   
4536         2.24          5          50     Man City  11/05/2022   39   
4537         2.05          0          42      Arsenal  12/05/2022   39   

     FullTimeResult  HomeGoals HomeTeamName  HomeTeamid  Season  \
50                A          2      Arsenal          42    2010   
51                D          0   Birmingham          54    2010   
52                A          1    Blackpool        1356    2010   
53                D          0       Fulham          36    2010   
54                D          2    Liverpool          40    2010   
...             ...        ...          ...         ...     ...   
4533              A          0        Leeds          63    2021   
4534              H          3    Leicester          46    2021   
4535              D          0      Watford          38    2021   
4536              A          1       Wolves          39    2021   
4537              H          3    Tottenham          47    2021   

      away_away_clean_sheets  away_away_draws  away_away_goals_against  \
50                         0                0                        7   
51                         1                0                        0   
52                         0                1                        3   
53                         0                0                        2   
54                         0                1                        2   
...                      ...              ...                      ...   
4533                       9                4                       11   
4534                       3                3                       37   
4535                       1                3                       36   
4536                      10                3                        8   
4537                       6                1                       26   

      away_away_goals_for  away_away_loses  away_away_wins  \
50                      0                2               0   
51                      1                0               1   
52                      2                1               0   
53                      0                2               0   
54                      1                1               0   
...                   ...              ...             ...   
4533                   36                3              11   
45

## Define indexes and labels

In [19]:
indexes = ['AverageAwayWinOdd', 'AverageDrawWinOdd', 'AverageHomeWinOdd',
               'AvgOver2_5', 'AvgUnder2_5', 'AwayGoals', 'AwayTeamId',
               'AwayTeamId', 'AwayTeamName', 'Date', 'Div',
               'HomeGoals', 'HomeTeamName', 'HomeTeamid', 'Season',
               'FullTimeResult'
               ]

label = ['goals']

footballdata_wTeamStats[label] = footballdata_wTeamStats['AwayGoals'] + footballdata_wTeamStats['HomeGoals']

In [20]:
print(footballdata_wTeamStats.drop(columns=indexes).dtypes.sort_index().to_string())

away_away_clean_sheets                           int64
away_away_draws                                  int64
away_away_goals_against                          int64
away_away_goals_for                              int64
away_away_loses                                  int64
away_away_wins                                   int64
away_failed_to_score_away                        int64
away_failed_to_score_home                        int64
away_failed_to_score_total                       int64
away_form_last10games_draws                    float64
away_form_last10games_loses                    float64
away_form_last10games_wins                     float64
away_form_last1games_draws                     float64
away_form_last1games_loses                     float64
away_form_last1games_wins                      float64
away_form_last2games_draws                     float64
away_form_last2games_loses                     float64
away_form_last2games_wins                      float64
away_form_

In [21]:
list(set(footballdata_wTeamStats.columns.to_list())-set(indexes)-set(label))

['away_failed_to_score_away',
 'away_goals_against_minute_31_45_percentage',
 'home_form_last10games_wins',
 'home_goals_for_minute_91_105_percentage',
 'home_goals_against_minute_0_15_percentage',
 'home_total_draws',
 'away_goals_against_minute_0_15_percentage',
 'home_away_draws',
 'away_goals_against_minute_61_75_percentage',
 'away_home_wins',
 'away_form_last5games_wins',
 'home_form_last10games_draws',
 'away_away_clean_sheets',
 'away_goals_for_minute_16_30_percentage',
 'home_away_clean_sheets',
 'away_goals_for_minute_76_90_percentage',
 'home_goals_against_minute_31_45_percentage',
 'away_goals_against_minute_61_75',
 'home_form_last2games_draws',
 'home_form_last1games_draws',
 'away_total_loses',
 'away_goals_against_minute_91_105_percentage',
 'home_goals_against_minute_31_45',
 'home_goals_for_minute_16_30',
 'away_form_last1games_loses',
 'away_form_last5games_draws',
 'home_total_wins',
 'home_goals_for_minute_16_30_percentage',
 'home_form_last2games_wins',
 'away_goa

## Normalize Features (per game)

In [22]:
away_away_games_norm = ['away_away_clean_sheets', 'away_away_draws', 'away_away_goals_against',
                      'away_away_goals_for', 'away_away_loses', 'away_away_wins', 'away_failed_to_score_away']

away_home_games_norm = ['away_failed_to_score_home', 'away_home_clean_sheets',
                       'away_home_draws', 'away_home_goals_against', 'away_home_goals_for',
                       'away_home_loses', 'away_home_wins']

away_total_games_norm = ['away_failed_to_score_total', 'away_goals_against_minute_0_15',
                        'away_goals_against_minute_16_30', 'away_goals_against_minute_31_45',
                        'away_goals_against_minute_46_60', 'away_goals_against_minute_61_75',
                        'away_goals_against_minute_76_90', 'away_goals_against_minute_91_105',
                        'away_goals_for_minute_0_15', 'away_goals_for_minute_16_30',
                        'away_goals_for_minute_31_45', 'away_goals_for_minute_46_60',
                        'away_goals_for_minute_61_75', 'away_goals_for_minute_76_90',
                        'away_goals_for_minute_91_105', 'away_penalties_for', 'away_total_clean_sheets',
                        'away_total_draws', 'away_total_goals_against', 'away_total_goals_for', 'away_total_loses',
                        'away_total_wins']

home_away_games_norm = ['home_away_clean_sheets', 'home_away_draws', 'home_away_goals_against',
                      'home_away_goals_for', 'home_away_loses', 'home_away_wins', 'home_failed_to_score_away']

home_home_games_norm = ['home_failed_to_score_home', 'home_home_clean_sheets',
                       'home_home_draws', 'home_home_goals_against', 'home_home_goals_for',
                       'home_home_loses', 'home_home_wins']

home_total_games_norm = ['home_failed_to_score_total', 'home_goals_against_minute_0_15',
                        'home_goals_against_minute_16_30', 'home_goals_against_minute_31_45',
                        'home_goals_against_minute_46_60', 'home_goals_against_minute_61_75',
                        'home_goals_against_minute_76_90', 'home_goals_against_minute_91_105',
                        'home_goals_for_minute_0_15', 'home_goals_for_minute_16_30',
                        'home_goals_for_minute_31_45', 'home_goals_for_minute_46_60',
                        'home_goals_for_minute_61_75', 'home_goals_for_minute_76_90',
                        'home_goals_for_minute_91_105', 'home_penalties_for', 'home_total_clean_sheets',
                        'home_total_draws', 'home_total_goals_against', 'home_total_goals_for', 'home_total_loses',
                        'home_total_wins']

In [23]:
for feature in away_away_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['away_total_away_games']
for feature in away_home_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['away_total_home_games']
for feature in away_total_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['away_total_games']
    
for feature in home_away_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['home_total_away_games']
for feature in home_home_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['home_total_home_games']
for feature in home_total_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['home_total_games']
    
footballdata_wTeamStats

away_failed_to_score_away  away_goals_against_minute_31_45_percentage  \
50                     1.000000                                       10.00   
51                     0.000000                                       30.77   
52                     0.000000                                        0.00   
53                     1.000000                                       28.57   
54                     0.500000                                        0.00   
...                         ...                                         ...   
4533                   0.166667                                        6.45   
4534                   0.647059                                       17.33   
4535                   0.352941                                       15.09   
4536                   0.117647                                        4.35   
4537                   0.352941                                       18.60   

      home_goals_for_minute_91_105_percentage  \
50                                       0.00   
51                                       0.00   
52                                       0.00   
53                                       0.00   
54                                       0.00   
...                                       ...   
4533                                    15.00   
4534                                     4.00   
4535                                    11.76   
4536                                    12.12   
4537                                     7.27   

      home_goals_against_minute_0_15_percentage  \
50                                         0.00   
51                                         0.00   
52                                        23.08   
53                                        50.00   
54                                        16.67   
...                                         ...   
4533                                      13.70   
4534                                      16.36   
4535                                      14.71   
4536                                       2.78   
4537                                      15.56   

      away_goals_against_minute_0_15_percentage  home_away_draws  \
50                                        20.00         0.666667   
51                                         0.00         0.666667   
52                                         0.00         0.000000   
53                                        28.57         1.000000   
54                                        16.67         0.333333   
...                                         ...              ...   
4533                                       6.45         0.277778   
4534                                      14.67         0.294118   
4535                                      11.32         0.166667   
4536                                      26.09         0.166667   
4537                                      11.63         0.222222   

      away_goals_against_minute_61_75_percentage  away_home_wins  AwayGoals  \
50                                         30.00        0.666667          3   
51                                         23.08        0.000000          0   
52                                         16.67        0.333333          2   
53                                         28.57        0.000000          0   
54                                          0.00        0.333333          2   
...                                          ...             ...        ...   
4533                                       19.35        0.470588          3   
4534                                       18.67        0.166667          0   
4535                                       16.98        0.470588          0   
4536                                        8.70        0.777778          5   
4537                                       20.93        0.666667          0   

      away_away_clean_sheets  away_goals_for_minute_16_30_percentage  Season  \
50       

In [24]:
#TODO: this is based only on home team games (for most cases should be ok)
footballdata_wTeamStats['total_games'] = footballdata_wTeamStats['home_total_games']
footballdata_wTeamStats = \
    footballdata_wTeamStats.drop(columns=['away_total_away_games','away_total_home_games', 'away_total_games',
                                          'home_total_away_games', 'home_total_home_games', 'home_total_games'])
footballdata_wTeamStats

away_failed_to_score_away  away_goals_against_minute_31_45_percentage  \
50                     1.000000                                       10.00   
51                     0.000000                                       30.77   
52                     0.000000                                        0.00   
53                     1.000000                                       28.57   
54                     0.500000                                        0.00   
...                         ...                                         ...   
4533                   0.166667                                        6.45   
4534                   0.647059                                       17.33   
4535                   0.352941                                       15.09   
4536                   0.117647                                        4.35   
4537                   0.352941                                       18.60   

      home_goals_for_minute_91_105_percentage  \
50                                       0.00   
51                                       0.00   
52                                       0.00   
53                                       0.00   
54                                       0.00   
...                                       ...   
4533                                    15.00   
4534                                     4.00   
4535                                    11.76   
4536                                    12.12   
4537                                     7.27   

      home_goals_against_minute_0_15_percentage  \
50                                         0.00   
51                                         0.00   
52                                        23.08   
53                                        50.00   
54                                        16.67   
...                                         ...   
4533                                      13.70   
4534                                      16.36   
4535                                      14.71   
4536                                       2.78   
4537                                      15.56   

      away_goals_against_minute_0_15_percentage  home_away_draws  \
50                                        20.00         0.666667   
51                                         0.00         0.666667   
52                                         0.00         0.000000   
53                                        28.57         1.000000   
54                                        16.67         0.333333   
...                                         ...              ...   
4533                                       6.45         0.277778   
4534                                      14.67         0.294118   
4535                                      11.32         0.166667   
4536                                      26.09         0.166667   
4537                                      11.63         0.222222   

      away_goals_against_minute_61_75_percentage  away_home_wins  AwayGoals  \
50                                         30.00        0.666667          3   
51                                         23.08        0.000000          0   
52                                         16.67        0.333333          2   
53                                         28.57        0.000000          0   
54                                          0.00        0.333333          2   
...                                          ...             ...        ...   
4533                                       19.35        0.470588          3   
4534                                       18.67        0.166667          0   
4535                                       16.98        0.470588          0   
4536                                        8.70        0.777778          5   
4537                                       20.93        0.666667          0   

      away_away_clean_sheets  away_goals_for_minute_16_30_percentage  Season  \
50       

## Extract Features

In [25]:
footballdata_wTeamStats.groupby(label).count()

away_failed_to_score_away  away_goals_against_minute_31_45_percentage  \
goals                                                                          
0                            281                                         281   
1                            656                                         656   
2                            929                                         929   
3                            904                                         904   
4                            610                                         610   
5                            339                                         339   
6                            135                                         135   
7                             52                                          52   
8                             19                                          19   
9                             10                                          10   
10                             2                                           2   

       home_goals_for_minute_91_105_percentage  \
goals                                            
0                                          281   
1                                          656   
2                                          929   
3                                          904   
4                                          610   
5                                          339   
6                                          135   
7                                           52   
8                                           19   
9                                           10   
10                                           2   

       home_goals_against_minute_0_15_percentage  \
goals                                              
0                                            281   
1                                            656   
2                                            929   
3                                            904   
4                                            610   
5                                            339   
6                                            135   
7                                             52   
8                                             19   
9                                             10   
10                                             2   

       away_goals_against_minute_0_15_percentage  home_away_draws  \
goals                                                               
0                                            281              281   
1                                            656              656   
2                                            929              929   
3                                            904              904   
4                                            610              610   
5                                            339              339   
6                                            135              135   
7                                             52               52   
8                                             19               19   
9                                             10               10   
10                                             2                2   

       away_goals_against_minute_61_75_percentage  away_home_wins  AwayGoals  \
goals                                                                          
0                                             281             281        281   
1                                             656             656        656   
2                                             929             929        929   
3                                             904             904        904   
4                                             610             610        610   
5                                             339             339        339   
6                                             135             135        135   
7                   

In [26]:
X = footballdata_wTeamStats[list(set(footballdata_wTeamStats.columns.to_list())-set(indexes)-set(label))].values
y = footballdata_wTeamStats[label].values
y = y.reshape((y.shape[0],))
y = (y>2.5).astype(int)
#y = np.array([0 if label=='H' else 1 if label=='D' else 2 for label in y])

In [28]:
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
X

array([[-0.67603271, -0.33784454,  3.58304246, ...,  0.35139512,
         2.78689   ,  0.13715961],
       [-0.67603271, -1.66884483, -1.68602343, ...,  1.21827094,
        -0.84464084, -0.94196667],
       [-0.67603271, -0.33784454, -1.68602343, ..., -1.59780813,
        -0.84464084, -0.94196667],
       ...,
       [-0.67603271, -0.10296214,  0.17364688, ...,  0.26648184,
         0.97112458, -0.43414254],
       [-0.67603271,  0.23258415, -1.06613333, ...,  0.70625656,
         0.97112458,  2.14125128],
       [-0.67603271,  0.61286995,  0.17364688, ...,  0.0155441 ,
         0.97112458,  1.2162859 ]])

In [29]:
print ('The first element of X is: ', X[0])

The first element of X is:  [-0.67603271 -0.33784454  3.58304246 -0.62905642  1.11991248 -1.02674515
 -1.71334288  1.21707815 -1.93153824  1.05674562  2.53004808  3.66069243
  1.48714511  1.08792727  1.37583172  1.05596208 -1.39176705 -1.79983584
 -1.01870202 -1.45098669  2.14998382  0.83243739 -2.17434847  0.56487127
 -1.64043751 -0.7349832  -0.83887884  2.88240217 -0.54819468  2.24977821
  3.65397149  2.91910455  0.18316667  5.45576675  1.14707657 -1.05379503
 -1.50003116 -0.09048922 -1.02915653  1.60422132 -0.68132332  0.62367073
  1.25461888  0.15627577  1.55897539 -0.08610973 -0.30145263  0.10843084
  2.50013671  0.98175479 -1.55478628 -2.18697096 -1.7613771  -1.18877844
  0.90037071 -0.25881824 -1.16935698  1.5017462   2.52821315 -1.4026712
 -1.05967165 -1.6756865   2.12493978  2.55775581 -2.0267237   1.09736101
  1.14654644 -1.58386917 -0.61283756 -1.45092405 -1.54184814 -1.61610922
  0.09329849  1.09055577 -1.90913194 -1.00860431 -1.56882314  0.2400149
 -0.2797958   2.79977167 

In [30]:
print ('The first element of y is: ', y[0])
print ('The last element of y is: ', y[-1])

The first element of y is:  1
The last element of y is:  1


In [31]:
print ('The shape of X is: ' + str(X.shape))
print ('The shape of y is: ' + str(y.shape))

The shape of X is: (3937, 125)
The shape of y is: (3937,)


In [40]:
#train_size = int(X.shape[0]*0.8)
#train_size

3149

In [41]:
#X_train = X[:train_size]
#print(X_train.shape)
#X_test = X[train_size:]
#print(X_test.shape)

(3149, 125)
(788, 125)


In [42]:
#y_train = y[:train_size]
#print(y_train.shape)
#y_test = y[train_size:]
#print(y_test.shape)

(3149,)
(788,)


In [32]:
X_train, X_test, y_train, y_test \
    = train_test_split(X, y, test_size=0.2, random_state=1)

X_train, X_val, y_train, y_val \
    = train_test_split(X_train, y_train, test_size=0.25, random_state=1) # 0.25 x 0.8 = 0.2

In [33]:
print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

(2361, 125)
(788, 125)
(788, 125)


In [34]:
print(y_train.shape)
print(y_val.shape)
print(y_test.shape)

(2361,)
(788,)
(788,)


# ML Algorithms

In [35]:
def accuracy(confusion_matrix):
    diagonal_sum = confusion_matrix.trace()
    sum_of_all_elements = confusion_matrix.sum()
    return diagonal_sum / sum_of_all_elements

## GBT

### Test changing only max_depth

In [42]:
max_val_score = 0
iterations_wo_update = 0
for max_depth in range(125):
    max_depth += 1 # start on 1
    print(f"Testing Max Depth: {max_depth}")
    gbtClassifier = GradientBoostingClassifier(max_depth = max_depth, n_iter_no_change=7, verbose=1, validation_fraction=0.1)\
        .fit(X_train, y_train)
    val_score = gbtClassifier.score(X_val, y_val)
    if val_score > max_val_score:
        iterations_wo_update = 0
        best_max_depth = max_depth
        max_val_score = val_score
        best_model = gbtClassifier
        print(f"New best max depth: {best_max_depth}, validation score: {max_val_score}")
    else:
        iterations_wo_update +=1
        if iterations_wo_update >= 10:
            print("No improvements on the last 10 iterations, stopping here...")
            break
            
gbtClassifier = best_model

Testing Max Depth: 1
      Iter       Train Loss   Remaining Time 
         1           1.3847            1.01s
         2           1.3834            1.04s
         3           1.3823            0.98s
         4           1.3812            0.87s
         5           1.3801            0.69s
         6           1.3791            0.82s
         7           1.3781            0.83s
         8           1.3772            0.72s
New best max depth: 1, validation score: 0.5583756345177665
Testing Max Depth: 2
      Iter       Train Loss   Remaining Time 
         1           1.3825            3.09s
         2           1.3793            2.30s
         3           1.3766            2.04s
         4           1.3737            1.89s
         5           1.3715            1.79s
         6           1.3677            1.80s
         7           1.3654            1.78s
         8           1.3628            1.62s
         9           1.3604            1.58s
        10           1.3579            1.

In [43]:
best_model.score(X_train, y_train)

0.5463786531130876

In [44]:
best_model.score(X_test, y_test)

0.5444162436548223

In [45]:
y_train_pred = gbtClassifier.predict(X_train)
y_test_pred = gbtClassifier.predict(X_test)

In [46]:
cm_train = confusion_matrix(y_train_pred, y_train)
cm_train

array([[310, 219],
       [852, 980]], dtype=int64)

In [47]:
cm_test = confusion_matrix(y_test_pred, y_test)
cm_test

array([[ 93,  99],
       [260, 336]], dtype=int64)

### Test changing also n_estimators

In [54]:
gbtClassifier = GradientBoostingClassifier(n_estimators=3, verbose=1, validation_fraction=0.1).fit(X_train, y_train)
print(gbtClassifier.score(X_train, y_train))
gbtClassifier.score(X_test, y_test)

      Iter       Train Loss   Remaining Time 
         1           1.3800            0.06s
         2           1.3729            0.03s
         3           1.3671            0.00s
0.5950868276154172


0.5368020304568528

In [55]:
max_val_score = 0
for n_estimators in range(5,100,5):
    print(f"Testing N Estimators: {n_estimators}")
    iterations_wo_update = 0
    for max_depth in range(125):
        max_depth += 1 # start on 1
        gbtClassifier = GradientBoostingClassifier(max_depth = max_depth, n_estimators=n_estimators, validation_fraction=0.1)\
            .fit(X_train, y_train)
        val_score = gbtClassifier.score(X_val, y_val)
        if val_score > max_val_score:
            iterations_wo_update = 0
            best_max_depth = max_depth
            max_val_score = val_score
            best_model = gbtClassifier
            print(f"New best max depth and N estimators: ({best_max_depth}, {n_estimators}), validation score: {max_val_score}")
        else:
            iterations_wo_update +=1
            if iterations_wo_update >= 10:
                print("No improvements on the last 10 iterations, moving on...")
                break
            
gbtClassifier = best_model

Testing N Estimators: 5
New best max depth and N estimators: (1, 5), validation score: 0.5685279187817259
No improvements on the last 10 iterations, moving on...
Testing N Estimators: 10
No improvements on the last 10 iterations, moving on...
Testing N Estimators: 15
No improvements on the last 10 iterations, moving on...
Testing N Estimators: 20


KeyboardInterrupt: 

In [56]:
gbtClassifier.score(X_train, y_train)

1.0

In [57]:
gbtClassifier.score(X_test, y_test)

0.5342639593908629

In [104]:
y_train_pred = gbtClassifier.predict(X_train)
y_test_pred = gbtClassifier.predict(X_test)

In [105]:
cm_train = confusion_matrix(y_train_pred, y_train)
cm_train

array([[913, 400, 372],
       [  4,  39,   1],
       [139, 135, 358]], dtype=int64)

In [106]:
cm_test = confusion_matrix(y_test_pred, y_test)
cm_test

array([[312, 130, 133],
       [  8,   5,   7],
       [ 54,  37, 102]], dtype=int64)

## MLP

In [60]:
model = Sequential(
    [ 
        tf.keras.Input(shape=(125,)),
        Dense(20, activation = 'relu', name='L1', kernel_regularizer=tf.keras.regularizers.l2(0.1)),
        Dense(20, activation = 'relu', name='L2', kernel_regularizer=tf.keras.regularizers.l2(0.1)),
        Dense(3, activation = 'linear', name='L3')    # < softmax activation here
    ]
)
model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.Adam(0.0001),
)
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 L1 (Dense)                  (None, 20)                2520      
                                                                 
 L2 (Dense)                  (None, 20)                420       
                                                                 
 L3 (Dense)                  (None, 3)                 63        
                                                                 
Total params: 3,003
Trainable params: 3,003
Non-trainable params: 0
_________________________________________________________________


In [61]:
model.fit(
    X_train,y_train,
    epochs=200
)

Epoch 1/200
74/74 [==============================] - 0s 1ms/step - loss: 6.3091
Epoch 2/200
74/74 [==============================] - 0s 1ms/step - loss: 5.8893
Epoch 3/200
74/74 [==============================] - 0s 801us/step - loss: 5.5081
Epoch 4/200
74/74 [==============================] - 0s 1ms/step - loss: 5.1586
Epoch 5/200
74/74 [==============================] - 0s 835us/step - loss: 4.8358
Epoch 6/200
74/74 [==============================] - 0s 884us/step - loss: 4.5361
Epoch 7/200
74/74 [==============================] - 0s 968us/step - loss: 4.2572
Epoch 8/200
74/74 [==============================] - 0s 814us/step - loss: 3.9978
Epoch 9/200
74/74 [==============================] - 0s 945us/step - loss: 3.7565
Epoch 10/200
74/74 [==============================] - 0s 857us/step - loss: 3.5318
Epoch 11/200
74/74 [==============================] - 0s 1ms/step - loss: 3.3228
Epoch 12/200
74/74 [==============================] - 0s 736us/step - loss: 3.1283
Epoch 13/200
74/74 [=

74/74 [==============================] - 0s 1ms/step - loss: 0.6975
Epoch 101/200
74/74 [==============================] - 0s 856us/step - loss: 0.6973
Epoch 102/200
74/74 [==============================] - 0s 854us/step - loss: 0.6973
Epoch 103/200
74/74 [==============================] - 0s 1ms/step - loss: 0.6970
Epoch 104/200
74/74 [==============================] - 0s 944us/step - loss: 0.6968
Epoch 105/200
74/74 [==============================] - 0s 1ms/step - loss: 0.6967
Epoch 106/200
74/74 [==============================] - 0s 1ms/step - loss: 0.6967
Epoch 107/200
74/74 [==============================] - 0s 797us/step - loss: 0.6965
Epoch 108/200
74/74 [==============================] - 0s 1ms/step - loss: 0.6965
Epoch 109/200
74/74 [==============================] - 0s 805us/step - loss: 0.6962
Epoch 110/200
74/74 [==============================] - 0s 1ms/step - loss: 0.6962
Epoch 111/200
74/74 [==============================] - 0s 1ms/step - loss: 0.6960
Epoch 112/200
74/74 

74/74 [==============================] - 0s 872us/step - loss: 0.6934
Epoch 199/200
74/74 [==============================] - 0s 838us/step - loss: 0.6934
Epoch 200/200
74/74 [==============================] - 0s 752us/step - loss: 0.6934


In [62]:
[layer1, layer2, layer3] = model.layers
W1,b1 = layer1.get_weights()
W2,b2 = layer2.get_weights()
W3,b3 = layer3.get_weights()

In [63]:
W1

array([[-3.8830818e-05,  4.0531046e-05,  3.1025222e-05, ...,
        -3.7587582e-05,  3.4074612e-05,  2.5132815e-34],
       [ 4.0918853e-04, -3.5500419e-05, -9.9958697e-06, ...,
         4.6062432e-04, -3.3419801e-05, -1.9609705e-34],
       [-1.6981454e-04, -3.9194787e-05, -5.4212083e-05, ...,
        -1.8772326e-04, -4.5260869e-05, -2.2977055e-34],
       ...,
       [-1.2770386e-03,  1.4701382e-05,  6.5732456e-06, ...,
        -1.4730997e-03,  9.6608346e-07, -7.7488596e-36],
       [ 5.2168197e-04,  2.5828358e-06,  1.2970322e-05, ...,
         6.0329941e-04,  1.2989772e-05, -2.5579315e-34],
       [ 1.6839328e-04,  1.6365679e-05,  2.4200013e-05, ...,
         1.9354658e-04,  1.7770561e-05, -1.7377978e-34]], dtype=float32)

In [64]:
y_train_pred_probs = tf.nn.softmax(model.predict(X_train)).numpy()
y_train_pred_probs

74/74 [==============================] - 0s 656us/step


array([[4.9188522e-01, 5.0789255e-01, 2.2219648e-04],
       [4.9254808e-01, 5.0722927e-01, 2.2264228e-04],
       [4.9243137e-01, 5.0734609e-01, 2.2254622e-04],
       ...,
       [4.9276927e-01, 5.0700796e-01, 2.2278234e-04],
       [4.9247172e-01, 5.0730568e-01, 2.2258059e-04],
       [4.9199164e-01, 5.0778610e-01, 2.2227514e-04]], dtype=float32)

In [65]:
y_test_pred_probs = tf.nn.softmax(model.predict(X_test)).numpy()
y_test_pred_probs

25/25 [==============================] - 0s 646us/step


array([[4.9231756e-01, 5.0746000e-01, 2.2248838e-04],
       [4.9251407e-01, 5.0726330e-01, 2.2259363e-04],
       [4.9204916e-01, 5.0772852e-01, 2.2231597e-04],
       ...,
       [4.9236763e-01, 5.0740987e-01, 2.2251085e-04],
       [4.9243975e-01, 5.0733763e-01, 2.2256192e-04],
       [4.9209329e-01, 5.0768429e-01, 2.2233774e-04]], dtype=float32)

In [66]:
y_train_pred = np.argmax(y_train_pred_probs, axis=1)
y_test_pred = np.argmax(y_test_pred_probs, axis=1)

In [67]:
cm_train = confusion_matrix(y_train_pred, y_train)
cm_train

array([[   0,    0],
       [1162, 1199]], dtype=int64)

In [68]:
cm_test = confusion_matrix(y_test_pred, y_test)
cm_test

array([[  0,   0],
       [353, 435]], dtype=int64)

In [69]:
for i in range(10):
    print( f"{y_train_pred_probs[-i]}, predicted_category: {np.argmax(y_train_pred_probs[-i])}, category: {y_train[-i]}")

[4.9188522e-01 5.0789255e-01 2.2219648e-04], predicted_category: 1, category: 0
[4.9199164e-01 5.0778610e-01 2.2227514e-04], predicted_category: 1, category: 1
[4.9247172e-01 5.0730568e-01 2.2258059e-04], predicted_category: 1, category: 0
[4.9276927e-01 5.0700796e-01 2.2278234e-04], predicted_category: 1, category: 0
[4.9236959e-01 5.0740784e-01 2.2252799e-04], predicted_category: 1, category: 1
[4.9247015e-01 5.0730729e-01 2.2258003e-04], predicted_category: 1, category: 0
[4.9230766e-01 5.0746989e-01 2.2248729e-04], predicted_category: 1, category: 1
[4.9208525e-01 5.0769240e-01 2.2232984e-04], predicted_category: 1, category: 1
[4.9209502e-01 5.0768262e-01 2.2234963e-04], predicted_category: 1, category: 1
[4.9209496e-01 5.0768274e-01 2.2233908e-04], predicted_category: 1, category: 0


In [147]:
for i in range(10):
    print( f"{y_test_pred_probs[-i]}, predicted_category: {np.argmax(y_test_pred_probs[-i])}, category: {y_test[-i]}")

[0.46438932 0.26013002 0.2754806 ], predicted_category: 0, category: 0
[0.45374075 0.25880393 0.28745532], predicted_category: 0, category: 0
[0.14754826 0.24316351 0.6092882 ], predicted_category: 2, category: 2
[0.3451147 0.274435  0.3804503], predicted_category: 2, category: 1
[0.6681957 0.1987667 0.1330376], predicted_category: 0, category: 0
[0.1846948  0.25842822 0.556877  ], predicted_category: 2, category: 2
[0.16090234 0.24836555 0.59073216], predicted_category: 2, category: 2
[0.8806478  0.09074179 0.02861039], predicted_category: 0, category: 0
[0.31032193 0.27536654 0.41431153], predicted_category: 2, category: 2
[0.5812784  0.229438   0.18928358], predicted_category: 0, category: 2


In [70]:
print('Train accuracy: '+ str(accuracy(cm_train)))
print('Test accuracy: '+ str(accuracy(cm_test)))

Train accuracy: 0.5078356628547226
Test accuracy: 0.5520304568527918
