# Imports

In [63]:
import pandas as pd
pd.set_option('display.max_columns', None)

import os
from datetime import datetime, timedelta

In [64]:
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [65]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Variables

In [66]:
footballdata_wTeamStats_path = \
    os.path.abspath(os.getcwd())+"\\Data\\teamStats_byLeague\\footballdata_wTeamStats_englishpremierleague.csv"

# Load Football-Data File with Indexes

In [67]:
footballdata_wTeamStats = pd.read_csv(footballdata_wTeamStats_path, index_col=0)
footballdata_wTeamStats.head(5)

C:\Users\ldoutors\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (96,113,194,211) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


AverageAwayWinOdd  AverageDrawWinOdd  AverageHomeWinOdd  AvgOver2_5  \
0                4.0               3.30               2.00        2.01   
1                2.5               3.25               2.88        2.08   
2                3.4               3.30               2.20        2.09   
3               17.0               7.00               1.17        1.49   
4                3.6               3.30               2.10        2.16   

   AvgUnder2_5  AwayGoals  AwayTeamId AwayTeamName        Date  Div  \
0         1.75          0          48     West Ham  14/08/2010   39   
1         1.70          0          45      Everton  14/08/2010   39   
2         1.69          0          36       Fulham  14/08/2010   39   
3         2.49          0          60    West Brom  14/08/2010   39   
4         1.65          2          54   Birmingham  14/08/2010   39   

  FullTimeResult  HomeGoals HomeTeamName  HomeTeamid  Season  \
0              H          3  Aston Villa          66    2010   
1              H          1    Blackburn          67    2010   
2              D          0       Bolton          68    2010   
3              H          6      Chelsea          49    2010   
4              D          2   Sunderland         746    2010   

   away_average_away_goals_against  away_average_away_goals_for  \
0                              0.0                          0.0   
1                              0.0                          0.0   
2                              0.0                          0.0   
3                              0.0                          0.0   
4                              0.0                          0.0   

   away_average_home_goals_against  away_average_home_goals_for  \
0                              0.0                          0.0   
1                              0.0                          0.0   
2                              0.0                          0.0   
3                              0.0                          0.0   
4                              0.0                          0.0   

   away_average_total_goals_against  away_average_total_goals_for  \
0                               0.0                           0.0   
1                               0.0                           0.0   
2                               0.0                           0.0   
3                               0.0                           0.0   
4                               0.0                           0.0   

   away_away_clean_sheets  away_away_draws  away_away_goals_against  \
0                       0                0                        0   
1                       0                0                        0   
2                       0                0                        0   
3                       0                0                        0   
4                       0                0                        0   

   away_away_goals_for  away_away_loses  away_away_wins  \
0                    0                0               0   
1                    0                0               0   
2                    0                0               0   
3                    0                0               0   
4                    0                0               0   

   away_biggest_away_goals_against  away_biggest_away_goals_for  \
0                                0                            0   
1                                0                            0   
2                                0                            0   
3                                0                            0   
4                                0                            0   

  away_biggest_away_lose away_biggest_away_win  away_biggest_draw_streak  \
0                    NaN                   NaN                         0   
1                    NaN                   NaN                         0   
2                    NaN                   NaN                         0   
3                    NaN            

# Data Prep

## Remove Incomplete Columns & Non important (except indexes)

In [68]:
not_complete = ['away_red_cards_minute_0_15', 'away_red_cards_minute_0_15_percentage',
               'away_red_cards_minute_16_30', 'away_red_cards_minute_16_30_percentage',
               'away_red_cards_minute_31_45', 'away_red_cards_minute_31_45_percentage',
               'away_red_cards_minute_46_60', 'away_red_cards_minute_46_60_percentage',
               'away_red_cards_minute_61_75', 'away_red_cards_minute_61_75_percentage',
               'away_red_cards_minute_61_75', 'away_red_cards_minute_61_75_percentage',
               'away_red_cards_minute_76_90', 'away_red_cards_minute_76_90_percentage',
               'away_red_cards_minute_91_105', 'away_red_cards_minute_91_105_percentage',
               'away_yellow_cards_minute_0_15', 'away_yellow_cards_minute_0_15_percentage',
               'away_yellow_cards_minute_16_30', 'away_yellow_cards_minute_16_30_percentage',
               'away_yellow_cards_minute_31_45', 'away_yellow_cards_minute_31_45_percentage',
               'away_yellow_cards_minute_46_60', 'away_yellow_cards_minute_46_60_percentage',
               'away_yellow_cards_minute_61_75', 'away_yellow_cards_minute_61_75_percentage',
               'away_yellow_cards_minute_76_90', 'away_yellow_cards_minute_76_90_percentage',
               'away_yellow_cards_minute_91_105', 'away_yellow_cards_minute_91_105_percentage',
                'home_red_cards_minute_0_15', 'home_red_cards_minute_0_15_percentage',
               'home_red_cards_minute_16_30', 'home_red_cards_minute_16_30_percentage',
               'home_red_cards_minute_31_45', 'home_red_cards_minute_31_45_percentage',
               'home_red_cards_minute_46_60', 'home_red_cards_minute_46_60_percentage',
               'home_red_cards_minute_61_75', 'home_red_cards_minute_61_75_percentage',
               'home_red_cards_minute_61_75', 'home_red_cards_minute_61_75_percentage',
               'home_red_cards_minute_76_90', 'home_red_cards_minute_76_90_percentage',
               'home_red_cards_minute_91_105', 'home_red_cards_minute_91_105_percentage',
               'home_yellow_cards_minute_0_15', 'home_yellow_cards_minute_0_15_percentage',
               'home_yellow_cards_minute_16_30', 'home_yellow_cards_minute_16_30_percentage',
               'home_yellow_cards_minute_31_45', 'home_yellow_cards_minute_31_45_percentage',
               'home_yellow_cards_minute_46_60', 'home_yellow_cards_minute_46_60_percentage',
               'home_yellow_cards_minute_61_75', 'home_yellow_cards_minute_61_75_percentage',
               'home_yellow_cards_minute_76_90', 'home_yellow_cards_minute_76_90_percentage',
               'home_yellow_cards_minute_91_105', 'home_yellow_cards_minute_91_105_percentage']

not_features = [
               'away_biggest_away_lose', 'away_biggest_away_win', 'away_biggest_home_lose', 'away_biggest_home_win',
               'away_lineups',
               'home_biggest_away_lose', 'home_biggest_away_win', 'home_biggest_home_lose', 'home_biggest_home_win',
               'home_lineups',
    
               'away_biggest_away_goals_against', 'away_biggest_away_goals_for', 'away_biggest_draw_streak',
               'away_biggest_home_goals_against', 'away_biggest_home_goals_for', 'away_biggest_lose_streak',
               'away_biggest_win_streak',
               'home_biggest_away_goals_against', 'home_biggest_away_goals_for', 'home_biggest_draw_streak',
               'home_biggest_home_goals_against', 'home_biggest_home_goals_for', 'home_biggest_lose_streak',
               'home_biggest_win_streak',
    
               'away_average_away_goals_against', 'away_average_away_goals_for', 'away_average_home_goals_against',
               'away_average_home_goals_for', 'away_average_total_goals_against', 'away_average_total_goals_for',
               'home_average_away_goals_against', 'home_average_away_goals_for', 'home_average_home_goals_against',
               'home_average_home_goals_for', 'home_average_total_goals_against', 'home_average_total_goals_for',
    
               'away_penalties_missed', 'away_penalties_missed_percentage', 'away_penalties_scored',
               'away_penalties_scored', 'away_penalties_scored_percentage',
               'home_penalties_missed', 'home_penalties_missed_percentage', 'home_penalties_scored',
               'home_penalties_scored', 'home_penalties_scored_percentage'
               ]

In [69]:
footballdata_wTeamStats = \
    footballdata_wTeamStats[list(set(footballdata_wTeamStats.columns.tolist()) - set(not_complete + not_features))]
footballdata_wTeamStats

home_goals_for_minute_46_60_percentage  away_away_goals_against  \
0                                       NaN                        0   
1                                       NaN                        0   
2                                       NaN                        0   
3                                       NaN                        0   
4                                       NaN                        0   
...                                     ...                      ...   
4533                                 17.50%                       11   
4534                                 14.00%                       37   
4535                                  2.94%                       36   
4536                                 21.21%                        8   
4537                                 21.82%                       26   

      away_goals_against_minute_31_45  \
0                                 NaN   
1                                 NaN   
2                                 NaN   
3                                 NaN   
4                                 NaN   
...                               ...   
4533                              2.0   
4534                             13.0   
4535                              8.0   
4536                              1.0   
4537                              8.0   

     away_goals_against_minute_61_75_percentage  away_away_loses  \
0                                           NaN                0   
1                                           NaN                0   
2                                           NaN                0   
3                                           NaN                0   
4                                           NaN                0   
...                                         ...              ...   
4533                                     19.35%                3   
4534                                     18.67%               12   
4535                                     16.98%               12   
4536                                      8.70%                1   
4537                                     20.93%                7   

      home_total_goals_against  away_goals_for_minute_46_60  \
0                            0                          NaN   
1                            0                          NaN   
2                            0                          NaN   
3                            0                          NaN   
4                            0                          NaN   
...                        ...                          ...   
4533                        74                         19.0   
4534                        56                          5.0   
4535                        70                          8.0   
4536                        34                         10.0   
4537                        40                         12.0   

      home_away_clean_sheets  away_total_clean_sheets  \
0                          0                        0   
1                          0                        0   
2                          0                        0   
3                          0                        0   
4                          0                        0   
...                      ...                      ...   
4533                       3                       15   
4534                       1                        6   
4535                       3                        7   
4536                       7                       21   
4537                       7                       13   

     home_goals_against_minute_46_60_percentage  \
0                                           NaN   
1                                           NaN   
2                                           NaN   
3                                           NaN   
4                                           NaN   
...                                         ...   
4533                           

## Convert NaN/Nulls to 0

In [70]:
nan_to_zero = ['away_goals_against_minute_0_15', 'away_goals_against_minute_0_15_percentage',
            'away_goals_against_minute_16_30', 'away_goals_against_minute_16_30_percentage',
            'away_goals_against_minute_16_30_percentage', 'away_goals_against_minute_31_45',
             'away_goals_against_minute_31_45_percentage', 'away_goals_against_minute_46_60',
            'away_goals_against_minute_46_60_percentage', 'away_goals_against_minute_61_75',
            'away_goals_against_minute_61_75_percentage', 'away_goals_against_minute_76_90',
            'away_goals_against_minute_76_90_percentage', 'away_goals_against_minute_91_105',
            'away_goals_against_minute_91_105_percentage', 'away_goals_for_minute_0_15',
            'away_goals_for_minute_0_15_percentage', 'away_goals_for_minute_16_30', 'away_goals_for_minute_16_30_percentage',
            'away_goals_for_minute_31_45', 'away_goals_for_minute_31_45_percentage', 'away_goals_for_minute_46_60',
            'away_goals_for_minute_46_60_percentage', 'away_goals_for_minute_61_75', 'away_goals_for_minute_61_75_percentage',
            'away_goals_for_minute_76_90', 'away_goals_for_minute_76_90_percentage', 'away_goals_for_minute_91_105',
            'away_goals_for_minute_91_105_percentage',
             'home_goals_against_minute_0_15', 'home_goals_against_minute_0_15_percentage',
            'home_goals_against_minute_16_30', 'home_goals_against_minute_16_30_percentage',
            'home_goals_against_minute_16_30_percentage', 'home_goals_against_minute_31_45',
             'home_goals_against_minute_31_45_percentage', 'home_goals_against_minute_46_60',
            'home_goals_against_minute_46_60_percentage', 'home_goals_against_minute_61_75',
            'home_goals_against_minute_61_75_percentage', 'home_goals_against_minute_76_90',
            'home_goals_against_minute_76_90_percentage', 'home_goals_against_minute_91_105',
            'home_goals_against_minute_91_105_percentage', 'home_goals_for_minute_0_15',
            'home_goals_for_minute_0_15_percentage', 'home_goals_for_minute_16_30', 'home_goals_for_minute_16_30_percentage',
            'home_goals_for_minute_31_45', 'home_goals_for_minute_31_45_percentage', 'home_goals_for_minute_46_60',
            'home_goals_for_minute_46_60_percentage', 'home_goals_for_minute_61_75', 'home_goals_for_minute_61_75_percentage',
            'home_goals_for_minute_76_90', 'home_goals_for_minute_76_90_percentage', 'home_goals_for_minute_91_105',
            'home_goals_for_minute_91_105_percentage']

In [71]:
print(footballdata_wTeamStats.count().sort_values().to_string())

away_goals_against_minute_91_105_percentage    2813
away_goals_against_minute_91_105               2813
home_goals_against_minute_91_105               2816
home_goals_against_minute_91_105_percentage    2816
home_goals_for_minute_91_105                   2878
home_goals_for_minute_91_105_percentage        2878
away_goals_for_minute_91_105_percentage        2887
away_goals_for_minute_91_105                   2887
away_goals_against_minute_0_15_percentage      3760
away_goals_against_minute_0_15                 3760
home_goals_against_minute_0_15                 3762
home_goals_against_minute_0_15_percentage      3762
away_goals_for_minute_0_15                     3781
away_goals_for_minute_0_15_percentage          3781
home_goals_for_minute_16_30                    3781
home_goals_for_minute_16_30_percentage         3781
home_goals_for_minute_0_15                     3783
home_goals_for_minute_0_15_percentage          3783
away_goals_for_minute_16_30_percentage         3802
away_goals_f

In [72]:
for column in footballdata_wTeamStats.columns:
    if 'percentage' in column:
        footballdata_wTeamStats[column] = footballdata_wTeamStats[column].str.slice(0,-1,1).astype(float)

for column in nan_to_zero:
    if 'percentage' in column:
        footballdata_wTeamStats[column] = footballdata_wTeamStats[column].fillna(0.0)
    else:
        footballdata_wTeamStats[column] = footballdata_wTeamStats[column].fillna(0).astype(int)
footballdata_wTeamStats

home_goals_for_minute_46_60_percentage  away_away_goals_against  \
0                                       0.00                        0   
1                                       0.00                        0   
2                                       0.00                        0   
3                                       0.00                        0   
4                                       0.00                        0   
...                                      ...                      ...   
4533                                   17.50                       11   
4534                                   14.00                       37   
4535                                    2.94                       36   
4536                                   21.21                        8   
4537                                   21.82                       26   

      away_goals_against_minute_31_45  \
0                                   0   
1                                   0   
2                                   0   
3                                   0   
4                                   0   
...                               ...   
4533                                2   
4534                               13   
4535                                8   
4536                                1   
4537                                8   

      away_goals_against_minute_61_75_percentage  away_away_loses  \
0                                           0.00                0   
1                                           0.00                0   
2                                           0.00                0   
3                                           0.00                0   
4                                           0.00                0   
...                                          ...              ...   
4533                                       19.35                3   
4534                                       18.67               12   
4535                                       16.98               12   
4536                                        8.70                1   
4537                                       20.93                7   

      home_total_goals_against  away_goals_for_minute_46_60  \
0                            0                            0   
1                            0                            0   
2                            0                            0   
3                            0                            0   
4                            0                            0   
...                        ...                          ...   
4533                        74                           19   
4534                        56                            5   
4535                        70                            8   
4536                        34                           10   
4537                        40                           12   

      home_away_clean_sheets  away_total_clean_sheets  \
0                          0                        0   
1                          0                        0   
2                          0                        0   
3                          0                        0   
4                          0                        0   
...                      ...                      ...   
4533                       3                       15   
4534                       1                        6   
4535                       3                        7   
4536                       7                       21   
4537                       7                       13   

      home_goals_against_minute_46_60_percentage  \
0                                           0.00   
1                                           0.00   
2                                           0.00   
3                                           0.00   
4                                           0.00   
...                                          ...   
4

In [73]:
footballdata_wTeamStats.tail(5)

home_goals_for_minute_46_60_percentage  away_away_goals_against  \
4533                                   17.50                       11   
4534                                   14.00                       37   
4535                                    2.94                       36   
4536                                   21.21                        8   
4537                                   21.82                       26   

      away_goals_against_minute_31_45  \
4533                                2   
4534                               13   
4535                                8   
4536                                1   
4537                                8   

      away_goals_against_minute_61_75_percentage  away_away_loses  \
4533                                       19.35                3   
4534                                       18.67               12   
4535                                       16.98               12   
4536                                        8.70                1   
4537                                       20.93                7   

      home_total_goals_against  away_goals_for_minute_46_60  \
4533                        74                           19   
4534                        56                            5   
4535                        70                            8   
4536                        34                           10   
4537                        40                           12   

      home_away_clean_sheets  away_total_clean_sheets  \
4533                       3                       15   
4534                       1                        6   
4535                       3                        7   
4536                       7                       21   
4537                       7                       13   

      home_goals_against_minute_46_60_percentage  \
4533                                       23.29   
4534                                       10.91   
4535                                       14.71   
4536                                       11.11   
4537                                        8.89   

      home_goals_against_minute_76_90  home_goals_for_minute_16_30_percentage  \
4533                                9                                   17.50   
4534                                8                                   12.00   
4535                               10                                   20.59   
4536                                6                                   15.15   
4537                                8                                   12.73   

            Date  away_goals_against_minute_0_15  \
4533  11/05/2022                               2   
4534  11/05/2022                              11   
4535  11/05/2022                               6   
4536  11/05/2022                               6   
4537  12/05/2022                               5   

      away_goals_against_minute_91_105  \
4533                                 3   
4534                                 5   
4535                                 2   
4536                                 2   
4537                                 4   

      home_goals_against_minute_91_105_percentage  \
4533                                         6.85   
4534                                         9.09   
4535                                         8.82   
4536                                         8.33   
4537                                         8.89   

      away_goals_for_minute_76_90  home_home_wins  away_home_clean_sheets  \
4533                            9               4                       6   
4534                            3               8                       3   
4535                            6               2                       6   
4536                           13               7                      11   
4537                            6              11                       7   

      away_goals_for_minute_16_30_p

In [74]:
print(footballdata_wTeamStats.count().sort_values().to_string())

home_form                                      4418
away_form                                      4418
home_goals_for_minute_46_60_percentage         4538
away_goals_for_minute_91_105                   4538
away_goals_for_minute_61_75                    4538
away_goals_for_minute_31_45                    4538
home_goals_for_minute_91_105                   4538
away_home_loses                                4538
AwayTeamId                                     4538
AvgOver2_5                                     4538
home_goals_against_minute_0_15                 4538
away_total_goals_for                           4538
away_goals_for_minute_31_45_percentage         4538
home_goals_for_minute_91_105_percentage        4538
home_goals_for_minute_31_45_percentage         4538
home_goals_for_minute_31_45                    4538
away_goals_against_minute_76_90                4538
away_goals_for_minute_91_105_percentage        4538
away_goals_against_minute_61_75                4538
home_goals_a

## Modifications

### Add Total wins, draws & losses

In [75]:
footballdata_wTeamStats['home_total_wins'] = \
    footballdata_wTeamStats['home_home_wins'] + footballdata_wTeamStats['home_away_wins']
footballdata_wTeamStats['home_total_draws'] = \
    footballdata_wTeamStats['home_home_draws'] + footballdata_wTeamStats['home_away_draws']
footballdata_wTeamStats['home_total_loses'] = \
    footballdata_wTeamStats['home_home_loses'] + footballdata_wTeamStats['home_away_loses']

footballdata_wTeamStats['home_total_games'] = footballdata_wTeamStats['home_total_wins']+\
    footballdata_wTeamStats['home_total_draws']+footballdata_wTeamStats['home_total_loses']

footballdata_wTeamStats['away_total_wins'] = \
    footballdata_wTeamStats['away_home_wins'] + footballdata_wTeamStats['away_away_wins']
footballdata_wTeamStats['away_total_draws'] = \
    footballdata_wTeamStats['away_home_draws'] + footballdata_wTeamStats['away_away_draws']
footballdata_wTeamStats['away_total_loses'] = \
    footballdata_wTeamStats['away_home_loses'] + footballdata_wTeamStats['away_away_loses']

footballdata_wTeamStats

home_goals_for_minute_46_60_percentage  away_away_goals_against  \
0                                       0.00                        0   
1                                       0.00                        0   
2                                       0.00                        0   
3                                       0.00                        0   
4                                       0.00                        0   
...                                      ...                      ...   
4533                                   17.50                       11   
4534                                   14.00                       37   
4535                                    2.94                       36   
4536                                   21.21                        8   
4537                                   21.82                       26   

      away_goals_against_minute_31_45  \
0                                   0   
1                                   0   
2                                   0   
3                                   0   
4                                   0   
...                               ...   
4533                                2   
4534                               13   
4535                                8   
4536                                1   
4537                                8   

      away_goals_against_minute_61_75_percentage  away_away_loses  \
0                                           0.00                0   
1                                           0.00                0   
2                                           0.00                0   
3                                           0.00                0   
4                                           0.00                0   
...                                          ...              ...   
4533                                       19.35                3   
4534                                       18.67               12   
4535                                       16.98               12   
4536                                        8.70                1   
4537                                       20.93                7   

      home_total_goals_against  away_goals_for_minute_46_60  \
0                            0                            0   
1                            0                            0   
2                            0                            0   
3                            0                            0   
4                            0                            0   
...                        ...                          ...   
4533                        74                           19   
4534                        56                            5   
4535                        70                            8   
4536                        34                           10   
4537                        40                           12   

      home_away_clean_sheets  away_total_clean_sheets  \
0                          0                        0   
1                          0                        0   
2                          0                        0   
3                          0                        0   
4                          0                        0   
...                      ...                      ...   
4533                       3                       15   
4534                       1                        6   
4535                       3                        7   
4536                       7                       21   
4537                       7                       13   

      home_goals_against_minute_46_60_percentage  \
0                                           0.00   
1                                           0.00   
2                                           0.00   
3                                           0.00   
4                                           0.00   
...                                          ...   
4

### Away Team & Home Team Form

In [76]:
to_modify = ['away_form', 'home_form']

In [77]:
games = [1, 2, 5]
for column in to_modify:
    footballdata_wTeamStats[column] = footballdata_wTeamStats[column].fillna('')
    for nr in games:
        footballdata_wTeamStats[column+f"_last{nr}games_wins"] = \
            footballdata_wTeamStats[column].apply(lambda x : x[-nr:]).str.count('W')
        footballdata_wTeamStats[column+f"_last{nr}games_draws"] = \
            footballdata_wTeamStats[column].apply(lambda x : x[-nr:]).str.count('D')
        footballdata_wTeamStats[column+f"_last{nr}games_loses"] = \
            footballdata_wTeamStats[column].apply(lambda x : x[-nr:]).str.count('L')
footballdata_wTeamStats

home_goals_for_minute_46_60_percentage  away_away_goals_against  \
0                                       0.00                        0   
1                                       0.00                        0   
2                                       0.00                        0   
3                                       0.00                        0   
4                                       0.00                        0   
...                                      ...                      ...   
4533                                   17.50                       11   
4534                                   14.00                       37   
4535                                    2.94                       36   
4536                                   21.21                        8   
4537                                   21.82                       26   

      away_goals_against_minute_31_45  \
0                                   0   
1                                   0   
2                                   0   
3                                   0   
4                                   0   
...                               ...   
4533                                2   
4534                               13   
4535                                8   
4536                                1   
4537                                8   

      away_goals_against_minute_61_75_percentage  away_away_loses  \
0                                           0.00                0   
1                                           0.00                0   
2                                           0.00                0   
3                                           0.00                0   
4                                           0.00                0   
...                                          ...              ...   
4533                                       19.35                3   
4534                                       18.67               12   
4535                                       16.98               12   
4536                                        8.70                1   
4537                                       20.93                7   

      home_total_goals_against  away_goals_for_minute_46_60  \
0                            0                            0   
1                            0                            0   
2                            0                            0   
3                            0                            0   
4                            0                            0   
...                        ...                          ...   
4533                        74                           19   
4534                        56                            5   
4535                        70                            8   
4536                        34                           10   
4537                        40                           12   

      home_away_clean_sheets  away_total_clean_sheets  \
0                          0                        0   
1                          0                        0   
2                          0                        0   
3                          0                        0   
4                          0                        0   
...                      ...                      ...   
4533                       3                       15   
4534                       1                        6   
4535                       3                        7   
4536                       7                       21   
4537                       7                       13   

      home_goals_against_minute_46_60_percentage  \
0                                           0.00   
1                                           0.00   
2                                           0.00   
3                                           0.00   
4                                           0.00   
...                                          ...   
4

In [78]:
# Same as before but normalized
games = [1, 2, 5, 10]
for column in to_modify:
    footballdata_wTeamStats[column] = footballdata_wTeamStats[column].fillna('')
    for nr in games:
        footballdata_wTeamStats[column+f"_last{nr}games_wins"] = \
            footballdata_wTeamStats[column].apply(lambda x : x[-nr:]).str.count('W') / \
            footballdata_wTeamStats['home_total_games'].clip(upper=10)
        footballdata_wTeamStats[column+f"_last{nr}games_draws"] = \
            footballdata_wTeamStats[column].apply(lambda x : x[-nr:]).str.count('D') / \
            footballdata_wTeamStats['home_total_games'].clip(upper=10)
        footballdata_wTeamStats[column+f"_last{nr}games_loses"] = \
            footballdata_wTeamStats[column].apply(lambda x : x[-nr:]).str.count('L') / \
            footballdata_wTeamStats['home_total_games'].clip(upper=10)
footballdata_wTeamStats

home_goals_for_minute_46_60_percentage  away_away_goals_against  \
0                                       0.00                        0   
1                                       0.00                        0   
2                                       0.00                        0   
3                                       0.00                        0   
4                                       0.00                        0   
...                                      ...                      ...   
4533                                   17.50                       11   
4534                                   14.00                       37   
4535                                    2.94                       36   
4536                                   21.21                        8   
4537                                   21.82                       26   

      away_goals_against_minute_31_45  \
0                                   0   
1                                   0   
2                                   0   
3                                   0   
4                                   0   
...                               ...   
4533                                2   
4534                               13   
4535                                8   
4536                                1   
4537                                8   

      away_goals_against_minute_61_75_percentage  away_away_loses  \
0                                           0.00                0   
1                                           0.00                0   
2                                           0.00                0   
3                                           0.00                0   
4                                           0.00                0   
...                                          ...              ...   
4533                                       19.35                3   
4534                                       18.67               12   
4535                                       16.98               12   
4536                                        8.70                1   
4537                                       20.93                7   

      home_total_goals_against  away_goals_for_minute_46_60  \
0                            0                            0   
1                            0                            0   
2                            0                            0   
3                            0                            0   
4                            0                            0   
...                        ...                          ...   
4533                        74                           19   
4534                        56                            5   
4535                        70                            8   
4536                        34                           10   
4537                        40                           12   

      home_away_clean_sheets  away_total_clean_sheets  \
0                          0                        0   
1                          0                        0   
2                          0                        0   
3                          0                        0   
4                          0                        0   
...                      ...                      ...   
4533                       3                       15   
4534                       1                        6   
4535                       3                        7   
4536                       7                       21   
4537                       7                       13   

      home_goals_against_minute_46_60_percentage  \
0                                           0.00   
1                                           0.00   
2                                           0.00   
3                                           0.00   
4                                           0.00   
...                                          ...   
4

In [79]:
footballdata_wTeamStats = footballdata_wTeamStats.drop(columns=to_modify)

In [80]:
print(footballdata_wTeamStats.dtypes.sort_values().to_string())

home_goals_against_minute_91_105                 int32
home_goals_for_minute_61_75                      int32
away_goals_for_minute_0_15                       int32
home_goals_for_minute_76_90                      int32
home_goals_against_minute_46_60                  int32
away_goals_against_minute_61_75                  int32
home_goals_for_minute_46_60                      int32
home_goals_for_minute_0_15                       int32
away_goals_against_minute_76_90                  int32
home_goals_for_minute_31_45                      int32
home_goals_for_minute_16_30                      int32
home_goals_against_minute_61_75                  int32
away_goals_for_minute_76_90                      int32
away_goals_for_minute_16_30                      int32
home_goals_against_minute_31_45                  int32
away_goals_against_minute_0_15                   int32
away_goals_for_minute_91_105                     int32
away_goals_against_minute_31_45                  int32
away_goals

### Remove 1st 5 "jornadas"

In [81]:
footballdata_wTeamStats = footballdata_wTeamStats[footballdata_wTeamStats['home_total_games']>=5]
footballdata_wTeamStats

home_goals_for_minute_46_60_percentage  away_away_goals_against  \
50                                     30.77                        7   
51                                     44.44                        0   
52                                      0.00                        3   
53                                     33.33                        2   
54                                     20.00                        2   
...                                      ...                      ...   
4533                                   17.50                       11   
4534                                   14.00                       37   
4535                                    2.94                       36   
4536                                   21.21                        8   
4537                                   21.82                       26   

      away_goals_against_minute_31_45  \
50                                  1   
51                                  4   
52                                  0   
53                                  2   
54                                  0   
...                               ...   
4533                                2   
4534                               13   
4535                                8   
4536                                1   
4537                                8   

      away_goals_against_minute_61_75_percentage  away_away_loses  \
50                                         30.00                2   
51                                         23.08                0   
52                                         16.67                1   
53                                         28.57                2   
54                                          0.00                1   
...                                          ...              ...   
4533                                       19.35                3   
4534                                       18.67               12   
4535                                       16.98               12   
4536                                        8.70                1   
4537                                       20.93                7   

      home_total_goals_against  away_goals_for_minute_46_60  \
50                           4                            1   
51                           8                            0   
52                          12                            1   
53                           6                            0   
54                           7                            0   
...                        ...                          ...   
4533                        74                           19   
4534                        56                            5   
4535                        70                            8   
4536                        34                           10   
4537                        40                           12   

      home_away_clean_sheets  away_total_clean_sheets  \
50                         0                        1   
51                         0                        1   
52                         2                        1   
53                         1                        0   
54                         1                        1   
...                      ...                      ...   
4533                       3                       15   
4534                       1                        6   
4535                       3                        7   
4536                       7                       21   
4537                       7                       13   

      home_goals_against_minute_46_60_percentage  \
50                                         20.00   
51                                         33.33   
52                                         15.38   
53                                          0.00   
54                                         33.33   
...                                          ...   
4

## Define indexes and labels

In [82]:
indexes = ['AverageAwayWinOdd', 'AverageDrawWinOdd', 'AverageHomeWinOdd',
               'AvgOver2_5', 'AvgUnder2_5', 'AwayGoals', 'AwayTeamId',
               'AwayTeamId', 'AwayTeamName', 'Date', 'Div',
               'HomeGoals', 'HomeTeamName', 'HomeTeamid', 'Season',
               ]
label = ['FullTimeResult']

In [83]:
print(footballdata_wTeamStats.drop(columns=indexes).dtypes.sort_values().to_string())

away_goals_against_minute_16_30                  int32
away_goals_for_minute_91_105                     int32
away_goals_for_minute_61_75                      int32
away_goals_for_minute_0_15                       int32
home_goals_for_minute_76_90                      int32
away_goals_for_minute_31_45                      int32
home_goals_for_minute_91_105                     int32
home_goals_for_minute_61_75                      int32
home_goals_against_minute_31_45                  int32
home_goals_against_minute_0_15                   int32
home_goals_against_minute_46_60                  int32
away_goals_against_minute_46_60                  int32
home_goals_for_minute_0_15                       int32
home_goals_against_minute_61_75                  int32
away_goals_for_minute_76_90                      int32
away_goals_against_minute_91_105                 int32
away_goals_against_minute_0_15                   int32
home_goals_for_minute_31_45                      int32
home_goals

In [84]:
list(set(footballdata_wTeamStats.columns.to_list())-set(indexes)-set(label))

['home_goals_for_minute_46_60_percentage',
 'away_failed_to_score_away',
 'away_away_goals_against',
 'home_away_draws',
 'home_away_wins',
 'home_goals_for_minute_61_75_percentage',
 'away_goals_against_minute_0_15_percentage',
 'away_form_last5games_wins',
 'away_away_draws',
 'away_goals_for_minute_0_15_percentage',
 'away_goals_against_minute_31_45',
 'away_goals_against_minute_61_75_percentage',
 'home_form_last2games_draws',
 'away_away_loses',
 'home_total_goals_against',
 'away_goals_for_minute_46_60',
 'home_away_clean_sheets',
 'home_form_last10games_loses',
 'home_form_last2games_loses',
 'away_total_clean_sheets',
 'home_goals_against_minute_46_60_percentage',
 'home_goals_against_minute_76_90',
 'home_goals_against_minute_16_30_percentage',
 'home_form_last5games_draws',
 'home_goals_for_minute_16_30_percentage',
 'away_goals_against_minute_61_75',
 'away_goals_for_minute_91_105_percentage',
 'home_goals_for_minute_46_60',
 'home_total_draws',
 'home_form_last1games_wins',

In [85]:
X = footballdata_wTeamStats[list(set(footballdata_wTeamStats.columns.to_list())-set(indexes)-set(label))].values
y = footballdata_wTeamStats[label].values
y = y.reshape((y.shape[0],))
y = np.array([0 if label=='H' else 1 if label=='D' else 2 for label in y])

In [86]:
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
X

array([[ 1.35916279, -0.54276862, -0.95694981, ..., -1.03519388,
        -1.05379503, -1.09645181],
       [ 2.84378807, -1.38356345, -1.74899052, ..., -1.03519388,
        -1.05379503, -1.09645181],
       [-1.98260164, -1.38356345, -1.4095445 , ..., -1.03519388,
        -1.05379503, -1.09645181],
       ...,
       [-1.66330403,  1.13882104,  2.32436173, ...,  3.24660439,
        -0.24680965,  0.99921812],
       [ 0.32090254, -0.54276862, -0.84380113, ...,  1.10570525,
         0.80847892, -0.74717349],
       [ 0.38715137,  1.13882104,  1.19287499, ...,  1.8193383 ,
         0.93691161,  0.30066148]])

In [87]:
print ('The first element of X is: ', X[0])

The first element of X is:  [ 1.35916279 -0.54276862 -0.95694981 -0.38492192 -0.8877899  -1.90913194
  1.05674562  1.37583172 -1.39139378 -1.57831341 -1.11637713  1.48714511
  2.24977821 -0.7969567  -1.61860064 -1.1466469  -1.31350365 -1.93153824
 -1.07657744 -1.31055522  0.19378691 -0.91312454  0.73016078  2.42391208
  0.15627577 -0.59085006 -1.00860431 -0.33577184 -1.05324526 -0.67603271
 -1.21509826 -0.7656015  -0.00855176 -0.61733901 -1.02803677 -1.05967165
  1.45193001 -1.02674515 -1.14497459 -0.78606875 -1.06168262  1.14654644
 -1.42181324 -1.4357211  -1.33269906 -1.79983584 -1.03720734 -1.24949554
 -1.09050735 -1.15240261 -1.04342181 -1.59451679 -1.53058378 -1.50003116
  0.89564073 -0.84005408 -1.30467623 -0.68132332  1.55897539  2.50013671
 -0.84368385 -0.60786107 -1.4969001  -1.53302954 -1.48422495 -0.57136632
 -0.55857261  0.56487127 -0.32809903 -1.35317354 -0.83887884 -1.43335562
 -1.43638648 -0.54380173  0.74910274 -0.62905642 -1.71334288  2.78689
 -0.92014775  1.05596208 -

In [88]:
print ('The first element of y is: ', y[0])
print ('The last element of y is: ', y[-1])

The first element of y is:  2
The last element of y is:  0


In [89]:
print ('The shape of X is: ' + str(X.shape))
print ('The shape of y is: ' + str(y.shape))

The shape of X is: (3937, 125)
The shape of y is: (3937,)


In [90]:
train_size = int(X.shape[0]*0.9)
train_size

3543

In [91]:
X_train = X[:train_size]
print(X_train.shape)
X_test = X[train_size:]
print(X_test.shape)

(3543, 125)
(394, 125)


In [92]:
y_train = y[:train_size]
print(y_train.shape)
y_test = y[train_size:]
print(y_test.shape)

(3543,)
(394,)


# Useful Functions

In [93]:
def accuracy(confusion_matrix):
    diagonal_sum = confusion_matrix.trace()
    sum_of_all_elements = confusion_matrix.sum()
    return diagonal_sum / sum_of_all_elements

# MLP

In [94]:
# TODO: Activation Functions ReLU on hidden layers -> softmax for output (result case), ReLU for output (goals case)

#(spareCategoricalCrossentropy loss function) for softmax

## Tensorflow

In [99]:
model = Sequential(
    [ 
        tf.keras.Input(shape=(125,)),
        Dense(60, activation = 'relu', name='L1', kernel_regularizer=tf.keras.regularizers.l2(0.1)),
        Dense(20, activation = 'relu', name='L2', kernel_regularizer=tf.keras.regularizers.l2(0.1)),
        Dense(3, activation = 'linear', name='L3')    # < softmax activation here
    ]
)
model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.Adam(0.001),
)
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 L1 (Dense)                  (None, 60)                7560      
                                                                 
 L2 (Dense)                  (None, 20)                1220      
                                                                 
 L3 (Dense)                  (None, 3)                 63        
                                                                 
Total params: 8,843
Trainable params: 8,843
Non-trainable params: 0
_________________________________________________________________


In [100]:
[layer1, layer2, layer3] = model.layers
W1,b1 = layer1.get_weights()
W2,b2 = layer2.get_weights()
W3,b3 = layer3.get_weights()

In [101]:
W1

array([[ 0.16643617,  0.03450373,  0.12801075, ...,  0.0614228 ,
         0.1242305 ,  0.01898353],
       [ 0.16202947, -0.01246955,  0.09162456, ...,  0.07575369,
         0.05468798, -0.0578872 ],
       [-0.17637222, -0.16729057,  0.04088804, ...,  0.14176986,
         0.08568123,  0.04439685],
       ...,
       [ 0.16473758, -0.03194015, -0.02755943, ...,  0.1557163 ,
        -0.03727616, -0.17633894],
       [-0.05952009,  0.15320772,  0.09365794, ...,  0.02853778,
         0.07811096, -0.10125683],
       [-0.09847302, -0.00565001,  0.17454848, ..., -0.0567055 ,
        -0.07672161,  0.14375684]], dtype=float32)

In [102]:
model.fit(
    X_train,y_train,
    epochs=1000
)

Epoch 1/1000
111/111 [==============================] - 1s 3ms/step - loss: 7.0207
Epoch 2/1000
111/111 [==============================] - 0s 3ms/step - loss: 2.1841
Epoch 3/1000
111/111 [==============================] - 0s 3ms/step - loss: 1.2338
Epoch 4/1000
111/111 [==============================] - 0s 3ms/step - loss: 1.0691
Epoch 5/1000
111/111 [==============================] - 0s 3ms/step - loss: 1.0377
Epoch 6/1000
111/111 [==============================] - 0s 3ms/step - loss: 1.0319
Epoch 7/1000
111/111 [==============================] - 0s 3ms/step - loss: 1.0283
Epoch 8/1000
111/111 [==============================] - 0s 3ms/step - loss: 1.0263
Epoch 9/1000
111/111 [==============================] - 0s 3ms/step - loss: 1.0270
Epoch 10/1000
111/111 [==============================] - 0s 2ms/step - loss: 1.0252
Epoch 11/1000
111/111 [==============================] - 0s 2ms/step - loss: 1.0235
Epoch 12/1000
111/111 [==============================] - 0s 2ms/step - loss: 1.0246
E

111/111 [==============================] - 0s 2ms/step - loss: 1.0006
Epoch 99/1000
111/111 [==============================] - 0s 3ms/step - loss: 1.0014
Epoch 100/1000
111/111 [==============================] - 0s 3ms/step - loss: 1.0008
Epoch 101/1000
111/111 [==============================] - 0s 2ms/step - loss: 1.0009
Epoch 102/1000
111/111 [==============================] - 0s 2ms/step - loss: 1.0004
Epoch 103/1000
111/111 [==============================] - 0s 3ms/step - loss: 1.0015
Epoch 104/1000
111/111 [==============================] - 0s 3ms/step - loss: 1.0003
Epoch 105/1000
111/111 [==============================] - 0s 2ms/step - loss: 1.0018
Epoch 106/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9995
Epoch 107/1000
111/111 [==============================] - 0s 4ms/step - loss: 1.0003
Epoch 108/1000
111/111 [==============================] - 0s 2ms/step - loss: 1.0001
Epoch 109/1000
111/111 [==============================] - 0s 3ms/step - loss: 1.0

111/111 [==============================] - 0s 3ms/step - loss: 0.9976
Epoch 195/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9984
Epoch 196/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9967
Epoch 197/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9971
Epoch 198/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9989
Epoch 199/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9978
Epoch 200/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9966
Epoch 201/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9968
Epoch 202/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9986
Epoch 203/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9965
Epoch 204/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9976
Epoch 205/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.

111/111 [==============================] - 0s 2ms/step - loss: 0.9951
Epoch 291/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9962
Epoch 292/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9974
Epoch 293/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9965
Epoch 294/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9970
Epoch 295/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9961
Epoch 296/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9966
Epoch 297/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9950
Epoch 298/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9964
Epoch 299/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9965
Epoch 300/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9959
Epoch 301/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.

111/111 [==============================] - 0s 2ms/step - loss: 0.9981
Epoch 387/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9942
Epoch 388/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9941
Epoch 389/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9938
Epoch 390/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9934
Epoch 391/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9949
Epoch 392/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9958
Epoch 393/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9960
Epoch 394/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9947
Epoch 395/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9948
Epoch 396/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9945
Epoch 397/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.

111/111 [==============================] - 0s 3ms/step - loss: 0.9949
Epoch 483/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9982
Epoch 484/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9947
Epoch 485/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9947
Epoch 486/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9966
Epoch 487/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9953
Epoch 488/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9944
Epoch 489/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9944
Epoch 490/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9958
Epoch 491/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9945
Epoch 492/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9950
Epoch 493/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.

111/111 [==============================] - 0s 3ms/step - loss: 0.9960
Epoch 579/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9938
Epoch 580/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9938
Epoch 581/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9985
Epoch 582/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9936
Epoch 583/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9951
Epoch 584/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9966
Epoch 585/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9937
Epoch 586/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9935
Epoch 587/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9937
Epoch 588/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9940
Epoch 589/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.

111/111 [==============================] - 0s 3ms/step - loss: 0.9958
Epoch 675/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9955
Epoch 676/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9947
Epoch 677/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9938
Epoch 678/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9936
Epoch 679/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9922
Epoch 680/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9958
Epoch 681/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9926
Epoch 682/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9931
Epoch 683/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9925
Epoch 684/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9929
Epoch 685/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.

111/111 [==============================] - 0s 3ms/step - loss: 0.9941
Epoch 771/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9945
Epoch 772/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9938
Epoch 773/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9924
Epoch 774/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9931
Epoch 775/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9918
Epoch 776/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9912
Epoch 777/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9927
Epoch 778/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9945
Epoch 779/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9926
Epoch 780/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9938
Epoch 781/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.

111/111 [==============================] - 0s 2ms/step - loss: 0.9912
Epoch 867/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9939
Epoch 868/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9923
Epoch 869/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9921
Epoch 870/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9936
Epoch 871/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9960
Epoch 872/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9932
Epoch 873/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9942
Epoch 874/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9937
Epoch 875/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9916
Epoch 876/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9928
Epoch 877/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.

111/111 [==============================] - 0s 3ms/step - loss: 0.9925
Epoch 963/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9929
Epoch 964/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9918
Epoch 965/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9918
Epoch 966/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9942
Epoch 967/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9932
Epoch 968/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9927
Epoch 969/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9918
Epoch 970/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9926
Epoch 971/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9923
Epoch 972/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9928
Epoch 973/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.

In [103]:
[layer1, layer2, layer3] = model.layers
W1,b1 = layer1.get_weights()
W2,b2 = layer2.get_weights()
W3,b3 = layer3.get_weights()

In [104]:
W1

array([[ 6.47685190e-36, -2.68634783e-35, -6.16376891e-36, ...,
        -3.31505593e-35, -5.42827708e-36,  1.17220815e-35],
       [-1.82052191e-35, -5.79120264e-35, -4.69307711e-35, ...,
        -1.38089477e-35, -4.15296960e-35, -3.91767098e-35],
       [ 1.38739873e-35, -1.68226916e-35, -5.70272028e-36, ...,
         1.04391941e-35, -2.22322888e-35, -4.51698886e-35],
       ...,
       [ 8.45383768e-37,  2.82091495e-35,  4.08422757e-35, ...,
         1.43529984e-35,  3.25814203e-35,  2.01658438e-35],
       [ 5.17628593e-35, -6.27495444e-36,  5.16343929e-35, ...,
         4.58898760e-35,  3.34773129e-35, -2.70236796e-35],
       [-2.23363571e-35,  2.46411970e-35, -1.95860346e-35, ...,
         4.67991909e-35, -1.13437946e-35,  3.85510992e-36]], dtype=float32)

In [105]:
y_train_pred_probs = tf.nn.softmax(model.predict(X_train)).numpy()
y_train_pred_probs

111/111 [==============================] - 0s 2ms/step


array([[0.49626386, 0.25342688, 0.2503093 ],
       [0.59926134, 0.22569978, 0.17503895],
       [0.40790382, 0.26782316, 0.32427308],
       ...,
       [0.6784502 , 0.19698377, 0.12456603],
       [0.16912176, 0.24811122, 0.582767  ],
       [0.4396181 , 0.2634835 , 0.29689834]], dtype=float32)

In [106]:
y_test_pred_probs = tf.nn.softmax(model.predict(X_test)).numpy()
y_test_pred_probs

13/13 [==============================] - 0s 1ms/step


array([[0.4441321 , 0.26309383, 0.29277405],
       [0.21406297, 0.2610053 , 0.5249317 ],
       [0.55950814, 0.23777214, 0.20271976],
       ...,
       [0.28752214, 0.27103943, 0.4414385 ],
       [0.10563646, 0.2182122 , 0.67615134],
       [0.40959913, 0.26680243, 0.3235984 ]], dtype=float32)

In [107]:
y_train_pred = np.argmax(y_train_pred_probs, axis=1)
y_test_pred = np.argmax(y_test_pred_probs, axis=1)

In [108]:
cm_train = confusion_matrix(y_train_pred, y_train)
cm_train

array([[1382,  596,  543],
       [   0,    0,    0],
       [ 247,  257,  518]], dtype=int64)

In [109]:
cm_test = confusion_matrix(y_test_pred, y_test)
cm_test

array([[142,  57,  74],
       [  0,   0,   0],
       [ 24,  29,  68]], dtype=int64)

In [110]:
for i in range(10):
    print( f"{y_train_pred_probs[-i]}, predicted_category: {np.argmax(y_train_pred_probs[-i])}, category: {y_train[-i]}")

[0.49626386 0.25342688 0.2503093 ], predicted_category: 0, category: 2
[0.4396181  0.2634835  0.29689834], predicted_category: 0, category: 2
[0.16912176 0.24811122 0.582767  ], predicted_category: 2, category: 2
[0.6784502  0.19698377 0.12456603], predicted_category: 0, category: 0
[0.7362694  0.17180984 0.09192079], predicted_category: 0, category: 2
[0.4226418  0.26608837 0.31126988], predicted_category: 0, category: 2
[0.49852806 0.25202376 0.24944821], predicted_category: 0, category: 1
[0.50540054 0.25165302 0.2429464 ], predicted_category: 0, category: 0
[0.30112863 0.27176914 0.42710224], predicted_category: 2, category: 2
[0.3873813  0.2697907  0.34282798], predicted_category: 0, category: 2


In [111]:
for i in range(10):
    print( f"{y_test_pred_probs[-i]}, predicted_category: {np.argmax(y_test_pred_probs[-i])}, category: {y_test[-i]}")

[0.4441321  0.26309383 0.29277405], predicted_category: 0, category: 0
[0.40959913 0.26680243 0.3235984 ], predicted_category: 0, category: 0
[0.10563646 0.2182122  0.67615134], predicted_category: 2, category: 2
[0.28752214 0.27103943 0.4414385 ], predicted_category: 2, category: 1
[0.74616    0.16678208 0.08705799], predicted_category: 0, category: 0
[0.14623637 0.23963428 0.61412936], predicted_category: 2, category: 2
[0.11360846 0.22311369 0.66327786], predicted_category: 2, category: 2
[0.8461473  0.11122313 0.04262945], predicted_category: 0, category: 0
[0.26597315 0.2692167  0.4648102 ], predicted_category: 2, category: 2
[0.6681413  0.20107612 0.13078253], predicted_category: 0, category: 2


In [112]:
print('Train accuracy: '+ str(accuracy(cm_train)))
print('Test accuracy: '+ str(accuracy(cm_test)))

Train accuracy: 0.5362686988427886
Test accuracy: 0.5329949238578681


## Sckit-learn

In [113]:
mlp = MLPClassifier(hidden_layer_sizes=(20, 12), random_state=1, max_iter=1000)
mlp.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=(20, 12), max_iter=1000, random_state=1)

In [114]:
ypred = mlp.predict(X_test)
ypred

array([0, 0, 0, 1, 0, 2, 2, 2, 2, 2, 2, 0, 1, 0, 1, 0, 0, 2, 0, 0, 2, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 2, 0, 2, 2, 0, 1, 2, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 2, 2, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 2, 2, 1, 0, 2, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 2, 0, 1, 2, 0, 2, 0,
       2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0, 1, 0, 0, 0, 2, 0,
       0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 2, 0, 2, 2, 1, 2, 0,
       0, 2, 1, 0, 0, 1, 2, 2, 0, 0, 0, 1, 0, 2, 2, 0, 2, 2, 0, 1, 2, 0,
       1, 0, 2, 2, 1, 0, 1, 1, 2, 1, 0, 2, 0, 0, 2, 1, 2, 0, 0, 0, 0, 1,
       2, 0, 0, 1, 2, 2, 2, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 1, 2,
       0, 2, 2, 1, 0, 1, 0, 1, 0, 0, 0, 2, 2, 0, 1, 1, 0, 2, 2, 1, 1, 0,
       1, 0, 0, 2, 0, 1, 0, 1, 0, 0, 2, 1, 2, 0, 1, 1, 0, 2, 0, 0, 2, 0,
       2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 0, 2, 0, 1, 1, 1, 0, 0, 1, 0, 2,
       2, 2, 0, 0, 1, 0, 0, 0, 0, 0, 2, 2, 0, 0, 1,

In [115]:
cm = confusion_matrix(ypred, y_test)
cm

array([[83, 44, 57],
       [40, 23, 35],
       [43, 19, 50]], dtype=int64)

In [116]:
accuracy(cm)

0.39593908629441626

# Logistic Regression

In [117]:
log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [118]:
ypred_train = log_reg.predict(X_train)
ypred_train

array([0, 0, 0, ..., 0, 2, 0])

In [119]:
cm = confusion_matrix(ypred_train, y_train)
cm

array([[1315,  514,  466],
       [  49,   86,   61],
       [ 265,  253,  534]], dtype=int64)

In [120]:
accuracy(cm)

0.54614733276884

In [121]:
ypred = log_reg.predict(X_test)
ypred

array([1, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2, 2, 2, 0, 2, 2, 0, 0, 0, 0,
       0, 0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2, 2, 2, 0, 0, 2, 0, 0, 2, 0,
       2, 1, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 2, 1, 0, 0, 0, 0, 2, 0,
       0, 1, 2, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 0, 2, 0,
       2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2, 0, 2, 0, 0, 2, 0,
       0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 2, 0,
       0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 2, 2, 2, 0, 0,
       0, 1, 2, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 0,
       0, 0, 0, 2, 2, 0, 2, 0, 2, 0, 0, 2, 2, 2, 0, 2, 1, 2, 0, 2, 0, 2,
       2, 0, 0, 1, 1, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 2, 0, 2,
       1, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 2, 0, 0, 1, 2,
       2, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2,

In [122]:
cm = confusion_matrix(ypred, y_test)
cm

array([[132,  57,  66],
       [  8,   7,   9],
       [ 26,  22,  67]], dtype=int64)

In [123]:
accuracy(cm)

0.5228426395939086

In [124]:
print(log_reg.coef_)

[[-4.64528550e-04 -1.76069100e-02  4.70303932e-02  2.22878567e-02
   1.41105918e-01 -5.01511912e-03 -6.15476485e-02  2.60019144e-02
  -8.46477992e-02  1.34251509e-02 -1.72418605e-01 -3.00543990e-02
  -1.84859753e-02 -1.23701133e-01 -9.55456773e-02 -1.24943669e-02
  -1.07910293e-01 -6.78428514e-02  4.80110416e-04 -4.55333212e-03
   8.67216796e-02  4.08033667e-02  9.60719262e-02  4.29880149e-02
   3.27110008e-02  5.98120290e-03 -6.26135224e-02  8.25694849e-02
   1.99896891e-02  1.59193685e-02  1.01530409e-01  1.23472688e-01
  -2.42850260e-02  3.83513307e-02  4.53876193e-02  9.39567521e-02
   2.24022040e-02 -2.95049394e-02 -9.68024553e-03 -1.18878358e-01
  -1.39187976e-02  3.12277668e-02 -8.23872751e-02  1.88746243e-02
   3.62080683e-02  3.79348174e-02  8.83900268e-02 -1.23136624e-01
  -4.98857338e-02  9.69661613e-02  8.59601155e-02 -9.81617667e-02
  -4.13263969e-02 -4.04915025e-02 -1.03660998e-02 -1.55542420e-02
   3.64502615e-02  2.87391468e-02 -3.42394774e-02  9.29955211e-02
   8.41206

In [125]:
pd.DataFrame(data=log_reg.coef_, columns=list(set(footballdata_wTeamStats.columns.to_list())-set(indexes)-set(label)))

home_goals_for_minute_46_60_percentage  away_failed_to_score_away  \
0                               -0.000465                  -0.017607   
1                               -0.034297                   0.047386   
2                                0.034761                  -0.029779   

   away_away_goals_against  home_away_draws  home_away_wins  \
0                 0.047030         0.022288        0.141106   
1                 0.049952        -0.098773       -0.236926   
2                -0.096982         0.076485        0.095820   

   home_goals_for_minute_61_75_percentage  \
0                               -0.005015   
1                                0.002964   
2                                0.002051   

   away_goals_against_minute_0_15_percentage  away_form_last5games_wins  \
0                                  -0.061548                   0.026002   
1                                   0.043171                  -0.061994   
2                                   0.018377                   0.035992   

   away_away_draws  away_goals_for_minute_0_15_percentage  \
0        -0.084648                               0.013425   
1         0.069876                               0.009792   
2         0.014772                              -0.023217   

   away_goals_against_minute_31_45  \
0                        -0.172419   
1                         0.083203   
2                         0.089216   

   away_goals_against_minute_61_75_percentage  home_form_last2games_draws  \
0                                   -0.030054                   -0.018486   
1                                    0.057120                   -0.001797   
2                                   -0.027065                    0.020283   

   away_away_loses  home_total_goals_against  away_goals_for_minute_46_60  \
0        -0.123701                 -0.095546                    -0.012494   
1         0.147077                  0.129911                     0.044070   
2        -0.023376                 -0.034365                    -0.031576   

   home_away_clean_sheets  home_form_last10games_loses  \
0               -0.107910                    -0.067843   
1                0.065224                     0.010527   
2                0.042687                     0.057316   

   home_form_last2games_loses  away_total_clean_sheets  \
0                    0.000480                -0.004553   
1                    0.008687                -0.020679   
2                   -0.009167                 0.025233   

   home_goals_against_minute_46_60_percentage  \
0                                    0.086722   
1                                    0.089219   
2                                   -0.175941   

   home_goals_against_minute_76_90  \
0                         0.040803   
1                        -0.085122   
2                         0.044319   

   home_goals_against_minute_16_30_percentage  home_form_last5games_draws  \
0                                    0.096072                    0.042988   
1                                    0.034341                   -0.027144   
2                                   -0.130413                   -0.015844   

   home_goals_for_minute_16_30_percentage  away_goals_against_minute_61_75  \
0                                0.032711                         0.005981   
1                                0.040795                        -0.140975   
2                               -0.073506                         0.134994   

   away_goals_for_minute_91_105_percentage  home_goals_for_minute_46_60  \
0                                -0.062614                     0.082569   
1                                -0.041008                     0.048149   
2                                 0.103622                    -0.130719   

   home_total_draws  home_form_last1games_wins  \
0          0.019990                   0.015919   
1         -0.086944                   0.002730   
2          0.066955                  -0.018649   

   away_goals_against_m