# Imports

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

import os
from datetime import datetime, timedelta

In [59]:
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingRegressor

In [3]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Variables

In [28]:
footballdata_wTeamStats_path = \
    os.path.abspath(os.getcwd())+"\\Data\\teamStats_byLeague\\footballdata_wTeamStats_englishpremierleague.csv"

# Load Football-Data File with Indexes

In [29]:
footballdata_wTeamStats = pd.read_csv(footballdata_wTeamStats_path, index_col=0)
footballdata_wTeamStats.head(5)

C:\Users\ldoutors\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (96,113,194,211) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


AverageAwayWinOdd  AverageDrawWinOdd  AverageHomeWinOdd  AvgOver2_5  \
0                4.0               3.30               2.00        2.01   
1                2.5               3.25               2.88        2.08   
2                3.4               3.30               2.20        2.09   
3               17.0               7.00               1.17        1.49   
4                3.6               3.30               2.10        2.16   

   AvgUnder2_5  AwayGoals  AwayTeamId AwayTeamName        Date  Div  \
0         1.75          0          48     West Ham  14/08/2010   39   
1         1.70          0          45      Everton  14/08/2010   39   
2         1.69          0          36       Fulham  14/08/2010   39   
3         2.49          0          60    West Brom  14/08/2010   39   
4         1.65          2          54   Birmingham  14/08/2010   39   

  FullTimeResult  HomeGoals HomeTeamName  HomeTeamid  Season  \
0              H          3  Aston Villa          66    2010   
1              H          1    Blackburn          67    2010   
2              D          0       Bolton          68    2010   
3              H          6      Chelsea          49    2010   
4              D          2   Sunderland         746    2010   

   away_average_away_goals_against  away_average_away_goals_for  \
0                              0.0                          0.0   
1                              0.0                          0.0   
2                              0.0                          0.0   
3                              0.0                          0.0   
4                              0.0                          0.0   

   away_average_home_goals_against  away_average_home_goals_for  \
0                              0.0                          0.0   
1                              0.0                          0.0   
2                              0.0                          0.0   
3                              0.0                          0.0   
4                              0.0                          0.0   

   away_average_total_goals_against  away_average_total_goals_for  \
0                               0.0                           0.0   
1                               0.0                           0.0   
2                               0.0                           0.0   
3                               0.0                           0.0   
4                               0.0                           0.0   

   away_away_clean_sheets  away_away_draws  away_away_goals_against  \
0                       0                0                        0   
1                       0                0                        0   
2                       0                0                        0   
3                       0                0                        0   
4                       0                0                        0   

   away_away_goals_for  away_away_loses  away_away_wins  \
0                    0                0               0   
1                    0                0               0   
2                    0                0               0   
3                    0                0               0   
4                    0                0               0   

   away_biggest_away_goals_against  away_biggest_away_goals_for  \
0                                0                            0   
1                                0                            0   
2                                0                            0   
3                                0                            0   
4                                0                            0   

  away_biggest_away_lose away_biggest_away_win  away_biggest_draw_streak  \
0                    NaN                   NaN                         0   
1                    NaN                   NaN                         0   
2                    NaN                   NaN                         0   
3                    NaN            

# Data Prep

## Remove Incomplete Columns & Non important (except indexes)

In [30]:
not_complete = ['away_red_cards_minute_0_15', 'away_red_cards_minute_0_15_percentage',
               'away_red_cards_minute_16_30', 'away_red_cards_minute_16_30_percentage',
               'away_red_cards_minute_31_45', 'away_red_cards_minute_31_45_percentage',
               'away_red_cards_minute_46_60', 'away_red_cards_minute_46_60_percentage',
               'away_red_cards_minute_61_75', 'away_red_cards_minute_61_75_percentage',
               'away_red_cards_minute_61_75', 'away_red_cards_minute_61_75_percentage',
               'away_red_cards_minute_76_90', 'away_red_cards_minute_76_90_percentage',
               'away_red_cards_minute_91_105', 'away_red_cards_minute_91_105_percentage',
               'away_yellow_cards_minute_0_15', 'away_yellow_cards_minute_0_15_percentage',
               'away_yellow_cards_minute_16_30', 'away_yellow_cards_minute_16_30_percentage',
               'away_yellow_cards_minute_31_45', 'away_yellow_cards_minute_31_45_percentage',
               'away_yellow_cards_minute_46_60', 'away_yellow_cards_minute_46_60_percentage',
               'away_yellow_cards_minute_61_75', 'away_yellow_cards_minute_61_75_percentage',
               'away_yellow_cards_minute_76_90', 'away_yellow_cards_minute_76_90_percentage',
               'away_yellow_cards_minute_91_105', 'away_yellow_cards_minute_91_105_percentage',
                'home_red_cards_minute_0_15', 'home_red_cards_minute_0_15_percentage',
               'home_red_cards_minute_16_30', 'home_red_cards_minute_16_30_percentage',
               'home_red_cards_minute_31_45', 'home_red_cards_minute_31_45_percentage',
               'home_red_cards_minute_46_60', 'home_red_cards_minute_46_60_percentage',
               'home_red_cards_minute_61_75', 'home_red_cards_minute_61_75_percentage',
               'home_red_cards_minute_61_75', 'home_red_cards_minute_61_75_percentage',
               'home_red_cards_minute_76_90', 'home_red_cards_minute_76_90_percentage',
               'home_red_cards_minute_91_105', 'home_red_cards_minute_91_105_percentage',
               'home_yellow_cards_minute_0_15', 'home_yellow_cards_minute_0_15_percentage',
               'home_yellow_cards_minute_16_30', 'home_yellow_cards_minute_16_30_percentage',
               'home_yellow_cards_minute_31_45', 'home_yellow_cards_minute_31_45_percentage',
               'home_yellow_cards_minute_46_60', 'home_yellow_cards_minute_46_60_percentage',
               'home_yellow_cards_minute_61_75', 'home_yellow_cards_minute_61_75_percentage',
               'home_yellow_cards_minute_76_90', 'home_yellow_cards_minute_76_90_percentage',
               'home_yellow_cards_minute_91_105', 'home_yellow_cards_minute_91_105_percentage']

# away average goals and home average goals will be removed because we will average all columns
not_features = [
               'away_biggest_away_lose', 'away_biggest_away_win', 'away_biggest_home_lose', 'away_biggest_home_win',
               'away_lineups',
               'home_biggest_away_lose', 'home_biggest_away_win', 'home_biggest_home_lose', 'home_biggest_home_win',
               'home_lineups',
    
               'away_biggest_away_goals_against', 'away_biggest_away_goals_for', 'away_biggest_draw_streak',
               'away_biggest_home_goals_against', 'away_biggest_home_goals_for', 'away_biggest_lose_streak',
               'away_biggest_win_streak',
               'home_biggest_away_goals_against', 'home_biggest_away_goals_for', 'home_biggest_draw_streak',
               'home_biggest_home_goals_against', 'home_biggest_home_goals_for', 'home_biggest_lose_streak',
               'home_biggest_win_streak',
    
               'away_average_away_goals_against', 'away_average_away_goals_for', 'away_average_home_goals_against',
               'away_average_home_goals_for', 'away_average_total_goals_against', 'away_average_total_goals_for',
               'home_average_away_goals_against', 'home_average_away_goals_for', 'home_average_home_goals_against',
               'home_average_home_goals_for', 'home_average_total_goals_against', 'home_average_total_goals_for',
    
               'away_penalties_missed', 'away_penalties_missed_percentage', 'away_penalties_scored',
               'away_penalties_scored', 'away_penalties_scored_percentage',
               'home_penalties_missed', 'home_penalties_missed_percentage', 'home_penalties_scored',
               'home_penalties_scored', 'home_penalties_scored_percentage'
               ]

In [31]:
footballdata_wTeamStats = \
    footballdata_wTeamStats[list(set(footballdata_wTeamStats.columns.tolist()) - set(not_complete + not_features))]
footballdata_wTeamStats

home_goals_for_minute_16_30_percentage  AwayTeamId FullTimeResult  \
0                                       NaN          48              H   
1                                       NaN          45              H   
2                                       NaN          36              D   
3                                       NaN          60              H   
4                                       NaN          54              D   
...                                     ...         ...            ...   
4533                                 17.50%          49              A   
4534                                 12.00%          71              H   
4535                                 20.59%          45              D   
4536                                 15.15%          50              A   
4537                                 12.73%          42              H   

      away_home_wins  AverageHomeWinOdd  home_goals_against_minute_91_105  \
0                  0               2.00                               NaN   
1                  0               2.88                               NaN   
2                  0               2.20                               NaN   
3                  0               1.17                               NaN   
4                  0               2.10                               NaN   
...              ...                ...                               ...   
4533               8               4.98                               5.0   
4534               3               1.44                               5.0   
4535               8               4.26                               6.0   
4536              14              12.83                               3.0   
4537              12               2.12                               4.0   

     away_goals_against_minute_91_105_percentage  away_penalties_for  \
0                                            NaN                   0   
1                                            NaN                   0   
2                                            NaN                   0   
3                                            NaN                   0   
4                                            NaN                   0   
...                                          ...                 ...   
4533                                       9.68%                   8   
4534                                       6.67%                   3   
4535                                       3.77%                   5   
4536                                       8.70%                   7   
4537                                       9.30%                   4   

      home_away_goals_for  home_goals_against_minute_76_90  \
0                       0                              NaN   
1                       0                              NaN   
2                       0                              NaN   
3                       0                              NaN   
4                       0                              NaN   
...                   ...                              ...   
4533                   21                              9.0   
4534                   22                              8.0   
4535                   16                             10.0   
4536                   17                              6.0   
4537                   26                              8.0   

     home_goals_for_minute_91_105_percentage  home_goals_against_minute_61_75  \
0                                        NaN                              NaN   
1                                        NaN                              NaN   
2                                        NaN                              NaN   
3                                        NaN                              NaN   
4                                        NaN                              NaN   
...                                      ...                              ...   
4533          

## Convert NaN/Nulls to 0

In [32]:
nan_to_zero = ['away_goals_against_minute_0_15', 'away_goals_against_minute_0_15_percentage',
            'away_goals_against_minute_16_30', 'away_goals_against_minute_16_30_percentage',
            'away_goals_against_minute_16_30_percentage', 'away_goals_against_minute_31_45',
             'away_goals_against_minute_31_45_percentage', 'away_goals_against_minute_46_60',
            'away_goals_against_minute_46_60_percentage', 'away_goals_against_minute_61_75',
            'away_goals_against_minute_61_75_percentage', 'away_goals_against_minute_76_90',
            'away_goals_against_minute_76_90_percentage', 'away_goals_against_minute_91_105',
            'away_goals_against_minute_91_105_percentage', 'away_goals_for_minute_0_15',
            'away_goals_for_minute_0_15_percentage', 'away_goals_for_minute_16_30', 'away_goals_for_minute_16_30_percentage',
            'away_goals_for_minute_31_45', 'away_goals_for_minute_31_45_percentage', 'away_goals_for_minute_46_60',
            'away_goals_for_minute_46_60_percentage', 'away_goals_for_minute_61_75', 'away_goals_for_minute_61_75_percentage',
            'away_goals_for_minute_76_90', 'away_goals_for_minute_76_90_percentage', 'away_goals_for_minute_91_105',
            'away_goals_for_minute_91_105_percentage',
             'home_goals_against_minute_0_15', 'home_goals_against_minute_0_15_percentage',
            'home_goals_against_minute_16_30', 'home_goals_against_minute_16_30_percentage',
            'home_goals_against_minute_16_30_percentage', 'home_goals_against_minute_31_45',
             'home_goals_against_minute_31_45_percentage', 'home_goals_against_minute_46_60',
            'home_goals_against_minute_46_60_percentage', 'home_goals_against_minute_61_75',
            'home_goals_against_minute_61_75_percentage', 'home_goals_against_minute_76_90',
            'home_goals_against_minute_76_90_percentage', 'home_goals_against_minute_91_105',
            'home_goals_against_minute_91_105_percentage', 'home_goals_for_minute_0_15',
            'home_goals_for_minute_0_15_percentage', 'home_goals_for_minute_16_30', 'home_goals_for_minute_16_30_percentage',
            'home_goals_for_minute_31_45', 'home_goals_for_minute_31_45_percentage', 'home_goals_for_minute_46_60',
            'home_goals_for_minute_46_60_percentage', 'home_goals_for_minute_61_75', 'home_goals_for_minute_61_75_percentage',
            'home_goals_for_minute_76_90', 'home_goals_for_minute_76_90_percentage', 'home_goals_for_minute_91_105',
            'home_goals_for_minute_91_105_percentage']

In [33]:
print(footballdata_wTeamStats.count().sort_values().to_string())

away_goals_against_minute_91_105_percentage    2813
away_goals_against_minute_91_105               2813
home_goals_against_minute_91_105               2816
home_goals_against_minute_91_105_percentage    2816
home_goals_for_minute_91_105                   2878
home_goals_for_minute_91_105_percentage        2878
away_goals_for_minute_91_105                   2887
away_goals_for_minute_91_105_percentage        2887
away_goals_against_minute_0_15_percentage      3760
away_goals_against_minute_0_15                 3760
home_goals_against_minute_0_15                 3762
home_goals_against_minute_0_15_percentage      3762
home_goals_for_minute_16_30_percentage         3781
home_goals_for_minute_16_30                    3781
away_goals_for_minute_0_15                     3781
away_goals_for_minute_0_15_percentage          3781
home_goals_for_minute_0_15                     3783
home_goals_for_minute_0_15_percentage          3783
away_goals_for_minute_16_30_percentage         3802
away_goals_f

In [34]:
for column in footballdata_wTeamStats.columns:
    if 'percentage' in column:
        footballdata_wTeamStats[column] = footballdata_wTeamStats[column].str.slice(0,-1,1).astype(float)

for column in nan_to_zero:
    if 'percentage' in column:
        footballdata_wTeamStats[column] = footballdata_wTeamStats[column].fillna(0.0)
    else:
        footballdata_wTeamStats[column] = footballdata_wTeamStats[column].fillna(0).astype(int)
footballdata_wTeamStats

home_goals_for_minute_16_30_percentage  AwayTeamId FullTimeResult  \
0                                       0.00          48              H   
1                                       0.00          45              H   
2                                       0.00          36              D   
3                                       0.00          60              H   
4                                       0.00          54              D   
...                                      ...         ...            ...   
4533                                   17.50          49              A   
4534                                   12.00          71              H   
4535                                   20.59          45              D   
4536                                   15.15          50              A   
4537                                   12.73          42              H   

      away_home_wins  AverageHomeWinOdd  home_goals_against_minute_91_105  \
0                  0               2.00                                 0   
1                  0               2.88                                 0   
2                  0               2.20                                 0   
3                  0               1.17                                 0   
4                  0               2.10                                 0   
...              ...                ...                               ...   
4533               8               4.98                                 5   
4534               3               1.44                                 5   
4535               8               4.26                                 6   
4536              14              12.83                                 3   
4537              12               2.12                                 4   

      away_goals_against_minute_91_105_percentage  away_penalties_for  \
0                                            0.00                   0   
1                                            0.00                   0   
2                                            0.00                   0   
3                                            0.00                   0   
4                                            0.00                   0   
...                                           ...                 ...   
4533                                         9.68                   8   
4534                                         6.67                   3   
4535                                         3.77                   5   
4536                                         8.70                   7   
4537                                         9.30                   4   

      home_away_goals_for  home_goals_against_minute_76_90  \
0                       0                                0   
1                       0                                0   
2                       0                                0   
3                       0                                0   
4                       0                                0   
...                   ...                              ...   
4533                   21                                9   
4534                   22                                8   
4535                   16                               10   
4536                   17                                6   
4537                   26                                8   

      home_goals_for_minute_91_105_percentage  \
0                                        0.00   
1                                        0.00   
2                                        0.00   
3                                        0.00   
4                                        0.00   
...                                       ...   
4533                                    15.00   
4534                                     4.00   
4535                                    11.76   
4536                                    12.12   
4537               

In [35]:
footballdata_wTeamStats.tail(5)

home_goals_for_minute_16_30_percentage  AwayTeamId FullTimeResult  \
4533                                   17.50          49              A   
4534                                   12.00          71              H   
4535                                   20.59          45              D   
4536                                   15.15          50              A   
4537                                   12.73          42              H   

      away_home_wins  AverageHomeWinOdd  home_goals_against_minute_91_105  \
4533               8               4.98                                 5   
4534               3               1.44                                 5   
4535               8               4.26                                 6   
4536              14              12.83                                 3   
4537              12               2.12                                 4   

      away_goals_against_minute_91_105_percentage  away_penalties_for  \
4533                                         9.68                   8   
4534                                         6.67                   3   
4535                                         3.77                   5   
4536                                         8.70                   7   
4537                                         9.30                   4   

      home_away_goals_for  home_goals_against_minute_76_90  \
4533                   21                                9   
4534                   22                                8   
4535                   16                               10   
4536                   17                                6   
4537                   26                                8   

      home_goals_for_minute_91_105_percentage  \
4533                                    15.00   
4534                                     4.00   
4535                                    11.76   
4536                                    12.12   
4537                                     7.27   

      home_goals_against_minute_61_75  home_penalties_for  \
4533                               11                   4   
4534                                9                   2   
4535                                8                   1   
4536                               11                   1   
4537                                8                   3   

                                home_form  home_failed_to_score_home  \
4533  LDDLDLWLDWDLDWDLLLWWLDLLLLLLWWDWDLL                          5   
4534   WLWLLDDWWLDLWDLWLWLDLDLWWLWDWLDDLL                          4   
4535  WLLLWDLLWLLWLLLLLLDLDLLWLDLLWLLLLLL                          7   
4536  LLLWLWWWDWLWDDLLWDWWWLWWLLLWWLWLLLD                          9   
4537  WWWLLLWWLLDWWWDWDWWLLLWLWWLWWWWLDWD                          4   

      home_failed_to_score_total  home_away_goals_against  \
4533                          12                       40   
4534                           6                       34   
4535                          17                       29   
4536                          16                       15   
4537                          10                       21   

      home_goals_against_minute_76_90_percentage  away_failed_to_score_home  \
4533                                       12.33                          1   
4534                                       14.55                          9   
4535                                       14.71                          5   
4536                                       16.67                          2   
4537                                       17.78                          3   

      away_home_draws  away_goals_for_minute_46_60  away_away_clean_sheets  \
4533                6                           19                       9   
4534                3                            5                       3   
4535                2                            8                       1   
4536                2          

In [36]:
print(footballdata_wTeamStats.count().sort_values().to_string())

home_form                                      4418
away_form                                      4418
away_goals_for_minute_16_30                    4538
away_goals_against_minute_31_45                4538
away_goals_for_minute_76_90_percentage         4538
home_goals_for_minute_91_105                   4538
away_goals_against_minute_91_105               4538
AwayTeamName                                   4538
home_goals_for_minute_31_45                    4538
away_goals_for_minute_61_75                    4538
away_home_goals_for                            4538
away_goals_against_minute_16_30                4538
home_home_wins                                 4538
home_goals_for_minute_16_30_percentage         4538
HomeTeamid                                     4538
home_goals_for_minute_61_75_percentage         4538
away_goals_against_minute_0_15                 4538
away_home_loses                                4538
home_goals_against_minute_31_45                4538
home_goals_a

## Modifications

### Add Total wins, draws & losses

In [37]:
footballdata_wTeamStats['home_total_wins'] = \
    footballdata_wTeamStats['home_home_wins'] + footballdata_wTeamStats['home_away_wins']
footballdata_wTeamStats['home_total_draws'] = \
    footballdata_wTeamStats['home_home_draws'] + footballdata_wTeamStats['home_away_draws']
footballdata_wTeamStats['home_total_loses'] = \
    footballdata_wTeamStats['home_home_loses'] + footballdata_wTeamStats['home_away_loses']

# TODO: total games is computed bases only on the home games (might require future change)
footballdata_wTeamStats['home_total_games'] = footballdata_wTeamStats['home_total_wins']+\
    footballdata_wTeamStats['home_total_draws']+footballdata_wTeamStats['home_total_loses']

footballdata_wTeamStats['away_total_wins'] = \
    footballdata_wTeamStats['away_home_wins'] + footballdata_wTeamStats['away_away_wins']
footballdata_wTeamStats['away_total_draws'] = \
    footballdata_wTeamStats['away_home_draws'] + footballdata_wTeamStats['away_away_draws']
footballdata_wTeamStats['away_total_loses'] = \
    footballdata_wTeamStats['away_home_loses'] + footballdata_wTeamStats['away_away_loses']

footballdata_wTeamStats['away_total_games'] = footballdata_wTeamStats['away_total_wins']+\
    footballdata_wTeamStats['away_total_draws']+footballdata_wTeamStats['away_total_loses']

footballdata_wTeamStats['home_total_home_games'] = footballdata_wTeamStats['home_home_wins']+\
    footballdata_wTeamStats['home_home_draws']+footballdata_wTeamStats['home_home_loses']
footballdata_wTeamStats['home_total_away_games'] = footballdata_wTeamStats['home_away_wins']+\
    footballdata_wTeamStats['home_away_draws']+footballdata_wTeamStats['home_away_loses']

footballdata_wTeamStats['away_total_home_games'] = footballdata_wTeamStats['away_home_wins']+\
    footballdata_wTeamStats['away_home_draws']+footballdata_wTeamStats['away_home_loses']
footballdata_wTeamStats['away_total_away_games'] = footballdata_wTeamStats['away_away_wins']+\
    footballdata_wTeamStats['away_away_draws']+footballdata_wTeamStats['away_away_loses']

footballdata_wTeamStats

home_goals_for_minute_16_30_percentage  AwayTeamId FullTimeResult  \
0                                       0.00          48              H   
1                                       0.00          45              H   
2                                       0.00          36              D   
3                                       0.00          60              H   
4                                       0.00          54              D   
...                                      ...         ...            ...   
4533                                   17.50          49              A   
4534                                   12.00          71              H   
4535                                   20.59          45              D   
4536                                   15.15          50              A   
4537                                   12.73          42              H   

      away_home_wins  AverageHomeWinOdd  home_goals_against_minute_91_105  \
0                  0               2.00                                 0   
1                  0               2.88                                 0   
2                  0               2.20                                 0   
3                  0               1.17                                 0   
4                  0               2.10                                 0   
...              ...                ...                               ...   
4533               8               4.98                                 5   
4534               3               1.44                                 5   
4535               8               4.26                                 6   
4536              14              12.83                                 3   
4537              12               2.12                                 4   

      away_goals_against_minute_91_105_percentage  away_penalties_for  \
0                                            0.00                   0   
1                                            0.00                   0   
2                                            0.00                   0   
3                                            0.00                   0   
4                                            0.00                   0   
...                                           ...                 ...   
4533                                         9.68                   8   
4534                                         6.67                   3   
4535                                         3.77                   5   
4536                                         8.70                   7   
4537                                         9.30                   4   

      home_away_goals_for  home_goals_against_minute_76_90  \
0                       0                                0   
1                       0                                0   
2                       0                                0   
3                       0                                0   
4                       0                                0   
...                   ...                              ...   
4533                   21                                9   
4534                   22                                8   
4535                   16                               10   
4536                   17                                6   
4537                   26                                8   

      home_goals_for_minute_91_105_percentage  \
0                                        0.00   
1                                        0.00   
2                                        0.00   
3                                        0.00   
4                                        0.00   
...                                       ...   
4533                                    15.00   
4534                                     4.00   
4535                                    11.76   
4536                                    12.12   
4537               

### Away Team & Home Team Form

In [38]:
to_modify = ['away_form', 'home_form']

In [39]:
# Same as before but normalized
games = [1, 2, 5, 10]
for column in to_modify:
    footballdata_wTeamStats[column] = footballdata_wTeamStats[column].fillna('')
    for nr in games:
        footballdata_wTeamStats[column+f"_last{nr}games_wins"] = \
            footballdata_wTeamStats[column].apply(lambda x : x[-nr:]).str.count('W') / \
            footballdata_wTeamStats['home_total_games'].clip(upper=10)
        footballdata_wTeamStats[column+f"_last{nr}games_draws"] = \
            footballdata_wTeamStats[column].apply(lambda x : x[-nr:]).str.count('D') / \
            footballdata_wTeamStats['home_total_games'].clip(upper=10)
        footballdata_wTeamStats[column+f"_last{nr}games_loses"] = \
            footballdata_wTeamStats[column].apply(lambda x : x[-nr:]).str.count('L') / \
            footballdata_wTeamStats['home_total_games'].clip(upper=10)
footballdata_wTeamStats

home_goals_for_minute_16_30_percentage  AwayTeamId FullTimeResult  \
0                                       0.00          48              H   
1                                       0.00          45              H   
2                                       0.00          36              D   
3                                       0.00          60              H   
4                                       0.00          54              D   
...                                      ...         ...            ...   
4533                                   17.50          49              A   
4534                                   12.00          71              H   
4535                                   20.59          45              D   
4536                                   15.15          50              A   
4537                                   12.73          42              H   

      away_home_wins  AverageHomeWinOdd  home_goals_against_minute_91_105  \
0                  0               2.00                                 0   
1                  0               2.88                                 0   
2                  0               2.20                                 0   
3                  0               1.17                                 0   
4                  0               2.10                                 0   
...              ...                ...                               ...   
4533               8               4.98                                 5   
4534               3               1.44                                 5   
4535               8               4.26                                 6   
4536              14              12.83                                 3   
4537              12               2.12                                 4   

      away_goals_against_minute_91_105_percentage  away_penalties_for  \
0                                            0.00                   0   
1                                            0.00                   0   
2                                            0.00                   0   
3                                            0.00                   0   
4                                            0.00                   0   
...                                           ...                 ...   
4533                                         9.68                   8   
4534                                         6.67                   3   
4535                                         3.77                   5   
4536                                         8.70                   7   
4537                                         9.30                   4   

      home_away_goals_for  home_goals_against_minute_76_90  \
0                       0                                0   
1                       0                                0   
2                       0                                0   
3                       0                                0   
4                       0                                0   
...                   ...                              ...   
4533                   21                                9   
4534                   22                                8   
4535                   16                               10   
4536                   17                                6   
4537                   26                                8   

      home_goals_for_minute_91_105_percentage  \
0                                        0.00   
1                                        0.00   
2                                        0.00   
3                                        0.00   
4                                        0.00   
...                                       ...   
4533                                    15.00   
4534                                     4.00   
4535                                    11.76   
4536                                    12.12   
4537               

In [40]:
footballdata_wTeamStats = footballdata_wTeamStats.drop(columns=to_modify)

In [41]:
print(footballdata_wTeamStats.dtypes.sort_values().to_string())

home_goals_for_minute_31_45                      int32
home_goals_for_minute_46_60                      int32
home_goals_for_minute_61_75                      int32
away_goals_for_minute_76_90                      int32
away_goals_for_minute_16_30                      int32
away_goals_against_minute_31_45                  int32
away_goals_against_minute_61_75                  int32
home_goals_for_minute_91_105                     int32
home_goals_against_minute_0_15                   int32
away_goals_against_minute_76_90                  int32
home_goals_for_minute_76_90                      int32
away_goals_for_minute_61_75                      int32
away_goals_against_minute_16_30                  int32
away_goals_for_minute_31_45                      int32
away_goals_against_minute_0_15                   int32
home_goals_against_minute_31_45                  int32
home_goals_against_minute_16_30                  int32
away_goals_against_minute_91_105                 int32
away_goals

### Remove 1st 5 "jornadas"

In [42]:
footballdata_wTeamStats = footballdata_wTeamStats[footballdata_wTeamStats['home_total_games']>=5]
footballdata_wTeamStats.reindex(sorted(footballdata_wTeamStats.columns), axis=1)

AverageAwayWinOdd  AverageDrawWinOdd  AverageHomeWinOdd  AvgOver2_5  \
50                15.00               6.00               1.22        1.42   
51                 4.50               3.50               1.83        2.13   
52                 2.30               3.25               3.20        1.81   
53                 2.63               3.20               2.75        2.18   
54                 7.50               4.33               1.44        1.90   
...                 ...                ...                ...         ...   
4533               1.67               4.17               4.98        1.64   
4534               7.02               4.90               1.44        1.61   
4535               1.87               3.68               4.26        1.91   
4536               1.26               5.88              12.83        1.66   
4537               3.42               3.60               2.12        1.78   

      AvgUnder2_5  AwayGoals  AwayTeamId AwayTeamName        Date  Div  \
50           2.68          3          60    West Brom  25/09/2010   39   
51           1.67          0          61        Wigan  25/09/2010   39   
52           1.95          2          67    Blackburn  25/09/2010   39   
53           1.65          0          45      Everton  25/09/2010   39   
54           1.85          2         746   Sunderland  25/09/2010   39   
...           ...        ...         ...          ...         ...  ...   
4533         2.28          3          49      Chelsea  11/05/2022   39   
4534         2.34          0          71      Norwich  11/05/2022   39   
4535         1.92          0          45      Everton  11/05/2022   39   
4536         2.24          5          50     Man City  11/05/2022   39   
4537         2.05          0          42      Arsenal  12/05/2022   39   

     FullTimeResult  HomeGoals HomeTeamName  HomeTeamid  Season  \
50                A          2      Arsenal          42    2010   
51                D          0   Birmingham          54    2010   
52                A          1    Blackpool        1356    2010   
53                D          0       Fulham          36    2010   
54                D          2    Liverpool          40    2010   
...             ...        ...          ...         ...     ...   
4533              A          0        Leeds          63    2021   
4534              H          3    Leicester          46    2021   
4535              D          0      Watford          38    2021   
4536              A          1       Wolves          39    2021   
4537              H          3    Tottenham          47    2021   

      away_away_clean_sheets  away_away_draws  away_away_goals_against  \
50                         0                0                        7   
51                         1                0                        0   
52                         0                1                        3   
53                         0                0                        2   
54                         0                1                        2   
...                      ...              ...                      ...   
4533                       9                4                       11   
4534                       3                3                       37   
4535                       1                3                       36   
4536                      10                3                        8   
4537                       6                1                       26   

      away_away_goals_for  away_away_loses  away_away_wins  \
50                      0                2               0   
51                      1                0               1   
52                      2                1               0   
53                      0                2               0   
54                      1                1               0   
...                   ...              ...             ...   
4533                   36                3              11   
45

## Define indexes and labels

In [43]:
indexes = ['AverageAwayWinOdd', 'AverageDrawWinOdd', 'AverageHomeWinOdd',
               'AvgOver2_5', 'AvgUnder2_5', 'AwayGoals', 'AwayTeamId',
               'AwayTeamId', 'AwayTeamName', 'Date', 'Div',
               'HomeGoals', 'HomeTeamName', 'HomeTeamid', 'Season',
               'FullTimeResult'
               ]

label = ['goals']

footballdata_wTeamStats[label] = footballdata_wTeamStats['AwayGoals'] + footballdata_wTeamStats['HomeGoals']

In [44]:
print(footballdata_wTeamStats.drop(columns=indexes).dtypes.sort_index().to_string())

away_away_clean_sheets                           int64
away_away_draws                                  int64
away_away_goals_against                          int64
away_away_goals_for                              int64
away_away_loses                                  int64
away_away_wins                                   int64
away_failed_to_score_away                        int64
away_failed_to_score_home                        int64
away_failed_to_score_total                       int64
away_form_last10games_draws                    float64
away_form_last10games_loses                    float64
away_form_last10games_wins                     float64
away_form_last1games_draws                     float64
away_form_last1games_loses                     float64
away_form_last1games_wins                      float64
away_form_last2games_draws                     float64
away_form_last2games_loses                     float64
away_form_last2games_wins                      float64
away_form_

In [45]:
list(set(footballdata_wTeamStats.columns.to_list())-set(indexes)-set(label))

['home_goals_for_minute_16_30_percentage',
 'home_form_last2games_wins',
 'home_form_last10games_wins',
 'home_form_last1games_wins',
 'away_home_wins',
 'home_goals_against_minute_91_105',
 'away_goals_against_minute_91_105_percentage',
 'away_total_games',
 'away_penalties_for',
 'home_away_goals_for',
 'home_goals_against_minute_76_90',
 'home_goals_for_minute_91_105_percentage',
 'away_form_last10games_loses',
 'home_goals_against_minute_61_75',
 'home_penalties_for',
 'home_failed_to_score_home',
 'home_failed_to_score_total',
 'home_away_goals_against',
 'home_goals_against_minute_76_90_percentage',
 'home_total_home_games',
 'away_form_last5games_draws',
 'away_form_last5games_loses',
 'away_failed_to_score_home',
 'away_home_draws',
 'away_form_last10games_draws',
 'away_goals_for_minute_46_60',
 'away_away_clean_sheets',
 'away_away_wins',
 'away_goals_for_minute_31_45_percentage',
 'home_goals_against_minute_46_60_percentage',
 'away_goals_for_minute_0_15',
 'home_goals_for_m

## Normalize Features (per game)

In [46]:
away_away_games_norm = ['away_away_clean_sheets', 'away_away_draws', 'away_away_goals_against',
                      'away_away_goals_for', 'away_away_loses', 'away_away_wins', 'away_failed_to_score_away']

away_home_games_norm = ['away_failed_to_score_home', 'away_home_clean_sheets',
                       'away_home_draws', 'away_home_goals_against', 'away_home_goals_for',
                       'away_home_loses', 'away_home_wins']

away_total_games_norm = ['away_failed_to_score_total', 'away_goals_against_minute_0_15',
                        'away_goals_against_minute_16_30', 'away_goals_against_minute_31_45',
                        'away_goals_against_minute_46_60', 'away_goals_against_minute_61_75',
                        'away_goals_against_minute_76_90', 'away_goals_against_minute_91_105',
                        'away_goals_for_minute_0_15', 'away_goals_for_minute_16_30',
                        'away_goals_for_minute_31_45', 'away_goals_for_minute_46_60',
                        'away_goals_for_minute_61_75', 'away_goals_for_minute_76_90',
                        'away_goals_for_minute_91_105', 'away_penalties_for', 'away_total_clean_sheets',
                        'away_total_draws', 'away_total_goals_against', 'away_total_goals_for', 'away_total_loses',
                        'away_total_wins']

home_away_games_norm = ['home_away_clean_sheets', 'home_away_draws', 'home_away_goals_against',
                      'home_away_goals_for', 'home_away_loses', 'home_away_wins', 'home_failed_to_score_away']

home_home_games_norm = ['home_failed_to_score_home', 'home_home_clean_sheets',
                       'home_home_draws', 'home_home_goals_against', 'home_home_goals_for',
                       'home_home_loses', 'home_home_wins']

home_total_games_norm = ['home_failed_to_score_total', 'home_goals_against_minute_0_15',
                        'home_goals_against_minute_16_30', 'home_goals_against_minute_31_45',
                        'home_goals_against_minute_46_60', 'home_goals_against_minute_61_75',
                        'home_goals_against_minute_76_90', 'home_goals_against_minute_91_105',
                        'home_goals_for_minute_0_15', 'home_goals_for_minute_16_30',
                        'home_goals_for_minute_31_45', 'home_goals_for_minute_46_60',
                        'home_goals_for_minute_61_75', 'home_goals_for_minute_76_90',
                        'home_goals_for_minute_91_105', 'home_penalties_for', 'home_total_clean_sheets',
                        'home_total_draws', 'home_total_goals_against', 'home_total_goals_for', 'home_total_loses',
                        'home_total_wins']

In [47]:
for feature in away_away_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['away_total_away_games']
for feature in away_home_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['away_total_home_games']
for feature in away_total_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['away_total_games']
    
for feature in home_away_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['home_total_away_games']
for feature in home_home_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['home_total_home_games']
for feature in home_total_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['home_total_games']
    
footballdata_wTeamStats

home_goals_for_minute_16_30_percentage  AwayTeamId FullTimeResult  \
50                                     15.38          60              A   
51                                      0.00          61              D   
52                                     14.29          67              A   
53                                      0.00          45              D   
54                                      0.00         746              D   
...                                      ...         ...            ...   
4533                                   17.50          49              A   
4534                                   12.00          71              H   
4535                                   20.59          45              D   
4536                                   15.15          50              A   
4537                                   12.73          42              H   

      away_home_wins  AverageHomeWinOdd  home_goals_against_minute_91_105  \
50          0.666667               1.22                          0.000000   
51          0.000000               1.83                          0.000000   
52          0.333333               3.20                          0.000000   
53          0.000000               2.75                          0.000000   
54          0.333333               1.44                          0.000000   
...              ...                ...                               ...   
4533        0.470588               4.98                          0.142857   
4534        0.166667               1.44                          0.147059   
4535        0.470588               4.26                          0.171429   
4536        0.777778              12.83                          0.085714   
4537        0.666667               2.12                          0.114286   

      away_goals_against_minute_91_105_percentage  away_penalties_for  \
50                                           0.00            0.000000   
51                                           0.00            0.000000   
52                                           0.00            0.000000   
53                                           0.00            0.000000   
54                                           0.00            0.400000   
...                                           ...                 ...   
4533                                         9.68            0.228571   
4534                                         6.67            0.085714   
4535                                         3.77            0.147059   
4536                                         8.70            0.200000   
4537                                         9.30            0.114286   

      home_away_goals_for  home_goals_against_minute_76_90  \
50               1.333333                         0.400000   
51               1.666667                         0.200000   
52               1.500000                         0.400000   
53               1.000000                         0.200000   
54               0.666667                         0.200000   
...                   ...                              ...   
4533             1.166667                         0.257143   
4534             1.294118                         0.235294   
4535             0.888889                         0.285714   
4536             0.944444                         0.171429   
4537             1.444444                         0.228571   

      home_goals_for_minute_91_105_percentage  \
50                                       0.00   
51                                       0.00   
52                                       0.00   
53                                       0.00   
54                                       0.00   
...                                       ...   
4533                                    15.00   
4534                                     4.00   
4535                                    11.76   
4536                                    12.12   
4537               

In [48]:
#TODO: this is based only on home team games (for most cases should be ok)
footballdata_wTeamStats['total_games'] = footballdata_wTeamStats['home_total_games']
footballdata_wTeamStats = \
    footballdata_wTeamStats.drop(columns=['away_total_away_games','away_total_home_games', 'away_total_games',
                                          'home_total_away_games', 'home_total_home_games', 'home_total_games'])
footballdata_wTeamStats

home_goals_for_minute_16_30_percentage  AwayTeamId FullTimeResult  \
50                                     15.38          60              A   
51                                      0.00          61              D   
52                                     14.29          67              A   
53                                      0.00          45              D   
54                                      0.00         746              D   
...                                      ...         ...            ...   
4533                                   17.50          49              A   
4534                                   12.00          71              H   
4535                                   20.59          45              D   
4536                                   15.15          50              A   
4537                                   12.73          42              H   

      away_home_wins  AverageHomeWinOdd  home_goals_against_minute_91_105  \
50          0.666667               1.22                          0.000000   
51          0.000000               1.83                          0.000000   
52          0.333333               3.20                          0.000000   
53          0.000000               2.75                          0.000000   
54          0.333333               1.44                          0.000000   
...              ...                ...                               ...   
4533        0.470588               4.98                          0.142857   
4534        0.166667               1.44                          0.147059   
4535        0.470588               4.26                          0.171429   
4536        0.777778              12.83                          0.085714   
4537        0.666667               2.12                          0.114286   

      away_goals_against_minute_91_105_percentage  away_penalties_for  \
50                                           0.00            0.000000   
51                                           0.00            0.000000   
52                                           0.00            0.000000   
53                                           0.00            0.000000   
54                                           0.00            0.400000   
...                                           ...                 ...   
4533                                         9.68            0.228571   
4534                                         6.67            0.085714   
4535                                         3.77            0.147059   
4536                                         8.70            0.200000   
4537                                         9.30            0.114286   

      home_away_goals_for  home_goals_against_minute_76_90  \
50               1.333333                         0.400000   
51               1.666667                         0.200000   
52               1.500000                         0.400000   
53               1.000000                         0.200000   
54               0.666667                         0.200000   
...                   ...                              ...   
4533             1.166667                         0.257143   
4534             1.294118                         0.235294   
4535             0.888889                         0.285714   
4536             0.944444                         0.171429   
4537             1.444444                         0.228571   

      home_goals_for_minute_91_105_percentage  \
50                                       0.00   
51                                       0.00   
52                                       0.00   
53                                       0.00   
54                                       0.00   
...                                       ...   
4533                                    15.00   
4534                                     4.00   
4535                                    11.76   
4536                                    12.12   
4537               

## Extract Features

In [49]:
footballdata_wTeamStats.groupby('FullTimeResult').count()

home_goals_for_minute_16_30_percentage  AwayTeamId  \
FullTimeResult                                                       
A                                                 1203        1203   
D                                                  939         939   
H                                                 1795        1795   

                away_home_wins  AverageHomeWinOdd  \
FullTimeResult                                      
A                         1203               1203   
D                          939                939   
H                         1795               1795   

                home_goals_against_minute_91_105  \
FullTimeResult                                     
A                                           1203   
D                                            939   
H                                           1795   

                away_goals_against_minute_91_105_percentage  \
FullTimeResult                                                
A                                                      1203   
D                                                       939   
H                                                      1795   

                away_penalties_for  home_away_goals_for  \
FullTimeResult                                            
A                             1203                 1203   
D                              939                  939   
H                             1795                 1795   

                home_goals_against_minute_76_90  \
FullTimeResult                                    
A                                          1203   
D                                           939   
H                                          1795   

                home_goals_for_minute_91_105_percentage  \
FullTimeResult                                            
A                                                  1203   
D                                                   939   
H                                                  1795   

                home_goals_against_minute_61_75  home_penalties_for  \
FullTimeResult                                                        
A                                          1203                1203   
D                                           939                 939   
H                                          1795                1795   

                home_failed_to_score_home  home_failed_to_score_total  \
FullTimeResult                                                          
A                                    1203                        1203   
D                                     939                         939   
H                                    1795                        1795   

                home_away_goals_against  \
FullTimeResult                            
A                                  1203   
D                                   939   
H                                  1795   

                home_goals_against_minute_76_90_percentage  \
FullTimeResult                                               
A                                                     1203   
D                                                      939   
H                                                     1795   

                away_failed_to_score_home  away_home_draws  \
FullTimeResult                                               
A                                    1203             1203   
D                                     939              939   
H                                    1795             1795   

                away_goals_for_minute_46_60  away_away_clean_sheets  \
FullTimeResult                                                        
A                                      1203                    1203   
D                                       939                     939   
H                                      1795                    1795   

                away_away_wins  away_goals_for_minute_31_4

In [50]:
X = footballdata_wTeamStats[list(set(footballdata_wTeamStats.columns.to_list())-set(indexes)-set(label))].values
y = footballdata_wTeamStats[label].values
y = y.reshape((y.shape[0],))
#y = np.array([0 if label=='H' else 1 if label=='D' else 2 for label in y])

In [51]:
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
X

array([[ 0.15627577,  1.21707815,  1.55897539, ..., -1.18877844,
        -1.57831341, -2.17434847],
       [-1.78726322,  2.92621534, -0.99788439, ...,  4.27883159,
        -1.57831341, -1.01119672],
       [ 0.01853471, -0.49205905,  1.55897539, ..., -0.48328037,
         0.91881521,  0.15195503],
       ...,
       [ 0.81465277, -1.22454641, -0.99788439, ..., -0.10978139,
        -0.3297491 ,  1.97976493],
       [ 0.12721115, -0.98038396, -0.99788439, ..., -1.07119543,
         0.57421146,  0.31811957],
       [-0.17859928, -0.98038396,  0.2805455 , ..., -0.71844639,
         0.91881521, -0.34653857]])

In [52]:
print ('The first element of X is: ', X[0])

The first element of X is:  [ 0.15627577  1.21707815  1.55897539  2.52821315  1.11991248 -1.45098669
 -0.67603271 -0.68132332  0.13715961 -0.49188987  1.08792727 -1.02915653
 -1.05379503 -0.00855176 -0.08610973  2.5637142  -1.16935698  0.20018941
 -1.58386917  1.24818757 -1.02674515  0.74910274 -2.0267237   0.14344788
 -0.59330484 -1.55478628 -1.88427812 -0.62905642  1.14707657  0.07323557
 -0.36893069 -1.4026712  -2.05617383 -0.99833619  2.50013671  1.45193001
 -0.61283756  2.79977167  0.62367073  0.01112387  1.5017462   2.78689
  0.09329849 -1.44502664  1.09055577 -1.00860431 -1.6796285  -1.71334288
  3.65397149 -0.09048922  0.4981882  -0.32809903 -1.61610922  1.37583172
 -0.33784454 -1.50003116  2.24211528 -0.9918544  -1.39176705 -1.90913194
  1.05596208  0.89564073  0.03019046 -1.45092405  0.2400149   1.14654644
 -0.25881824  1.46406383 -1.01870202 -1.01605976  2.24977821  0.83243739
 -0.08159073 -1.56882314  2.55775581  0.19378691 -0.2797958   0.56487127
 -0.54819468 -1.7613771  -

In [53]:
print ('The first element of y is: ', y[0])
print ('The last element of y is: ', y[-1])

The first element of y is:  5
The last element of y is:  3


In [54]:
print ('The shape of X is: ' + str(X.shape))
print ('The shape of y is: ' + str(y.shape))

The shape of X is: (3937, 125)
The shape of y is: (3937,)


In [40]:
#train_size = int(X.shape[0]*0.8)
#train_size

3149

In [41]:
#X_train = X[:train_size]
#print(X_train.shape)
#X_test = X[train_size:]
#print(X_test.shape)

(3149, 125)
(788, 125)


In [42]:
#y_train = y[:train_size]
#print(y_train.shape)
#y_test = y[train_size:]
#print(y_test.shape)

(3149,)
(788,)


In [55]:
X_train, X_test, y_train, y_test \
    = train_test_split(X, y, test_size=0.2, random_state=1)

X_train, X_val, y_train, y_val \
    = train_test_split(X_train, y_train, test_size=0.25, random_state=1) # 0.25 x 0.8 = 0.2

In [56]:
print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

(2361, 125)
(788, 125)
(788, 125)


In [57]:
print(y_train.shape)
print(y_val.shape)
print(y_test.shape)

(2361,)
(788,)
(788,)


# ML Algorithms

In [58]:
def accuracy(confusion_matrix):
    diagonal_sum = confusion_matrix.trace()
    sum_of_all_elements = confusion_matrix.sum()
    return diagonal_sum / sum_of_all_elements

## GBT

### Test changing only max_depth

In [61]:
max_val_score = 0
iterations_wo_update = 0
for max_depth in range(125):
    max_depth += 1 # start on 1
    print(f"Testing Max Depth: {max_depth}")
    gbtRegressor = GradientBoostingRegressor(max_depth = max_depth, n_iter_no_change=7, verbose=1).fit(X_train, y_train)
    val_score = gbtRegressor.score(X_val, y_val)
    if val_score > max_val_score:
        iterations_wo_update = 0
        best_max_depth = max_depth
        max_val_score = val_score
        best_model = gbtRegressor
        print(f"New best max depth: {best_max_depth}, validation score: {max_val_score}")
    else:
        iterations_wo_update +=1
        if iterations_wo_update >= 10:
            print("No improvements on the last 10 iterations, stopping here...")
            break
            
gbtRegressor = best_model

Testing Max Depth: 1
      Iter       Train Loss   Remaining Time 
         1           2.7316            0.99s
         2           2.7266            0.98s
         3           2.7223            0.82s
         4           2.7183            0.61s
         5           2.7148            0.73s
         6           2.7118            0.85s
         7           2.7090            0.72s
         8           2.7063            0.80s
         9           2.7037            0.70s
        10           2.7012            0.77s
        20           2.6804            0.68s
New best max depth: 1, validation score: 0.003399729704110843
Testing Max Depth: 2
      Iter       Train Loss   Remaining Time 
         1           2.6818            1.81s
         2           2.6729            1.66s
         3           2.6631            1.57s
         4           2.6548            1.54s
         5           2.6460            1.51s
         6           2.6378            1.49s
         7           2.6297            

In [62]:
best_model.score(X_train, y_train)

0.226086658542066

In [63]:
best_model.score(X_test, y_test)

0.00036447904684377974

In [64]:
y_train_pred = gbtRegressor.predict(X_train)
y_test_pred = gbtRegressor.predict(X_test)

In [70]:
y_train_over = (y_train>2.5).astype(int)
y_train_pred_over = (y_train_pred>2.5).astype(int)
y_test_over = (y_test>2.5).astype(int)
y_test_pred_over = (y_test_pred>2.5).astype(int)

In [72]:
cm_train = confusion_matrix(y_train_pred_over, y_train_over)
cm_train

array([[ 421,   62],
       [ 741, 1137]], dtype=int64)

In [73]:
cm_test = confusion_matrix(y_test_pred_over, y_test_over)
cm_test

array([[ 55,  75],
       [298, 360]], dtype=int64)

### Test changing also n_estimators

In [81]:
gbtClassifier = GradientBoostingClassifier(n_estimators=20, verbose=1).fit(X_train, y_train)
print(gbtClassifier.score(X_train, y_train))
gbtClassifier.score(X_test, y_test)

      Iter       Train Loss   Remaining Time 
         1           1.0491            1.82s
         2           1.0344            1.65s
         3           1.0217            1.56s
         4           1.0101            1.46s
         5           0.9994            1.35s
         6           0.9903            1.26s
         7           0.9819            1.17s
         8           0.9736            1.08s
         9           0.9663            0.98s
        10           0.9596            0.89s
        20           0.9019            0.00s
0.5883100381194409


0.5329949238578681

In [96]:
max_val_score = 0
for n_estimators in range(5,100,5):
    print(f"Testing N Estimators: {n_estimators}")
    iterations_wo_update = 0
    for max_depth in range(125):
        max_depth += 1 # start on 1
        gbtClassifier = GradientBoostingClassifier(max_depth = max_depth, n_estimators=n_estimators).fit(X_train, y_train)
        val_score = gbtClassifier.score(X_val, y_val)
        if val_score > max_val_score:
            iterations_wo_update = 0
            best_max_depth = max_depth
            max_val_score = val_score
            best_model = gbtClassifier
            print(f"New best max depth and N estimators: ({best_max_depth}, {n_estimators}), validation score: {max_val_score}")
        else:
            iterations_wo_update +=1
            if iterations_wo_update >= 10:
                print("No improvements on the last 10 iterations, moving on...")
                break
            
gbtClassifier = best_model

Testing N Estimators: 5
New best max depth and N estimators: (1, 5), validation score: 0.4631979695431472
New best max depth and N estimators: (2, 5), validation score: 0.5101522842639594
New best max depth and N estimators: (3, 5), validation score: 0.5114213197969543
No improvements on the last 10 iterations, moving on...
Testing N Estimators: 10
New best max depth and N estimators: (2, 10), validation score: 0.5241116751269036
No improvements on the last 10 iterations, moving on...
Testing N Estimators: 15
No improvements on the last 10 iterations, moving on...
Testing N Estimators: 20
No improvements on the last 10 iterations, moving on...
Testing N Estimators: 25
No improvements on the last 10 iterations, moving on...
Testing N Estimators: 30
New best max depth and N estimators: (2, 30), validation score: 0.5304568527918782
No improvements on the last 10 iterations, moving on...
Testing N Estimators: 35
No improvements on the last 10 iterations, moving on...
Testing N Estimators: 

In [102]:
gbtClassifier.score(X_train, y_train)

0.554849639983058

In [103]:
gbtClassifier.score(X_test, y_test)

0.5317258883248731

In [104]:
y_train_pred = gbtClassifier.predict(X_train)
y_test_pred = gbtClassifier.predict(X_test)

In [105]:
cm_train = confusion_matrix(y_train_pred, y_train)
cm_train

array([[913, 400, 372],
       [  4,  39,   1],
       [139, 135, 358]], dtype=int64)

In [106]:
cm_test = confusion_matrix(y_test_pred, y_test)
cm_test

array([[312, 130, 133],
       [  8,   5,   7],
       [ 54,  37, 102]], dtype=int64)

## MLP

In [137]:
model = Sequential(
    [ 
        tf.keras.Input(shape=(125,)),
        Dense(20, activation = 'relu', name='L1', kernel_regularizer=tf.keras.regularizers.l2(0.1)),
        Dense(20, activation = 'relu', name='L2', kernel_regularizer=tf.keras.regularizers.l2(0.1)),
        Dense(3, activation = 'linear', name='L3')    # < softmax activation here
    ]
)
model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.Adam(0.0001),
)
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 L1 (Dense)                  (None, 20)                2520      
                                                                 
 L2 (Dense)                  (None, 20)                420       
                                                                 
 L3 (Dense)                  (None, 3)                 63        
                                                                 
Total params: 3,003
Trainable params: 3,003
Non-trainable params: 0
_________________________________________________________________


In [138]:
model.fit(
    X_train,y_train,
    epochs=1000
)

Epoch 1/1000
111/111 [==============================] - 1s 3ms/step - loss: 6.6018
Epoch 2/1000
111/111 [==============================] - 0s 3ms/step - loss: 6.0157
Epoch 3/1000
111/111 [==============================] - 0s 3ms/step - loss: 5.4996
Epoch 4/1000
111/111 [==============================] - 0s 3ms/step - loss: 5.0372
Epoch 5/1000
111/111 [==============================] - 0s 2ms/step - loss: 4.6191
Epoch 6/1000
111/111 [==============================] - 0s 2ms/step - loss: 4.2403
Epoch 7/1000
111/111 [==============================] - 0s 2ms/step - loss: 3.8972
Epoch 8/1000
111/111 [==============================] - 0s 2ms/step - loss: 3.5865
Epoch 9/1000
111/111 [==============================] - 0s 3ms/step - loss: 3.3055
Epoch 10/1000
111/111 [==============================] - 0s 3ms/step - loss: 3.0520
Epoch 11/1000
111/111 [==============================] - 0s 3ms/step - loss: 2.8234
Epoch 12/1000
111/111 [==============================] - 0s 2ms/step - loss: 2.6176
E

111/111 [==============================] - 0s 2ms/step - loss: 0.9966
Epoch 195/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9964
Epoch 196/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9964
Epoch 197/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9964
Epoch 198/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9966
Epoch 199/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9963
Epoch 200/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9962
Epoch 201/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9962
Epoch 202/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9961
Epoch 203/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9961
Epoch 204/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9962
Epoch 205/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.

111/111 [==============================] - 1s 5ms/step - loss: 0.9907
Epoch 387/1000
111/111 [==============================] - 0s 4ms/step - loss: 0.9910
Epoch 388/1000
111/111 [==============================] - 1s 5ms/step - loss: 0.9911
Epoch 389/1000
111/111 [==============================] - 0s 4ms/step - loss: 0.9909
Epoch 390/1000
111/111 [==============================] - 0s 4ms/step - loss: 0.9910
Epoch 391/1000
111/111 [==============================] - 1s 5ms/step - loss: 0.9910
Epoch 392/1000
111/111 [==============================] - 0s 4ms/step - loss: 0.9909
Epoch 393/1000
111/111 [==============================] - 0s 4ms/step - loss: 0.9908
Epoch 394/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9910
Epoch 395/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9906
Epoch 396/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9909
Epoch 397/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.

111/111 [==============================] - 0s 3ms/step - loss: 0.9876
Epoch 579/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9877
Epoch 580/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9875
Epoch 581/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9878
Epoch 582/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9878
Epoch 583/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9876
Epoch 584/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9875
Epoch 585/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9877
Epoch 586/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9876
Epoch 587/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9875
Epoch 588/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9876
Epoch 589/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.

111/111 [==============================] - 0s 2ms/step - loss: 0.9854
Epoch 771/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9848
Epoch 772/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9851
Epoch 773/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9851
Epoch 774/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9851
Epoch 775/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9851
Epoch 776/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9850
Epoch 777/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9849
Epoch 778/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9850
Epoch 779/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9850
Epoch 780/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9850
Epoch 781/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.

111/111 [==============================] - 0s 3ms/step - loss: 0.9827
Epoch 963/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9824
Epoch 964/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9827
Epoch 965/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9827
Epoch 966/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9826
Epoch 967/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9824
Epoch 968/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9825
Epoch 969/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9825
Epoch 970/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9824
Epoch 971/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9824
Epoch 972/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9824
Epoch 973/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.

In [139]:
[layer1, layer2, layer3] = model.layers
W1,b1 = layer1.get_weights()
W2,b2 = layer2.get_weights()
W3,b3 = layer3.get_weights()

In [140]:
W1

array([[-3.1290039e-34,  7.8969998e-03,  2.6002321e-03, ...,
         3.8971480e-03,  3.4866780e-03,  5.3276604e-34],
       [-2.4301220e-34,  2.0039938e-02, -7.7724806e-03, ...,
        -5.5732852e-04,  8.0334311e-03, -8.6154977e-35],
       [ 1.0791125e-34, -1.1884933e-02,  6.9113229e-03, ...,
         4.4076606e-03, -3.9039669e-03, -5.0616658e-34],
       ...,
       [ 7.6492150e-35, -1.7731458e-04, -1.1077951e-02, ...,
        -8.3890753e-03,  7.5112036e-03,  3.1851388e-34],
       [ 8.3804379e-35,  5.5134306e-03,  6.9521004e-03, ...,
         5.1117959e-03,  6.2084908e-04,  1.6034705e-34],
       [ 1.3671720e-34, -9.0701776e-03,  2.0495967e-03, ...,
         2.0148486e-03, -4.2821034e-03, -1.4035589e-34]], dtype=float32)

In [141]:
y_train_pred_probs = tf.nn.softmax(model.predict(X_train)).numpy()
y_train_pred_probs

111/111 [==============================] - 0s 2ms/step


array([[0.7414078 , 0.1668334 , 0.09175882],
       [0.5946549 , 0.22586152, 0.17948356],
       [0.260075  , 0.2735496 , 0.4663754 ],
       ...,
       [0.63571775, 0.21127789, 0.15300429],
       [0.29861066, 0.26938498, 0.43200433],
       [0.42486346, 0.2649965 , 0.31013995]], dtype=float32)

In [142]:
y_test_pred_probs = tf.nn.softmax(model.predict(X_test)).numpy()
y_test_pred_probs

13/13 [==============================] - 0s 3ms/step


array([[0.46438932, 0.26013002, 0.2754806 ],
       [0.27057377, 0.27411923, 0.45530704],
       [0.6085722 , 0.22115739, 0.17027041],
       ...,
       [0.3451147 , 0.274435  , 0.3804503 ],
       [0.14754826, 0.24316351, 0.6092882 ],
       [0.45374075, 0.25880393, 0.28745532]], dtype=float32)

In [143]:
y_train_pred = np.argmax(y_train_pred_probs, axis=1)
y_test_pred = np.argmax(y_test_pred_probs, axis=1)

In [144]:
cm_train = confusion_matrix(y_train_pred, y_train)
cm_train

array([[1373,  562,  495],
       [   0,    0,    0],
       [ 256,  291,  566]], dtype=int64)

In [145]:
cm_test = confusion_matrix(y_test_pred, y_test)
cm_test

array([[131,  57,  69],
       [  0,   0,   0],
       [ 35,  29,  73]], dtype=int64)

In [146]:
for i in range(10):
    print( f"{y_train_pred_probs[-i]}, predicted_category: {np.argmax(y_train_pred_probs[-i])}, category: {y_train[-i]}")

[0.7414078  0.1668334  0.09175882], predicted_category: 0, category: 2
[0.42486346 0.2649965  0.31013995], predicted_category: 0, category: 2
[0.29861066 0.26938498 0.43200433], predicted_category: 2, category: 2
[0.63571775 0.21127789 0.15300429], predicted_category: 0, category: 0
[0.65596986 0.20388407 0.1401461 ], predicted_category: 0, category: 2
[0.49826044 0.2515875  0.25015205], predicted_category: 0, category: 2
[0.49491912 0.251669   0.2534119 ], predicted_category: 0, category: 1
[0.4440607 0.2645487 0.2913906], predicted_category: 0, category: 0
[0.33770368 0.27549848 0.38679785], predicted_category: 2, category: 2
[0.4100076  0.2681028  0.32188967], predicted_category: 0, category: 2


In [147]:
for i in range(10):
    print( f"{y_test_pred_probs[-i]}, predicted_category: {np.argmax(y_test_pred_probs[-i])}, category: {y_test[-i]}")

[0.46438932 0.26013002 0.2754806 ], predicted_category: 0, category: 0
[0.45374075 0.25880393 0.28745532], predicted_category: 0, category: 0
[0.14754826 0.24316351 0.6092882 ], predicted_category: 2, category: 2
[0.3451147 0.274435  0.3804503], predicted_category: 2, category: 1
[0.6681957 0.1987667 0.1330376], predicted_category: 0, category: 0
[0.1846948  0.25842822 0.556877  ], predicted_category: 2, category: 2
[0.16090234 0.24836555 0.59073216], predicted_category: 2, category: 2
[0.8806478  0.09074179 0.02861039], predicted_category: 0, category: 0
[0.31032193 0.27536654 0.41431153], predicted_category: 2, category: 2
[0.5812784  0.229438   0.18928358], predicted_category: 0, category: 2


In [148]:
print('Train accuracy: '+ str(accuracy(cm_train)))
print('Test accuracy: '+ str(accuracy(cm_test)))

Train accuracy: 0.5472763195032458
Test accuracy: 0.5177664974619289
