# Imports

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

import os
from datetime import datetime, timedelta

In [35]:
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier

In [3]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Variables

In [4]:
footballdata_wTeamStats_path = \
    os.path.abspath(os.getcwd())+"\\Data\\teamStats_byLeague\\footballdata_wTeamStats_englishpremierleague.csv"

# Load Football-Data File with Indexes

In [5]:
footballdata_wTeamStats = pd.read_csv(footballdata_wTeamStats_path, index_col=0)
footballdata_wTeamStats.head(5)

C:\Users\ldoutors\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (96,113,194,211) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


AverageAwayWinOdd  AverageDrawWinOdd  AverageHomeWinOdd  AvgOver2_5  \
0                4.0               3.30               2.00        2.01   
1                2.5               3.25               2.88        2.08   
2                3.4               3.30               2.20        2.09   
3               17.0               7.00               1.17        1.49   
4                3.6               3.30               2.10        2.16   

   AvgUnder2_5  AwayGoals  AwayTeamId AwayTeamName        Date  Div  \
0         1.75          0          48     West Ham  14/08/2010   39   
1         1.70          0          45      Everton  14/08/2010   39   
2         1.69          0          36       Fulham  14/08/2010   39   
3         2.49          0          60    West Brom  14/08/2010   39   
4         1.65          2          54   Birmingham  14/08/2010   39   

  FullTimeResult  HomeGoals HomeTeamName  HomeTeamid  Season  \
0              H          3  Aston Villa          66    2010   
1              H          1    Blackburn          67    2010   
2              D          0       Bolton          68    2010   
3              H          6      Chelsea          49    2010   
4              D          2   Sunderland         746    2010   

   away_average_away_goals_against  away_average_away_goals_for  \
0                              0.0                          0.0   
1                              0.0                          0.0   
2                              0.0                          0.0   
3                              0.0                          0.0   
4                              0.0                          0.0   

   away_average_home_goals_against  away_average_home_goals_for  \
0                              0.0                          0.0   
1                              0.0                          0.0   
2                              0.0                          0.0   
3                              0.0                          0.0   
4                              0.0                          0.0   

   away_average_total_goals_against  away_average_total_goals_for  \
0                               0.0                           0.0   
1                               0.0                           0.0   
2                               0.0                           0.0   
3                               0.0                           0.0   
4                               0.0                           0.0   

   away_away_clean_sheets  away_away_draws  away_away_goals_against  \
0                       0                0                        0   
1                       0                0                        0   
2                       0                0                        0   
3                       0                0                        0   
4                       0                0                        0   

   away_away_goals_for  away_away_loses  away_away_wins  \
0                    0                0               0   
1                    0                0               0   
2                    0                0               0   
3                    0                0               0   
4                    0                0               0   

   away_biggest_away_goals_against  away_biggest_away_goals_for  \
0                                0                            0   
1                                0                            0   
2                                0                            0   
3                                0                            0   
4                                0                            0   

  away_biggest_away_lose away_biggest_away_win  away_biggest_draw_streak  \
0                    NaN                   NaN                         0   
1                    NaN                   NaN                         0   
2                    NaN                   NaN                         0   
3                    NaN            

# Data Prep

## Remove Incomplete Columns & Non important (except indexes)

In [6]:
not_complete = ['away_red_cards_minute_0_15', 'away_red_cards_minute_0_15_percentage',
               'away_red_cards_minute_16_30', 'away_red_cards_minute_16_30_percentage',
               'away_red_cards_minute_31_45', 'away_red_cards_minute_31_45_percentage',
               'away_red_cards_minute_46_60', 'away_red_cards_minute_46_60_percentage',
               'away_red_cards_minute_61_75', 'away_red_cards_minute_61_75_percentage',
               'away_red_cards_minute_61_75', 'away_red_cards_minute_61_75_percentage',
               'away_red_cards_minute_76_90', 'away_red_cards_minute_76_90_percentage',
               'away_red_cards_minute_91_105', 'away_red_cards_minute_91_105_percentage',
               'away_yellow_cards_minute_0_15', 'away_yellow_cards_minute_0_15_percentage',
               'away_yellow_cards_minute_16_30', 'away_yellow_cards_minute_16_30_percentage',
               'away_yellow_cards_minute_31_45', 'away_yellow_cards_minute_31_45_percentage',
               'away_yellow_cards_minute_46_60', 'away_yellow_cards_minute_46_60_percentage',
               'away_yellow_cards_minute_61_75', 'away_yellow_cards_minute_61_75_percentage',
               'away_yellow_cards_minute_76_90', 'away_yellow_cards_minute_76_90_percentage',
               'away_yellow_cards_minute_91_105', 'away_yellow_cards_minute_91_105_percentage',
                'home_red_cards_minute_0_15', 'home_red_cards_minute_0_15_percentage',
               'home_red_cards_minute_16_30', 'home_red_cards_minute_16_30_percentage',
               'home_red_cards_minute_31_45', 'home_red_cards_minute_31_45_percentage',
               'home_red_cards_minute_46_60', 'home_red_cards_minute_46_60_percentage',
               'home_red_cards_minute_61_75', 'home_red_cards_minute_61_75_percentage',
               'home_red_cards_minute_61_75', 'home_red_cards_minute_61_75_percentage',
               'home_red_cards_minute_76_90', 'home_red_cards_minute_76_90_percentage',
               'home_red_cards_minute_91_105', 'home_red_cards_minute_91_105_percentage',
               'home_yellow_cards_minute_0_15', 'home_yellow_cards_minute_0_15_percentage',
               'home_yellow_cards_minute_16_30', 'home_yellow_cards_minute_16_30_percentage',
               'home_yellow_cards_minute_31_45', 'home_yellow_cards_minute_31_45_percentage',
               'home_yellow_cards_minute_46_60', 'home_yellow_cards_minute_46_60_percentage',
               'home_yellow_cards_minute_61_75', 'home_yellow_cards_minute_61_75_percentage',
               'home_yellow_cards_minute_76_90', 'home_yellow_cards_minute_76_90_percentage',
               'home_yellow_cards_minute_91_105', 'home_yellow_cards_minute_91_105_percentage']

# away average goals and home average goals will be removed because we will average all columns
not_features = [
               'away_biggest_away_lose', 'away_biggest_away_win', 'away_biggest_home_lose', 'away_biggest_home_win',
               'away_lineups',
               'home_biggest_away_lose', 'home_biggest_away_win', 'home_biggest_home_lose', 'home_biggest_home_win',
               'home_lineups',
    
               'away_biggest_away_goals_against', 'away_biggest_away_goals_for', 'away_biggest_draw_streak',
               'away_biggest_home_goals_against', 'away_biggest_home_goals_for', 'away_biggest_lose_streak',
               'away_biggest_win_streak',
               'home_biggest_away_goals_against', 'home_biggest_away_goals_for', 'home_biggest_draw_streak',
               'home_biggest_home_goals_against', 'home_biggest_home_goals_for', 'home_biggest_lose_streak',
               'home_biggest_win_streak',
    
               'away_average_away_goals_against', 'away_average_away_goals_for', 'away_average_home_goals_against',
               'away_average_home_goals_for', 'away_average_total_goals_against', 'away_average_total_goals_for',
               'home_average_away_goals_against', 'home_average_away_goals_for', 'home_average_home_goals_against',
               'home_average_home_goals_for', 'home_average_total_goals_against', 'home_average_total_goals_for',
    
               'away_penalties_missed', 'away_penalties_missed_percentage', 'away_penalties_scored',
               'away_penalties_scored', 'away_penalties_scored_percentage',
               'home_penalties_missed', 'home_penalties_missed_percentage', 'home_penalties_scored',
               'home_penalties_scored', 'home_penalties_scored_percentage'
               ]

In [7]:
footballdata_wTeamStats = \
    footballdata_wTeamStats[list(set(footballdata_wTeamStats.columns.tolist()) - set(not_complete + not_features))]
footballdata_wTeamStats

AwayGoals home_goals_for_minute_0_15_percentage  \
0             0                                   NaN   
1             0                                   NaN   
2             0                                   NaN   
3             0                                   NaN   
4             2                                   NaN   
...         ...                                   ...   
4533          3                                10.00%   
4534          0                                12.00%   
4535          0                                14.71%   
4536          5                                18.18%   
4537          0                                12.73%   

     away_goals_against_minute_91_105_percentage  HomeTeamid  AvgOver2_5  \
0                                            NaN          66        2.01   
1                                            NaN          67        2.08   
2                                            NaN          68        2.09   
3                                            NaN          49        1.49   
4                                            NaN         746        2.16   
...                                          ...         ...         ...   
4533                                       9.68%          63        1.64   
4534                                       6.67%          46        1.61   
4535                                       3.77%          38        1.91   
4536                                       8.70%          39        1.66   
4537                                       9.30%          47        1.78   

      home_home_loses  home_goals_against_minute_61_75  \
0                   0                              NaN   
1                   0                              NaN   
2                   0                              NaN   
3                   0                              NaN   
4                   0                              NaN   
...               ...                              ...   
4533                8                             11.0   
4534                5                              9.0   
4535               14                              8.0   
4536                8                             11.0   
4537                5                              8.0   

      home_failed_to_score_away  home_goals_against_minute_76_90  \
0                             0                              NaN   
1                             0                              NaN   
2                             0                              NaN   
3                             0                              NaN   
4                             0                              NaN   
...                         ...                              ...   
4533                          7                              9.0   
4534                          2                              8.0   
4535                         10                             10.0   
4536                          7                              6.0   
4537                          6                              8.0   

      away_away_draws  home_away_goals_against  \
0                   0                        0   
1                   0                        0   
2                   0                        0   
3                   0                        0   
4                   0                        0   
...               ...                      ...   
4533                4                       40   
4534                3                       34   
4535                3                       29   
4536                3                       15   
4537                1                       21   

     away_goals_against_minute_16_30_percentage  Season  \
0                                           NaN    2010   
1                                           NaN    2010   
2                                           NaN    2010   
3                                           NaN    2010  

## Convert NaN/Nulls to 0

In [8]:
nan_to_zero = ['away_goals_against_minute_0_15', 'away_goals_against_minute_0_15_percentage',
            'away_goals_against_minute_16_30', 'away_goals_against_minute_16_30_percentage',
            'away_goals_against_minute_16_30_percentage', 'away_goals_against_minute_31_45',
             'away_goals_against_minute_31_45_percentage', 'away_goals_against_minute_46_60',
            'away_goals_against_minute_46_60_percentage', 'away_goals_against_minute_61_75',
            'away_goals_against_minute_61_75_percentage', 'away_goals_against_minute_76_90',
            'away_goals_against_minute_76_90_percentage', 'away_goals_against_minute_91_105',
            'away_goals_against_minute_91_105_percentage', 'away_goals_for_minute_0_15',
            'away_goals_for_minute_0_15_percentage', 'away_goals_for_minute_16_30', 'away_goals_for_minute_16_30_percentage',
            'away_goals_for_minute_31_45', 'away_goals_for_minute_31_45_percentage', 'away_goals_for_minute_46_60',
            'away_goals_for_minute_46_60_percentage', 'away_goals_for_minute_61_75', 'away_goals_for_minute_61_75_percentage',
            'away_goals_for_minute_76_90', 'away_goals_for_minute_76_90_percentage', 'away_goals_for_minute_91_105',
            'away_goals_for_minute_91_105_percentage',
             'home_goals_against_minute_0_15', 'home_goals_against_minute_0_15_percentage',
            'home_goals_against_minute_16_30', 'home_goals_against_minute_16_30_percentage',
            'home_goals_against_minute_16_30_percentage', 'home_goals_against_minute_31_45',
             'home_goals_against_minute_31_45_percentage', 'home_goals_against_minute_46_60',
            'home_goals_against_minute_46_60_percentage', 'home_goals_against_minute_61_75',
            'home_goals_against_minute_61_75_percentage', 'home_goals_against_minute_76_90',
            'home_goals_against_minute_76_90_percentage', 'home_goals_against_minute_91_105',
            'home_goals_against_minute_91_105_percentage', 'home_goals_for_minute_0_15',
            'home_goals_for_minute_0_15_percentage', 'home_goals_for_minute_16_30', 'home_goals_for_minute_16_30_percentage',
            'home_goals_for_minute_31_45', 'home_goals_for_minute_31_45_percentage', 'home_goals_for_minute_46_60',
            'home_goals_for_minute_46_60_percentage', 'home_goals_for_minute_61_75', 'home_goals_for_minute_61_75_percentage',
            'home_goals_for_minute_76_90', 'home_goals_for_minute_76_90_percentage', 'home_goals_for_minute_91_105',
            'home_goals_for_minute_91_105_percentage']

In [9]:
print(footballdata_wTeamStats.count().sort_values().to_string())

away_goals_against_minute_91_105               2813
away_goals_against_minute_91_105_percentage    2813
home_goals_against_minute_91_105_percentage    2816
home_goals_against_minute_91_105               2816
home_goals_for_minute_91_105                   2878
home_goals_for_minute_91_105_percentage        2878
away_goals_for_minute_91_105_percentage        2887
away_goals_for_minute_91_105                   2887
away_goals_against_minute_0_15                 3760
away_goals_against_minute_0_15_percentage      3760
home_goals_against_minute_0_15_percentage      3762
home_goals_against_minute_0_15                 3762
away_goals_for_minute_0_15_percentage          3781
away_goals_for_minute_0_15                     3781
home_goals_for_minute_16_30                    3781
home_goals_for_minute_16_30_percentage         3781
home_goals_for_minute_0_15                     3783
home_goals_for_minute_0_15_percentage          3783
away_goals_for_minute_16_30                    3802
away_goals_f

In [10]:
for column in footballdata_wTeamStats.columns:
    if 'percentage' in column:
        footballdata_wTeamStats[column] = footballdata_wTeamStats[column].str.slice(0,-1,1).astype(float)

for column in nan_to_zero:
    if 'percentage' in column:
        footballdata_wTeamStats[column] = footballdata_wTeamStats[column].fillna(0.0)
    else:
        footballdata_wTeamStats[column] = footballdata_wTeamStats[column].fillna(0).astype(int)
footballdata_wTeamStats

AwayGoals  home_goals_for_minute_0_15_percentage  \
0             0                                   0.00   
1             0                                   0.00   
2             0                                   0.00   
3             0                                   0.00   
4             2                                   0.00   
...         ...                                    ...   
4533          3                                  10.00   
4534          0                                  12.00   
4535          0                                  14.71   
4536          5                                  18.18   
4537          0                                  12.73   

      away_goals_against_minute_91_105_percentage  HomeTeamid  AvgOver2_5  \
0                                            0.00          66        2.01   
1                                            0.00          67        2.08   
2                                            0.00          68        2.09   
3                                            0.00          49        1.49   
4                                            0.00         746        2.16   
...                                           ...         ...         ...   
4533                                         9.68          63        1.64   
4534                                         6.67          46        1.61   
4535                                         3.77          38        1.91   
4536                                         8.70          39        1.66   
4537                                         9.30          47        1.78   

      home_home_loses  home_goals_against_minute_61_75  \
0                   0                                0   
1                   0                                0   
2                   0                                0   
3                   0                                0   
4                   0                                0   
...               ...                              ...   
4533                8                               11   
4534                5                                9   
4535               14                                8   
4536                8                               11   
4537                5                                8   

      home_failed_to_score_away  home_goals_against_minute_76_90  \
0                             0                                0   
1                             0                                0   
2                             0                                0   
3                             0                                0   
4                             0                                0   
...                         ...                              ...   
4533                          7                                9   
4534                          2                                8   
4535                         10                               10   
4536                          7                                6   
4537                          6                                8   

      away_away_draws  home_away_goals_against  \
0                   0                        0   
1                   0                        0   
2                   0                        0   
3                   0                        0   
4                   0                        0   
...               ...                      ...   
4533                4                       40   
4534                3                       34   
4535                3                       29   
4536                3                       15   
4537                1                       21   

      away_goals_against_minute_16_30_percentage  Season  \
0                                           0.00    2010   
1                                           0.00    2010   
2                                           0.00    2010   
3                            

In [11]:
footballdata_wTeamStats.tail(5)

AwayGoals  home_goals_for_minute_0_15_percentage  \
4533          3                                  10.00   
4534          0                                  12.00   
4535          0                                  14.71   
4536          5                                  18.18   
4537          0                                  12.73   

      away_goals_against_minute_91_105_percentage  HomeTeamid  AvgOver2_5  \
4533                                         9.68          63        1.64   
4534                                         6.67          46        1.61   
4535                                         3.77          38        1.91   
4536                                         8.70          39        1.66   
4537                                         9.30          47        1.78   

      home_home_loses  home_goals_against_minute_61_75  \
4533                8                               11   
4534                5                                9   
4535               14                                8   
4536                8                               11   
4537                5                                8   

      home_failed_to_score_away  home_goals_against_minute_76_90  \
4533                          7                                9   
4534                          2                                8   
4535                         10                               10   
4536                          7                                6   
4537                          6                                8   

      away_away_draws  home_away_goals_against  \
4533                4                       40   
4534                3                       34   
4535                3                       29   
4536                3                       15   
4537                1                       21   

      away_goals_against_minute_16_30_percentage  Season  \
4533                                        9.68    2021   
4534                                        9.33    2021   
4535                                       13.21    2021   
4536                                        8.70    2021   
4537                                       11.63    2021   

      home_goals_against_minute_91_105  \
4533                                 5   
4534                                 5   
4535                                 6   
4536                                 3   
4537                                 4   

      home_goals_for_minute_31_45_percentage  \
4533                                   10.00   
4534                                   26.00   
4535                                   11.76   
4536                                    6.06   
4537                                   16.36   

      away_goals_against_minute_91_105  away_total_goals_against  \
4533                                 3                        31   
4534                                 5                        75   
4535                                 2                        56   
4536                                 2                        21   
4537                                 4                        42   

      home_goals_for_minute_16_30_percentage  away_away_clean_sheets  \
4533                                   17.50                       9   
4534                                   12.00                       3   
4535                                   20.59                       1   
4536                                   15.15                      10   
4537                                   12.73                       6   

      home_goals_for_minute_16_30  home_home_draws  AverageHomeWinOdd  \
4533                            7                5               4.98   
4534                            6                4               1.44   
4535                            7                1               4.26   
4536                            5                2              12.83   
4537                     

In [12]:
print(footballdata_wTeamStats.count().sort_values().to_string())

home_form                                      4418
away_form                                      4418
AwayGoals                                      4538
home_goals_for_minute_76_90_percentage         4538
away_goals_for_minute_76_90_percentage         4538
away_goals_for_minute_31_45                    4538
home_home_clean_sheets                         4538
home_goals_against_minute_46_60                4538
away_goals_for_minute_61_75                    4538
home_failed_to_score_total                     4538
home_home_goals_against                        4538
home_total_goals_for                           4538
home_goals_for_minute_91_105_percentage        4538
home_goals_against_minute_31_45                4538
home_total_goals_against                       4538
home_away_goals_for                            4538
HomeGoals                                      4538
away_goals_against_minute_76_90                4538
home_away_wins                                 4538
AverageDrawW

## Modifications

### Add Total wins, draws & losses

In [13]:
footballdata_wTeamStats['home_total_wins'] = \
    footballdata_wTeamStats['home_home_wins'] + footballdata_wTeamStats['home_away_wins']
footballdata_wTeamStats['home_total_draws'] = \
    footballdata_wTeamStats['home_home_draws'] + footballdata_wTeamStats['home_away_draws']
footballdata_wTeamStats['home_total_loses'] = \
    footballdata_wTeamStats['home_home_loses'] + footballdata_wTeamStats['home_away_loses']

# TODO: total games is computed bases only on the home games (might require future change)
footballdata_wTeamStats['home_total_games'] = footballdata_wTeamStats['home_total_wins']+\
    footballdata_wTeamStats['home_total_draws']+footballdata_wTeamStats['home_total_loses']

footballdata_wTeamStats['away_total_wins'] = \
    footballdata_wTeamStats['away_home_wins'] + footballdata_wTeamStats['away_away_wins']
footballdata_wTeamStats['away_total_draws'] = \
    footballdata_wTeamStats['away_home_draws'] + footballdata_wTeamStats['away_away_draws']
footballdata_wTeamStats['away_total_loses'] = \
    footballdata_wTeamStats['away_home_loses'] + footballdata_wTeamStats['away_away_loses']

footballdata_wTeamStats['away_total_games'] = footballdata_wTeamStats['away_total_wins']+\
    footballdata_wTeamStats['away_total_draws']+footballdata_wTeamStats['away_total_loses']

footballdata_wTeamStats['home_total_home_games'] = footballdata_wTeamStats['home_home_wins']+\
    footballdata_wTeamStats['home_home_draws']+footballdata_wTeamStats['home_home_loses']
footballdata_wTeamStats['home_total_away_games'] = footballdata_wTeamStats['home_away_wins']+\
    footballdata_wTeamStats['home_away_draws']+footballdata_wTeamStats['home_away_loses']

footballdata_wTeamStats['away_total_home_games'] = footballdata_wTeamStats['away_home_wins']+\
    footballdata_wTeamStats['away_home_draws']+footballdata_wTeamStats['away_home_loses']
footballdata_wTeamStats['away_total_away_games'] = footballdata_wTeamStats['away_away_wins']+\
    footballdata_wTeamStats['away_away_draws']+footballdata_wTeamStats['away_away_loses']

footballdata_wTeamStats

AwayGoals  home_goals_for_minute_0_15_percentage  \
0             0                                   0.00   
1             0                                   0.00   
2             0                                   0.00   
3             0                                   0.00   
4             2                                   0.00   
...         ...                                    ...   
4533          3                                  10.00   
4534          0                                  12.00   
4535          0                                  14.71   
4536          5                                  18.18   
4537          0                                  12.73   

      away_goals_against_minute_91_105_percentage  HomeTeamid  AvgOver2_5  \
0                                            0.00          66        2.01   
1                                            0.00          67        2.08   
2                                            0.00          68        2.09   
3                                            0.00          49        1.49   
4                                            0.00         746        2.16   
...                                           ...         ...         ...   
4533                                         9.68          63        1.64   
4534                                         6.67          46        1.61   
4535                                         3.77          38        1.91   
4536                                         8.70          39        1.66   
4537                                         9.30          47        1.78   

      home_home_loses  home_goals_against_minute_61_75  \
0                   0                                0   
1                   0                                0   
2                   0                                0   
3                   0                                0   
4                   0                                0   
...               ...                              ...   
4533                8                               11   
4534                5                                9   
4535               14                                8   
4536                8                               11   
4537                5                                8   

      home_failed_to_score_away  home_goals_against_minute_76_90  \
0                             0                                0   
1                             0                                0   
2                             0                                0   
3                             0                                0   
4                             0                                0   
...                         ...                              ...   
4533                          7                                9   
4534                          2                                8   
4535                         10                               10   
4536                          7                                6   
4537                          6                                8   

      away_away_draws  home_away_goals_against  \
0                   0                        0   
1                   0                        0   
2                   0                        0   
3                   0                        0   
4                   0                        0   
...               ...                      ...   
4533                4                       40   
4534                3                       34   
4535                3                       29   
4536                3                       15   
4537                1                       21   

      away_goals_against_minute_16_30_percentage  Season  \
0                                           0.00    2010   
1                                           0.00    2010   
2                                           0.00    2010   
3                            

### Away Team & Home Team Form

In [14]:
to_modify = ['away_form', 'home_form']

In [15]:
# Same as before but normalized
games = [1, 2, 5, 10]
for column in to_modify:
    footballdata_wTeamStats[column] = footballdata_wTeamStats[column].fillna('')
    for nr in games:
        footballdata_wTeamStats[column+f"_last{nr}games_wins"] = \
            footballdata_wTeamStats[column].apply(lambda x : x[-nr:]).str.count('W') / \
            footballdata_wTeamStats['home_total_games'].clip(upper=10)
        footballdata_wTeamStats[column+f"_last{nr}games_draws"] = \
            footballdata_wTeamStats[column].apply(lambda x : x[-nr:]).str.count('D') / \
            footballdata_wTeamStats['home_total_games'].clip(upper=10)
        footballdata_wTeamStats[column+f"_last{nr}games_loses"] = \
            footballdata_wTeamStats[column].apply(lambda x : x[-nr:]).str.count('L') / \
            footballdata_wTeamStats['home_total_games'].clip(upper=10)
footballdata_wTeamStats

AwayGoals  home_goals_for_minute_0_15_percentage  \
0             0                                   0.00   
1             0                                   0.00   
2             0                                   0.00   
3             0                                   0.00   
4             2                                   0.00   
...         ...                                    ...   
4533          3                                  10.00   
4534          0                                  12.00   
4535          0                                  14.71   
4536          5                                  18.18   
4537          0                                  12.73   

      away_goals_against_minute_91_105_percentage  HomeTeamid  AvgOver2_5  \
0                                            0.00          66        2.01   
1                                            0.00          67        2.08   
2                                            0.00          68        2.09   
3                                            0.00          49        1.49   
4                                            0.00         746        2.16   
...                                           ...         ...         ...   
4533                                         9.68          63        1.64   
4534                                         6.67          46        1.61   
4535                                         3.77          38        1.91   
4536                                         8.70          39        1.66   
4537                                         9.30          47        1.78   

      home_home_loses  home_goals_against_minute_61_75  \
0                   0                                0   
1                   0                                0   
2                   0                                0   
3                   0                                0   
4                   0                                0   
...               ...                              ...   
4533                8                               11   
4534                5                                9   
4535               14                                8   
4536                8                               11   
4537                5                                8   

      home_failed_to_score_away  home_goals_against_minute_76_90  \
0                             0                                0   
1                             0                                0   
2                             0                                0   
3                             0                                0   
4                             0                                0   
...                         ...                              ...   
4533                          7                                9   
4534                          2                                8   
4535                         10                               10   
4536                          7                                6   
4537                          6                                8   

      away_away_draws  home_away_goals_against  \
0                   0                        0   
1                   0                        0   
2                   0                        0   
3                   0                        0   
4                   0                        0   
...               ...                      ...   
4533                4                       40   
4534                3                       34   
4535                3                       29   
4536                3                       15   
4537                1                       21   

      away_goals_against_minute_16_30_percentage  Season  \
0                                           0.00    2010   
1                                           0.00    2010   
2                                           0.00    2010   
3                            

In [16]:
footballdata_wTeamStats = footballdata_wTeamStats.drop(columns=to_modify)

In [17]:
print(footballdata_wTeamStats.dtypes.sort_values().to_string())

away_goals_for_minute_61_75                      int32
away_goals_against_minute_31_45                  int32
away_goals_against_minute_76_90                  int32
home_goals_for_minute_61_75                      int32
home_goals_for_minute_0_15                       int32
home_goals_for_minute_76_90                      int32
away_goals_for_minute_31_45                      int32
away_goals_for_minute_0_15                       int32
away_goals_for_minute_46_60                      int32
home_goals_against_minute_46_60                  int32
away_goals_for_minute_91_105                     int32
away_goals_against_minute_16_30                  int32
away_goals_against_minute_61_75                  int32
home_goals_against_minute_16_30                  int32
home_goals_for_minute_91_105                     int32
away_goals_against_minute_0_15                   int32
away_goals_for_minute_16_30                      int32
home_goals_against_minute_31_45                  int32
away_goals

### Remove 1st 5 "jornadas"

In [18]:
footballdata_wTeamStats = footballdata_wTeamStats[footballdata_wTeamStats['home_total_games']>=5]
footballdata_wTeamStats.reindex(sorted(footballdata_wTeamStats.columns), axis=1)

AverageAwayWinOdd  AverageDrawWinOdd  AverageHomeWinOdd  AvgOver2_5  \
50                15.00               6.00               1.22        1.42   
51                 4.50               3.50               1.83        2.13   
52                 2.30               3.25               3.20        1.81   
53                 2.63               3.20               2.75        2.18   
54                 7.50               4.33               1.44        1.90   
...                 ...                ...                ...         ...   
4533               1.67               4.17               4.98        1.64   
4534               7.02               4.90               1.44        1.61   
4535               1.87               3.68               4.26        1.91   
4536               1.26               5.88              12.83        1.66   
4537               3.42               3.60               2.12        1.78   

      AvgUnder2_5  AwayGoals  AwayTeamId AwayTeamName        Date  Div  \
50           2.68          3          60    West Brom  25/09/2010   39   
51           1.67          0          61        Wigan  25/09/2010   39   
52           1.95          2          67    Blackburn  25/09/2010   39   
53           1.65          0          45      Everton  25/09/2010   39   
54           1.85          2         746   Sunderland  25/09/2010   39   
...           ...        ...         ...          ...         ...  ...   
4533         2.28          3          49      Chelsea  11/05/2022   39   
4534         2.34          0          71      Norwich  11/05/2022   39   
4535         1.92          0          45      Everton  11/05/2022   39   
4536         2.24          5          50     Man City  11/05/2022   39   
4537         2.05          0          42      Arsenal  12/05/2022   39   

     FullTimeResult  HomeGoals HomeTeamName  HomeTeamid  Season  \
50                A          2      Arsenal          42    2010   
51                D          0   Birmingham          54    2010   
52                A          1    Blackpool        1356    2010   
53                D          0       Fulham          36    2010   
54                D          2    Liverpool          40    2010   
...             ...        ...          ...         ...     ...   
4533              A          0        Leeds          63    2021   
4534              H          3    Leicester          46    2021   
4535              D          0      Watford          38    2021   
4536              A          1       Wolves          39    2021   
4537              H          3    Tottenham          47    2021   

      away_away_clean_sheets  away_away_draws  away_away_goals_against  \
50                         0                0                        7   
51                         1                0                        0   
52                         0                1                        3   
53                         0                0                        2   
54                         0                1                        2   
...                      ...              ...                      ...   
4533                       9                4                       11   
4534                       3                3                       37   
4535                       1                3                       36   
4536                      10                3                        8   
4537                       6                1                       26   

      away_away_goals_for  away_away_loses  away_away_wins  \
50                      0                2               0   
51                      1                0               1   
52                      2                1               0   
53                      0                2               0   
54                      1                1               0   
...                   ...              ...             ...   
4533                   36                3              11   
45

## Define indexes and labels

In [19]:
indexes = ['AverageAwayWinOdd', 'AverageDrawWinOdd', 'AverageHomeWinOdd',
               'AvgOver2_5', 'AvgUnder2_5', 'AwayGoals', 'AwayTeamId',
               'AwayTeamId', 'AwayTeamName', 'Date', 'Div',
               'HomeGoals', 'HomeTeamName', 'HomeTeamid', 'Season',
               ]
label = ['FullTimeResult']

In [20]:
print(footballdata_wTeamStats.drop(columns=indexes).dtypes.sort_index().to_string())

FullTimeResult                                  object
away_away_clean_sheets                           int64
away_away_draws                                  int64
away_away_goals_against                          int64
away_away_goals_for                              int64
away_away_loses                                  int64
away_away_wins                                   int64
away_failed_to_score_away                        int64
away_failed_to_score_home                        int64
away_failed_to_score_total                       int64
away_form_last10games_draws                    float64
away_form_last10games_loses                    float64
away_form_last10games_wins                     float64
away_form_last1games_draws                     float64
away_form_last1games_loses                     float64
away_form_last1games_wins                      float64
away_form_last2games_draws                     float64
away_form_last2games_loses                     float64
away_form_

In [21]:
list(set(footballdata_wTeamStats.columns.to_list())-set(indexes)-set(label))

['home_goals_for_minute_0_15_percentage',
 'away_goals_against_minute_91_105_percentage',
 'home_home_loses',
 'home_goals_against_minute_61_75',
 'home_failed_to_score_away',
 'home_goals_against_minute_76_90',
 'away_away_draws',
 'home_away_goals_against',
 'away_goals_against_minute_16_30_percentage',
 'home_total_home_games',
 'home_goals_against_minute_91_105',
 'home_goals_for_minute_31_45_percentage',
 'away_goals_against_minute_91_105',
 'away_total_goals_against',
 'away_total_games',
 'home_form_last1games_wins',
 'away_form_last10games_loses',
 'home_goals_for_minute_16_30_percentage',
 'away_form_last5games_wins',
 'away_away_clean_sheets',
 'home_form_last10games_wins',
 'home_goals_for_minute_16_30',
 'away_total_home_games',
 'away_form_last1games_loses',
 'home_home_draws',
 'away_home_goals_for',
 'home_total_wins',
 'away_goals_for_minute_46_60_percentage',
 'away_home_clean_sheets',
 'home_total_away_games',
 'home_form_last10games_loses',
 'away_failed_to_score_hom

## Normalize Features (per game)

In [22]:
away_away_games_norm = ['away_away_clean_sheets', 'away_away_draws', 'away_away_goals_against',
                      'away_away_goals_for', 'away_away_loses', 'away_away_wins', 'away_failed_to_score_away']

away_home_games_norm = ['away_failed_to_score_home', 'away_home_clean_sheets',
                       'away_home_draws', 'away_home_goals_against', 'away_home_goals_for',
                       'away_home_loses', 'away_home_wins']

away_total_games_norm = ['away_failed_to_score_total', 'away_goals_against_minute_0_15',
                        'away_goals_against_minute_16_30', 'away_goals_against_minute_31_45',
                        'away_goals_against_minute_46_60', 'away_goals_against_minute_61_75',
                        'away_goals_against_minute_76_90', 'away_goals_against_minute_91_105',
                        'away_goals_for_minute_0_15', 'away_goals_for_minute_16_30',
                        'away_goals_for_minute_31_45', 'away_goals_for_minute_46_60',
                        'away_goals_for_minute_61_75', 'away_goals_for_minute_76_90',
                        'away_goals_for_minute_91_105', 'away_penalties_for', 'away_total_clean_sheets',
                        'away_total_draws', 'away_total_goals_against', 'away_total_goals_for', 'away_total_loses',
                        'away_total_wins']

home_away_games_norm = ['home_away_clean_sheets', 'home_away_draws', 'home_away_goals_against',
                      'home_away_goals_for', 'home_away_loses', 'home_away_wins', 'home_failed_to_score_away']

home_home_games_norm = ['home_failed_to_score_home', 'home_home_clean_sheets',
                       'home_home_draws', 'home_home_goals_against', 'home_home_goals_for',
                       'home_home_loses', 'home_home_wins']

home_total_games_norm = ['home_failed_to_score_total', 'home_goals_against_minute_0_15',
                        'home_goals_against_minute_16_30', 'home_goals_against_minute_31_45',
                        'home_goals_against_minute_46_60', 'home_goals_against_minute_61_75',
                        'home_goals_against_minute_76_90', 'home_goals_against_minute_91_105',
                        'home_goals_for_minute_0_15', 'home_goals_for_minute_16_30',
                        'home_goals_for_minute_31_45', 'home_goals_for_minute_46_60',
                        'home_goals_for_minute_61_75', 'home_goals_for_minute_76_90',
                        'home_goals_for_minute_91_105', 'home_penalties_for', 'home_total_clean_sheets',
                        'home_total_draws', 'home_total_goals_against', 'home_total_goals_for', 'home_total_loses',
                        'home_total_wins']

In [23]:
for feature in away_away_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['away_total_away_games']
for feature in away_home_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['away_total_home_games']
for feature in away_total_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['away_total_games']
    
for feature in home_away_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['home_total_away_games']
for feature in home_home_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['home_total_home_games']
for feature in home_total_games_norm:
    footballdata_wTeamStats[feature] = footballdata_wTeamStats[feature] / footballdata_wTeamStats['home_total_games']
    
footballdata_wTeamStats

AwayGoals  home_goals_for_minute_0_15_percentage  \
50            3                                  15.38   
51            0                                  22.22   
52            2                                   0.00   
53            0                                   0.00   
54            2                                   0.00   
...         ...                                    ...   
4533          3                                  10.00   
4534          0                                  12.00   
4535          0                                  14.71   
4536          5                                  18.18   
4537          0                                  12.73   

      away_goals_against_minute_91_105_percentage  HomeTeamid  AvgOver2_5  \
50                                           0.00          42        1.42   
51                                           0.00          54        2.13   
52                                           0.00        1356        1.81   
53                                           0.00          36        2.18   
54                                           0.00          40        1.90   
...                                           ...         ...         ...   
4533                                         9.68          63        1.64   
4534                                         6.67          46        1.61   
4535                                         3.77          38        1.91   
4536                                         8.70          39        1.66   
4537                                         9.30          47        1.78   

      home_home_loses  home_goals_against_minute_61_75  \
50           0.000000                         0.000000   
51           0.000000                         0.400000   
52           0.000000                         0.200000   
53           0.000000                         0.000000   
54           0.000000                         0.200000   
...               ...                              ...   
4533         0.470588                         0.314286   
4534         0.294118                         0.264706   
4535         0.823529                         0.228571   
4536         0.470588                         0.314286   
4537         0.294118                         0.228571   

      home_failed_to_score_away  home_goals_against_minute_76_90  \
50                     0.000000                         0.400000   
51                     0.000000                         0.200000   
52                     0.500000                         0.400000   
53                     0.333333                         0.200000   
54                     0.666667                         0.200000   
...                         ...                              ...   
4533                   0.388889                         0.257143   
4534                   0.117647                         0.235294   
4535                   0.555556                         0.285714   
4536                   0.388889                         0.171429   
4537                   0.333333                         0.228571   

      away_away_draws  home_away_goals_against  \
50           0.000000                 1.000000   
51           0.000000                 2.333333   
52           0.500000                 2.500000   
53           0.000000                 1.000000   
54           0.500000                 2.000000   
...               ...                      ...   
4533         0.222222                 2.222222   
4534         0.176471                 2.000000   
4535         0.176471                 1.611111   
4536         0.176471                 0.833333   
4537         0.058824                 1.166667   

      away_goals_against_minute_16_30_percentage  Season  \
50                                         10.00    2010   
51                                          7.69    2010   
52                                         16.67    2010   
53                           

In [24]:
#TODO: this is based only on home team games (for most cases should be ok)
footballdata_wTeamStats['total_games'] = footballdata_wTeamStats['home_total_games']
footballdata_wTeamStats = \
    footballdata_wTeamStats.drop(columns=['away_total_away_games','away_total_home_games', 'away_total_games',
                                          'home_total_away_games', 'home_total_home_games', 'home_total_games'])
footballdata_wTeamStats

AwayGoals  home_goals_for_minute_0_15_percentage  \
50            3                                  15.38   
51            0                                  22.22   
52            2                                   0.00   
53            0                                   0.00   
54            2                                   0.00   
...         ...                                    ...   
4533          3                                  10.00   
4534          0                                  12.00   
4535          0                                  14.71   
4536          5                                  18.18   
4537          0                                  12.73   

      away_goals_against_minute_91_105_percentage  HomeTeamid  AvgOver2_5  \
50                                           0.00          42        1.42   
51                                           0.00          54        2.13   
52                                           0.00        1356        1.81   
53                                           0.00          36        2.18   
54                                           0.00          40        1.90   
...                                           ...         ...         ...   
4533                                         9.68          63        1.64   
4534                                         6.67          46        1.61   
4535                                         3.77          38        1.91   
4536                                         8.70          39        1.66   
4537                                         9.30          47        1.78   

      home_home_loses  home_goals_against_minute_61_75  \
50           0.000000                         0.000000   
51           0.000000                         0.400000   
52           0.000000                         0.200000   
53           0.000000                         0.000000   
54           0.000000                         0.200000   
...               ...                              ...   
4533         0.470588                         0.314286   
4534         0.294118                         0.264706   
4535         0.823529                         0.228571   
4536         0.470588                         0.314286   
4537         0.294118                         0.228571   

      home_failed_to_score_away  home_goals_against_minute_76_90  \
50                     0.000000                         0.400000   
51                     0.000000                         0.200000   
52                     0.500000                         0.400000   
53                     0.333333                         0.200000   
54                     0.666667                         0.200000   
...                         ...                              ...   
4533                   0.388889                         0.257143   
4534                   0.117647                         0.235294   
4535                   0.555556                         0.285714   
4536                   0.388889                         0.171429   
4537                   0.333333                         0.228571   

      away_away_draws  home_away_goals_against  \
50           0.000000                 1.000000   
51           0.000000                 2.333333   
52           0.500000                 2.500000   
53           0.000000                 1.000000   
54           0.500000                 2.000000   
...               ...                      ...   
4533         0.222222                 2.222222   
4534         0.176471                 2.000000   
4535         0.176471                 1.611111   
4536         0.176471                 0.833333   
4537         0.058824                 1.166667   

      away_goals_against_minute_16_30_percentage  Season  \
50                                         10.00    2010   
51                                          7.69    2010   
52                                         16.67    2010   
53                           

## Extract Features

In [25]:
footballdata_wTeamStats.groupby('FullTimeResult').count()

AwayGoals  home_goals_for_minute_0_15_percentage  \
FullTimeResult                                                     
A                    1203                                   1203   
D                     939                                    939   
H                    1795                                   1795   

                away_goals_against_minute_91_105_percentage  HomeTeamid  \
FullTimeResult                                                            
A                                                      1203        1203   
D                                                       939         939   
H                                                      1795        1795   

                AvgOver2_5  home_home_loses  home_goals_against_minute_61_75  \
FullTimeResult                                                                 
A                     1203             1203                             1203   
D                      939              939                              939   
H                     1795             1795                             1795   

                home_failed_to_score_away  home_goals_against_minute_76_90  \
FullTimeResult                                                               
A                                    1203                             1203   
D                                     939                              939   
H                                    1795                             1795   

                away_away_draws  home_away_goals_against  \
FullTimeResult                                             
A                          1203                     1203   
D                           939                      939   
H                          1795                     1795   

                away_goals_against_minute_16_30_percentage  Season  \
FullTimeResult                                                       
A                                                     1203    1203   
D                                                      939     939   
H                                                     1795    1795   

                home_goals_against_minute_91_105  \
FullTimeResult                                     
A                                           1203   
D                                            939   
H                                           1795   

                home_goals_for_minute_31_45_percentage  \
FullTimeResult                                           
A                                                 1203   
D                                                  939   
H                                                 1795   

                away_goals_against_minute_91_105  away_total_goals_against  \
FullTimeResult                                                               
A                                           1203                      1203   
D                                            939                       939   
H                                           1795                      1795   

                home_goals_for_minute_16_30_percentage  \
FullTimeResult                                           
A                                                 1203   
D                                                  939   
H                                                 1795   

                away_away_clean_sheets  home_goals_for_minute_16_30  \
FullTimeResult                                                        
A                                 1203                         1203   
D                                  939                          939   
H                                 1795                         1795   

                home_home_draws  AverageHomeWinOdd  away_home_goals_for  \
FullTimeResult                                                            
A                          1203               1203                 1203   
D                           939         

In [26]:
X = footballdata_wTeamStats[list(set(footballdata_wTeamStats.columns.to_list())-set(indexes)-set(label))].values
y = footballdata_wTeamStats[label].values
y = y.reshape((y.shape[0],))
y = np.array([0 if label=='H' else 1 if label=='D' else 2 for label in y])

In [27]:
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
X

array([[-1.57831341,  0.09329849, -2.02426245, ..., -0.49188987,
         2.42391208,  1.35916279],
       [-1.57831341, -0.88771128,  1.88748073, ..., -0.49188987,
         4.23491336,  2.84378807],
       [ 0.91881521, -0.88771128, -1.12173304, ...,  1.23998698,
         0.61291081, -1.98260164],
       ...,
       [-0.3297491 ,  0.09329849, -0.64406143, ..., -0.95032787,
        -1.19809047, -1.66330403],
       [ 0.57421146,  1.56481314,  1.56238237, ..., -0.98671183,
        -0.29258983,  0.32090254],
       [ 0.91881521,  1.07430826,  0.06247004, ..., -1.48153379,
         0.61291081,  0.38715137]])

In [28]:
print ('The first element of X is: ', X[0])

The first element of X is:  [-1.57831341  0.09329849 -2.02426245  0.35139512  1.05674562 -1.05379503
 -0.7349832  -1.55478628  2.78689     0.10843084 -0.32809903 -1.88427812
 -1.7613771  -0.9918544   1.24818757 -1.50518944 -0.99833619 -0.30145263
 -0.54819468  0.20018941 -1.4470595   0.90037071 -0.09048922  2.79977167
 -1.4938432  -2.05617383 -1.02915653 -0.00855176 -0.25881824 -1.01870202
 -0.36893069  1.09055577  2.12493978 -0.67603271  0.14344788  0.98175479
  0.15627577 -0.08610973  1.37583172 -1.39176705  0.83243739  1.11991248
  1.55897539  0.63497873  1.60422132 -1.02674515 -0.68132332 -1.58386917
  0.2400149   1.48714511  1.25461888  0.74910274 -1.05967165  2.91910455
  0.07323557 -1.93153824 -1.44502664 -1.6796285  -0.83887884  1.45193001
 -1.00860431 -1.90913194 -1.45092405  2.5637142  -0.08159073  1.46406383
 -1.45098669  0.19378691  2.14998382 -1.50003116 -1.18877844 -2.17434847
 -2.0267237   5.45576675  3.65397149 -1.6756865   2.24977821  3.66069243
 -1.71334288 -1.0765774

In [29]:
print ('The first element of y is: ', y[0])
print ('The last element of y is: ', y[-1])

The first element of y is:  2
The last element of y is:  0


In [30]:
print ('The shape of X is: ' + str(X.shape))
print ('The shape of y is: ' + str(y.shape))

The shape of X is: (3937, 125)
The shape of y is: (3937,)


In [40]:
#train_size = int(X.shape[0]*0.8)
#train_size

3149

In [41]:
#X_train = X[:train_size]
#print(X_train.shape)
#X_test = X[train_size:]
#print(X_test.shape)

(3149, 125)
(788, 125)


In [42]:
#y_train = y[:train_size]
#print(y_train.shape)
#y_test = y[train_size:]
#print(y_test.shape)

(3149,)
(788,)


In [58]:
X_train, X_test, y_train, y_test \
    = train_test_split(X, y, test_size=0.2, random_state=1)

X_train, X_val, y_train, y_val \
    = train_test_split(X_train, y_train, test_size=0.25, random_state=1) # 0.25 x 0.8 = 0.2

In [59]:
print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

(2361, 125)
(788, 125)
(788, 125)


In [60]:
print(y_train.shape)
print(y_val.shape)
print(y_test.shape)

(2361,)
(788,)
(788,)


# ML Algorithms

In [43]:
def accuracy(confusion_matrix):
    diagonal_sum = confusion_matrix.trace()
    sum_of_all_elements = confusion_matrix.sum()
    return diagonal_sum / sum_of_all_elements

## GBT

### Test changing only max_depth

In [87]:
max_val_score = 0
iterations_wo_update = 0
for max_depth in range(125):
    max_depth += 1 # start on 1
    print(f"Testing Max Depth: {max_depth}")
    gbtClassifier = GradientBoostingClassifier(max_depth = max_depth, n_iter_no_change=7, verbose=1).fit(X_train, y_train)
    val_score = gbtClassifier.score(X_val, y_val)
    if val_score > max_val_score:
        iterations_wo_update = 0
        best_max_depth = max_depth
        max_val_score = val_score
        best_model = gbtClassifier
        print(f"New best max depth: {best_max_depth}, validation score: {max_val_score}")
    else:
        iterations_wo_update +=1
        if iterations_wo_update >= 10:
            print("No improvements on the last 10 iterations, stopping here...")
            break
            
gbtClassifier = best_model

Testing Max Depth: 1
      Iter       Train Loss   Remaining Time 
         1           1.0600            3.05s
         2           1.0540            2.91s
         3           1.0488            2.80s
         4           1.0441            2.80s
         5           1.0396            2.82s
         6           1.0356            2.82s
         7           1.0319            2.81s
         8           1.0284            2.80s
         9           1.0252            2.75s
        10           1.0222            2.73s
        20           1.0000            2.41s
        30           0.9857            2.11s
        40           0.9750            1.82s
        50           0.9666            1.51s
        60           0.9594            1.21s
New best max depth: 1, validation score: 0.5126903553299492
Testing Max Depth: 2
      Iter       Train Loss   Remaining Time 
         1           1.0535            5.17s
         2           1.0421            5.26s
         3           1.0324            5.

In [88]:
best_model.score(X_train, y_train)

0.6450656501482422

In [89]:
best_model.score(X_test, y_test)

0.5253807106598984

In [92]:
y_train_pred = gbtClassifier.predict(X_train)
y_test_pred = gbtClassifier.predict(X_test)

In [93]:
cm_train = confusion_matrix(y_train_pred, y_train)
cm_train

array([[949, 330, 282],
       [  0, 127,   2],
       [107, 117, 447]], dtype=int64)

In [94]:
cm_test = confusion_matrix(y_test_pred, y_test)
cm_test

array([[302, 131, 130],
       [ 13,   8,   8],
       [ 59,  33, 104]], dtype=int64)

### Test changing also n_estimators

In [81]:
gbtClassifier = GradientBoostingClassifier(n_estimators=20, verbose=1).fit(X_train, y_train)
print(gbtClassifier.score(X_train, y_train))
gbtClassifier.score(X_test, y_test)

      Iter       Train Loss   Remaining Time 
         1           1.0491            1.82s
         2           1.0344            1.65s
         3           1.0217            1.56s
         4           1.0101            1.46s
         5           0.9994            1.35s
         6           0.9903            1.26s
         7           0.9819            1.17s
         8           0.9736            1.08s
         9           0.9663            0.98s
        10           0.9596            0.89s
        20           0.9019            0.00s
0.5883100381194409


0.5329949238578681

In [96]:
max_val_score = 0
for n_estimators in range(5,100,5):
    print(f"Testing N Estimators: {n_estimators}")
    iterations_wo_update = 0
    for max_depth in range(125):
        max_depth += 1 # start on 1
        gbtClassifier = GradientBoostingClassifier(max_depth = max_depth, n_estimators=n_estimators).fit(X_train, y_train)
        val_score = gbtClassifier.score(X_val, y_val)
        if val_score > max_val_score:
            iterations_wo_update = 0
            best_max_depth = max_depth
            max_val_score = val_score
            best_model = gbtClassifier
            print(f"New best max depth and N estimators: ({best_max_depth}, {n_estimators}), validation score: {max_val_score}")
        else:
            iterations_wo_update +=1
            if iterations_wo_update >= 10:
                print("No improvements on the last 10 iterations, moving on...")
                break
            
gbtClassifier = best_model

Testing N Estimators: 5
New best max depth and N estimators: (1, 5), validation score: 0.4631979695431472
New best max depth and N estimators: (2, 5), validation score: 0.5101522842639594
New best max depth and N estimators: (3, 5), validation score: 0.5114213197969543
No improvements on the last 10 iterations, moving on...
Testing N Estimators: 10
New best max depth and N estimators: (2, 10), validation score: 0.5241116751269036
No improvements on the last 10 iterations, moving on...
Testing N Estimators: 15
No improvements on the last 10 iterations, moving on...
Testing N Estimators: 20
No improvements on the last 10 iterations, moving on...
Testing N Estimators: 25
No improvements on the last 10 iterations, moving on...
Testing N Estimators: 30
New best max depth and N estimators: (2, 30), validation score: 0.5304568527918782
No improvements on the last 10 iterations, moving on...
Testing N Estimators: 35
No improvements on the last 10 iterations, moving on...
Testing N Estimators: 

In [102]:
gbtClassifier.score(X_train, y_train)

0.554849639983058

In [103]:
gbtClassifier.score(X_test, y_test)

0.5317258883248731

In [104]:
y_train_pred = gbtClassifier.predict(X_train)
y_test_pred = gbtClassifier.predict(X_test)

In [105]:
cm_train = confusion_matrix(y_train_pred, y_train)
cm_train

array([[913, 400, 372],
       [  4,  39,   1],
       [139, 135, 358]], dtype=int64)

In [106]:
cm_test = confusion_matrix(y_test_pred, y_test)
cm_test

array([[312, 130, 133],
       [  8,   5,   7],
       [ 54,  37, 102]], dtype=int64)

## MLP

In [137]:
model = Sequential(
    [ 
        tf.keras.Input(shape=(125,)),
        Dense(20, activation = 'relu', name='L1', kernel_regularizer=tf.keras.regularizers.l2(0.1)),
        Dense(20, activation = 'relu', name='L2', kernel_regularizer=tf.keras.regularizers.l2(0.1)),
        Dense(3, activation = 'linear', name='L3')    # < softmax activation here
    ]
)
model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.Adam(0.0001),
)
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 L1 (Dense)                  (None, 20)                2520      
                                                                 
 L2 (Dense)                  (None, 20)                420       
                                                                 
 L3 (Dense)                  (None, 3)                 63        
                                                                 
Total params: 3,003
Trainable params: 3,003
Non-trainable params: 0
_________________________________________________________________


In [138]:
model.fit(
    X_train,y_train,
    epochs=1000
)

Epoch 1/1000
111/111 [==============================] - 1s 3ms/step - loss: 6.6018
Epoch 2/1000
111/111 [==============================] - 0s 3ms/step - loss: 6.0157
Epoch 3/1000
111/111 [==============================] - 0s 3ms/step - loss: 5.4996
Epoch 4/1000
111/111 [==============================] - 0s 3ms/step - loss: 5.0372
Epoch 5/1000
111/111 [==============================] - 0s 2ms/step - loss: 4.6191
Epoch 6/1000
111/111 [==============================] - 0s 2ms/step - loss: 4.2403
Epoch 7/1000
111/111 [==============================] - 0s 2ms/step - loss: 3.8972
Epoch 8/1000
111/111 [==============================] - 0s 2ms/step - loss: 3.5865
Epoch 9/1000
111/111 [==============================] - 0s 3ms/step - loss: 3.3055
Epoch 10/1000
111/111 [==============================] - 0s 3ms/step - loss: 3.0520
Epoch 11/1000
111/111 [==============================] - 0s 3ms/step - loss: 2.8234
Epoch 12/1000
111/111 [==============================] - 0s 2ms/step - loss: 2.6176
E

111/111 [==============================] - 0s 2ms/step - loss: 0.9966
Epoch 195/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9964
Epoch 196/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9964
Epoch 197/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9964
Epoch 198/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9966
Epoch 199/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9963
Epoch 200/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9962
Epoch 201/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9962
Epoch 202/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9961
Epoch 203/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9961
Epoch 204/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9962
Epoch 205/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.

111/111 [==============================] - 1s 5ms/step - loss: 0.9907
Epoch 387/1000
111/111 [==============================] - 0s 4ms/step - loss: 0.9910
Epoch 388/1000
111/111 [==============================] - 1s 5ms/step - loss: 0.9911
Epoch 389/1000
111/111 [==============================] - 0s 4ms/step - loss: 0.9909
Epoch 390/1000
111/111 [==============================] - 0s 4ms/step - loss: 0.9910
Epoch 391/1000
111/111 [==============================] - 1s 5ms/step - loss: 0.9910
Epoch 392/1000
111/111 [==============================] - 0s 4ms/step - loss: 0.9909
Epoch 393/1000
111/111 [==============================] - 0s 4ms/step - loss: 0.9908
Epoch 394/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9910
Epoch 395/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9906
Epoch 396/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9909
Epoch 397/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.

111/111 [==============================] - 0s 3ms/step - loss: 0.9876
Epoch 579/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9877
Epoch 580/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9875
Epoch 581/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9878
Epoch 582/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9878
Epoch 583/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9876
Epoch 584/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9875
Epoch 585/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9877
Epoch 586/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9876
Epoch 587/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9875
Epoch 588/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9876
Epoch 589/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.

111/111 [==============================] - 0s 2ms/step - loss: 0.9854
Epoch 771/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9848
Epoch 772/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9851
Epoch 773/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9851
Epoch 774/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9851
Epoch 775/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9851
Epoch 776/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9850
Epoch 777/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9849
Epoch 778/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9850
Epoch 779/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9850
Epoch 780/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.9850
Epoch 781/1000
111/111 [==============================] - 0s 2ms/step - loss: 0.

111/111 [==============================] - 0s 3ms/step - loss: 0.9827
Epoch 963/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9824
Epoch 964/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9827
Epoch 965/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9827
Epoch 966/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9826
Epoch 967/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9824
Epoch 968/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9825
Epoch 969/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9825
Epoch 970/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9824
Epoch 971/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9824
Epoch 972/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.9824
Epoch 973/1000
111/111 [==============================] - 0s 3ms/step - loss: 0.

In [139]:
[layer1, layer2, layer3] = model.layers
W1,b1 = layer1.get_weights()
W2,b2 = layer2.get_weights()
W3,b3 = layer3.get_weights()

In [140]:
W1

array([[-3.1290039e-34,  7.8969998e-03,  2.6002321e-03, ...,
         3.8971480e-03,  3.4866780e-03,  5.3276604e-34],
       [-2.4301220e-34,  2.0039938e-02, -7.7724806e-03, ...,
        -5.5732852e-04,  8.0334311e-03, -8.6154977e-35],
       [ 1.0791125e-34, -1.1884933e-02,  6.9113229e-03, ...,
         4.4076606e-03, -3.9039669e-03, -5.0616658e-34],
       ...,
       [ 7.6492150e-35, -1.7731458e-04, -1.1077951e-02, ...,
        -8.3890753e-03,  7.5112036e-03,  3.1851388e-34],
       [ 8.3804379e-35,  5.5134306e-03,  6.9521004e-03, ...,
         5.1117959e-03,  6.2084908e-04,  1.6034705e-34],
       [ 1.3671720e-34, -9.0701776e-03,  2.0495967e-03, ...,
         2.0148486e-03, -4.2821034e-03, -1.4035589e-34]], dtype=float32)

In [141]:
y_train_pred_probs = tf.nn.softmax(model.predict(X_train)).numpy()
y_train_pred_probs

111/111 [==============================] - 0s 2ms/step


array([[0.7414078 , 0.1668334 , 0.09175882],
       [0.5946549 , 0.22586152, 0.17948356],
       [0.260075  , 0.2735496 , 0.4663754 ],
       ...,
       [0.63571775, 0.21127789, 0.15300429],
       [0.29861066, 0.26938498, 0.43200433],
       [0.42486346, 0.2649965 , 0.31013995]], dtype=float32)

In [142]:
y_test_pred_probs = tf.nn.softmax(model.predict(X_test)).numpy()
y_test_pred_probs

13/13 [==============================] - 0s 3ms/step


array([[0.46438932, 0.26013002, 0.2754806 ],
       [0.27057377, 0.27411923, 0.45530704],
       [0.6085722 , 0.22115739, 0.17027041],
       ...,
       [0.3451147 , 0.274435  , 0.3804503 ],
       [0.14754826, 0.24316351, 0.6092882 ],
       [0.45374075, 0.25880393, 0.28745532]], dtype=float32)

In [143]:
y_train_pred = np.argmax(y_train_pred_probs, axis=1)
y_test_pred = np.argmax(y_test_pred_probs, axis=1)

In [144]:
cm_train = confusion_matrix(y_train_pred, y_train)
cm_train

array([[1373,  562,  495],
       [   0,    0,    0],
       [ 256,  291,  566]], dtype=int64)

In [145]:
cm_test = confusion_matrix(y_test_pred, y_test)
cm_test

array([[131,  57,  69],
       [  0,   0,   0],
       [ 35,  29,  73]], dtype=int64)

In [146]:
for i in range(10):
    print( f"{y_train_pred_probs[-i]}, predicted_category: {np.argmax(y_train_pred_probs[-i])}, category: {y_train[-i]}")

[0.7414078  0.1668334  0.09175882], predicted_category: 0, category: 2
[0.42486346 0.2649965  0.31013995], predicted_category: 0, category: 2
[0.29861066 0.26938498 0.43200433], predicted_category: 2, category: 2
[0.63571775 0.21127789 0.15300429], predicted_category: 0, category: 0
[0.65596986 0.20388407 0.1401461 ], predicted_category: 0, category: 2
[0.49826044 0.2515875  0.25015205], predicted_category: 0, category: 2
[0.49491912 0.251669   0.2534119 ], predicted_category: 0, category: 1
[0.4440607 0.2645487 0.2913906], predicted_category: 0, category: 0
[0.33770368 0.27549848 0.38679785], predicted_category: 2, category: 2
[0.4100076  0.2681028  0.32188967], predicted_category: 0, category: 2


In [147]:
for i in range(10):
    print( f"{y_test_pred_probs[-i]}, predicted_category: {np.argmax(y_test_pred_probs[-i])}, category: {y_test[-i]}")

[0.46438932 0.26013002 0.2754806 ], predicted_category: 0, category: 0
[0.45374075 0.25880393 0.28745532], predicted_category: 0, category: 0
[0.14754826 0.24316351 0.6092882 ], predicted_category: 2, category: 2
[0.3451147 0.274435  0.3804503], predicted_category: 2, category: 1
[0.6681957 0.1987667 0.1330376], predicted_category: 0, category: 0
[0.1846948  0.25842822 0.556877  ], predicted_category: 2, category: 2
[0.16090234 0.24836555 0.59073216], predicted_category: 2, category: 2
[0.8806478  0.09074179 0.02861039], predicted_category: 0, category: 0
[0.31032193 0.27536654 0.41431153], predicted_category: 2, category: 2
[0.5812784  0.229438   0.18928358], predicted_category: 0, category: 2


In [148]:
print('Train accuracy: '+ str(accuracy(cm_train)))
print('Test accuracy: '+ str(accuracy(cm_test)))

Train accuracy: 0.5472763195032458
Test accuracy: 0.5177664974619289
